### ISSUE TITLE
Updated request/response pattern?

### ISSUE THREAD

**Issue by Logopher** [zeromq/netmq#1023]
### Environment

    NetMQ Version:    4.0.1.8
    Operating System: Windows 10 IoT Enterprise LTSC
    .NET Version:     6.0

### Expected behaviour

Requests should appear in Wireshark when I watch the relevant port and be received by the other end, then responses should do the same.

Or, stepping back a bit, I'm having trouble building a request/response setup and I doubt it's actually a bug in NetMQ, but I think the documentation is lacking.

### Actual behaviour

Requests are supposedly sent but do not appear in Wireshark and are not received on the other end.

### Steps to reproduce the behaviour

I wouldn't mind copying the content over to here, but my instincts tell me it's better to leave it in one spot:

https://stackoverflow.com/questions/72819193/what-is-the-currently-proper-request-response-pattern-for-netmq

**Comment by dxdjgl** [comment]
I believe if you bind your response socket your code would work. Right now your 2 socket are both connecting, so no connection is established.

**Comment by Logopher** [comment]
Thanks, that was indeed the problem.
