### ISSUE TITLE
Missing License Information In Nuget metadata

### ISSUE THREAD

**Issue by LiorBanai** [zeromq/netmq#1065]
Hi,
Could the license information be added to the nuget information?
it is good to add it so it will be shown in Visual Studio nuget management.

example:

	<PropertyGroup>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryType>git</RepositoryType>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

Also some tools can create auto generated report like (dotnet-project-licenses)  but right now those create missing entry:
![image](https://github.com/zeromq/netmq/assets/36262995/5db07dc5-2421-44df-843b-3ca2aa201673)

**Comment by drewnoakes** [comment]
This project uses a modified version of the LGPL. I believe the modification is not uncommon, but don't know if there's a PackageLicenseExpression that accurately reflects that.

**Comment by LiorBanai** [comment]
@drewnoakes  Any reason why not to switch to some common license like MIT?

**Comment by drewnoakes** [comment]
Relicensing would be a lot of work and require approval from all contributors. I'm not aware of any problem with the current license. Is it causing you any problem?

**Comment by LiorBanai** [comment]
No, no real problem. just a little more work for us regarding OSS reporting and such. 
we can close this.

Thanks.
