### ISSUE TITLE
Leverage framework dependencies where possible

### ISSUE THREAD

**Issue by thompson-tomo** [zeromq/netmq#1090]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want only the dependencies not available as part of the framework to be included for net standard as this will reduce maintenance effort.

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by drewnoakes** [comment]
Can you provide specific examples of the dependencies you think could be omitted? Even just a screenshot from an IDE.

**Comment by thompson-tomo** [comment]
@drewnoakes to make it easier i have just submitted the optimisations as #1091

**Comment by drewnoakes** [comment]
Thank you. Nothing is a concrete as a code diff :)

Running CI now and if it passes I'll merge.

**Comment by thompson-tomo** [comment]
No worries at all. 🙂
