### ISSUE TITLE
zeromq versions compatibility

### ISSUE THREAD

**Issue by dkrikun** [zeromq/netmq#137]
Hello,

What libzmq versions are compatible with NetMQ? In particular, does NetMQ supports zeromq-4.x features, like security mechanisms and ZMQ_CONFLATE?

Thanks,

**Comment by Wolf-SO** [comment]
@somdoron Hopefully you can point me to where I can find more information about the interoperability of different libzmq versions? Many thanks in advance.

<sub>You haven't the [discussion feature](https://github.com/features/discussions) enabled for this project,  please excuse me for abusing this old issue (which I got to via web search).</sub>
