### ISSUE TITLE
inproc protocol requires bind before you can connect.

### ISSUE THREAD

**Issue by JefStat** [zeromq/netmq#165]
Following the guide example using a QueueDevice with blocking device mode you cannot start your threads since they will call connect likely before you start the queue which undermines using the blocking device mode.
http://zguide.zeromq.org/cs:mtserver

**Comment by SriramSakthivel** [comment]
Hi, I'm running into the very same problem. I've noticed that this has been [answered here](http://stackoverflow.com/questions/26638792/how-do-you-shutdown-a-zmq-queuedevice-from-a-worker-thread-in-c-sharp).

Do I have to build the assembly from [this code](https://github.com/somdoron/netmq/blob/DeviceBaseInitialize/src/NetMQ/Devices/DeviceBase.cs)? Or any chances of getting the code merged?

Will this `Initialize` method be available in future [nuget package](https://www.nuget.org/packages/NetMQ/) or I'll have to build the code myself?

Thanks.

**Comment by leverate-somech** [comment]
@SriramSakthivel pull request is added, will probably get merged soon

**Comment by SriramSakthivel** [comment]
@leverate-somech Thanks for the very quick action :)

**Comment by drewnoakes** [comment]
@SriramSakthivel, it's merged now.

**Comment by SriramSakthivel** [comment]
@drewnoakes Thanks. When this will be published in nuget?

**Comment by zyf0330** [comment]
Hello, when will this be published?
