### ISSUE TITLE
PCL (Portable Class Library) profile 78 support

### ISSUE THREAD

**Issue by mellson** [zeromq/netmq#190]
Is it possible to add support for PCL profile 78?
This would make it possible to use NetMQ with the new unified api's from Xamarin.

**Comment by zone117x** [comment]
How dependent is NetMQ on AsyncIO? I converted NetMQ to a shared project, referenced it from a Xamarin iOS project and tried compiling, looks like the only thing that won't work is AsyncIO.

**Comment by zone117x** [comment]
Good news! I converted the AsyncIO-Unity source to a shared project type and was able to reference it and NetMQ from an iOS app. It builds and runs on an iPhone. I recommend you get a Xamarin.iOS package on Nuget. Probably get a lot of users for it!

**Comment by somdoron** [comment]
Very. But you can compile asyncio as pcl as well.

**Comment by somdoron** [comment]
Do you want to make a pull request to AsyncIO and NetMQ with the portable
library?

I can release a version of AsyncIO to nuget once the PR is in place and we
can do the same for NetMQ

**Comment by BrannonKing** [comment]
Any status updates on this? Was a pull request made? Should I do it?

**Comment by somdoron** [comment]
No, it will be great if you can do it..

**Comment by BrannonKing** [comment]
Looking at this further: AsyncIO cannot be converted to a portable project. However, we don't need to do that. The .NET 4.5 Socket support includes the ReceiveAsync method, which uses the IO Completion Ports. Any PCL project would support .NET 4.5. Are we okay to make a new project that has different transport classes? The new project would not rely on AsyncIO. That way the AsyncIO would only be a dependency for .NET 4.0 and 3.5 support. To be honest, I'm not sure we need to support those older frameworks.

**Comment by somdoron** [comment]
IO Completion port also existed in earlier version through ReceiveAsync and
Begin/End pattern, however you no control over which thread is handling the
completion status (which you do it you use win32 directly), this is what
AsyncIO is solving.

AsyncIO also have a dotnet implementation using the Async methods (which is
active on linu or if ForceDotNet is used), anyway I think the project that
can be made portable is actually the AsyncIO.Unity (badly named) which same
API but only one implementation of the DotNet.

**Comment by BrannonKing** [comment]
Okay. I give up. All of the socket stuff used in AsyncIO.Unity is not available in any PCL profile.

**Comment by somdoron** [comment]
the only problem is Windows Phone which doesn't support dotNet sockets at all.

**Comment by ProEns08** [comment]
I tried to build AsyncIO myself to use NetMQ. But I get this problem. Could you see this:
http://stackoverflow.com/questions/37186812/added-reference-not-detected-in-visual-studio
?

**Comment by somdoron** [comment]
latest netmq pre-release on nuget support Xamarin IOS and Mono.
