### ISSUE TITLE
NetMQSocket implements IDisposable but is missing a finalizer

### ISSUE THREAD

**Issue by panuhorsmalahti** [zeromq/netmq#194]
The best practice for a class that implement the IDisposable interface is to implement a finalizer (more on this [here](http://msdn.microsoft.com/en-us/library/vstudio/b1yfkh5e%28v=vs.100%29.aspx]) ). NetMQSocket is missing one (and this is not documented anywhere from what I've seen).

**Comment by somdoron** [comment]
@panuhorsmalahti can you provide a fix?

**Comment by panuhorsmalahti** [comment]
I'm actually unsure if the class should implement a finalizer. Microsoft's best practice seems to differ from the opinion that a class shouldn't implement a finalizer if it doesn't contain unmanaged resources. However, apparently "the disposable pattern" is still recommended.

**Comment by somdoron** [comment]
@panuhorsmalahti I think it ok to follow the dispose pattern (I usually try to follow)
