### ISSUE TITLE
The NetMQSocket.InvokeEvents(object sender, PollEvents events) in NetMQ3.5 problem

### ISSUE THREAD

**Issue by xzhigewu** [zeromq/netmq#195]
Hi,
I use the RouterSocket of NetMQ3.5 and RouterSocket.Poll to check data receive.But I meet some problem. 

    public abstract class NetMQSocket : IOutgoingSocket, IReceivingSocket,ISocketPollable, IDisposable

        internal void InvokeEvents(object sender, PollEvents events)
        {
            if (!m_isClosed)
            {
                m_socketEventArgs.Init(events);

                if (events.HasFlag(PollEvents.PollIn))     //the events is none but it pass the condition
                {
                   .....
                   .....

        public static class EnumHelper
        {
            public static bool HasFlag(this Enum value, Enum flag)
            {
                .....
                .....
                ulong num = Convert.ToUInt64(value);
                return ((Convert.ToUInt64(value) & num) == num);
            }
            .....
            .....
       
see the HasFlag code seems always return true.

thanks.

**Comment by somdoron** [comment]
Can you provide code to reproduce?

**Comment by xzhigewu** [comment]
Hi, flowing is my code to reproduce.The project's reference use the NetMQ3.5.

        static void Main(string[] args)
        {
            using (NetMQContext ctx = NetMQContext.Create())
            {
                using (var server = ctx.CreateRouterSocket())
                {
                    server.Bind("tcp://127.0.0.1:5556");
                    server.ReceiveReady += (sender, e) =>
                    {
                        //no data receive but every 1s to display ReceiveReady.
                        Console.WriteLine("ReceiveReady!");
                    };

                    while (true)
                    {
                        server.Poll(TimeSpan.FromMilliseconds(1000));
                    }
                }
            }

**Comment by somdoron** [comment]
@xzhigewu I actually already fixed the issue in the past, but it never made it into the main repository.

I fixed it again, I have a pending pull request, for now you can use the following repository with the fix:

https://github.com/somdoron/netmq
