### ISSUE TITLE
A subscriber socket that get disconnected block its context from being disposed

### ISSUE THREAD

**Issue by ndextraze-pbp** [zeromq/netmq#196]
NetMQ version: nuget package 3.3.0.11

Here is the failing test I have.

```
[Test]
        public void ASubscriberSocketThatGetDisconnectedBlockItsContextFromBeingDisposed()
        {
            using (var subscriberCtx = NetMQContext.Create()) {
                using (var publisherCtx = NetMQContext.Create()) {
                    using (var pubSocket = publisherCtx.CreatePublisherSocket())
                    using (var subSocket = subscriberCtx.CreateSubscriberSocket()) {

                        pubSocket.Options.Linger = TimeSpan.FromSeconds(0);
                        pubSocket.Options.SendTimeout = TimeSpan.FromSeconds(2);

                        subSocket.Options.Linger = TimeSpan.FromSeconds(0);
                        subSocket.Connect("tcp://localhost:12345");
                        subSocket.Subscribe("");
                        Debug.WriteLine("Subscriber socket connecting...");
                        Thread.Sleep(2000);

                        Debug.WriteLine("Publisher socket binding...");
                        pubSocket.Bind("tcp://localhost:12345");

                        Thread.Sleep(2000);

                        for (var i = 0; i < 100; i++) {
                            var msg = "msg-" + i;
                            pubSocket.Send("msg-" + i);
                            var recvMsg = subSocket.ReceiveString();
                            Assert.AreEqual(recvMsg, msg);
                        }
                        Debug.WriteLine("Sockets exchanged messages.");

                        pubSocket.Close();

                        Thread.Sleep(1000);
                    }
                    Debug.WriteLine("Sockets disposed.");
                }
                Debug.WriteLine("Publisher ctx disposed.");
            }
            Debug.WriteLine("Subscriber ctx disposed.");
        }
```

The code never gets to writing "Subscriber ctx disposed." as the context dispose is blocking.

Thanks.

**Comment by sachabarber** [comment]
I am sure Doron will answer this one, but this code looks invalid for me. There should only be one Context created not 2. The context should live for duration of the the sockets being used that were created from it.

**Comment by ndextraze-pbp** [comment]
I am creating two contexts to reproduce real situation where I'll have a service and a client applications. Those two applications would not create the sockets in the same context.

This code works with netmq v3.3.0.10 but not 3.3.0.11.

**Comment by ndextraze-pbp** [comment]
Additional information: The subscriber context does dispose if the subscriber socket gets back to a Connected state (ie. the publisher endpoint gets back up)

**Comment by somdoron** [comment]
Can you test if the problem still exist when compiling from master?

**Comment by somdoron** [comment]
@ndextraze-pbp I think I found the issue, I have a pending pull request with the fix, you can use following repository for now:

https://github.com/somdoron/netmq

**Comment by ndextraze-pbp** [comment]
It does work with that repository code.
Do you know when the next nuget package release will be?

**Comment by somdoron** [comment]
By the end of the week, working on that.

**Comment by ndextraze-pbp** [comment]
Cool.

I also have some random context Disposing issue with the same version of the library. My sockets are not instrumented with monitoring so I can't know if they fail with the same state as this bug. I would say that 20% of the time I have a context that block on Dispose with the same tests working 80% of the time. Anyway I've read your blog about IOCP and it looks promising, hopefully that will fix all our issues with the netmq Ctx.

**Comment by somdoron** [comment]
@ndextraze-pbp does the issue exist with the new version?

**Comment by ndextraze-pbp** [comment]
No. It is working correctly with 3.3.0.12-rc1.

**Comment by somdoron** [comment]
cool. closing the issue
