### ISSUE TITLE
Potential Large Object Heap issue?

### ISSUE THREAD

**Issue by geopars** [zeromq/netmq#198]
Hi,
I have recently come up with an issue of Large Object Heap on the StreamEngine and I would like to check if it is just my bad.

I have a simple design of a QueueDevice to which a number of ResponseSockets are connected. The sockets receive a request from a client to transmit some large data, and they respond accordingly. What I notice after some small check with ANTS is that the more responds the sockets perform the more the m_inpos buffer increases.

Is there any way to avoid this issue?

Here are the screenshots.
http://s7.postimg.org/v4mfhwoqj/Capture1.png
http://s7.postimg.org/opnel8i0r/Capture2.png
http://s7.postimg.org/c8gqy2muz/Capture3.png
http://s7.postimg.org/lhix86vqz/Capture4.png
http://s7.postimg.org/qdmjzvvwb/Capture5.png

**Comment by leverate-somech** [comment]
there is a memory bug, we might already solved it, try to reproduce from following source:
https://github.com/somdoron/netmq

**Comment by geopars** [comment]
Thanks, I will give it a go.

**Comment by geopars** [comment]
I retested it. The problem still persists. If you are transferring large byte arrays (unless you divide them into smaller parts) the ByteArraySegment of m_inpos at the StreamEngine will continue growing the LOH. I am not sure if this is by design though. 

I would appreciate an opinion in order to close the issue.
Thanks

**Comment by somdoron** [comment]
Can you provide code to reproduce?

**Comment by somdoron** [comment]
by the way you can also try to enable the buffer pooling, it might help. Any way let me know how to reproduce.

**Comment by deanroker123** [comment]
Hi Georgios, how big is big?

I had a problem with that, but the fix Doron did resolved it for me.

Thanks

Dean

**Comment by somdoron** [comment]
@geopars can you check if following branch fix the issue?

https://github.com/somdoron/netmq/commits/LOH

**Comment by geopars** [comment]
Hi guys, 
First of all thank you for the replies! 
I will give it a go within the next hours and I will send you an update.

Cheers,
George

**Comment by somdoron** [comment]
@geopars any news?

**Comment by geopars** [comment]
Hi Somdoron,
Your fix does the job. Tested it with big size files and it works smoothly.
