### ISSUE TITLE
OpCode.Open() crash in Unity @ OSX

### ISSUE THREAD

**Issue by barzto** [zeromq/netmq#199]
Hi guys,

we're using NetMQ on Unity (primarily targeting iOS, but also running it on OSX desktop for testing/developing purposes, as it has shorter iteration time). We've encounter Unity crash after calling  (Dealer)Socket.Connect() when running on OSX (in Unity Editor/Desktop Player).

We've tracked the issue to `OpCode.Open()` method, namely to place where `mmap()` is called.
 
```C#
codeBuffer = (IntPtr)mmap.Invoke(null, new object[] { IntPtr.Zero, 
          size, mmapProtsParam, mmapFlagsParam, -1, 0 });
```
It fails for some unknown reason, the `codeBuffer` gets value = -1 (I guess this is the value of MMAP_FAILED). As the return value of `mmap` is not tested anywhere, it gets passed as destination address here:

```C#
Marshal.Copy(rdtscCode, 0, codeBuffer, rdtscCode.Length);
```
Which in turn crashes Unity Player.

I've patched our copy with following (being placed prior calling `Marshal.Copy()`), which basically turns off the RDSTC support.

```C#
                codeBuffer = (IntPtr)mmap.Invoke(null, new object[] { IntPtr.Zero, 
          size, mmapProtsParam, mmapFlagsParam, -1, 0 });

                if (codeBuffer == IntPtr.Zero || codeBuffer == (IntPtr)(-1))
                {
                    throw new InvalidOperationException("Mmap failed");
                }
```

It's not the best solution, but it do its job for us.

Seeing your assembler black magic there (one part of me really likes it, the other is pretty scared :) ), it brings one question to me: How this works on non x86 processors (like on ARM powering iOS devices). I guess it fails at some point and an exception is thrown, which disables RDTSC same way as my "fix", but I just one to bring this question up, so someone with better knowledge of NetMQ internals can properly answer it. 

Anyway great job with NetMQ, we're big fans!
Cheers,
-Jan

**Comment by somdoron** [comment]
@barzto I'm not big fun of it myself, it's a port from the original project, I will look into removing it soon.

Can you provide a pull request with the patch you have made?

**Comment by barzto** [comment]
Here we go: https://github.com/zeromq/netmq/pull/202

**Comment by somdoron** [comment]
thanks
