### ISSUE TITLE
Randomly does not work in long distance

### ISSUE THREAD

**Issue by betimer** [zeromq/netmq#204]
HI, 

I found a weird issue and it did not show any exception.
I use PUB/SUB pattern.
The PUB located in Hong Kong, while the SUB located in Bangkok.
The PUB sends netmq message around every minute. 

The former is the background. Here is phenomenon:
The SUB works for a few days (from 2 to 5) and pending there, cannot get message any more.
However, if the SUB located in Hong Kong as well, this problem never happens.

Does anybody know why this happened? 
Connection lost and SUB cannot recover from it?

**Comment by somdoron** [comment]
Hi @betimer , I'm taking a guess that the subscriber connects and the publisher binds.

TCP is complex, the problem you have is that the connection actually drops but the subscriber doesn't know the connection is down. You have few solutions to this problem:

1. If appropriate you can make the subscriber binds and the publisher connects, the one sending messages is the one knows the connection is down and can then reconnect.
2. Enable tcp keep alive on both the subscriber and publisher.
3. On the publisher side send a keep alive every 30 seconds for example and on subscriber side if you don't receive a message after 90 seconds drop the subscriber and create a new one.
4. If you use xsub and xpub you can actually sends messages from subscriber to publisher (leading byte should be different than zero or one), just make sure to drops the messages on the publisher side. If you don't receive a message in let's say 30 seconds sends a message from subscriber to publisher, this will make the subscriber recognize if the connection is down.

**Comment by betimer** [comment]
Thank you for your explanation.

Is there a function to check whether the connection is alive or not?
So that the subscriber could detect by itself and recover by itself.

**Comment by somdoron** [comment]
As said you can enable tcp keep alive on a socket. Take a look at the
following test:
https://github.com/zeromq/netmq/blob/master/src/NetMQ.Tests/SocketTests.cs#L163

**Comment by deanroker123** [comment]
Hi Doron will the keep alive, reconnect the client and resend the message
if necessary?

I implemented the lazy pirate pattern in my app, but was mostly thinking
about network disconnection, rather than application problems.

Because of this I have had to tune the timeouts of the lazy pirate to take
into account slow upload times for large messages on slow links, but that
makes disconnection slow to detect.

Tcp keep alive would mean I could tune them separately.

Thanks

Dean

**Comment by leverate-somech** [comment]
TCP keep alive will help recognize disconnection but won't resend messages. In my opinion application level solution is better when it is comes to disconnection. I actually prefer to recognize disconnection without a tcp keep alive, I use application keep alive from subscriber to publisher, subscriber then dispose the socket and create a new one if disconnection is recognized.

**Comment by deanroker123** [comment]
I am using request reply socket, rather than publisher subscriber so all I
can go on is the response time and configure my own timeout isn't?

How can the application know that the socket is disconnected and resend the
message if tcp keep alive fails?

**Comment by leverate-somech** [comment]
You don't and shouldn't, I think what you are doing is the correct solution. TCP Keep alive is important for long living connection, not for a single request and it doesn't change the level of reliability of TCP.

**Comment by betimer** [comment]
Thank you for every body here discussing it.
Actually i removed the server in distance to subscribe the publisher.
I will try the keep alive in next product with long distance, especially different countries.
I will chose this issue currently.
:)
