### ISSUE TITLE
NetMQMonitor hangs on stop if monitor exits due to an exception [netmq 3.3.0.12-rc1]

### ISSUE THREAD

**Issue by ndextraze-pbp** [zeromq/netmq#205]
Stopping the NetMQMonitor hangs if monitor exited due to an exception.

InternalClose can be called after an exception on MonitoringSocket, and the first call in InternalClose is on MonitoringSocket which will likely throw again. This call should be enclosed in a try/finally so that the monitor can stop properly.

private void InternalClose()
{
  try 
  {
    MonitoringSocket.Disconnect(Endpoint);
  }
  finally
  {
    IsRunning = false;
    m_isStoppedEvent.Set();
  }
}

**Comment by somdoron** [comment]
@ndextraze-pbp can you provide a pull request?

**Comment by ndextraze-pbp** [comment]
Yes I'll get one ready.
________________________________

**Comment by ndextraze-pbp** [comment]
Submitted a pull request to your repo at https://github.com/somdoron/netmq

**Comment by ndextraze-pbp** [comment]
https://github.com/zeromq/netmq/pull/206
