### ISSUE TITLE
ArgumentOutOfRangeException in publisher.Send(msg)

### ISSUE THREAD

**Issue by thomastvedt** [zeromq/netmq#221]
I'm writing a Lync MSPL application which listens to sip-messages and uses a netmq publisher to send messages to one or more subscribers. It works ok, but sometimes (possibly under heavy load?) I get the following errormessage:

    System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
    Parameter name: index
    at System.Collections.Generic.List'1.get_Item(Int32 index)
    at NetMQ.zmq.Dist.Distribute(Msg& msg, SendReceiveOptions flags)
    at NetMW.zmq.XPub.XSend(Msg& msg, SendReceiveOptions flags)
    at NetMQ.zmq.SocketBase.Send(Msg& msg, SendReceiveOptions flags)
    at NetMQ.OutgoingSocketExtensions.Send(IOutgoingSocket socket, String message, Encoding encoding, SendReceiveOptions options)
    at Myapp.Filter.OnResponse(Object sender, NotificationReceivedEventArgs e)

parts of my publisher code:

    class Filter : IDisposable
    {
      public Filter()
      {
        _netMqContext = NetMQContext.Create();
        _publisherSocket = _netMqContext.CreatePublisherSocket();
        _address = "tcp://*:7878";
        _publisher.Bind(_address);
      }

     public void OnResponse(object sender, NotificationReceivedEventArgs e)
     {
        _publisherSocket.Send(message, encoding)
     }

	public void Dispose()
	{
		try
		{
			if (_publisher != null)
			{
				_publisher.Unbind(_address);
				_publisher.Dispose();
			}
			if (_netMqContext != null)
			{
				_netMqContext.Dispose();
			}
		}
		catch (Exception exception)
		{
			Log.Error(exception);
		}
	}
   }

I'm sure that I'm doing something wrong, can you see what is causing the errormessage?

**Comment by krisrok** [comment]
where is OnResponse called from? another thread maybe?

**Comment by leverate-somech** [comment]
@thomastvedt can you test if this also happen on version v3.3.0.12?

**Comment by leverate-somech** [comment]
also as @krisrok mentioned, any chance you are using the socket on multiple threads?

**Comment by thomastvedt** [comment]
Hmm, I thought it was only using one thread. I'm running a windows service, spawning a new Thread, and all of my interactions with NetMQ is in this thread. But I noticed when logging with log4net that OnResponse is actually called by different threads. OnResponse is called by Lync (https://msdn.microsoft.com/en-us/library/office/hh364644(v=office.14).aspx). Thanks for the tip, I'm looking at this now.

I'll also try to update from v3.3.0.11 to v3.3.0.12

**Comment by thomastvedt** [comment]
If I do this:

     public void OnResponse(object sender, NotificationReceivedEventArgs e)
     {
        lock(_object)
        {
            _publisherSocket.Send(message, encoding)
         }
     }

Is this an "anti-pattern" in zmq? Or is it ok to do this?
http://zguide.zeromq.org/page:all#Chapter-Sockets-and-Patterns : "Stay away from the classic concurrency mechanisms like as mutexes, critical sections, semaphores, etc. These are an anti-pattern in ZeroMQ applications."

SUB---PUB(Filter)---- Lync T1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |-- Lync T2

Could I do something like this? :

SUB---DEALER---- PUB Lync T1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |-- PUB Lync T2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|-- PUB Lync T3

**Comment by somdoron** [comment]
it is not the prefer solution, but it is ok.

**Comment by tobi-tobsen** [comment]
Also, see this question and associated answers: http://stackoverflow.com/questions/5841896/0mq-how-to-use-zeromq-in-a-threadsafe-manner

**Comment by krisrok** [comment]
also there is the NetMQScheduler which is quite nice if you're already working with the TPL/TAP. but whatever path you choose, you HAVE to be aware of the pitfalls that come with each of them.

[here's somdoron's relevant blog entry](http://somdoron.com/2013/06/netmq-scheduler/)

**Comment by thomastvedt** [comment]
Service has been running ok now for two days without any exceptions after I syncronized OnResponse :+1: Thanks for many good answers :sake:

**Comment by krisrok** [comment]
just out of interest - which route did you take?

**Comment by thomastvedt** [comment]
I just
