### ISSUE TITLE
code formatting: tab size

### ISSUE THREAD

**Issue by krisrok** [zeromq/netmq#222]
just a little petty issue:

the readme.md says:
> Make sure you are using Keep Spaces and 2 for tab and indent size.

but all the code seems to be formatted with 4 chars for tab/indent size. 

i'm all for the suggestion in the readme, but i guess for most of you it will be easier to just adjust the readme text.

**Comment by krisrok** [comment]
and i guess it should read "insert spaces" as it's the setting's name in visual studio

**Comment by somdoron** [comment]
yes. Please fix the readme.
