### ISSUE TITLE
CreateMonitorSocket creates pair socket with no owner

### ISSUE THREAD

**Issue by dnallicus** [zeromq/netmq#223]
The useful function CreateMonitorSocket will create a pair socket inside of it.  But since the monitor doesn't own the pair socket, it is never disposed, and thus the context will hang on disposal.

Example, it will hang on context.Dispose:

            var context = NetMQ.NetMQContext.Create();
            using(var monitorSocket = context.CreateMonitorSocket(@"inproc://montior1234"))
            {
                System.Console.WriteLine(monitorSocket.Endpoint);
            }
            context.Dispose();

Doing the same thing as the CreateMontorSocket but putting the pair socket in a using will work though:

            var context = NetMQ.NetMQContext.Create();
            using (var pairSocket = context.CreatePairSocket())
            using (var monitorSocket = new NetMQMonitor(pairSocket, @"inproc://montior1234"))
            {
                System.Console.WriteLine(monitorSocket.Endpoint);
            }
            context.Dispose();

Maybe add a flag to the NetMQMonitor that defaults to false that signals whether or not the monitor should own the pair socket?

**Comment by somdoron** [comment]
do you want to provide the pull request?

**Comment by dnallicus** [comment]
Sure, if you think that is a good solution.  I can add that example above as a test as well.

**Comment by somdoron** [comment]
Great.

**Comment by Nebula83** [comment]
What is the status of this? And could it be related to  https://github.com/zeromq/netmq/issues/310?

**Comment by dnallicus** [comment]
Ah, I need to commit this fix still, sorry.  It is unrelated though, in #310
<https://github.com/zeromq/netmq/issues/310> it is using the constructor
rather than the CreateMonitorSocket function.  If it was
using CreateMonitorSocket, it would hang on the first monitor.Dispose();

**Comment by drewnoakes** [comment]
Put a small PR together for this. Thanks for the bug report.

**Comment by Nebula83** [comment]
Thanks guys! Any news when this will be released?

**Comment by drewnoakes** [comment]
Can get a new prerelease build out today, but the question of a new stable
release is still open.

**Comment by Nebula83** [comment]
Ah I see. What is blocking the new stable release? Can I help in some way?

**Comment by drewnoakes** [comment]
Discussion is happening in #342.

**Comment by drewnoakes** [comment]
`NetMQ.3.3.0.13-alpha594` is now available on NuGet as a prerelease package.

**Comment by Nebula83** [comment]
Great, thanks!
