### ISSUE TITLE
HelloWorld hangs in Context.Dispose on Unity

### ISSUE THREAD

**Issue by barzto** [zeromq/netmq#230]
Hi guys,

I've got this code derived from HelloWorld example

``` C#
private static void TestNetMQ()
{
    using (NetMQContext ctx = NetMQContext.Create())
    {
        using (var server = ctx.CreateResponseSocket())
        {
            server.Bind("tcp://127.0.0.1:5556");

            using (var client = ctx.CreateRequestSocket())
            {
                client.Connect("tcp://127.0.0.1:5556");
                client.Send("Hello");
                string m1 = server.ReceiveString();
                server.Send("Hi Back");
                string m2 = client.ReceiveString();
            }
        }
    }
}

```

When I run it in standalone Mono installed form MacPorts on OSX, it runs without any issue, but when I run it in Unity Editor, it hangs when disposing context. I've tracked down the place  where main-thread gets dead-locked:

```
System.Net.Sockets.Socket.Poll (time_us=-1000, mode=The requested item has been unloaded.) in 
NetMQ.zmq.Utils.Signaler.WaitEvent (timeout=-1) in .../Assets/Scripts/ThirdParty/NetMQ/src/zmq/Utils/Signaler.cs:118
NetMQ.zmq.Mailbox.Recv (timeout=-1) in .../Assets/Scripts/ThirdParty/NetMQ/src/zmq/Mailbox.cs:208
NetMQ.zmq.Ctx.Terminate () in .../Assets/Scripts/ThirdParty/NetMQ/src/zmq/Ctx.cs:209
NetMQ.NetMQContext.Terminate () in .../Assets/Scripts/ThirdParty/NetMQ/src/NetMQContext.cs:267
NetMQ.NetMQContext.Dispose () in .../Assets/Scripts/ThirdParty/NetMQ/src/NetMQContext.cs:273
```

The standalone mono's --version is:

```
Mono JIT compiler version 3.12.0 ((detached/de2f33f Mon Feb  2 14:42:07 EST 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           normal
    SIGSEGV:       altstack
    Notification:  kqueue
    Architecture:  x86
    Disabled:      none
    Misc:          softdebug 
    LLVM:          yes(3.6.0svn-mono-(detached/5486eb2)
    GC:            sgen
```

The Unity editor's mono is:

```
Mono JIT compiler version 2.6.5 (tarball Mon Jan 19 16:08:20 CET 2015)
Copyright (C) 2002-2010 Novell, Inc and Contributors. www.mono-project.com
    TLS:           normal
    GC:            Included Boehm (with typed GC)
    SIGSEGV:       normal
    Notification:  Thread + polling
    Architecture:  x86
    Disabled:      none
```

Both running OSX 10.9.

Any idea what can go wrong here? Any good place to put breakpoint, log etc.?

Cheers,
-Jan

**Comment by somdoron** [comment]
There is anyway I can try to reproduce this on linux machine? It will be hard to solve this only by the stacktrace...

**Comment by krisrok** [comment]
i've tested around a bit with a minimal chat app in unity on osx and exported to ios with success. i remember it wasn't exactly plug n play though. i'll l

**Comment by barzto** [comment]
I was able to reproduce this issue on OSX and Windows. I've made a small repo with Unity project you can use to debug it---https://github.com/barzto/netmq-unity-reaperissue. You'll need to get Unity Pro (to get System.Socket API access), fortunately there's 30 day trial available. Unfortunately there's no Unity for Linux, only OSX & Win.

If you open TestScene in project, and run it, it'll get freeze. There's a Run.cs file which is executed on scene launch and runs the HelloWorld sample. There's also simple logging utility that logs to file (see <projectRoot>/Game.log).

If you take look in this log, there're logged ZObject.ProcessCommand executions. You should see something like this:
```
<<ProcessCommand(Plug)>>
<<ProcessCommand(Plug)>>
<<ProcessCommand(Plug)>>
<<ProcessCommand(Own)>>
<<ProcessCommand(Own)>>
<<ProcessCommand(Plug)>>
<<ProcessCommand(Own)>>
<<ProcessCommand(Attach)>>
<<ProcessCommand(Own)>>
<<ProcessCommand(Attach)>>
<<ProcessCommand(TermReq)>>
<<ProcessCommand(Bind)>>
<<ProcessCommand(Term)>>
<<ProcessCommand(TermAck)>>
<<ProcessCommand(ActivateRead)>>
From Client: Hello
<<ProcessCommand(ActivateRead)>>
<<ProcessCommand(ActivateWrite)>>
<<ProcessCommand(ActivateRead)>>
From Server: Hi Back
<<Sending Reap>>
<<Sending Reap>>
```

If I compile the same code with standalone Mono and run HelloWorld app, I get this log output

```
<<ProcessCommand(Plug)>>
<<ProcessCommand(Own)>>
<<ProcessCommand(Plug)>>
<<ProcessCommand(Plug)>>
<<ProcessCommand(Own)>>
<<ProcessCommand(Own)>>
<<ProcessCommand(Plug)>>
<<ProcessCommand(Own)>>
<<ProcessCommand(Attach)>>
<<ProcessCommand(Bind)>>
<<ProcessCommand(Attach)>>
<<ProcessCommand(TermReq)>>
<<ProcessCommand(Term)>>
<<ProcessCommand(TermAck)>>
<<ProcessCommand(ActivateRead)>>
From Client: Hello
<<ProcessCommand(ActivateRead)>>
From Server: Hi Back

<<Sending Reap>>
<<Sending Reap>>
<<ProcessCommand(Reap)>>
<<ProcessCommand(PipeTerm)>>
<<ProcessCommand(ActivateRead)>>
<<ProcessCommand(Reap)>>
<<ProcessCommand(Term)>>
<<ProcessCommand(ActivateWrite)>>
<<ProcessCommand(Stop)>>
<<ProcessCommand(PipeTermAck)>>
<<ProcessCommand(ActivateWrite)>>
<<ProcessCommand(Stop)>>
<<ProcessCommand(PipeTerm)>>
<<ProcessCommand(ActivateRead)>>
<<ProcessCommand(Term)>>
<<ProcessCommand(PipeTermAck)>>
<<ProcessCommand(PipeTermAck)>>
<<ProcessCommand(TermAck)>>
<<ProcessCommand(PipeTermAck)>>
<<ProcessCommand(Term)>>
<<ProcessCommand(TermAck)>>
<<ProcessCommand(Reaped)>>
<<ProcessCommand(TermAck)>>
<<ProcessCommand(Stop)>>
<<ProcessCommand(Reaped)>>
<<REAPED>>
<<ProcessCommand(Stop)>>

```

**Comment by krisrok** [comment]
unity pro is only needed for sockets on ios (and possibly android), so the free version for osx/win is fine.

i'm currently looking into my old project too. it works with a manual polling strategy (using a coroutine) most of the time, but sometimes it just freezes on startup.

**Comment by barzto** [comment]
I think I've tracked down where the problem is. It looks like Socket.Select never marks a read socket. So the Utils.Poller.Loop() (used by Reaper) never ends.

Here's the min repro I've compiled out of NetMQ sources if you're interested:
```C#
    private Socket _readSocket;
    private Socket _writeSocket;
    private byte[] _dummyRead = new byte[]{0};
    private byte[] _dummyWrite = new byte[]{0};
    
    private void MakeSocketsPair()
    {
        using (Socket listner = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Unspecified))
        {
            listner.NoDelay = true;
            listner.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
            
            // using ephemeral port            
            listner.Bind(new IPEndPoint(IPAddress.Loopback, 0));
            listner.Listen(1);
            
            _writeSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Unspecified);
            _writeSocket.NoDelay = true;
            
            _writeSocket.Connect(listner.LocalEndPoint);
            _readSocket = listner.Accept();
        }            
    }
    
    // Use this for initialization
    void Start()
    {
    	MakeSocketsPair();
    
	    int sent = _writeSocket.Send(_dummyWrite);
        Base.Utils.GameDebug.Assert(sent == 1);
        
		List<Socket> readList = new List<Socket>();
		List<Socket> writeList = new List<Socket>();
		List<Socket> errorList = new List<Socket>();
		while (true)
        {
        	readList.Clear();
			writeList.Clear();
			errorList.Clear();
			readList.Add(_readSocket);
			errorList.Add(_readSocket);
			
			Socket.Select(readList, writeList, errorList, 0);
			
			if (readList.Count > 0)
			{
				Base.Utils.GameDebug.Log("Read ready");
                
				break;
			}
			Base.Utils.GameDebug.Log("Tick");
        }
		
		int recv = _readSocket.Receive(_dummyRead);
		Base.Utils.GameDebug.Assert(recv == 1);
    }
```

I've created Unity Bug Report with this code, so hopefully I'll hear from UT guys soon.

**Comment by somdoron** [comment]
I think somebody actually report is in the past and suggest a workaround, will look for that. I think it is a bug in specific mono version

**Comment by barzto** [comment]
@somdoron That would be great, if there's a workaround for this. At this point we're blocked with this issue. I was googling to find out on my own, if there's some workaround, but haven't found yet anything useful, only forum post from 2010, that looks like the issue with Socket.Select in Unity is for last 5 years (which makes me less optimistic about chance guys at Unity Technologies will fix this easily).
So any hints how to get around this are more then welcomed ;)

**Comment by somdoron** [comment]
@barzto read the following thread and specifically this comment:

https://github.com/zeromq/netmq/issues/98#issuecomment-60374763

a link for the workaround:

https://github.com/fredrikm/netmq/commit/b8863879122a8518f029ae8648bd5b95b3c7f6ac?w=1

The change a bit but found the Socket.Select code and apply the patch.

You can also send a pull request with the patch if you can apply it only when running with mono and the problematic version.

**Comment by barzto** [comment]
Thanks @somdoron , that helped a lot. I've put extra Socket Poll to SocketUtility.Select, and I'm able to create and dispose Context without freeze. However if there're two contexts created (in series, i.e. context A created, A disposed, B created, B disposed), the app freezes in same Select and extra Poll is not helping.

It's not big issue for me, as one context is enough for our use case, but I wouldn't call this as final fix.

Btw. for testing purpose I've created Select implementation via Poll (absolutely ineffective of course), and it has the same problem. socket.Poll(0, SocketRead) never returns socket being ready for read. So it makes me thing there's some issue with Mono 2.6 Unity is still using.

**Comment by n1cholson** [comment]
It appears that the NetMQ plugin for Unity installs NetMQ version 3.3.0.12, instead of the current stable release 3.3.0.11 from nuget.  Could this be part of the problem?  The sample CS script in the Unity package hangs during .receiveString.  Adding a timeout to the sample script receiveString call avoids the timeout but no messages are ever received.  Tried with Unity 4 and Unity 5, same results.  Also happens if rewritten to use Pub Sub.  Going to try reverting to 3.3.0.11 with Unity and see if that helps.

**Comment by fostebr** [comment]
Just wondering what the status was with this?  I'm experiencing the same exact issue running the OP's code on Windows, building with Visual Studio 2013.  I currently have the dispose call commented out in my actual code, but that's certainly not a fix at all.  I using the current master branch as well.

**Comment by barzto** [comment]
@fostebr As you mentioned you use Visual studio to build the code, I'm wondering if we're both talking about running NetMQ in Unity? (Sounds to me like you're building plain .Net app)

I've reported the issue with `Socket.Select()`, which seems to work incorrectly in Unity (i.e. in Mono they're using to run Editor & Game runtime). The bug report number is 674077 and it's marked still as opened in fogbugz tracker.


Looking into my mailbox, this is the last info I've got from Unity QA team (received on 2015-03-30):

> We have been able to reproduce this bug on mac 10.8 and have sent it for resolution with our developers. We cannot say when the resolution will be publicly available.

In our code, we're still using the extra Socket.Poll I was mentioning above...

**Comment by fostebr** [comment]
Correct, I'm just using plain .NET.  I guess I made the poor assumption it'd be the same fix across the board.  Should I submit a separate issue for the environment I'm experiencing it in?

**Comment by drewnoakes** [comment]
@fostebr, first of all make sure you're using the latest *pre-release*
version from NuGet. If so, then open a new issue.

**Comment by fostebr** [comment]
Tried the latest pre-release from NuGet (3.3.0.13-alpha594), still get the same behavior of dispose never returning.  However, after looking through some of the other issues, I've noticed that https://github.com/zeromq/netmq/issues/357 is more likely the culprit.  It is exactly what I'm trying to do.  (Apologies for bumping this thread.  I didn't see the other issue at first.)

**Comment by Sokharev** [comment]
Hello, I've expirienced the same problem in Unity (connect/send/dispose context hangs) with latest version and found problem in Ctx.cs in method Terminate(). I'am not sure that it's "right" but in my case it hangs in this line:
```Java
Command cmd = m_termMailbox.Recv(-1);
```
if've wrapped it with final "Poll" ( but for sure it's dirty & hacky ) and Unity Editor works ok now(no hangs)
```Java
if( m_termMailbox.Handle.Poll( 100, System.Net.Sockets.SelectMode.SelectRead ) )
{
    if (m_termMailbox.Handle.Connected)
       {
         Command cmd = m_termMailbox.Recv(-1);
         Debug.Assert(cmd != null);
         Debug.Assert(cmd.CommandType == CommandType.Done);
        }
}
```
@somdoron Could you please comment how to fix in right manner?

**Comment by somdoron** [comment]
Did you try the ForceDotNet.Force(); at the beginning of the application?

**Comment by somdoron** [comment]
When context hangs it is usually a sign that one of the sockets was not
closed properly.

Few solutions for this:
* Find out which socket is causing the problem
* Don't close the context, application will just die
* A new feature to close the context even if sockets are still alive.

**Comment by Sokharev** [comment]
@somdoron 
Yes, i'am doing AsyncIO.ForceDotNet.Force(); at very beginning.
Also i'am doing following:
1.I'am doing create/connect/send despite router server not running( ie no one listening )
2. start sending heartbeat messages
3. after 1-2 messages stopping editor and doing socket/context dispose.

**Comment by somdoron** [comment]
disposing socket is an async, so maybe because the messages are still
pending the socket is not being closed.

Try to set the socket linger to zero, it might solve the problem.

**Comment by Sokharev** [comment]
@somdoron Tried - it's really helps! thank you. But i'am not sure - is it breaks something else?

**Comment by somdoron** [comment]
No, the change cause the socket to be closed even if their are messages
pending.

The default behavior is to wait for all messages to be sent before closing,
you can change linger to number of seconds you want to wait for messages
before closing.

Because in your example the server is not up the socket will wait forever
