### ISSUE TITLE
NetMQ 3.3.0.11, SocketExceptions

### ISSUE THREAD

**Issue by JamesWHurst** [zeromq/netmq#231]
Greetings, I'm getting a slew of exceptions with just the first, most trivial of your code examples!

Using this..

```
            using (NetMQContext ctx = NetMQContext.Create())
            {
                using (var server = ctx.CreateResponseSocket())
                {
                    server.Bind("tcp://127.0.0.1:5556");
                    using (var client = ctx.CreateRequestSocket())
                    {
                        client.Connect("tcp://127.0.0.1:5556");
                        client.Send("Hello");

                        string m1 = server.ReceiveString();
                        Console.WriteLine("From Client: {0}", m1);
                        server.Send("Hi Back");

                        string m2 = client.ReceiveString();
                        Console.WriteLine("From Server: {0}", m2);
                        //Console.ReadLine();
                    }
                }
            }
```

In a Console application, in Debug mode, I am getting 8 SocketExceptions, 1 NetMQ.NetMQException, and 4 NetMQ.TerminatingExceptions !  What am I doing incorrectly?

Console output:
A first chance exception of type 'System.Net.Sockets.SocketException' occurred in System.dll
...
A first chance exception of type 'NetMQ.TerminatingException' occurred in NetMQ.dll

I'm using Visual Studio 2013 Ultimate, update 4, creating a C# library with .NET 4.5.1, "Any CPU", on Windows 7 x64.

Thank you for your help.

**Comment by somdoron** [comment]
also which version of netmq?

**Comment by somdoron** [comment]
I also think you have raise exceptions on the debug option.

**Comment by JamesWHurst** [comment]
NetMQ 3.3.0.11, and yes - this is in DEBUG mode. Are these exceptions that we expect in DEBUG mode, and which are being considered as normal?
I have not tried to drill down into the source-code to find these. But I do find it somewhat concerning, if we're accepting this as okay - as you know C# exceptions are relatively expensive, and it is considered a best-practice to *not* throw exceptions in the normal program-flow.  Or am I mistaken in this case?

**Comment by somdoron** [comment]
James I completely agree that exceptions should not be part of the main
flow (and I try to remove them as much as possible). Most of the exceptions
that you see are part of the context/socket dispose.

However I will take another look to try and minimize the exceptions. Any
pull requests are also welcome.

**Comment by chinattw** [comment]
Runing NETMQ
Win7 IS Succeed
Windows XP SP3 Is Faild

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.EntryPointNotFoundException
Stack:
   at AsyncIO.Windows.UnsafeMethods.GetQueuedCompletionStatusEx(IntPtr, IntPtr, Int32, Int32 ByRef, Int32, Boolean)
   at AsyncIO.Windows.CompletionPort.GetMultipleQueuedCompletionStatus(Int32, AsyncIO.CompletionStatus[], Int32 ByRef)
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by aungcodium** [comment]
Before you call any NetMQ Function, please add this line in your code at one time only.
AsyncIO.ForceDotNet.Force();

**Comment by dalebrubaker** [comment]
Why? What does this do?

**Comment by somdoron** [comment]
So async.io used pinvoke calls to win32 methods. Some frameworks like unity
does not support it. This call enforce async io to use regular .net sockets.

**Comment by migelU** [comment]
>>Runing NETMQ
>>Win7 IS Succeed
>>Windows XP SP3 Is Faild
Windows XP doesn`t  support **GetQueuedCompletionStatusEx** API
You need to modify AsyncIO library to work on Windows XP.
P.S 
I already done this and anyone intereesting in patch?

**Comment by sharpe5** [comment]
Definitely! You can fork the repositoy then create a pull request, or, failing that, send a patch in and we can create a pull request for you.

**Comment by migelU** [comment]
done:
https://github.com/somdoron/AsyncIO/pull/9

**Comment by eberkund** [comment]
I am getting a `NetMQ.TerminatingException` when I close my application from debug mode. Otherwise it doesn't affect my application's functionality but I would like to find the cause and prevent it from popping up every time if possible.

**Comment by somdoron** [comment]
Are you closing all of the sockets before the application exists?

**Comment by eberkund** [comment]
@somdoron, that turned out to be the issue. Thanks.
