### ISSUE TITLE
JetBrains.Annotations

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#232]
The `NetMQ.csproj` includes the `JetBrains.Annotations` namespace, however no code in the `NetMQ.dll` uses these annotations.

Is there interest in a PR that introduces these annotations?

If so, which annotations? `CanBeNull` and `NotNull` are probably the most useful. After that, `Pure` and `InstantHandle`.

Also the annotations are a bit out of date now. R# 9 includes quite a few new ones and seems to allow them to be included conditionally based upon the `JETBRAINS_ANNOTATIONS` compiler symbol (I haven't tried this).

All the ASP.NET annotations could probably be removed, along with a few other unused ones.

The benefit of applying these annotations is that users of NetMQ who also use ReSharper can have better feedback about incorrect of sub-optimal usage of the library.

**Comment by somdoron** [comment]
someone in the past added this but I don't think it is in use now.

Pull request will be great :-)
