### ISSUE TITLE
Intermittent exceptions in NetMQ.zmq.ZMQ.Poll

### ISSUE THREAD

**Issue by msykora** [zeromq/netmq#234]
Hello,

I am using NetMQ with poller and due to my requirements I need to dynamically add and remove multiple sockets during the app lifecycle. I am getting exceptions when removing the last/only socket from the poller while it's still running, sometimes it's an ObjectDisposedException, sometimes an ArgumentNullException, it is very intermittent (1 in ~10 runs) so I'm assuming a race condition when I remove/dispose the socket in just the wrong moment when the Poller is working...

The ArgumentNullException message is "Value cannot be null. Parameter name: All lists are either null or empty."
Stack trace:
   at System.Net.Sockets.Socket.Select(IList checkRead, IList checkWrite, IList checkError, Int32 microSeconds)
   at NetMQ.zmq.ZMQ.Poll(PollItem[] items, Int32 itemsCount, Int32 timeout)
   at NetMQ.Poller.PollWhile(Func`1 condition)
   at NetMQ.Poller.Start()
   at NetMQTest.Program.<>c__DisplayClass5.<Main>b__1() in c:\Users\sykoram\Documents\Visual Studio 2013\Projects\AsposeTest\NetMQ\Program.cs:line 29
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

some really silly sample code that will produce this if you run it enough times:

```
        var context = NetMQContext.Create();
        using (NetMQSocket requestSocket = context.CreateRouterSocket(), replySocket = context.CreateRouterSocket()) {
            var poller = new Poller();
            replySocket.Options.Linger = TimeSpan.Zero;
            replySocket.Options.Identity = Encoding.UTF8.GetBytes("server");
            replySocket.Bind("ipc://test");
            replySocket.ReceiveReady += (sender, revents) => {
                NetMQMessage msg = revents.Socket.ReceiveMessage();
                Console.WriteLine("msg received:" + Encoding.UTF8.GetString(msg[2].Buffer));
            };
            requestSocket.Options.Linger = TimeSpan.Zero;
            requestSocket.Options.Identity = Encoding.UTF8.GetBytes("client");
            requestSocket.Connect("ipc://test");
            Console.WriteLine("requestSocket connected");
            poller.AddSocket(replySocket);
            poller.PollTimeout = 50;
            Task.Factory.StartNew(() => {
                poller.Start();
                Console.WriteLine("Poller stopped");
            }, TaskCreationOptions.LongRunning);
            Console.WriteLine("Poller started");
            Thread.Sleep(500);
            requestSocket.SendMessage(new NetMQMessage(new byte[3][] { Encoding.UTF8.GetBytes("server"), new byte[0], Encoding.UTF8.GetBytes("hi") }));
            requestSocket.SendMessage(new NetMQMessage(new byte[3][] { Encoding.UTF8.GetBytes("server"), new byte[0], Encoding.UTF8.GetBytes("hi again") }));
            Thread.Sleep(500);
            Console.WriteLine("Poller removing socket");
            poller.RemoveSocket(replySocket);
            replySocket.Dispose();
            Console.WriteLine("Poller removed socket");
            Thread.Sleep(500);
            Console.WriteLine("Poller disposing");
            poller.Dispose();
            Console.WriteLine("Poller disposed");
            Thread.Sleep(500);
            Console.WriteLine("Poller isrunning:" + poller.IsStarted);
        } 
```

If the mistake is on my side, by all means correct me, and I know I should ideally stop polling first before removing the last socket, but as they come and go dynamically, that would mean I would need to keep information about the number of socket in the poller in a thread safe way and stop it before removing the last one...

**Comment by somdoron** [comment]
what version do you use?

**Comment by somdoron** [comment]
ahh poller is not thread safe. After starting the poller all the changes
must happen within the poller thread.

You can use NetMQScheduler to do that (invoke all the method inside a task
and start it on the netmqscheduler which attached to the poller)

**Comment by msykora** [comment]
I'm using the newest version from nuget, 3.3.0.11, I noticed code in here seems newer, but I have to use the nuget version :)

**Comment by somdoron** [comment]
There is a pre release version on nuget. I will release new version this
weekend. Anyway I think the issue you have is about thread safety

**Comment by msykora** [comment]
I realize that, I just expected Poller to be thread safe, I don't want to do all the work on a single thread. Just to be sure I understand correctly, I would need to invoker all socket methods on the poller thread, even send/receive? or just the Poller methods, as in AddSocket and RemoveSocket?

**Comment by msykora** [comment]
I definitely do not want to do all processing for a socket on my server (with potentially hunderds of client sockets connected) on a single thread, does that mean, if I want to do work with sockets on independent threads, each should have its own Poller?

**Comment by ndextraze-pbp** [comment]
Poller Stop and Dispose method are thread safe, but not RemoveSocket. You don't need to remove the socket before disposing of the Poller.

If you want to handle work receive by your socket on more than one thread you should start a new Task in the ReceiveReady method for each message you want to handle. Keep in mind that socket are  not thread safe, so if you need to respond use appropriate locking mechanism or NetMQScheduler.

**Comment by ndextraze-pbp** [comment]
Also if you want to do thread work with the received messages, you should use another pattern than request-reply. A reply socket can answer only the last request it has receive, so in a worker pattern that would be hard to accomplish. Try using push-pull.

**Comment by msykora** [comment]
The problem is I need to Dispose a socket that I no longer need, ideally while the Poller keeps running... If I don't do RemoveSocket I just get another exception about using a Disposed object...
And I'm using dealer and router, not req rep sockets, can't use push pull since communication is both ways.

**Comment by ndextraze-pbp** [comment]
Sorry got confuse by the name of the variable. I'm trying to understand what you are trying to do here. If you are using dealer - router pattern, then you only need one router socket on the server side. Why do you have more than one socket and why do you need to dispose of it and remove it from the Poller?

**Comment by msykora** [comment]
Actually, we use the dealer socket only for a security handshake (negotiating the protocol, exchanging the session encryption key, getting the server socket identity so the client can then switch to router without needing to know the identity beforehand), the actual communication is router - router because we want the behavior to be symmetric (no queuing when other side is unavailable and then flooding it with messages) as our model is more peer to peer than client-server, really. And exactly because of this, the client peer starts with a dealer socket, does handshake, then gets rid of it and connects via router socket with message level encryption.

Having said that, I could probably just use different Pollers for those 2 sockets on the client, not much overhead there, the dealer is only for establishing the session, but still, I might want to connect to several peers to consume different services they offer, and disconnect again, etc. and I would prefer to use one Poller just as I use one Context in every instance of my communication library...

**Comment by msykora** [comment]
Even the start - dispose combination doesn't seem to be thread safe, this code throws a "Poller Disposed" exception in the Start task:
                var poller = new Poller();
                poller.PollTimeout = 100;
                var scheduler = new NetMQScheduler(context, poller);
                var pollTask = Task.Factory.StartNew(() => {
                    Console.WriteLine("Poller started");
                    poller.Start();
                    Console.WriteLine("Poller stopped");
                }, TaskCreationOptions.LongRunning);
                Thread.Sleep(500);
                new Task(() => {
                    Console.WriteLine("Disposing Poller");
                    poller.Dispose();
                    Console.WriteLine("Poller disposed");
                }).Start(scheduler);
                Console.WriteLine("waiting for Poller to stop");
                pollTask.Wait();

The only way I was able to actually dispose the Poller without that exception was to do Poller.Stop() first, wait for the pollerTask to stop and then Dispose(). Which feels very useless btw after I already stopped the Poller and I am only doing it to avoid that finalizer...

**Comment by somdoron** [comment]
@msykora we can do multiple things to solve this, I agree with your point regarding the dispose, the dispose actually call cancel but doesn't wait for it to complete, we should change that so it will wait and it will solve your problem, do you want to make a pull request for that?

We can make poller add and remove thread safe by using a scheduler internally.
We can also change the poller so it will always have a default scheduler attach to it (and expose as public), it will be useful for async and await keywords used inside poller thread (we would also have to implement SynchronizationContext for that).

**Comment by msykora** [comment]
Another thing that baffles me is the temporal coupling between poller and scheduler, when I use the scheduler, I have to dispose it before stopping the poller, otherwise scheduler dispose will hang forever, same for context dispose...

**Comment by somdoron** [comment]
regarding the scheduler, you are right, I think somebody submitted a pull request few days ago for that.

Regarding the context, yes this is another annoying issue, getting the context dispose it's not easy.  You have to make sure you actually disposed all of your sockets. I want to make a default static context and make the context obsolete. That will make life easier.

**Comment by msykora** [comment]
It would be great if add and remove were thread safe, as well as dispose. To be honest, I am not sure how this works, with the pull request :-)

For context, yeah sockets need to be disposed, that comes with ZMQ, but even without sockets, when I create a scheduler and then stop poller before scheduler is disposed, the context dispose will hang...

**Comment by krisrok** [comment]
to create a pull request:
fork the project (button top right)
pull the fork from your github account
apply changes and commit (try to be concise doing both), then push
in the fork's github site choose 'new pull request'

**Comment by krisrok** [comment]
as for the issue discussed here, i'm all for making netmq easier to handle in multithreaded environments. but isn't that what zmq is trying to solve anyways? :)

**Comment by msykora** [comment]
I was afraid so, never touched an open source project, before, scary :-)

**Comment by somdoron** [comment]
Make sure to read [C4.1](http://rfc.zeromq.org/spec:22) this what we follow, we try to make it very easy to contribute to NetMQ (working well so far), so don't be afraid.

**Comment by somdoron** [comment]
take a look at:
https://github.com/zeromq/netmq/issues/98#issuecomment-60374763

and the actual patch:
https://github.com/fredrikm/netmq/commit/b8863879122a8518f029ae8648bd5b95b3c7f6ac?w=1

project changed a little since then so you need to find the place and apply the patch.

If you want to make a pull request that will be great, but we need to find a way to only apply this to the specific version of mono that has this bug.

**Comment by msykora** [comment]
Sorry, my workload has been slightly crazy in the last month and it doesn't seem to let up, and even though this is not a big change, I don't want to take it lightly... i am not sure when I can do this...
