### ISSUE TITLE
Proxy with external Poller

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#239]
Would this be a useful pattern?

Currently a Proxy produces its own internal poller in `Proxy.Start`. The method could be overloaded to accept an external poller.

`Proxy.Stop` would either throw or no-op when an external poller was provided.

**Comment by somdoron** [comment]
@drewnoakes do you want to join the maintainers of netmq? make sure to read:

http://rfc.zeromq.org/spec:22

Regarding your question, if you have a real problem so yes it will make a good solution.

**Comment by drewnoakes** [comment]
@somdoron, ok I'll make a pull request.

Thanks for the pointer to C4. It's a good specification.

I would be happy to help maintain the library. Over the next few months I expect to be using it quite heavily so will learn more about the project and what's needed.

As for using an external `Poller` with `Proxy`, I'll get a PR together.

**Comment by somdoron** [comment]
Great. I gave you maintainer rights. You can now merge pull requests.
