### ISSUE TITLE
Can the NetMQ.zmq namespace's types be made internal, recursively?

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#241]
What is the purpose of the `NetMQ.zmq.*` namespaces? My assumption is that they're for internal types that map neatly to the concepts of the canonical library, or some such.

As a consumer of NetMQ, I hit upon annoyances where types with the same name existed in both namespaces, and somehow `using NetMQ.zmp` and similar appeared in my code, and then all sorts of weird disambiguation code started to creep in. For example, the commonly used class `Poller` exists in both `NetMQ` and `NetMQ.zmq.Utils`.

Would it make sense to just mark everything in that namespace as `internal` to the assembly?

For unit tests, the `[InternalsVisibleTo]` attribute should suffice.

**Comment by drewnoakes** [comment]
Hmm... just checked `Poller` again and it seems to be `internal` already. This may be a difference between the current NuGet package and `master`, or my memory may have bits flipped.

Either way, there are still other types in these namespaces which are not internal. Should they be encapsulated, or are they intended to appear in user code?

**Comment by somdoron** [comment]
@drewnoakes the idea is to make the entire zmq internal, so yes we can make everything internal. However we need to make sure we don't do that for used classes, I can think of  Blob (which is obsolete) but maybe there are more.

**Comment by drewnoakes** [comment]
@somdoron actually `Blob` is in the project's root namespace, so there's no problem there. The list of affected types is in the PR's diff. Do you think any of those would be problematic?

**Comment by somdoron** [comment]
Seems fine. We will know soon if somebody will complain
