### ISSUE TITLE
Icon for NuGet package

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#242]
The current `NetMQ.nuspec` file omits the `<iconUrl>` element.

According to the [Nuspec reference](http://docs.nuget.org/Create/Nuspec-Reference):

> This should be a 32x32-pixel .png file that has a transparent background.

Here are two possible options:

![nuget-icon-1](https://cloud.githubusercontent.com/assets/350947/6311905/af2a6bcc-b962-11e4-868f-d0cdfa8c6e18.png)
![nuget-icon-2](https://cloud.githubusercontent.com/assets/350947/6311906/af4d692e-b962-11e4-8ba7-8fefe6c6b313.png)

Is it possible to host these on zeromq.org and then reference them in the NuSpec file?

The image will appear in the NuGet package search window in Visual Studio, and should also appear on the [nuget.org NetMQ package page](https://www.nuget.org/packages/NetMQ/).

**Comment by somdoron** [comment]
we can use githubusercontent link for this, like what zeromq project is using, take a look at the url of the picture in the next link:

http://www.nuget.org/packages/ZeroMQ/

**Comment by somdoron** [comment]
but maybe we can have  a NetMQ icon... like czmq:

http://www.nuget.org/packages/czmq

**Comment by drewnoakes** [comment]
Nice. Actually the ZeroMQ project's image is an ICO not a PNG, which seems better as it can be shown at different sizes in different contexts. The reference doesn't mention ICO files, but obviously they are supported.

This image has four versions, from 16x16 up to 128x128:

https://raw.githubusercontent.com/zeromq/clrzmq4/master/ZeroMQ.ico

I agree that a project-specific logo would be better. The CZMQ one is a bit hard to make out at 32px wide:

![logo-czmq](https://cloud.githubusercontent.com/assets/350947/6315092/ececef8e-b9ee-11e4-8e78-1a2bc4f5cd6b.png)

What do you think of this as a potential NetMQ project logo?

32px:

![netmqlogo-32px](https://cloud.githubusercontent.com/assets/350947/6315621/6b43fc3c-b9ff-11e4-8a60-b6e8cfb08d54.png)

128px:

![netmqlogo-128px](https://cloud.githubusercontent.com/assets/350947/6315626/97f31fa6-b9ff-11e4-843e-9435c4bf731f.png)

400px:

![netmqlogo-400px](https://cloud.githubusercontent.com/assets/350947/6315601/d1545b8a-b9fe-11e4-9ae0-c7839ba743bd.png)

The original file is vector based (SVG) so can be losslessly resized and will take advantage of on high-DPI screens. If it looks good to the project owner(s) then I'll make a PR with an ICO for the NuGet package.

**Comment by somdoron** [comment]
Looks great, make a pull request.
