### ISSUE TITLE
Q: Is there no help-file, to document the API for this library?

### ISSUE THREAD

**Issue by JamesWHurst** [zeromq/netmq#251]
Question: Is there no help-file of any kind for this library? !!

I mean like a .chm or other Windows Help File format, that lists every class, method and property?

If there is not - I can help create one. But I will need to get a *lot* more familiar with how to use this, to do a competent job of it. No serious library can be without a decent-quality help file. Especially if there is no Intellisense documentation, as apparently this one lacks.

**Comment by krisrok** [comment]
full fleshed documentation is missing, yes. not sure if we really need some chm file, i guess an offline version of http://netmq.readthedocs.org would do too. at least for the more verbose parts and to show how it all fits together. 

for everything else we should start to add xml doc comments (///) at least to public items. 

sadly i still feel the same as you regarding familiarity towards the lib. but i guess we could just start and others would correct our documentation errors..? :)

**Comment by somdoron** [comment]
I can help with direction and correction regarding the documentation. I
think the best is to invest in xml doc comments as we already have a
documentation project.

**Comment by drewnoakes** [comment]
Better XML doc coverage would be great.

I'll help out too. Doron, it'd be great if you could review the doc project
changes made yesterday, as well as future XML doc commits.

[via phone]

**Comment by JamesWHurst** [comment]
Ok - I cloned the current version of the code last night and am adding XML comments throughout a lot of it. Please let me know if any of you are doing the same - I don't want to waste effort. I'm thinking perhaps I should issue a pull-request when it's only partly done, so that more experienced minds can add it where I'm lacking.
I had already done a lot of it, when I was working on the .NET 3.5 compat. work last year - which never got incorporated and thus my comments never made it in.

**Comment by JamesWHurst** [comment]
How would you prefer me to submit questions related to XML-documentation (they're quite a few)? All here, or as separate issues (that may be too voluminous), or in an email?

Here're a few:
1) NetMQSocket.Subscribe is marked Obsolete, but I understand the intent is really to ensure this is only called for Subscriber sockets. I suggest this should be improved - because even with perfect code, your developers will still see this build-warning. I assume you don't want to simply throw an exception if the socket is not of that type, because you don't want to break existing code that calls this?

2) In Selector.Select, if itemsCount is zero when we enter this method but there is a non-zero timeout, this simply Sleeps for that period of time and then returns. Do we really want to do that? Would it not make sense to continually check for messages during that timeout-period, or at least at the end of it? Otherwise, this is simply burning time.

**Comment by drewnoakes** [comment]
@JamesWHurst, great that you're working on this. There was some discussion a while back on #13 that's worth revisiting (I know you posted there in 2013).

PRs allow you to push more code to them over time, but in this repo PRs are closed quickly as a matter of policy. If you push commits to your fork and want them reviewed, comment back here on this thread. I'll definitely take a look, although others are more knowledgeable on the library than me.

I believe you can reference this issue from another repo by including the text `zeromq/netmq#251` in the commit message, and those commits will show up here too.

**Comment by JamesWHurst** [comment]
Drewnoakes - why would I need to reference this issue from another repo?

Also, can I get some answers to my 2 questions above?

And - a newbie question (sorry - I'm a bit new to GitHub): I cloned the project, and did my edits. I did not create a branch yet, and I did not "fork" the project. Do I need to do both of those steps?  I thought forking was for only if I want to diverge from the main project and develop in a whole different direction, never to merge it back into the main branch - or am I totally mistaken on that?
My first round of edits are done - I'd like to get them committed for review now, so - please advise.

**Comment by drewnoakes** [comment]
@JamesWHurst -- changes to this repository occur via pull requests. This requires you to fork the repo via the GitHub UI and push your changes to your own fork:

    git@github.com:JamesWHurst/netmq

A fork on GitHub is just a public copy of the project's repository that you can push to. All contributors to this project push to their own forks, then submit a "pull request" to the original project's maintainers. The proposed changes are reviewed and normally merged straight in.  While it's true that forking a project could indeed take the project in a whole new direction, though this only seems to happen to dead projects or to projects where contributors differ irreconcilably in opinion.

It doesn't matter that you've cloned your local (working) repo from `zeromq/netmq` (which on your computer has the moniker `origin`). Add the location of your fork to the repository, then push to it.

Add the remote repository URL (this labels the remote repository `james`):

    git remote add james git@github.com:JamesWHurst/netmq

The first time you push, tell Git you want to "track" this particular remote repository, so that `fetch` and `push` operations happen against this remote by default. Do this with the `--set-upstream` option:

    git push james master --set-upstream

Then in future you only have to:

    git push

Once you've pushed your changes, visit your fork on github.com and there'll be a big obvious button to create a "pull request" from what you've just pushed.

**Comment by leverate-somech** [comment]
@drewnoakes I will review the documentation this weekend...

**Comment by somdoron** [comment]
leverate-somech is my job user.

**Comment by JamesWHurst** [comment]
I forked the repo (creating JamesWHurst/netmq), and committed edits. I noticed that it makes a lot of extra work when other files change in the upstream project *during* the time I am doing edits, necessitating differencing and merging again. When you can, please review my code-edits and merge it with the zmq/netmq project or else provide me with feedback, as soon as you conveniently can.

That took a *lot* of time. Nearly a solid work-week.  It should be current with the latest code in the repo as of one day ago.

Thank you for your advice drewnoakes.  Totally helped.

**Comment by drewnoakes** [comment]
Great. Looking forward to seeing the fruit of your efforts.

**Comment by drewnoakes** [comment]
Cross referencing with PRs #259, #262, #269, and #273.

**Comment by drewnoakes** [comment]
@JamesWHurst are you happy with this issue now?

**Comment by JamesWHurst** [comment]
Yes, thank you.  The answer was basically - freak'n roll up your sleeves and do it!  lol

**Comment by drewnoakes** [comment]
:)

**Comment by somdoron** [comment]
will try to review you it all, little limited in time for the next two
weeks.
