### ISSUE TITLE
NetMQ.SocketOptions.MaxMsgSize exception.

### ISSUE THREAD

**Issue by Nemonic** [zeromq/netmq#252]
Master branch.

NetMQ.SocketOptions.MaxMsgSize is an int property which is used to set NetMQ.zmq.Options.Maxmsgsize of type long in "Options.cs:234"

case ZmqSocketOptions.Maxmsgsize:
                    Maxmsgsize = (long)optval;
                    break;

Unboxing object(int) to (long) is invalid.

**Comment by drewnoakes** [comment]
Reproduced. Working on a unit test and patch now. Seems there are a few other properties on `SocketOptions` which cause trouble too.
