### ISSUE TITLE
NetMQ.Tests, PgmTests all hang.

### ISSUE THREAD

**Issue by JamesWHurst** [zeromq/netmq#256]
With code that I cloned from the NetMQ repository just this past Sunday (2015/2/22), All of the unit-tests within NetMQ.Tests pass, except all of the tests within PgmTests.  !!   Before I dump a bunch of time into that -- have you seen this?  Any idea what's going on?

I remember having an issue last year, when I tried to run it on a host that had only a single-core CPU. But it ran fine if I had more than one CPU-core. Here, my host does have 4 cores.

I'm using Visual Studio 2013 Ultimate, update 4, on Windows 7 x64.

Thank you for your help.

**Comment by tobi-tobsen** [comment]
Have you started visual studio with admin rights? Somehow this is needed for PGM sockets.

**Comment by JamesWHurst** [comment]
Yes I did.

Within PgmSocket.Init, at the line AsyncSocket.Create(AddressFamily.InterNetwork, SocketType.Rdm, PGM_PROTOCOL_TYPE);
it is throwing a SocketException with: The support for the specified socket type does not exist in this address family."

**Comment by tobi-tobsen** [comment]
Yeah, well you need to install PGM socket support which comes with MSQM: https://msdn.microsoft.com/en-us/library/aa967729%28v=vs.110%29.aspx

**Comment by JamesWHurst** [comment]
Thanks - that did seem to have fixed the problem. I always like to verify that all unit-tests run, before committing any code.
Since I'm doing documentation, I added a comment to the top of PgmTests that clues in any developer-users of this necessary step.

**Comment by JamesWHurst** [comment]
Q: Why do these PgmTests use IP-address 244.0.0.1  ?  That makes no sense to me - the loopback-address would seem to be 127.0.0.1.  ???   What's special about 244.0.0.1 ?

**Comment by deanroker123** [comment]
Hi James,

Multicast uses different addresses for the destination. They are a reserved
part of the ipv4 address space.

Please see here for more info.

http://en.m.wikipedia.org/wiki/Multicast_address

**Comment by JamesWHurst** [comment]
Thank you y'all - I very much appreciate your help.
