### ISSUE TITLE
CONTRIBUTING file

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#265]
GitHub has a nice feature where if you include a file called `CONTRIBUTING.md` then users see a message when opening issues/pull requests:

![image](https://cloud.githubusercontent.com/assets/350947/6415895/d976a634-be99-11e4-91e5-c2d8f4245157.png)

I quite like when a repository has this as it makes it possible to contribute in accordance with the project's wishes. And if they're not reasonable, then I might not bother. I think the C4 process is very reasonable and was happy to be introduced to it by this project.

If we want to add such a file to NetMQ, then we should choose one.

Here the ones I found from other zeromq organisation projects.

* [malamute](https://github.com/zeromq/malamute/blob/master/CONTRIBUTING.md) &mdash; minimal, references C4.1, license, AUTHORS
* [czmq](https://github.com/zeromq/czmq/blob/master/CONTRIBUTING.md) &mdash; extends the above with more stern language about patch quality
* [azmq](https://github.com/zeromq/azmq/blob/master/CONTRIBUTING.md) &mdash; longer and more explicit about things like licensing obligations, code style, commit messages and small, separate commits
* [pyzmq](https://github.com/zeromq/pyzmq/blob/master/CONTRIBUTING.md) &mdash; another, quite different set of guidelines

malamute's tone is simplest. czmq's might fit the C community than the .NET one. azmq and pyzmq both offer more detail.

Anyway, would this be useful, and what content should it include?

**Comment by drewnoakes** [comment]
@somdoron do you think this would be a suitable document? Any changes?

---

### Contributing to NetMQ

* The contributors are listed in [AUTHORS.md](https://github.com/zeromq/netmq/blob/master/AUTHORS.md) (add yourself).

* This project uses a modified version of the LGPL v3 license, see 
[COPYING.LESSER](https://github.com/zeromq/netmq/blob/master/COPYING.LESSER).

* We use the [C4.1 (Collective Code Construction Contract)](http://rfc.zeromq.org/spec:22) process for contributions.
Please read this if you are unfamiliar with it.

* Please maintain the existing code style. 

* Please try to keep your commits small and focussed.

* If the project diverges from your branch, please rebase instead of merging. This makes the commit graph easier to read.

**Comment by somdoron** [comment]
looks good. fits the philosophy...
