### ISSUE TITLE
AUTHORS file

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#266]
Should we add an AUTHORS file, as is done in many zeromq projects?

* https://github.com/zeromq/malamute/blob/master/AUTHORS
* https://github.com/zeromq/zmqpp/blob/develop/AUTHORS
* https://github.com/zeromq/pyzmq/blob/master/AUTHORS.md
* https://github.com/zeromq/filemq/blob/master/AUTHORS
* https://github.com/zeromq/czmqpp/blob/master/AUTHORS
* https://github.com/zeromq/jeromq/blob/master/AUTHORS
* https://github.com/zeromq/azmq/blob/master/AUTHORS
* https://github.com/zeromq/zyre/blob/master/AUTHORS
* https://github.com/zeromq/czmq/blob/master/AUTHORS ***
* https://github.com/zeromq/libzmq/blob/master/AUTHORS ***

### EDIT

I'll create an `AUTHORS.md` file and add people who elect to be included in this thread. Initially it's just be an alphabetically ordered list of contributor's names (and GitHub handles if desired).

Eg:

> John Doe &mdash; @johndoe

**Comment by somdoron** [comment]
I think it's a good idea...

**Comment by drewnoakes** [comment]
Attention: @sachabarber @mph911 @almazik @tobi-tobsen @reiroldan @JamesWHurst @GianniBortoloBossini @cjuniet @BDeus @bubbafat @gbirchmeier @iloginov @therealbappy @tjrobinson @hanswolff @KyleRudy @matthiasgeller @mbergin @buybackoff @dandezille @barzto @JayShelton @sofusmortensen @EugenDueck @kamlesh-patel @krisrok @majimenezp @oldrev @yallie @cbaxter 

As someone who GitHub identifies as a [contributor to NetMQ](https://github.com/zeromq/netmq/graphs/contributors), you're being @ mentioned to see if you'd like to be in the new [`AUTHOR.md`](https://github.com/zeromq/netmq/blob/master/AUTHORS.md) file.

If so, please reply back here to let us know how you'd like to appear.

Recommended formatting is:

> Full Name &mdash; @githubusername

**Comment by gbirchmeier** [comment]
Grant Birchmeier - @gbirchmeier

On Fri, Feb 27, 2015 at 2:03 PM, Drew Noakes <notifications@github.com>
wrote:

> Attention: @sachabarber <https://github.com/sachabarber> @mph911
> <https://github.com/mph911> @almazik <https://github.com/almazik>
> @tobi-tobsen <https://github.com/tobi-tobsen> @reiroldan
> <https://github.com/reiroldan> @JamesWHurst
> <https://github.com/JamesWHurst> @GianniBortoloBossini
> <https://github.com/GianniBortoloBossini> @cjuniet
> <https://github.com/cjuniet> @BDeus <https://github.com/BDeus> @bubbafat
> <https://github.com/bubbafat> @gbirchmeier
> <https://github.com/gbirchmeier> @iloginov <https://github.com/iloginov>
> @therealbappy <https://github.com/therealbappy> @tjrobinson
> <https://github.com/tjrobinson> @hanswolff <https://github.com/hanswolff>
> @KyleRudy <https://github.com/KyleRudy> @matthiasgeller
> <https://github.com/matthiasgeller> @mbergin <https://github.com/mbergin>
> @buybackoff <https://github.com/buybackoff> @dandezille
> <https://github.com/dandezille> @barzto <https://github.com/barzto>
> @JayShelton <https://github.com/JayShelton> @sofusmortensen
> <https://github.com/sofusmortensen> @EugenDueck
> <https://github.com/EugenDueck> @kamlesh-patel
> <https://github.com/kamlesh-patel> @krisrok <https://github.com/krisrok>
> @majimenezp <https://github.com/majimenezp> @oldrev
> <https://github.com/oldrev> @yallie <https://github.com/yallie> @cbaxter
> <https://github.com/cbaxter>
>
> As someone who GitHub identifies as a contributor to NetMQ
> <https://github.com/zeromq/netmq/graphs/contributors>, you're being @
> mentioned to see if you'd like to be in the new AUTHOR.md
> <https://github.com/zeromq/netmq/blob/master/AUTHORS.md> file.
>
> If so, please reply back here to let us know how you'd like to appear.
>
> Recommended formatting is:
>
> Full Name — @githubusername <https://github.com/githubusername>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zeromq/netmq/issues/266#issuecomment-76462095>.
>



-- 
Grant Birchmeier
*Connamara Systems, LLC*
*Made-To-Measure Trading Solutions.*
Exactly what you need. No more. No less.
http://connamara.com

**Comment by majimenezp** [comment]
Thanks, is great to be added to the contributor list, because i use a lot netMQ( and zeroMQ in general) with ARM, i am checking some other details that need to be refined, but as soon i have some spare time, i will work on that and send the pull request, here is my info in the required format:


Miguel Angel Jimenez - @majimenezp


Thanks again

**Comment by iloginov** [comment]
Ilya Loginov - @iloginov

Thanks

**Comment by ndextraze-pbp** [comment]
Nicolas Dextraze - @ndextraze-pbp

I wasn't showing in the contributors originally because I used a different email address not associated with my account when I commited. It's now fixed.

**Comment by cjuniet** [comment]
Christophe Juniet - @cjuniet <https://github.com/cjuniet>

Thanks!

**Comment by bubbafat** [comment]
Robert Horvick - @bubbafat

**Comment by tjrobinson** [comment]
Tom Robinson - @tjrobinson

**Comment by buybackoff** [comment]
Victor Baybekov - @buybackoff

That was not, by far, may intention initially with my lame commit, but why not :) Have some ideas and was too shy to make an issue of them before.

**Comment by tobi-tobsen** [comment]
Tobias Behr - @tobi-tobsen

**Comment by sachabarber** [comment]
Sachs barber

**Comment by mph911** [comment]
Peter H. Merkel   @mph911

Thank you 😊

Von meinem Windows Phone gesendet
________________________________
Von: Drew Noakes<mailto:notifications@github.com>
Gesendet: ‎27.‎02.‎2015 21:03
An: zeromq/netmq<mailto:netmq@noreply.github.com>
Cc: P. H. Merkel (MerkelConsult)<mailto:pm@merkelconsult.net>
Betreff: Re: [netmq] AUTHORS file (#266)


Attention: @sachabarber<https://github.com/sachabarber> @mph911<https://github.com/mph911> @almazik<https://github.com/almazik> @tobi-tobsen<https://github.com/tobi-tobsen> @reiroldan<https://github.com/reiroldan> @JamesWHurst<https://github.com/JamesWHurst> @GianniBortoloBossini<https://github.com/GianniBortoloBossini> @cjuniet<https://github.com/cjuniet> @BDeus<https://github.com/BDeus> @bubbafat<https://github.com/bubbafat> @gbirchmeier<https://github.com/gbirchmeier> @iloginov<https://github.com/iloginov> @therealbappy<https://github.com/therealbappy> @tjrobinson<https://github.com/tjrobinson> @hanswolff<https://github.com/hanswolff> @KyleRudy<https://github.com/KyleRudy> @matthiasgeller<https://github.com/matthiasgeller> @mbergin<https://github.com/mbergin> @buybackoff<https://github.com/buybackoff> @dandezille<https://github.com/dandezille> @barzto<https://github.com/barzto> @JayShelton<https://github.com/JayShelton> @sofusmortensen<https://github.com/sofusmortensen> @EugenDueck<https://github.com/EugenDueck> @kamlesh-patel<https://github.com/kamlesh-patel> @krisrok<https://github.com/krisrok> @majimenezp<https://github.com/majimenezp> @oldrev<https://github.com/oldrev> @yallie<https://github.com/yallie> @cbaxter<https://github.com/cbaxter>

As someone who GitHub identifies as a contributor to NetMQ<https://github.com/zeromq/netmq/graphs/contributors>, you're being @ mentioned to see if you'd like to be in the new AUTHOR.md<https://github.com/zeromq/netmq/blob/master/AUTHORS.md> file.

If so, please reply back here to let us know how you'd like to appear.

Recommended formatting is:

Full Name — @githubusername<https://github.com/githubusername>

**Comment by JayShelton** [comment]
Jay Shelton @jayshelton






Sent from Windows Mail





From: Drew Noakes
Sent: ‎Friday‎, ‎February‎ ‎27‎, ‎2015 ‎3‎:‎03‎ ‎PM
To: zeromq/netmq
Cc: Jay Shelton





Attention: @sachabarber @mph911 @almazik @tobi-tobsen @reiroldan @JamesWHurst @GianniBortoloBossini @cjuniet @BDeus @bubbafat @gbirchmeier @iloginov @therealbappy @tjrobinson @hanswolff @KyleRudy @matthiasgeller @mbergin @buybackoff @dandezille @barzto @JayShelton @sofusmortensen @EugenDueck @kamlesh-patel @krisrok @majimenezp @oldrev @yallie @cbaxter 

As someone who GitHub identifies as a contributor to NetMQ, you're being @ mentioned to see if you'd like to be in the new AUTHOR.md file.

If so, please reply back here to let us know how you'd like to appear.

Recommended formatting is:


Full Name — @githubusername

**Comment by EugenDueck** [comment]
Eugen Dück — @EugenDueck

Thanks

**Comment by JamesWHurst** [comment]
James Hurst -- @JamesWhurst

Thank you.

**Comment by yallie** [comment]
Alexey Yakovlev — @yallie

Thanks

**Comment by drewnoakes** [comment]
I'm going to close this issue now, but any replies will still be processed.

**Comment by dandezille** [comment]
Dan de Zille - @dandezille

Thanks!
