### ISSUE TITLE
Messages, Frames and the socket receiving APIs

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#275]
The extension methods for receiving from sockets are not very friendly when starting out with NetMQ. There are several ways to achieve the same thing (`SendReiveOptions.DontWait` vs `bool dontWait`) and the behaviour of non-blocking reads are not clear (do they return `null`, throw, or something else?)

In the ZeroMQ Guide, there's a distinction between messages and frames. NetMQ's API commonly refers to frames as messages. ~~This is pretty confusing and it'd be nice to get away from.~~ _Turns out that multipart message support is slated for removal in the future of ZeroMQ._

Here are some ideas for how the receiving APIs might work in future.

```csharp
//////// BLOCKING APIS

// Receiving frames

Frame frame; // rename of the current Msg class
socket.ReceiveFrame(ref frame); // void return

byte[] frame = socket.ReceiveFrameBytes();
byte[] frame = socket.ReceiveFrameBytes(out more);

string frame = socket.ReceiveFrameString();
string frame = socket.ReceiveFrameString(out more);
string frame = socket.ReceiveFrameString(Encoding);
string frame = socket.ReceiveFrameString(Encoding, out more);

// Receiving entire messages

NetMQMessage message = socket.ReceiveMessage();

List<byte[]> message = socket.ReceiveMessageBytes();

List<string> message = socket.ReceiveMessageStrings();
List<string> message = socket.ReceiveMessageStrings(Encoding);

//////// NON-BLOCKING APIS

// Receiving frames

Frame frame; // rename of the current Msg class
bool success = socket.TryReceiveFrame(ref frame); // void return

byte[] frame;
bool success = socket.TryReceiveFrameBytes(out frame);
bool success = socket.TryReceiveFrameBytes(out frame, out more);
bool success = socket.TryReceiveFrameBytes(TimeSpan, out frame);
bool success = socket.TryReceiveFrameBytes(TimeSpan, out frame, out more);

string frame;
bool success = socket.TryReceiveFrameString(out frame);
bool success = socket.TryReceiveFrameString(out frame, out more);
bool success = socket.TryReceiveFrameString(out frame, Encoding);
bool success = socket.TryReceiveFrameString(out frame, Encoding, out more);
bool success = socket.TryReceiveFrameString(TimeSpan, out frame);
bool success = socket.TryReceiveFrameString(TimeSpan, out frame, out more);
bool success = socket.TryReceiveFrameString(TimeSpan, out frame, Encoding);
bool success = socket.TryReceiveFrameString(TimeSpan, out frame, Encoding, out more);

// Receiving entire messages

NetMQMessage message;
bool success = socket.TryReceiveMessage(out message);
bool success = socket.TryReceiveMessage(TimeSpan, out message);

List<byte[]> message;
bool success = socket.TryReceiveMessageBytes(out message);
bool success = socket.TryReceiveMessageBytes(TimeSpan, out message);

List<string> message
bool success = socket.TryReceiveMessageStrings(out message);
bool success = socket.TryReceiveMessageStrings(out message, Encoding);
bool success = socket.TryReceiveMessageStrings(TimeSpan, out message);
bool success = socket.TryReceiveMessageStrings(TimeSpan, out message, Encoding);
```

Blocking receives never return `null`. The non-blocking versions always set their out params to `null` when they return `false` (or in the case of the `ref` param, they leave it unmodified).

The `SendReceiveOptions` enum makes the current API confusing. Is it valid to receive and set `SendMore`? I guess this is a throwback to the C API's enum where this kind of thing would seem more natural, but here it's confusing. I've deliberately left it out of the above, though another option would be to split it into `SendOptions` and `ReceiveOptions`.

Rather than using the `bool dontWait` value throughout, the above makes a distinction between a blocking receive, and a 'try' receive, which indicates failure with a boolean return value, not an `AgainException`. Exceptions should only be used for exceptional circumstances, not something as commonplace as there being nothing to receive. It's also more idiomatic in .NET to have a `Try*` method for operations which may fail, and users should know the semantics of the return value.

Overloads which take `TimeSpan` timeouts would only be available on `NetMQSocket`, not `IReceivingSocket` (unless the latter was modified to include a timeout in its interface&mdash;I'm unsure if this is feasible).

Would like to hear people's thoughts.

**Comment by somdoron** [comment]
I really really like the API you suggest.

By the way, you also have NetMQMessage which you can use.

Problem with NetMQMessage right now is that you allocate a new message on each message receive and send, if we can change that we will reuse same NetMQMessage that will useful.

**Comment by somdoron** [comment]
I would also mark anything else as obsolete and will promote the new api

**Comment by somdoron** [comment]
we can also improve the internal by stop throwing AgainException and return boolean instead, this will also improve performance on cases the operation is blocking.

**Comment by drewnoakes** [comment]
I wonder if it's possible to deprecate `Msg` and use a new `Frame` class instead. I suppose an obsolete `Msg` could just wrap the new (well, renamed) `Frame`.

**Comment by drewnoakes** [comment]
One thing this API doesn't include is support for `async` and `Task`. Given the IOCP stuff underpinning the comms, it seems a great candidate for true async support. I don't yet know enough about the internals, but do you think this would be a valuable and feasible addition to the API at this level?

**Comment by somdoron** [comment]
I think it is not possible to obsolete Msg, mainly because Msg is a struct and not a class and it is deep in the internal of NetMQ, we may be able to change the name to Frame and support Msg on the API just for backwards comparability.

Regarding Task and Async, we cannot add them directly on the API (we need a thread to handle the async), we can however make a wrapper like in: http://somdoron.com/2014/08/netmq-asp-net/

**Comment by krisrok** [comment]
great ideas, especially regarding the methods. 

one thought though: instead of cluttering the api with deprecated stuff, can we risk to deliberately collect some breaking changes (which may take a while to implement and test anyway) and release a clean api hand in hand with a major release, say 4.0?

**Comment by drewnoakes** [comment]
Regarding `Msg`, I was thinking the same. Rename it to `Frame` or maybe `FrameBuffer`, then generate a delegating struct that's only used in obsolete APIs.

In that case we won't consider `*Async` versions of the above methods.

C4.1 has a section on [Evolution of Public Contracts](http://rfc.zeromq.org/spec:22#toc8) which is worth a look. In particular:

> A patch that modifies a stable Public Contract SHOULD not break existing applications unless there is overriding consensus on the value of doing this.

I'm not sure there's anything wrong with having obsolete members of the API kicking around for a while. So unless we're simply unable to take the API in the direction we'd like to without making a breaking change, I'm in favour of trying to progress with obsoletion (if that's a word!)

**Comment by JamesWHurst** [comment]
I really, really like your proposed change. It makes it a *lot* clearer, for exactly the reasons you said. The proposal looks neat and symmetrical, easy to document and easy to understand.

I agree that it's confusing to have Msg named as such. I went nuts trying to figure out how to usefully comment that. Frame makes a lot more sense.

Your point regarding exceptions: Yes, absolutely!!  Having those spew out during normal execution slows down our code, pollutes the output when debugging, and makes our library look less polished.

Regarding migrating the API -- are we using the principles of Semantic Versioning?  Meaning you bump the major version-number if possibly-breaking changes are incorporated.

**Comment by drewnoakes** [comment]
I've started removing throws of `AgainException` during receive calls. Looking deeper into this turned up an additional complexity.

Something that currently prohibits the API described above is `SocketOptions.ReceiveTimeout`.

This option allows _any_ receive call to throw after a period of time. This doesn't fit with the non-`Try` family of functions planned.

I don't think there's a way around this. If we want to lose `AgainException` and have blocking receive calls, then these calls can't have timeouts as well. How would they signal?

After thinking this through for a while, I don't see any sensible option other than deprecating the `ReceiveTimeout` at the socket level. Receivers that want timeouts specify them in their calls where it's more explicit anyway.

This would give the following methods on `NetMQSocket` (and possibly `IReceivingSocket`):

    public void ReceiveFrame(ref msg);

    public bool TryReceiveFrame(ref msg, TimeSpan timeout);     // TimeSpan.Zero allowed

Other receive methods (for strings, entire messages, etc) would be extension methods and utilise these two methods.

I think this is actually a better situation for the users. Any thoughts?

_(All of this applies equally to sending as it does to receiving, though I'll tackle that afterwards.)_

**Comment by drewnoakes** [comment]
Another point here is that using `TimeSpan` to represent the timeout is slightly misleading, as the current implementation caters for integral millisecond timeouts, whereas a user could pass `TimeSpan.FromMilliseonds(0.1)`, expecting a 100µs timeout. This is probably a separate issue to track/fix, so I'll keep with `TimeSpan` for now unless anyone can foresee issues there.

**Comment by drewnoakes** [comment]
Also now that I've spent some more time in the code, I think that `Msg` should be renamed to `FrameBuffer` (assuming we can keep an obsolete public `Msg` struct for existing users to migrate from at their convenience).

**Comment by JamesWHurst** [comment]
Agreed - FrameBuffer captures it's purpose much more clearly. And it's confusing to have both Msg and NetMQMessage.

**Comment by JamesWHurst** [comment]
Minor note: I like your idea of *not* using TimeSpan there, since we nearly everywhere use numeric values representing milliseconds - which would seem to be clearer and more efficient.

Since you're proposing to introduce a slightly different syntax for receiving and sending, would this not be an opportune moment to introduce the newer FrameBuffer, and let the obsoleted methods still use Msg? That would yield fewer obsolete methods in our API afterward.

**Comment by JamesWHurst** [comment]
Q: Are you (drewnoakes) proposing methods that could block forever?  If so - why, as opposed to having all current-version methods have some sort of a timeout (which, I would think, helps our unit-tests) ?

**Comment by drewnoakes** [comment]
The API for sending will closely match that for receiving once this task is
complete.

It is already possible to block forever. In fact that's the default
behaviour for a receive call that doesn't specify DontWait and uses the
default socket ReceiveTimeout. It's not uncommon to have the unit tests
hang when bugs are introduced.

[via phone]

**Comment by somdoron** [comment]
@drewnoakes I think the idea to deprecate ReceiveTimout (and SendTimeout) is good, however we have to make sure that whoever call the old methods still get the functionality.

I suggest that the internal Receive method (on SocketBase) will have the following API

bool TryReceive(ref Msg msg, bool more, int timeout); // Minus 1 is forever

We can then in the old method throw again exception of false and set the timeout to Socket.ReceiveTimeout on old methods (and deprecate it).

By the way I'm not a big fun of using the term Frame, mainly because there is an intention to remove the multi-part messages from ZeroMQ. So maybe we can change it to Buffer. Also not a big fun of using it inside the Method names. Maybe when it clear like when we want to do SendMore.

**Comment by drewnoakes** [comment]
Hi Doron,

Thanks for taking the time to provide valuable feedback. I know you're particularly busy at the moment.

> I suggest that the internal Receive method (on SocketBase) will have the following API

Nice to see we're on the same page :) I came to the same conclusion last night, though without the `more` property (it's redundant with the `HasMore` flag on `Msg`), and using a `TimeSpan` for the timeout, to allow sub-millisecond timeout periods in the near future without having to churn the API yet again.

Your idea of using the `SocketOptions.ReceiveTimeout` only in the old, deprecated methods is nice. I'll look at this tonight. I'd just completely removed the implementation of that property, but your idea will make it nicer for current users.

If multipart messages are on the way out from ØMQ then I agree using the term _frame_ might be a bad idea. I'm curious to read more about this though&mdash;what would be the alternative? Wouldn't this require many other changes all the way from the API down to the wire protocol?

Hopefully I can finish up the receive API changes tonight and push to a branch on my fork for you and others to review. It was looking pretty nice last night. A few more extension methods are needed, and I'll integrate your feedback around naming.

**Comment by krisrok** [comment]
was a bit confused too, here's the relevant blog post:
http://hintjens.com/blog:84

i like your ideas though. and calling it "buffer" would still be a improvement over "frame" i guess :)

**Comment by somdoron** [comment]
@drewnoakes regarding the more parameter, we don't need it on the Receive, but we do need it on the Send as the SetFlags is called inside the SocketBase.Send.

We can also deprecate the SocketFlags enum.

**Comment by drewnoakes** [comment]
@krisrok thanks for the link. There are some good insights in there, and some sensible plans for the future. I'm going to have a further read about zproto.

I'm working to revise the proposed API based on the comments so far. One goal is to avoid changes now that make it hard to transition away from multipart later.

@somdoron, could a current frame-receiving method such as `ReceiveString` just be changed to be "chunk"-receiving? Or asked another way, can code that assumes it's reading frames work correctly when multipart is obsoleted?

If the behaviour of such methods cannot be changed without breaking code, then it would be better to add `Receive*Frame` methods now and deprecate them later in exchange for newer methods that have the new semantics.

If we're obsoleting `Socket.*Timeout`, then we must obsolete _all_ methods and extension methods on `IOutgoingSocket` and `IReceivingSocket` that send/receive in order to completely obsolete socket-level timeouts. This means we cannot reuse any of the current method signatures&mdash;particularly hard for `ReceiveString()`. `ReceiveFrameString` is available, but if we don't want to include `Frame` in the name, then I'm not sure what other name might work. Perhaps `ReceiveAsString`. I'm hoping we can use the name _frame_ now, and transition away from that once we know what it means to deprecate multipart.

---

Here is a revised proposal. In all of these, assume:

```csharp
IReceivingSocket socket;
```

### IReceivingSocket

```csharp
// New: blocking
socket.Receive(ref Msg); // returns void

// New: with timeout, or non-blocking (when timeout zero)
bool success = socket.TryReceive(ref Msg, TimeSpan);

// Obsolete
socket.Receive(ref Msg, SendReceiveOptions) // returns void
```

---

## Blocking receive

#### Single frames

```csharp
bool more;

byte[] frame = socket.ReceiveFrameBytes();
byte[] frame = socket.ReceiveFrameBytes(out more);

string frame = socket.ReceiveFrameString();
string frame = socket.ReceiveFrameString(out more);
string frame = socket.ReceiveFrameString(Encoding);
string frame = socket.ReceiveFrameString(Encoding, out more);
```

#### Multipart messages in full

```csharp
socket.ReceiveMultipartMessage(ref NetMQMessage); // returns void

NetMQMessage message = socket.ReceiveMultipartMessage();

List<byte[]> message = socket.ReceiveMultipartBytes();

List<string> message = socket.ReceiveMultipartStrings();
List<string> message = socket.ReceiveMultipartStrings(Encoding);
```

---

## Non-blocking receive

#### Single frames

```csharp
bool success = socket.TryReceive(ref Msg);

bool more;

bool success = socket.TryReceiveFrameBytes(out byte[]);
bool success = socket.TryReceiveFrameBytes(out byte[], out more);
bool success = socket.TryReceiveFrameBytes(TimeSpan, out byte[]);
bool success = socket.TryReceiveFrameBytes(TimeSpan, out byte[], out more);

bool success = socket.TryReceiveFrameString(out String);
bool success = socket.TryReceiveFrameString(out String, out more);
bool success = socket.TryReceiveFrameString(out String, Encoding);
bool success = socket.TryReceiveFrameString(out String, Encoding, out more);
bool success = socket.TryReceiveFrameString(TimeSpan, out String);
bool success = socket.TryReceiveFrameString(TimeSpan, out String, out more);
bool success = socket.TryReceiveFrameString(TimeSpan, out String, Encoding);
bool success = socket.TryReceiveFrameString(TimeSpan, out String, Encoding, out more);
```

#### Multipart messages in full

```csharp
bool success = socket.TryReceiveMultipartMessage(ref NetMQMessage);
bool success = socket.TryReceiveMultipartMessage(TimeSpan, ref NetMQMessage);

bool success = socket.TryReceiveMultipartMessage(out NetMQMessage);
bool success = socket.TryReceiveMultipartMessage(TimeSpan, out NetMQMessage);

bool success = socket.TryReceiveMultipartBytes(out List<byte[]>);
bool success = socket.TryReceiveMultipartBytes(TimeSpan, out List<byte[]>);

bool success = socket.TryReceiveMultipartStrings(out List<String>);
bool success = socket.TryReceiveMultipartStrings(out List<String>, Encoding);
bool success = socket.TryReceiveMultipartStrings(TimeSpan, out List<String>);
bool success = socket.TryReceiveMultipartStrings(TimeSpan, out List<String>, Encoding);
```

None of these functions return `null` or throw `AgainException`. `Try`-methods' `out` params are `null` when the return value is false`.

Feedback please! I'll get some commits up for review in the next few days.

**Comment by somdoron** [comment]
@drewnoakes @krisrok I actually had a part on that idea, you can also read the mail list:
http://lists.zeromq.org/pipermail/zeromq-dev/2015-February/028222.html

@drewnoakes I think we can use the same methods for both chunk and frame. Anyway we can go with the frame for now.

For the our list parameter you might want to consider ref to reduce memory usage (only allocate it if is null, other then that clear the list and add items).

We should consider something like this for NetMQMessage as well.

**Comment by JamesWHurst** [comment]
Have you considered a term that is less code-specific, such as "MessageUnit", or "MessageSubunit", or "MessageChunk" ?

Your note on that link is interesting. Yes, simplifying the code and having threadsafe sockets would be wonderful.

**Comment by drewnoakes** [comment]
@somdoron so it's your idea! Having learned ØMQ recently I imagine it could have been quite a bit simpler without multipart messages. Great stuff.

I'll add `ref` functions for `List<T>` methods as well, thanks. There are two in the list for `NetMQMessage` already.

Would be good to avoid using _frame_ in the name. I'll take another look at it tonight.

**Comment by drewnoakes** [comment]
To date, the default character encoding (when unspecified by the caller) is ASCII.

Are we happy with this? Is this an opportunity to migrate to UTF-8?

For now I'm pulling it into a static field on `ReceivingSocketExtensions`, though it could well be an instance setting on `NetMQSocket`.

**Comment by JamesWHurst** [comment]
My vote is for an immediate change to UTF-8.  Q - does it make any sense for it to be an instance setting? Would we ever want to have different encodings on different sockets (seems like unnecessary complexity)?

**Comment by drewnoakes** [comment]
In general the user should be aware of and control encoding. However it seems that UTF-8 has pretty much won the encodings battle for most of the planet, and is likely the best choice. Whether changing this might cause issues, I'm not certain. It seems unlikely to be a harmful change, as UTF-8 is a strict superset of ASCII.

**Comment by JamesWHurst** [comment]
Going to UTF-8 will be a requirement for an compatibility with Windows Store or Windows 10 code, and I can't see any possible downside unless having N characters convert to M bytes, where M > N, causes a problem. We should of course add unit-tests that send/receive strings that include non-ASCII characters that require >1 and >2 bytes each, to verify this.

I offer this suggestion: Every dimension of variability, multiplies the number of distinct method-signatures required and complicates the API. I would argue that having this (Encoding) as a parameter on the send/receive methods is unnecessary and inappropriate. Better to provide just a simple static Encoding property on the session class instead, which I believe is what you have already suggested.
