### ISSUE TITLE
NetMQSocket.IgnoreErrors

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#277]
`NetMQSocket.IgnoreErrors` is marked obsolete, but still used in `Poller.cs`.

Is the intention in making it obsolete that it's not possible to ignore errors on a socket?

If so, should we remove this check, stub out the property's backing storage, and be done with the compiler warning?

(I've been trying to get rid of all compiler warnings, and I think this is the last one.)

**Comment by JamesWHurst** [comment]
Agreed - this compiler-warning needs to be eliminated.

**Comment by somdoron** [comment]
I think we can remove the property and the usage in the poller. It was
ported from clrzmq at the time to have easy transition from clrzmq to
netmq, it is not needed now.
