### ISSUE TITLE
NetMQ 3.3.0.11 Connect and Bind Problems

### ISSUE THREAD

**Issue by jackdslin** [zeromq/netmq#284]
Hi,

I  use NetMQ Version: 3.3.0.11 to create Pub/Sub two application, 

Pub socket bind address is tcp://*:50007
Sub socket connect address is tcp://localhost:50007

When I shutdown Pub application, the Sub keep trying to reconnect Pub socket，I found the Sub socket will get a free port as source port to connect the Pub socket，finally the Sub get free port is 50007(the port is Pub bind Port) to connect, in the moment I start Pub application，will bind failed

Because Sub use same port to connect.
How do I to resolve this problem?

Thank you for your help.

**Comment by somdoron** [comment]
try to use a port that is not used by windows when connecting...

**Comment by somdoron** [comment]
the windows dynamic range is between 49152 and 65535

**Comment by jackdslin** [comment]
I will try.

Thank you.

**Comment by gvolpert** [comment]
I am having the same issue: NetMQ Ver. 4.0.0.0
Pub socket bind: tcp://*:51153
Sub socket connect: tcp://localhost:51153

After publisher and subscriber first start - everything works.
Then at some point publisher unbinds, but subscriber keeps re-connecting .
After some time subscriber's source port becomes the same as publisher's (51153) !
In other words, running this: **netstat -a -b | findstr 5115**
returns this:
TCP    127.0.0.1:**51153**        PBQAAPP01:**51153**        ESTABLISHED 

What am I doing wrong?

**Comment by gvolpert** [comment]
also tried port out of dynamic range (31153) - with the same result...

**Comment by somdoron** [comment]
I actually suffered from this problem as well. Bottom line, do not use a port from the ephemeral port range. Google to found the range on your OS.

* https://en.wikipedia.org/wiki/Ephemeral_port

**Comment by somdoron** [comment]
On most linux and windows version:

 49152 to 65535

**Comment by gvolpert** [comment]
Thanks, this worked!  What was confusing for me was that ephemeral port range on this Win2008 server is non-standard: 1025-58976 (not 49152-65535).  Running this command revealed it: **netsh int ipv4 show dynamicport tcp**.  And with my luck all ports I were in dynamic range... :-)
