### ISSUE TITLE
NetMQSocket.Poll (PollEvent, timeout) return value vs comment

### ISSUE THREAD

**Issue by mph911** [zeromq/netmq#290]
Please read the following comment, which I believe is wrong:

        /// <summary>
        /// polls the socket for an event as specified to happen within a given timeout period
        /// </summary>
        /// <param name="pollEvents">the poll event(s) to listen for</param>
        /// <param name="timeout">the timeout period</param>
        /// <returns>
        /// PollEvents.None     -> no message available
        /// PollEvents.PollIn   -> no message arrived             -> should read INBOUND MESSAGE ARRIVED
        /// PollEvents.PollOut  -> no message to send          -> should read OUTBOUND MESSAGE ARRIVED
        /// PollEvents.Error    -> an error has occured
        /// or any combination thereof
        /// </returns>
        public PollEvents Poll(PollEvents pollEvents, TimeSpan timeout)

Shouldn't it read as stated?
Cheers,
Peter

**Comment by drewnoakes** [comment]
@JamesWHurst, can you comment on this and review?

**Comment by JamesWHurst** [comment]
You're absolutely right (!!!) and this is my doing!  I copy/pasted the first PollEvents comment line, and neglected to remove the "no".  How embarrassing!!  I believe I still have a pull-request pending, right? I'll commit the fix right now.

**Comment by JamesWHurst** [comment]
Ok - corrected. Please review and merge in.

As I complete the XML-docing, I'll carefully read through it yet again, start to end, to scrutinize it for comment mistakes.  This *is* starting to yield a rather useful API-Reference help-document already.

**Comment by mph911** [comment]
@JamesWHurst, GREAT JOB! I love to have XML comments which help to understand the API!
