### ISSUE TITLE
TCP accept filters not working

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#300]
The internal `Options` class builds up a list of `TcpAcceptFilters` which are never queried.

The `TcpAddressMask.MatchAddress` is also never called.

**Comment by JamesWHurst** [comment]
Yes - I saw that and added a TODO comment asking what's up with that (see my latest PR).

**Comment by somdoron** [comment]
I think the feature is not used, it was ported incorrectly from ZeroMQ so I
removed it some time ago (it actually never worked).

I suggest to obsolete the Options, if somebody in the future will request
the feature we can try and implement it.

**Comment by drewnoakes** [comment]
Sounds good. Removed in 1549f3d.
