### ISSUE TITLE
PgmTests - all unit-tests hang, on my machine. ?

### ISSUE THREAD

**Issue by JamesWHurst** [zeromq/netmq#302]
When trying to run the unit-tests on the source-code (the most recent version as of today, 2015-3-17) - all tests pass except for those within PgmTests. All of the tests within PgmTests seem to hang indefinitely, when I try to run them.
If I select "Debug Unit tests" (I'm using ReSharper's test-runner), on (e.g.) BindBothTests, it looks like it's throwing a SocketException in PgmSender.Init, at m_socket.Bind, with an errorcode of FFFFFFFF.

Is this happening to anyone else?

I'm running VS2013 Ultimate w Update 4, on Windows 8.1 Pro x64. I tried it with both ReSharper, and with TestDriven.Net. I also tried it on a different box that's running Windows 7 x64. My home box is running an i7-5960x with 8 cores, so it should not be having a thread-starvation problem.

**Comment by tobi-tobsen** [comment]
Can you paste the socket exception? 
Are you sure you installed pgm via add /remove Windows components? Also you need to start your test runner with admin privileges.

**Comment by tobi-tobsen** [comment]
it might be the same issue you had in issue #256

**Comment by JamesWHurst** [comment]
That's what's weird - this is the same machine. And I double-checked that I still have the MSMQ components installed and am running as Admin.

**Comment by drewnoakes** [comment]
These tests have always failed on my machine, presumably as I don't have
MSMQ installed. I read somewhere that the process must also run with
elevated permissions.

Can you check the build log and verify that this is where the hang occurred?

[via phone]

**Comment by JamesWHurst** [comment]
I'm not sure how to check the build-log.

I see that this test (PgmTests -- all of those) hang on my home machine, but not on my machine at work. Both do have MSMQ installed. Home is running Win 8.1, with an 8-core i7-5960X, work is Win 7 with only 2 cores.  Last year I was noting that some certain tests hang when you run them on a box with only one core (I was using a virtual machine). Not the case here obviously.

**Comment by drewnoakes** [comment]
Is there some action to take on this issue, or can we close it?

**Comment by drewnoakes** [comment]
Closing this for now. Can reopen later if need be.
