### ISSUE TITLE
Client port in TIME_WAIT tcp state

### ISSUE THREAD

**Issue by yeowgit** [zeromq/netmq#303]
We use REP-REQ socket pattern over TCP transport. Upon client disconnection, the port stays in TIME_WAIT tcp state, waiting for its lifetime timeout to occur. This is a problem when there are high volume of rapid REQ connections within the timeout period and cause port exhaustion.
Is there a way to transition from TIME_WAIT state so that port is available to reuse once client has disconnected?

**Comment by yeowgit** [comment]
Below code shows the REP-REQ code flow

Server:
	...
	var context = NetMQContext.Create();
	using (var socket = context.CreateResponseSocket())
	{
		socket.Options.Identity = Encoding.ASCII.GetBytes("Server");
		socket.Bind("tcp://*:7099");

		while (true)
		{
			// Receive the message
			var msg = socket.ReceiveMessage(TimeSpan.FromMilliseconds(300));
			// Send response
			socket.Send(DateTime.Now.Ticks.ToString());
		}
	}
	
Client:
        ....
	var context = NetMQContext.Create();
	while (true)
	{
		var reqSocket = context.CreateRequestSocket();
		reqSocket.Connect("tcp://localhost:7099");
		reqSocket.Send("Request...");
		var replyB = reqSocket.Receive();
		reqSocket.Dispose();
	}

**Comment by somdoron** [comment]
First I suggest to also try the zeromq dev list, as this problem is true
for zeromq as well and somebody may already solve it.

Anyway I suggest to try and edit the following file, set the socket linger
to zero after accepting the socket:

https://github.com/zeromq/netmq/blob/master/src/NetMQ/zmq/Transports/Tcp/TcpListener.cs

**Comment by somdoron** [comment]
You can also have a Forward Device at the client side between the REQ and
REP sockets, then the REQ connect to the device using inproc and the device
forward the requests to the REP socket. Only the device will make the
connection to the REP socket. This will work if the services are long lived
and only the requests are short

**Comment by yeowgit** [comment]
Thanks to your quick response.
I set the linger option to 0 as below in TcpListener.cs but no success.

        private void Accept()
        {
            m_acceptedSocket = AsyncSocket.Create(m_address.Address.AddressFamily, SocketType.Stream, ProtocolType.Tcp);

            // start accepting socket async
            m_handle.Accept(m_acceptedSocket);

            m_acceptedSocket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.Linger, 0);
        }

**Comment by deanroker123** [comment]
I think this behavior is os specific and follows the tcp spec. They stay in
time wait for a period of time waiting for any stay packets to arrive that
might have been lost while the connection was alive. If you were to reuse
the same port pairs again straight away and a packet arrived for the old
connection it would cause issues.

I don't think there is anything netmq can do to change this.

Thanks

Dean

**Comment by deanroker123** [comment]
Oh I forgot to say, if you open another connection from the client it
should just pick a new source port and make the connection from that.

**Comment by yeowgit** [comment]
I find that setting linger option to 0 to 'm_handle' socket has the desired effect. TIME_WAIT has transition when Close/Dispose is call from Request socket.

    private void Accept()
    {
        m_acceptedSocket = AsyncSocket.Create(m_address.Address.AddressFamily, SocketType.Stream, ProtocolType.Tcp);

        // start accepting socket async
        m_handle.Accept(m_acceptedSocket);

        m_handle.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.Linger, 0);
    }

It seems m_handle socket property is not exposed and can't be set when you construct response socket. Is it possible to allow setting m_handle socket property on bind? Or there is another way?

**Comment by somdoron** [comment]
@yeowgit I suggest to create a new Socket option (DisableTimeWait?) on the socket options, then in the Accept method you mention above check if the socket option is set and and if it does set the linger to zero.

**Comment by yeowgit** [comment]
Thanks, I followed your advice. I created a pull request if interested.

**Comment by drewnoakes** [comment]
@yeowgit with #304 and #306 merged, are you satisfied that this issue has been addressed?

**Comment by yeowgit** [comment]
@drewnoakes yes, thanks very much for everyone assistance
