### ISSUE TITLE
Commercial Support

### ISSUE THREAD

**Issue by hivanov** [zeromq/netmq#309]
Hello,

We are wondering if there is commercial support for your Library. I see it not part of the original ZeroMQ project, and have been informed on the Zeromq IRC channel that this is an independent effort and thus not supported by them.

**Comment by somdoron** [comment]
@hivanov I don't know of any commercial support currently offered to the product. What is it exactly that you are looking for? you can also contact me privately at somdoron AT gmail DOT com
