### ISSUE TITLE
CancelAndJoin stays blocked

### ISSUE THREAD

**Issue by acnovais** [zeromq/netmq#316]
Hello,

I am having an issue with NetMQ on using a poller. When calling CancelAndJoin it gets on that instruction and never continues.

Is this a known issue?  Or can you point me to what I could be doing wrong ?

I am using nuget version 3.3.0.12-rc1

Thanks.

```
using (_socket = ContextManager.Instance.ZmqContext.CreateDealerSocket())
using (var poller = new Poller(_socket))
{
                _socket.Options.Identity = Config.Encoding.GetBytes(Id);
                _socket.Connect(Config.Endpoint);

                _socket.ReceiveReady += SocketOnReceiveReady;

                var timer = new NetMQTimer(TimeSpan.FromMilliseconds(50));

                timer.Elapsed += OnTimerOnElapsed;

                poller.AddTimer(timer);

                poller.PollTillCancelledNonBlocking();

                _shouldStopPollEvent.Wait(); //This is a MRE

                poller.CancelAndJoin();
                //It never gets here
}
```

**Comment by krisrok** [comment]
can you please add a self-containing code snippet trying to reproduce the issue so we do not have to make assumptions about the rest of your program

**Comment by acnovais** [comment]
Sorry, of course.

In the meantime I figured out the case in which this occurs. I am posting the code for my Dealer socket. My router socket is not relevant. 

The case is that the CancelAndJoin does not continue when there is no real connection (I shut down my Router socket) and there are messages to send by the dealer. If I then turn on my Router socket its able to continue execution. I then figured that it had to be the linger option but even when set the behaviour remaned the same. Am I missing something?

Thanks.

    namespace ConsoleApplication2
    {
    class Program
    {
        static void Main(string[] args)
        {
            var zmq = new ZmqTest();

            Console.ReadLine();
            zmq.Stop();
            Console.ReadLine();
        }
    }

    class ZmqTest
    {
        private NetMQ.Sockets.DealerSocket _socket;
        private readonly NetMQ.NetMQContext _context;
        private readonly ManualResetEventSlim _shouldStopPollEvent = new ManualResetEventSlim(false);
        private readonly ConcurrentQueue<string[]> _outgoingQueue = new ConcurrentQueue<string[]>();

        public ZmqTest()
        {
            _context = NetMQContext.Create();
            
            Task.Factory.StartNew(SocketProcessTask, TaskCreationOptions.LongRunning);
            Task.Factory.StartNew(SendStuffTask, TaskCreationOptions.LongRunning);
        }

        public void Stop()
        {
            _shouldStopPollEvent.Set();
        }

        public void SendStuffTask()
        {
            while (!_shouldStopPollEvent.IsSet)
            {
                _outgoingQueue.Enqueue(new[] {"frame1", "frame2", "frame3"});
                Thread.Sleep(1);
            }
            Console.WriteLine("Stopped sending");
        }

        private void SocketProcessTask()
        {
            try
            {
                using (_socket = _context.CreateDealerSocket())
                using (var poller = new Poller(_socket))
                {
                    _socket.Options.Identity = Encoding.UTF8.GetBytes("DealerTest");
                    _socket.Options.Linger = new TimeSpan(0);
                    _socket.Connect("tcp://system.local:6668");

                    _socket.ReceiveReady += SocketOnReceiveReady;

                    var timer = new NetMQTimer(TimeSpan.FromMilliseconds(10));

                    timer.Elapsed += OnTimerOnElapsed;

                    poller.AddTimer(timer);

                    poller.PollTillCancelledNonBlocking();

                    _shouldStopPollEvent.Wait();

                    Console.WriteLine("Cancelling poller");

                    poller.CancelAndJoin();   

                    Console.WriteLine("Exited normally");
                }
            }
            catch (Exception ex)
            {
                //
            }
            finally
            {
                if (!_shouldStopPollEvent.IsSet)
                {
                    _shouldStopPollEvent.Set();
                }
            }
        }

        private void OnTimerOnElapsed(object sender, NetMQTimerEventArgs e)
        {
            string[] messageParts;
            while (_outgoingQueue.TryDequeue(out messageParts))
            {
                var i = 0;
                byte[] messagePartsBytes;

                while (i < messageParts.Length - 1)
                {
                    messagePartsBytes = Encoding.UTF8.GetBytes(messageParts[i++]);
                    _socket.SendMore(messagePartsBytes, messagePartsBytes.Length);
                }

                messagePartsBytes = Encoding.UTF8.GetBytes(messageParts[i]);
                _socket.Send(messagePartsBytes, messagePartsBytes.Length);
            }
        }

        private void SocketOnReceiveReady(object sender, NetMQSocketEventArgs e)
        {
            string message = "";
            bool hasMore;
            do
            {
                var frame = _socket.Receive(false, out hasMore);
                int size = frame.Length;

                message += Encoding.UTF8.GetString(frame, 0, size) + " ";
                
            } while (hasMore);
            Console.WriteLine(message);
        }
    }
    }

**Comment by mpkramer** [comment]
m_isStoppedEvent is not needed in \netmq\src\NetMQ\Poller.cs ?

Interlocked.Exchange(ref m_cancel, 1); (in Cancel(bool waitForCloseToComplete)) is sufficient ?

**Comment by iloginov** [comment]
Could you please set Linger to non-zero value for testing?

**Comment by sjaini44u** [comment]
Did someone find solution or root cause for this , me too facing the same issue.

**Comment by somdoron** [comment]
I think NetMQPoller solved that

**Comment by sjaini44u** [comment]
I am using version which dont have NetMQPoller . What is fix for problem , if i could extend Poller and implement the same fix in extended poller class. Thanks in advance

**Comment by somdoron** [comment]
Just dont use CancelAndJoin, the problem is when using it nisde the poller
thread, the fix to just ignore tge stop when called inside poller thread.
Just use cancel. Anyway if it not the case it might be helpful to include
your code
