### ISSUE TITLE
"high" CPU utilization in Publisher.Server

### ISSUE THREAD

**Issue by meraydin** [zeromq/netmq#319]
I use the following code snippet in Publisher/Subscriber example. Code works okay however publisher consumes 25% CPU "continuosly" on "pub.SendMore(..)" line - regardless of the number of subscribers connected (including zero subscriber). 

Am I missing something?

P.S. "cq" in the code is a ConcurrentQueue.

        static void Server(NetMQContext context)
        {
            using (var pub = context.CreatePublisherSocket())
            {
                using (NetMQMonitor monitor = new NetMQMonitor(context, pub, "inproc://pub.inproc", SocketEvent.Accepted | SocketEvent.Listening | SocketEvent.Disconnected))
                {
                    // for publisher/subscriber mode, only the following events happen
                    monitor.Accepted += new EventHandler<NetMQMonitorSocketEventArgs>(monitor_Accepted);
                    monitor.Listening += new EventHandler<NetMQMonitorSocketEventArgs>(monitor_Listening);
                    monitor.Disconnected += new EventHandler<NetMQMonitorSocketEventArgs>(monitor_Disconnected);

                    monitor.Timeout = TimeSpan.FromHours(1); // TimeSpan.FromMilliseconds(1000);

                    // be careful with the event handlers, if an exception is thrown, monitor will die!
                    var pollerTask = Task.Factory.StartNew(monitor.Start);

                    // publisher uses 'bind' (subscriber uses 'connect')
                    pub.Bind("tcp://*:5002");

                    pub.Options.DelayAttachOnConnect = false;

                    while (hasMore)
                    {
                      
                        if (!cq.IsEmpty)
                        {
                            string item = string.Empty;
                            if (cq.TryDequeue(out item))
                            {
                                try
                                {
                                    System.Diagnostics.Debug.WriteLine("Sending " + item);
                                    pub.SendMore("topic").Send(item);
                                }
                                catch (Exception ex)
                                {
                                    System.Diagnostics.Debug.WriteLine(ex.Message);
                                }
                            }

                        }
                    }

                }
            }
        }

**Comment by AlekseiOhotnik** [comment]
You didn't mention that uncommenting 1000 ms timeout in your code fixes this problem. In case it doesn't in your app than check my point A which describes a busy spin to see if that is the case. While overflow described in B on the netmq side should be handled by fix.

There are mutliple issues which I see immediately in both NetMQ and your example:

A) It is not clear what values "hasMore" from your code has at any moment in time, but if it resolves to true most of the time while queue is empty this will cause a busy spin.

B) Timeout value of one hour is definetly not suitable for polling timeout as Socket.Select and Socket.Poll are using int in microseconds while netmq is int in milliseconds causing an guaranteed overflow. This overflow is corrected by netmq setting current running timeout to 0, thus thread will spin around polling functions.

**Comment by meraydin** [comment]
Hmm i was looking for the documentation for "timeout" parameter actually. I didn't know it has this effect. I will give it a try tonight and report back.

Thanks



Sent from my Samsung device


-------- Original message --------

**Comment by meraydin** [comment]
Test results:


·       Changing monitor.Timeout to 1000ms helped a little (was 25% now 12%) but still looks high to me. I’ve played with other values (timespan.zero, 100ms, 1ms) but it remained around 12-13% (flat line on taskmanager)

·       hasMore is a bool and is “true” for this example. Also checking cq.IsEmpty has no effect on cpu usage.

What I’ve discovered while playing with the code:


·       Adding Thread.Sleep(0) inside the loop has no effect  (12-13%)

·       Adding Thread.Sleep(1) inside the loop lowers CPU usage to zero! But this means I can execute this loop 1000 times a second max.

Any ideas?

**Comment by meraydin** [comment]
Well, it looks my code is somehow not correct. I cannot figure out how to write a realworld example that use NetMQ. I’m attaching the complete server code… Just run it and watch CPU…

What I’m trying to do:


·       Fill a concurrent queue from another thread

·       Have a worker thread that will watch the concurrent thread and send the messages to it’s subscribers

Above two topics look what NetMQ is written for but I cannot make it work without eating all cpu cycles… Problem(s) with the example


·       If I uncomment Threading.Thread.Sleep(1), it works ok (almost no cpu utilzation) however I don’t want to limit myself to 1000 executions/sec

If anyone come up with a complete code sample, I will be able to sleep ☺



using System;
using System.Collections.Concurrent;
using System.Threading.Tasks;
using NetMQ;
using NetMQ.Monitoring;
using NetMQ.zmq;

namespace Publisher
{

    class Program
    {
        static ConcurrentQueue<string> cq = new ConcurrentQueue<string>();
        static bool hasMore = true;

        static void Main(string[] args)
        {

            var t = new System.Timers.Timer();
            t.Elapsed += new System.Timers.ElapsedEventHandler(t_Elapsed);
            t.Interval = 900;
            t.Enabled = true;

            using (NetMQContext context = NetMQContext.Create())
            {
                Task serverTask = Task.Factory.StartNew(() => Server(context));
                Task.WaitAll(serverTask);
            }
        }

        static void t_Elapsed(object sender, System.Timers.ElapsedEventArgs e)
        {
            cq.Enqueue("Time is " + DateTime.Now.ToLongTimeString());
            //we can set hasMore to false here...
        }

        static void Server(NetMQContext context)
        {
            using (var pub = context.CreatePublisherSocket())
            {
                using (NetMQMonitor monitor = new NetMQMonitor(context, pub, "inproc://pub.inproc", SocketEvent.Accepted | SocketEvent.Listening | SocketEvent.Disconnected))
                {
                    // for publisher/subscriber mode, only the following events happen
                    monitor.Accepted += new EventHandler<NetMQMonitorSocketEventArgs>(monitor_Accepted);
                    monitor.Listening += new EventHandler<NetMQMonitorSocketEventArgs>(monitor_Listening);
                    monitor.Disconnected += new EventHandler<NetMQMonitorSocketEventArgs>(monitor_Disconnected);

                    monitor.Timeout = TimeSpan.FromMilliseconds(1000);

                    // be careful with the event handlers, if an exception is thrown, monitor will die!
                    var pollerTask = Task.Factory.StartNew(monitor.Start);

                    // publisher uses 'bind' (subscriber uses 'connect')
                    pub.Bind("tcp://*:5002");

                    pub.Options.DelayAttachOnConnect = false;

                    while (true)
                    {
                        // Thread.Sleep(1);
                        if (!cq.IsEmpty)
                        {
                            string item = string.Empty;
                            if (cq.TryDequeue(out item))
                            {
                                try
                                {
                                    //    System.Diagnostics.Debug.WriteLine("Sending " + item);
                                    pub.SendMore("topic").Send(item);

                                }
                                catch (Exception ex)
                                {
                                    System.Diagnostics.Debug.WriteLine(ex.Message);
                                }
                            }

                        }
                    }

                }
            }
        }

        static void monitor_Disconnected(object sender, NetMQMonitorSocketEventArgs e)
        {
            try
            {
                Console.WriteLine("Disconnected: " + e.Socket.RemoteEndPoint.ToString());
            }
            catch (Exception)
            {
            }
        }

        static void monitor_Listening(object sender, NetMQMonitorSocketEventArgs e)
        {
            try
            {
                Console.WriteLine("Listening on: " + e.Address);
            }
            catch (Exception)
            {
            }
        }

        static void monitor_Accepted(object sender, NetMQMonitorSocketEventArgs e)
        {
            try
            {
                Console.WriteLine("Accepted: " + e.Socket.RemoteEndPoint.ToString());
            }
            catch (Exception)
            {
            }
        }
    }
}



From: Murat Eraydın
Sent: Thursday, April 02, 2015 5:36 PM
To: 'zeromq/netmq'; zeromq/netmq
Subject: RE: [netmq] "high" CPU utilization in Publisher.Server (#319)

Test results:


·       Changing monitor.Timeout to 1000ms helped a little (was 25% now 12%) but still looks high to me. I’ve played with other values (timespan.zero, 100ms, 1ms) but it remained around 12-13% (flat line on taskmanager)

·       hasMore is a bool and is “true” for this example. Also checking cq.IsEmpty has no effect on cpu usage.

What I’ve discovered while playing with the code:


·       Adding Thread.Sleep(0) inside the loop has no effect  (12-13%)

·       Adding Thread.Sleep(1) inside the loop lowers CPU usage to zero! But this means I can execute this loop 1000 times a second max.

Any ideas?

**Comment by AlekseiOhotnik** [comment]
If all the cpu is doing is checking cq.IsEmpty it is exactly where all its cycles will go, so it consumes the whole core. You can find more explanations from links at the end. What you are looking for is some sort of signaling here so thead can suspend and resume when there is actual work to be done. If you don't want to bother with implementation yourself you can use BlockingCollection instead of the ConcurrentQueue:
https://msdn.microsoft.com/en-us/library/dd267312%28v=vs.110%29.aspx

It has a hand full of methods for checking to see if data is available, blocking and timeout versions of them. Also consuming enumberable iteration is possible, which blocks until items are inserted.

Here are some examples, just make sure to handle cancellation exception around all the methods accepting a token or mention such exception in their documentation. I didn't put them where should in examples.

// A)
// If you don't need to do anything else in the while loop you had, consuming enumerable is enough
try
{
    foreach (string item in cq.GetConsumingEnumerable(cts.Token))
    {
        // publish
    }
}
catch(OperationCanceledException) // this exception will be thrown on cancel
{
    System.Diagnostics.Debug.WriteLine("Publisher is not sending anymore");
}

// B)
while (!cts.Token.IsCancellationRequested)
{
    // Could be blocking if needed
    //string item = cq.Take();
    string item = cq.Take(cts.Token); // exception will be thrown on cancel

    // publish
}

// C)
while (!cts.Token.IsCancellationRequested)
{
    string item = null;
    if (cq.TryTake(out item))
    {
        // publish
    }
    else
    {
        // do something usefull
    }
}
// D)
while (!cts.Token.IsCancellationRequested)
{
    string item = null;
    //if(cq.TryTake(out item, 1000, cts.Token)) // exception will be thrown on cancel
    if (cq.TryTake(out item, 1000))
    {
        // publish
    }
    else
    {
        // do something usefull after 1000 second timeout
    }
}

http://en.wikipedia.org/wiki/Busy_waiting
http://en.wikipedia.org/wiki/Spinlock

**Comment by meraydin** [comment]
Thanks a lot… I’ve implemented “A” and now it works cool ;)

**Comment by BruceMellows** [comment]
You should do an experiment ... how many Sleep(1) can I do in one second 
- if you tell me the answer, I can tell you if you have a single or 
multi-core machine, and the answer will not even be close to 1000.

Hint - the answer should be (close to) either 60 or 100.

**Comment by meraydin** [comment]
Well, it looks like I can do 1014 sleeps in one sec. (empty loop)

If you’re asking “how many sleeps in that code section in one second”, can’t tell since I’ve already changed it with BlockingCollection.

**Comment by AlekseiOhotnik** [comment]
The correct answer how many iterations the loop with Sleep(1) is going to make depends on the frequency of the clock which can be in range of 64hz to 1000hz on windows systems. So it is any number between 60 and 1000  +/- some margin. Meraydin has probably a browser open on his system which requested windows to set resolution to maximum for multimedia latency purposes or some other software did this. This also cannot be used to tell how many cores are there as it is unrelated. Since there was mention of cpu loads I can assume 25% load on two threads leads us to 8 cores system, or 4 cores with HT on.

**Comment by meraydin** [comment]
Here is what I've come up with. This is working... HTH someone else. 

using System;
using System.Collections.Concurrent;
using System.Threading.Tasks;
using NetMQ;
using NetMQ.Monitoring;
using NetMQ.zmq;
using System.Threading;

namespace Publisher
{

    class Program
    {
       
        static BlockingCollection<string> bq = new BlockingCollection<string>();
        static CancellationTokenSource cts = new CancellationTokenSource();

        static bool hasMore = true;   
      
        static void Main(string[] args)
        {

            var t = new System.Timers.Timer();
            t.Elapsed += new System.Timers.ElapsedEventHandler(t_Elapsed);
            t.Interval = 500;
            t.Enabled = true;

            using (NetMQContext context = NetMQContext.Create())
            {
                Task serverTask = Task.Factory.StartNew(() => Server(context));
                Task.WaitAll(serverTask);
            }
        }

        static void t_Elapsed(object sender, System.Timers.ElapsedEventArgs e)
        {
           
            bq.Add("Time is " + DateTime.Now.ToLongTimeString());
            //stop publisher
            if (DateTime.Now.Second == 59) cts.Cancel();
        }

        static void Server(NetMQContext context)
        {
            using (var pub = context.CreatePublisherSocket())
            {
                using (NetMQMonitor monitor = new NetMQMonitor(context, pub, "inproc://pub.inproc", SocketEvent.Accepted | SocketEvent.Listening | SocketEvent.Disconnected))
                {
                    // for publisher/subscriber mode, only the following events happen
                    monitor.Accepted += new EventHandler<NetMQMonitorSocketEventArgs>(monitor_Accepted);
                    monitor.Listening += new EventHandler<NetMQMonitorSocketEventArgs>(monitor_Listening);
                    monitor.Disconnected += new EventHandler<NetMQMonitorSocketEventArgs>(monitor_Disconnected);
                    
                    monitor.Timeout = TimeSpan.FromMilliseconds(1000);

                    // be careful with the event handlers, if an exception is thrown, monitor will die!
                    var pollerTask = Task.Factory.StartNew(monitor.Start);

                    // publisher uses 'bind' (subscriber uses 'connect')
                    pub.Bind("tcp://*:5002");
                    pub.Options.DelayAttachOnConnect = false;

                    try
                    {
                        foreach (var item in bq.GetConsumingEnumerable(cts.Token))
                        {
                            pub.SendMore("topic").Send(item);
                        }
                    }
                    catch (OperationCanceledException ex)
                    {
                        // publisher not sending anymore...
                        System.Diagnostics.Debug.WriteLine("Publisher stopped..." + ex.Message);
                    }

                }
            }
        }

        static void monitor_Disconnected(object sender, NetMQMonitorSocketEventArgs e)
        {
            try
            {
                Console.WriteLine("Disconnected: " + e.Socket.RemoteEndPoint.ToString());
            }
            catch (Exception)
            {
            }
        }

        static void monitor_Listening(object sender, NetMQMonitorSocketEventArgs e)
        {
            try
            {
                Console.WriteLine("Listening on: " + e.Address);
            }
            catch (Exception)
            {
            }
        }

        static void monitor_Accepted(object sender, NetMQMonitorSocketEventArgs e)
        {
            try
            {
                Console.WriteLine("Accepted: " + e.Socket.RemoteEndPoint.ToString());
            }
            catch (Exception)
            {
            }
        }
    }
}
