### ISSUE TITLE
Still problems with netMQ 3.5 and Unity

### ISSUE THREAD

**Issue by FaisalZ** [zeromq/netmq#324]
Although it has been stated as solved in issue report #98, I am still facing problems when integrating zeroMQ into Unity.
It compiles and starts well when beeing used as managed plugin in Unity, but it does not send out any messages.
When I swap the NetMQ.dll and AsyncIO.dll for the ones compiled from somdoron's fork (without changing any code) it workes fine as expected.
@krisrok: Did you compile netMQ 3.5 with any settings differing from the default settings in the master branch?

**Comment by Mystfit** [comment]
I tested Unity 5.0.4 with the latest NetMq master code and hung when sending or receiving messages with nowait set to false.

I confirmed that the old Unity branch that I've been using for the past year still works, but it's pretty out of date at this stage (https://github.com/mystfit/netmq/tree/Net35Compat-BindRandom).

@FaisalZ, what branch on @somdoron's fork did you compile to get it working?

**Comment by somdoron** [comment]
What OS are you using? did you try to compile from master or using latest
pre-release from nuget?

**Comment by Mystfit** [comment]
I compiled from the master branch on Windows 8.1 .

**Comment by somdoron** [comment]
Try to have at the beginning of your application

ForceDotNet.Force();

This will instruct async io to use .net implementation instead of pinvoke.

**Comment by Mystfit** [comment]
@somdoron Can confirm that 
```
AsyncIO.ForceDotNet.Force();
```
fixes the hanging issue in Unity 5.1.0f3.

**Comment by o-zombi-o** [comment]
@somdoron I can also confirm that `AsyncIO.ForceDotNet.Force();` fixes the hanging issue in *Unity 5.0.2f1 Personal* compiling NetMQ from a master cloned no more than a few days ago (about 10/Jul/15).

**Comment by somdoron** [comment]
@o-zombi-o kind of long time, but there was a PR that fix this problem
