### ISSUE TITLE
Long running application error: "NetMQ.NetMQException NetMQ.zmq.TcpConnecter.Connect()"

### ISSUE THREAD

**Issue by joaoantunes** [zeromq/netmq#325]
Hi,

I've implemented a Service Broker using the Majordomo Pattern.
After I let my application running +/- a day, my application crashed and I've got following log, on the event viewer:

"Application: VW.Hosting.App.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: NetMQ.NetMQException
Stack:
   at NetMQ.zmq.TcpConnecter.Connect()
   at NetMQ.zmq.TcpConnecter.OutEvent()
   at NetMQ.zmq.Poller.Loop()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()"

Do you have any idea what may cause this? Am I out of sockets? Memory? 
I've lost already a bunch of time trying to diagnose what my cause this, like monitoring memory, threads, handles, processor, sockets, etc,, but everything seems normal. 

Obs: I'm using the last stable .NETMQ version 3.3.0.11. 
The code isn't small to put it here. Any idea how to track what may cause this exception?

**Comment by somdoron** [comment]
Can you try the latest code from master (soon will be released as stable
version)?

**Comment by joaoantunes** [comment]
Sure, I'll try that. 
I've download the source code, now I should use which which project? NetMQ or NetMQ3.5?

**Comment by drewnoakes** [comment]
The two projects are mostly identical. NetMQ3.5  targets .net 3.5, so
unless you're using that version of .net, use the other project.

**Comment by joaoantunes** [comment]
Ok I've made a NugetPackage with latest code from the master (29/04/2015).

So far so good, the ServiceBroker (and the rest of the app) is running. I'll let it run for some more time to check if everything is ok.

One thing that I've detected is that now my program doesn't close... I attached the program and check the threads and one was stuck here:

At netmq-master\src\NetMQ\Core\Utils\Signaler.cs
public bool WaitEvent(int timeout)
        {
            int timeoutInMicroSeconds = (timeout >= 0)
                ? timeout * 1000
                : Timeout.Infinite;

            if (m_readSocket.Connected)
                **return m_readSocket.Poll(timeoutInMicroSeconds, SelectMode.SelectRead);**

            return false;
        }

The variable timeout had the value: -1

So this will poll forever? There is nothing like a cancelationToken?
Here is the callstack:

 	NetMQ.dll!NetMQ.Core.Utils.Signaler.WaitEvent(int timeout) Line 113	C#
 	NetMQ.dll!NetMQ.Core.Mailbox.Recv(int timeout) Line 234	C#
 	NetMQ.dll!NetMQ.Core.Ctx.Terminate() Line 245	C#
 	NetMQ.dll!NetMQ.NetMQContext.Terminate() Line 282	C#
 	NetMQ.dll!NetMQ.NetMQContext.Dispose(bool disposing) Line 303	C#
 	NetMQ.dll!NetMQ.NetMQContext.Dispose() Line 290	C#
>	VW.Messaging.dll!VW.Messaging.MessagingContext..ctor.AnonymousMethod__1() Line 53	C#

I've had a NetMQContext a Poller and a Scheduler added to the poller.

Here is my the code that wasn't able to dispose:

var task = Task.Factory.StartNew(() =>
            {
               using (context = NetMQContext.Create())
               {
                  using (poller = new Poller())
                  {
                     poller.PollTimeout = Constants.HEARTBEAT_INTERVAL_IN_MILIS;
                     using (scheduler = new NetMQScheduler(context, poller))
                     {
                        startupWaiter.Set();
                        poller.Start();
                     }
                  }
               }
            }, TaskCreationOptions.LongRunning)
            .ContinueWith(x => logger.Error(x.Exception.ToString(), startupWaiter.Set()/*para desbloquear o program em caso de erro*/),
            TaskContinuationOptions.OnlyOnFaulted);

Should I open a new issue only related to this matter?

**Comment by joaoantunes** [comment]
Ok I after a long period of tests I think i finally found out what was the problem with my Service Broker.

I was was creating a destroying a Client for each messages I wanted to send, despite my linger was set to 0, windows takes a long time (depending on the machine configuration) to dispose this Socket (it enters on a TIME_WAIT state).

Mainly because i was creating sockets more rapidly than windows was destroying them, after a long run I was entering in a scenario that i had no available sockets. 

NETmq isn't atm suporting all Socket error codes, the error I was getting was "Access denied", because I've set windows to use "max" number of dynamic ports and for some reason windows was giving me ports that were denied. This issue was solved by changing the dynamic start port to 10000 and to use all beetween 10000 and 65535.

You can close this issue :+1:

**Comment by somdoron** [comment]
thanks

**Comment by DevsAnon** [comment]
> Can you try the latest code from master (soon will be released as stable
> version)?

What was the version that this changes ended up in?
