### ISSUE TITLE
Disposing NetMQScheduler hangs

### ISSUE THREAD

**Issue by kellyelton** [zeromq/netmq#326]
If you don't actually start the `NetMQScheduler` and try to `Dispose` it, it hangs.

**Comment by esskar** [comment]
Can you give an example? I added a test

    [Test]
    public void NoTask()
    {
        using (var context = NetMQContext.Create())
        {
            var scheduler = new NetMQScheduler(context);
            scheduler.Dispose();
        }
    }

but it runs just fine

**Comment by kellyelton** [comment]
I guess I did add a poller  to it as well, could try that.

**Comment by esskar** [comment]
@kellyelton could you just provide example code that fails. Guessing is not really helpful here

**Comment by kellyelton** [comment]
Yeah sure, just throwing thing out there, won't have access till tomarrow.
Also, as a side not probably going to open a second ticket because this
disposal system is pretty rube goldberg

**Comment by kellyelton** [comment]
var _context = NetMQContext.Create();
	var _ssocket = _context.CreateSubscriberSocket();
	var _poller = new Poller(_ssocket);
	var _scheduler = new NetMQScheduler(_context, _poller);
	_ssocket.Dispose();
	_scheduler.Dispose();
	_context.Dispose();

**Comment by esskar** [comment]
you must be doing something totally different.
please provide a unit test that fails.

        [Test(Description = "Disposing NetMQScheduler hangs #326")]
        public void Issue326()
        {
            var context = NetMQContext.Create();
            var ssocket = context.CreateSubscriberSocket();
            var poller = new Poller(ssocket);
            var scheduler = new NetMQScheduler(context, poller);
            
            ssocket.Dispose();
            scheduler.Dispose();
            context.Dispose();
        }

is working as expected; no hanging no nothing.

**Comment by drewnoakes** [comment]
Kelly, I'd that unit test fails on your computer then what environment are
you using? OS, .NET version, build configuration, etc...

**Comment by kellyelton** [comment]
Windows 8.1. Both .net 4.5.1 and running in linqpad.

**Comment by kellyelton** [comment]
That hangs ok every pc it's ran on. I'm also using the nuget  package.

**Comment by neoKushan** [comment]
Hi,

I believe I've managed to reproduce this issue. This was from an attempt at creating an async wrapper for the NetMQ req/rep sockets, found here: http://somdoron.com/2013/06/netmq-scheduler/.

    [Test(Description = "Disposing NetMQScheduler hangs #326")]
    public void Issue326()
    {
        var cts = new CancellationTokenSource();
        var context = NetMQContext.Create();
        var rsocket = context.CreateResponseSocket();
        var port = rsocket.BindRandomPort("tcp://127.0.0.1");
        var poller = new Poller(rsocket);
        var scheduler = new NetMQScheduler(context, poller);

        Task.Factory.StartNew(() =>
        {
            poller.PollTillCancelled();
        },
            cts.Token);


        var task = new Task<NetMQMessage>(() => rsocket.ReceiveMultipartMessage(), cts.Token);
        task.Start(scheduler);

        cts.Cancel();

        poller.CancelAndJoin(); // Will hang here

        rsocket.Dispose(); 
        scheduler.Dispose();
        context.Dispose();
    }

I am aware that I might just be doing something stupid, though.

**Comment by somdoron** [comment]
I will take a look.
