### ISSUE TITLE
Majordomo worker sample code hangs

### ISSUE THREAD

**Issue by eddylai** [zeromq/netmq#327]
I tried to start the netmq majordomo example (with VS2013 on Win7)
"StartMDPExample - Verbose.bat"
the worker terminal dead after few seconds, have anyone got the same problem?
and the client didnt get any reply from the worker
## the message from worker terminal like this:

Starting the worker!
[WORKER] connected to broker at tcp://localhost:5555
[WORKER] sending NetMQMessage[,MDPW01,?,echo] to broker / Command Ready
[WORKER] sending NetMQMessage[,MDPW01,?] to broker / Command Heartbeat
[WORKER] sending NetMQMessage[,MDPW01,?] to broker / Command Heartbeat
[WORKER INFO] disconnected from broker - retrying ...
[WORKER] connected to broker at tcp://localhost:5555
[WORKER] sending NetMQMessage[,MDPW01,?,echo] to broker / Command Ready
[WORKER] sending NetMQMessage[,MDPW01,?] to broker / Command Heartbeat
[WORKER] sending NetMQMessage[,MDPW01,?] to broker / Command Heartbeat

**Comment by eddylai** [comment]
have anyone tried this?

**Comment by chubbson** [comment]
have same issue:
Worker seems to react on heartbeat from broker about 3times, then disconnects for a while. after 15-20secs it will react on heartbeats again. if you start client while the worker is connected an reacts on heartbeats, everything is file. if you start the client while the worker is in Disconnected state, => no echo service available. MDSamples seems to be in a Buggy state. 

Ive portet the md sample on clrzmq4 which act like the c examples (outputbehaviour). was reading the guide while working on a c unix proj. havnt recognised there is sth like .netmq :] and ported some c# examples which i havent found thru the guide. ill check/fix this example in the next 2-3weeks.

**Comment by Camuvingian** [comment]
Any update on this guys?

**Comment by zedo02** [comment]
Any solution/workaround to this issue?
