### ISSUE TITLE
Solution files

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#333]
The project currently has three solution files. Each appears to be for a different version of Visual Studio, however the names don't match the actual versions.

* `NetMQ.sln` is version 11 (VS2010)
* `NetMQ.v11.sln` is version 12 (VS2012)
* `NetMQ.vs10.sln` is version 10 (VS2008)

Do we need these different solutions? If so, they should be renamed/corrected to reflect the correct VS versions.

**Comment by somdoron** [comment]
I think now we only need the 2013 solution...

**Comment by drewnoakes** [comment]
Ok. I'll get a PR together for that.

The build will need to be updated too as it currently seems to build
vs10.sln.

**Comment by leverate-somech** [comment]
@drewnoakes I fixed the build
