### ISSUE TITLE
Merge NetMQSchduler and Poller into NetMQPoller

### ISSUE THREAD

**Issue by somdoron** [zeromq/netmq#336]
What do you think of disposing the NetMQScheduler and make the Poller a scheduler?

**Comment by drewnoakes** [comment]
I really like this idea. In fact only today I hit upon something that this would have helped with -- Ideally the Poller/Scheduler would set the current `SynchronizationContext` so that tasks continue on the poller thread and not a threadpool thread. This was causing some weird bugs for us where messages were being interleaved.

To keep .NET 3.5 support, the scheduler code could be enclosed with `#if !NET35` ... `#endif`.

**Comment by drewnoakes** [comment]
Currently the types are:

```csharp
public class Poller : IDisposable { ... }

public class NetMQScheduler : TaskScheduler, IDisposable { ... }
```

Merging them we could end up with:

```csharp
public sealed class Poller :
#if !NET35
    TaskScheduler,
#endif
    IDisposable

[Obsolete("Poller is a scheduler, so use it directly.")]
public class NetMQScheduler : TaskScheduler, IDisposable { ... }
```

To make this a non-breaking change has a challenge. `NetMQScheduler`'s constructor uses an instance of `NetMQContext` to create push/pull sockets, however `Poller` doesn't require a context in its constructors.

Options I see are:

* Obtain a context from the first `NetMQSocket` or `NetMQTimer` added. This fails if only regular `Socket`s are added though.
* Enable scheduling only if a user calls `Poller.ScheduleOn(context)` or similar. Yuck.
* Mark both the current `Poller` and `NetMQScheduler` as obsolete and create a new type which encompasses the behaviour of both.

The last seems like the easiest, and we'll omit all currently obsolete members too.

This new class would also unify the adding/removing of sockets and timers, allowing use of the [collection initialiser syntax](https://msdn.microsoft.com/en-us/library/bb384062.aspx) of form:

    var poller = new NetMQPoller(context) { socket1, socket2 };

If we are to introduce a new class, perhaps it should be called `NetMQPoller`. This more closely fits with existing NetMQ class names.

---

I've started coding this so will get it up on a PR for review and discussion. If you see problems with this approach, please comment here as soon as is convenient.

**Comment by drewnoakes** [comment]
How do we feel about referencing [Microsoft.Bcl.Async](https://www.nuget.org/packages/Microsoft.Bcl.Async) to enable async/await on selected APIs while still targetting .NET 4.0?

I'm contemplating the following public API:

```csharp
public sealed class NetMQPoller : TaskScheduler, IEnumerable, IDisposable
{
    void Add(ISocketPollable socket);
    void Add(Socket socket, Action<Socket> callback);
    void Add(NetMQTimer timer);

    void Remove(ISocketPollable socket);
    void Remove(Socket socket, Action<Socket> callback);
    void Remove(NetMQTimer timer);

    void Start();      // blocks
    Task StartAsync(); // start in another thread

    void Stop();      // blocks until stopped
    Task StopAsync(); // returns a task that completes when the poller has stopped

    void Dispose()
}
```

For .NET 3.5, the `TaskScheduler` base class will be dropped, and `*Async` methods will return `void` instead of `Task`.

Also, is there a use case for the current `PollOnce` method?

**Comment by drewnoakes** [comment]
As `NetMQPoller` has an inbuilt scheduler, what if the `Add`/`Remove` and maybe even `Stop` and `Dispose` methods were internally scheduled to ensure thread safety?

**Comment by drewnoakes** [comment]
The scheduling of `Add`/`Remove` calls would be harder to do in .NET 3.5.

What about only obsoleting the current `Poller` in .NET 4+?

**Comment by drewnoakes** [comment]
WIP here: https://github.com/drewnoakes/netmq/blob/feature/merge-poller-and-scheduler/src/NetMQ/NetMQPoller.cs

**Comment by JamesWHurst** [comment]
I like your idea. It's very useful to be able to choose methods that do not block, and this follows an established pattern.

**Comment by drewnoakes** [comment]
@somdoron do you have time to review this? I've done a little more work on merging the `NetMQScheduler` and `Poller` into `NetMQPoller`. I've added some unit tests now.

Notes:

- `NetMQPoller` behaves differently on .NET 3.5 where there is not `System.Threading.Tasks`
- There's a half-baked abstraction over `Poller` and `NetMQPoller` to get tests working with `NetMQMonitor` and this abstraction will probably be extended if we are to replace usages of `Poller` internally
- There are still several uses of the now-obsolete `Poller` class throughout `NetMQ.dll` which will need to be migrated before this could be considered ready for a PR
- I will document the API if it looks like we will go ahead with this class

**Comment by somdoron** [comment]
Yes I will take a look today or tomorrow...

**Comment by somdoron** [comment]
@drewnoakes looks great, really nice. Few comments:

* Regarding the synchronization context, I'm not about the exception handling, right now the exception that will be thrown is the AggrgateException, which will eventually crash the system when be collected by the GC. how does the default synchronization context works?
* Regarding the locking and awake strategy, if we really want we actually make it better by using the pattern in https://github.com/zeromq/netmq/blob/master/src/NetMQ/Core/YPipe.cs, which will only awake when needed. However this is only important if the scheduler is going to be overloaded, we might want to do a performance check to see if we need that.
* Do we want a method called Yield or even better RunAndYield? it will switch your thread to the poller thread, like this:

```csharp

await poller.Yield();

// this code is running on the poller thread

```

**Comment by yeowgit** [comment]
Hi,
Just wondering how this work is progressing and any eta on when this feature will be available on master branch. Merge poller and scheduler with thread safe poller, will help our project greatly.
thanks

**Comment by somdoron** [comment]
@drewnoakes is it ready to be merged?

**Comment by drewnoakes** [comment]
No it's not yet ready as the questions and feedback need addressing. I would like to look at this, but can't guarantee I'll get around to it by a certain time. If others want to take a look, by all means do. Otherwise I'll try to have a look over the next week or two sometime.

I would also like to see poller/scheduler merge. I think it will clean up the API for modern C# code quite nicely.

**Comment by drewnoakes** [comment]
@somdoron just re-noticed your comments from earlier.

> Regarding the synchronization context, I'm not about the exception handling, right now the exception that will be thrown is the AggrgateException, which will eventually crash the system when be collected by the GC. how does the default synchronization context works?

Are you thinking of unobserved task exceptions? In modern .NET these don't crash the process, IIRC. Or are you referring to something else?

>Regarding the locking and awake strategy, if we really want we actually make it better by using the pattern in https://github.com/zeromq/netmq/blob/master/src/NetMQ/Core/YPipe.cs, which will only awake when needed. However this is only important if the scheduler is going to be overloaded, we might want to do a performance check to see if we need that.

I'll take a look at this. Hopefully it shouldn't change the public API, so could be added and tested later on.

>Do we want a method called Yield or even better RunAndYield? it will switch your thread to the poller thread.

This too is an interesting idea. I'll take a look.
