### ISSUE TITLE
netmq high cpu utilization pub/sub socket

### ISSUE THREAD

**Issue by SriramSakthivel** [zeromq/netmq#337]
Hi,

I've lately migrated to netmq from clrzmq. I discovered that netmq consumes high cpu usage when using `SubscribeSocket`. 

I'm specifying the infinite receive timeout. It doesn't matter whether the data is received or not, netmq takes high cpu.

I've created a minimal reproduction code to demonstrate the problem.

Following is the code which I tested with clrzmq. Which works good; zero percentage cpu usage when waiting in `ReceiveFrame` method.

    namespace ClrzmqReceivePerformance
    {
        class Program
        {
            static void Main(string[] args)
            {
                Run();
            }

            private static void Run()
            {
                using (ZmqContext context = ZmqContext.Create())
                using (ZmqSocket publisher = context.CreateSocket(SocketType.PUB))
                {
                    publisher.Bind(string.Format("tcp://*:{0}", 8181));
                    //Publish nothing; Even if you publish, it makes no difference

                    using (ZmqSocket subscriber = context.CreateSocket(SocketType.SUB))
                    {
                        subscriber.Connect(string.Format("tcp://127.0.0.1:{0}", 8181));
                        subscriber.Subscribe(Encoding.Default.GetBytes(""));
                        subscriber.ReceiveTimeout = TimeSpan.MinValue;

                        while (true)
                        {
                            Frame received = subscriber.ReceiveFrame();
                            Console.WriteLine(Encoding.Default.GetString(received.Buffer, 0, received.BufferSize));
                        }
                    }
                }
            }
        }
    }

And the following code which uses netmq consumes high cpu time. In a single cpu machine this takes up all. 100 % utilization, 50 % in dual core machine and so on. 

    namespace NetmqReceivePerformance
    {
        class Program
        {
            static void Main(string[] args)
            {
                Run();
            }

            private static void Run()
            {
                using (NetMQContext context = NetMQContext.Create())
                using (NetMQSocket publisher = context.CreateSocket(ZmqSocketType.Pub))
                {
                    publisher.Bind(string.Format("tcp://*:{0}", 8181));
                    //Publish nothing; Even if you publish, it makes no difference

                    using (SubscriberSocket subscriber = (SubscriberSocket) context.CreateSocket(ZmqSocketType.Sub))
                    {
                        subscriber.Connect(string.Format("tcp://127.0.0.1:{0}", 8181));
                        subscriber.Subscribe(Encoding.Default.GetBytes(""));
                        TimeSpan timeout = TimeSpan.MinValue;

                        while (true)
                        {
                            byte[] bytes;
                            bool received = subscriber.TryReceiveFrameBytes(timeout, out bytes);
                            if (received)
                            {
                                Console.WriteLine(Encoding.Default.GetString(bytes));
                            }
                        }
                    }
                }
            }
        }
    }
Am I doing something wrong? or the netmq is? Please help me in resolving this issue. Thanks in advance.

P.S: I've downloaded the netmq source and found out that most of the time is spent in `SocketBase.Recv` method which ultimately goes to `Signaler.WaitEvent` method which polls the socket; Looks like it uses a busy wait approach. I'm not sure how to go forward.

**Comment by tobi-tobsen** [comment]
It seems the documented way of passing a negative value to the [`System.net.sockets.socket.poll`](https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.poll%28v=vs.110%29.aspx) doesn't work as advertised:

>  Set the microSeconds parameter to a negative integer if you would like to wait indefinitely for a response.

 This might be a bug in the .Net framework since it doesn't block until data is available.
From the user of the zmq's API point of view, the observed behaviour is correct: `TryReceiveFrameBytes` returns only if the frame is available when passed a negative timeout. Unfortunatley, as you found out, zmq behaves in a busy-wait-style because of the aformentioned issue with `socket.poll`.

You might want to try suggestions from #319 or simply pass in an appropriate timeout and call `TryReceiveFrameBytes` again in case it returns false. This minimizes CPU utilization until it socket.poll works as documented.

Does that help?

**Comment by AlekseiOhotnik** [comment]
Pass:
1) TimeSpan.FromMilliseconds(-1) for infinity
2) TimeSpan.FromMilliseconds(0) for no polling
3) above zero values in milliseconds for maximum allowed polling time. It should be reasonable value below 30 min (in ms), but will work if above with multiple calls to sockets underneath.

Negative values were supposed to resolve to -1, but maybe you don't have the fix on version used.

**Comment by SriramSakthivel** [comment]
@AlekseiOhotnik  @tobi-tobsen Thanks for the reply. I checked the .net reference source. It just adds a special case for value -1 (infinite) not for all negative numbers as the documentation is claiming. 

But if I do `TimeSpan.FromMilliseconds(-1)`, then when the `Signaler.WaitEvent` method in netmq converts the millisecond to microsecond, it will become `-1000` which is wrong. We need to pass -1 to the `Socket.Poll` method right?

I guess we need to update the `Signaler.WaitEvent` method like the following.

    public bool WaitEvent(int timeout)
    {
        int timeoutInMicroSeconds = (timeout >= 0)
        ? timeout * 1000
        : Timeout.Infinite;

        if (m_readSocket.Connected)
            return m_readSocket.Poll(timeoutInMicroSeconds, SelectMode.SelectRead);

        return false;
    }

**Comment by SriramSakthivel** [comment]
I have updated the code and created a [pull request](https://github.com/zeromq/netmq/pull/338). Please review it and accept it.

**Comment by drewnoakes** [comment]
Thanks. Pushed as c0902f8e56a4f4c7c8e79d70daa7b5cc722e4f58.

**Comment by drewnoakes** [comment]
Fixed in 9aa582a5c2331cc46db26037f3c7047b66f4d310.
