### ISSUE TITLE
Nuget releasing

### ISSUE THREAD

**Issue by somdoron** [zeromq/netmq#342]
I would like to get more maintainers on the owners list on NetMQ nuget (https://www.nuget.org/packages/NetMQ/) so a versions will be released consistently, currently I'm the only and not always have the time to release version to nuget (like in the last few month).

Anyway to do that I think we need some kind of a guide/process on how to release a version, for example:
- is it beta / stable?
- how to manage stable releases?
- Release notes

If anyone up to the task for writing the guide let me know, also if you would like to join the owners on nuget let me know (should you be NetMQ maintainer first?) and I will add you (make sure to follow the future guide before releasing a version).

**Comment by buybackoff** [comment]
[FAKE](http://fsharp.github.io/FAKE/) workflow if very good for packaging. I use it even for small projects with local packages (on disk, not nuget.org). Requires several clicks to release a new version with updated release notes. Stable/pre is just a matter a version numbering in the RELEASE_NOTES.md file.

**Comment by drewnoakes** [comment]
Happy to help with this. I agree that a process is needed. Well put some
thought into it.

One idea is just to release after every merged PR as an alpha package (or
whatever NuGet calls unstable) with occasional stable releases. This
reduces the bed of people to take dependencies on source releases to get
the latest stuff.

**Comment by somdoron** [comment]
I like the idea of alpha releases, we can do this automatically with teamcity. Regarding the stable releases, how do we manage them? until now I did it without a process, just cherry-pick critical bugs and release a stable and alpha for master, when master become stable I released it as stable. However this is too complicated.

Suggested process:

1. Release an RC from time to time and branch (to different repository, we can use NetMQ organization) (http://hintjens.com/blog:24)
2. Cherry-pick critical fixes to RC
3. Release a new RC on every picked fix
4. Promote RC to Stable and branch
5. Go back to 1

**Comment by somdoron** [comment]
@drewnoakes do you have a nuget user?

**Comment by drewnoakes** [comment]
Yep: `drewnoakes`

**Comment by somdoron** [comment]
added you as owner

**Comment by drewnoakes** [comment]
I'd like to get an alpha release out now. Is there a nuspec file for the project we can base this off? Can we get it added to the repo?

**Comment by drewnoakes** [comment]
...actually I think I saw one once before. Will investigate further and respond shortly.

**Comment by drewnoakes** [comment]
I am going to push up what NuGet calls a [prerelease version](https://docs.nuget.org/create/versioning#prerelease-versions) shortly. The last prerelease version was `3.3.0.12-rc1`. Should I make `3.3.0.12-rc2` given that there was never a `3.3.0.12`? Quite a bit has changed so it may make sense to bump the version number.

**Comment by somdoron** [comment]
We can make it version 3.3.0.13-alpha?

**Comment by drewnoakes** [comment]
Ok cool. Should we also suffix with the build number, in preparation for having the build automatically deploy successful builds? The last build was 581, so I make that `3.3.0.13-alpha581`.

**Comment by drewnoakes** [comment]
Should we use `Debug` or `Release` builds?

**Comment by drewnoakes** [comment]
Never mind -- the nuspec file suggests we use Release.

**Comment by drewnoakes** [comment]
5349866cd7cab4c47b734267c2c3d3eec4107f0f (master as of today) is now available on NuGet as [3.3.0.13-alpha581](https://www.nuget.org/packages/NetMQ/3.3.0.13-alpha581).

Are we still thinking it'd be good to push these alpha builds automatically from Team City?

I made a few changes to the nuspec file (in 0e9eb826d94f7ee556b49cb89a921e7f02935e94) to support this. From the command line we should use something like:

    nuspec pack NetMQ.nuspec -Version 3.3.0.13-alpha581

**Comment by somdoron** [comment]
When do you think we should promote it to version 3.3.0.13? I think the
current master is stable.

**Comment by drewnoakes** [comment]
It also seems stable to me. Your send API changes would be nice to include,
though I guess they'd require waiting a while to stabilise.

**Comment by somdoron** [comment]
I think we can release a stable version, what do you think?

**Comment by drewnoakes** [comment]
Seems like a good time to me. Things appear to have been stable for a while.

What does this involve, other than pushing to NuGet?

- working out what actually changed for release notes (maybe a blog post
too)
- updating readthedocs to show non-obsolete APIs

Anything else?

**Comment by somdoron** [comment]
So lets give it few weeks

**Comment by drewnoakes** [comment]
A new prerelease build is up on NuGet: [3.3.0.13-alpha622](https://www.nuget.org/packages/NetMQ/3.3.0.13-alpha622)

**Comment by kdawg14** [comment]
Thanks so much for all your hard work; it's greatly appreciated. 

Do you guys have an estimate on when the final 3.3.0.13 package will be released?

**Comment by somdoron** [comment]
I think we are ready, @drewnoakes what do you think?

**Comment by drewnoakes** [comment]
Agree that we're ready. Is it enough to just label source control and push a build to NuGet? If so, I can do this.

**Comment by kdawg14** [comment]
Hopefully things are still moving towards a release soon.  I'm looking forward to it :) Thanks again.

**Comment by somdoron** [comment]
@drewnoakes pushing and some release notes, let me know if you have time, if not I will do it

**Comment by drewnoakes** [comment]
My first child was born a few days ago. Can't say when I'll have much free
time. However if all that's required is to build a binary and push it to
NuGet with appropriate release notes in the NuSpec, then I can find time
for that I'm sure. Beyond that we should ensure all documentation reflects
the new API.

**Comment by somdoron** [comment]
Drew congrats :-)

I have some time today so I will try to release new version.

I did one pass on the docs, I will do another one today.

**Comment by somdoron** [comment]
@drewnoakes I can see that the current assembly version for the master is 3.3.1.15040, should the stable release be 3.3.2.0?

**Comment by drewnoakes** [comment]
Thanks, it's an amazing time.

If you think 3.3.2 is good then that's fine.

Folks following this issue, @somdoron has put together PR #377 which gets us to the cusp of releasing the latest code from master to NuGet.

**Comment by somdoron** [comment]
released.

https://www.nuget.org/packages/NetMQ/3.3.2

will update the mailing list soon.

**Comment by iiwaasnet** [comment]
Great, was waiting for it!
To my understanding, the DEALER-ROUTER (re)connect issue for InProc is solved, right?

**Comment by somdoron** [comment]
If it was in the master so yes

**Comment by kdawg14** [comment]
Thanks!
