### ISSUE TITLE
RecieveReady Seems to Time Out

### ISSUE THREAD

**Issue by Camuvingian** [zeromq/netmq#353]
I am using the PUB-SUB pattern. I have a C# application that sends messages off to a C++ (engine) to do calculations. I send off all of my messages followed by a token that tells the engine that we are done - the engine then send the token back indicating to my C# app that we are finished. This works well in most cases, but I have found that if I send a large number of messages off followed by the token, I never recive the token back in the C# app via `subSocket.ReceiveReady += (s, a) => { ... }`. It is as if the `RecieveReady` times out.

I can confirm that the finalizing token is being sent by the C# app, is being recived, processed and sent back by the C++ code, but the `RecieveReady` does not pick up the token!? Any ideas as to what I can do to ensure the `ReciveReady` delegate does not "wonder off"?

My code for polling:

    private void StartPolling()
    {
        Task.Run(() =>
            {
                using (var subSocket = context.CreateSubscriberSocket())
                {
                    byte[] buffer = null;
                    subSocket.Options.ReceiveHighWatermark = 1000;
                    subSocket.Connect(SubscriberAddress);
                    subSocket.Subscribe(String.Empty);
                    subSocket.ReceiveReady += (s, a) =>
                    {
                        buffer = subSocket.Receive();
                        var handler = MessageRecieved;
                        if (handler != null)
                        {
                            handler(this, new MessageReceivedEventArgs<Taurus.FeedMux>(
                                buffer.ToObject<Taurus.FeedMux>()));
                        }
                    };

                    // Poll.
                    poller = new Poller();
                    poller.AddSocket(subSocket);
                    poller.PollTillCancelled();
                    token.ThrowIfCancellationRequested();
                }
            }, token).ContinueWith(ant => 
                {
                    pollerCancelled.Set();
                }, TaskContinuationOptions.OnlyOnCanceled);
    }

Any ideas?

**Comment by somdoron** [comment]
Can it be that the application is started after the token is already sent?
Or timing issue of when exactly did it started?

**Comment by Camuvingian** [comment]
I have found that this was because I was not setting the `HighWaterMark` high enough. I have changed this from 1000 -> 10,000 and this works fine.

**Comment by somdoron** [comment]
The message from C++ is multi-part or single part? maybe the more flag was
sent wrong and the message was not really sent on the wire?
