### ISSUE TITLE
NetMQ Dealer connect/send prior to Router bind/receive broken for tcp transport

### ISSUE THREAD

**Issue by chefhoobajoob** [zeromq/netmq#357]
This problem is not limited to the inproc transport with NetMQ.

I am finding that when using NetMQ, and only NetMQ (I'm using version 3.3.0.11), I must bind server-side router sockets prior to issuing client-side connect/send over dealer sockets when the dealer socket is a NetMQ socket.

Neither the C/C++ zmq libraries nor jeromq exhibit this behavior. If NetMQ is used for the server-side router socket, systems work as expected, regardless of the library used on the client-side. If NetMQ is in the client role with the dealer socket, messages from that client are never delivered (regardless of the library on server side).

Is this a known issue?

**Comment by somdoron** [comment]
No, can you provide code to reproduce the issue?

**Comment by jameswm** [comment]
Sure - give me some time to simplify and remove dependencies from our current nunit tests, and I'll update.

**Comment by jameswm** [comment]
Here is a receiver program:

	using System;
	using NetMQ;

	namespace receiver
	{
		class Program
		{
			static void Main( string[] args )
			{
				using ( var context = NetMQContext.Create() )
				using ( var receiver = context.CreateRouterSocket() )
				{
					receiver.Bind( "tcp://*:9045" );

					var message = receiver.ReceiveMessage();
					Console.WriteLine( "Received request" );
					var itr = message.GetEnumerator();
					Console.WriteLine( String.Format( "{0} identity frame", itr.MoveNext() ? "found" : "didn't find" ) );
					Console.WriteLine( String.Format( "{0} greeting frame", itr.MoveNext() ? "found" : "didn't find" ) );
					Console.WriteLine( String.Format( "Greeting is: {0}", itr.Current.ConvertToString() ) );

					var response = new NetMQMessage();
					response.Append( message.First );
					response.Append( "goodbye" );
					receiver.SendMessage( response );
					Console.WriteLine( "Sent response." );
					Console.WriteLine( "Hit any key to exit." );
					Console.ReadLine();
				}
			}
		}
	}


...and here is a sender:

	using System;
	using NetMQ;

	namespace sender
	{
		class Program
		{
			static void Main( string[] args )
			{
				using ( var context = NetMQContext.Create() )
				using ( var sender = context.CreateDealerSocket() )
				{
					sender.Connect( "tcp://127.0.0.1:9045" );

					var message = new NetMQMessage();
					message.Append( "hello" );
					sender.SendMessage( message );
					Console.WriteLine( "Sent request" );

					var response = sender.ReceiveMessage();
					Console.WriteLine( "Received response" );
					var itr = response.GetEnumerator();
					Console.WriteLine( String.Format( "{0} greeting frame", itr.MoveNext() ? "found" : "didn't find" ) );
					Console.WriteLine( String.Format( "Greeting is: {0}", itr.Current.ConvertToString() ) );
					Console.WriteLine( "Hit any key to exit." );
					Console.ReadLine();
				}
			}
		}
	}

**Comment by jameswm** [comment]
When I run the receiver, then run the sender, both programs run to completion.

When I run the sender, then run the receiver, neither program completes.

For comparison, if you like, I can post the equivalent programs in jeromq.

**Comment by jameswm** [comment]
Any update on this? Are you able to reproduce the behavior?

**Comment by somdoron** [comment]
I tested it with version
http://www.nuget.org/packages/NetMQ/3.3.0.13-alpha594 and it working...

Can you upgrade?

**Comment by jameswm** [comment]
I think so, but am out for the next few weeks - will update upon return.

**Comment by fostebr** [comment]
I've tried this with 3.3.0.13-alpha594.  As described by jameswm, it works.  However, try this simple modification.  All it does is try to send a message and exit.

```C#
static void Main(string[] args)
{
    using (var context = NetMQContext.Create())
    using (var sender = context.CreateDealerSocket())
    {
        sender.Options.SendTimeout = TimeSpan.FromSeconds(2);
        sender.Connect("tcp://127.0.0.1:9045");

        var message = new NetMQMessage();
        message.Append("hello");
        sender.SendMessage(message);
        Console.WriteLine("Sent request");
    }

    Console.WriteLine("Exiting");
}
```
Without any server, this code will never exit.  It gets hung up on disposing the context.  Looks like what is happening is the context is trying to clean up the dealer socket, but can't because that message hasn't been sent.  So I tried adding a send timeout, but still experienced the same issue.  By starting the server at any point, the message still gets sent (way past send timeout), the socket can be disposed, and the program exits.  Many programs, including my real one, have been freezing because of this (whenever we don't have the router server running).

**Comment by mas-dude** [comment]
Is there a solution to this problem? I am experiencing this issue with the latest version (3.3.2.1).
I have also tried the following which seems to replace the Options.SendTimeout.
```
sender.TrySendMultipartMessage(TimeSpan.FromSeconds(2), message);
```

**Comment by somdoron** [comment]
That is fine, set the linger option of the socket to zero.

**Comment by mas-dude** [comment]
Thanks for that. Much appreciated.
