### ISSUE TITLE
SocketOptions.ReceivevBuffer misspelled.

### ISSUE THREAD

**Issue by mmaguigan-dti** [zeromq/netmq#358]
I believe ```SocketOptions.ReceivevBuffer``` was accidentally misspelled.

**Comment by drewnoakes** [comment]
I'm pretty sure this is fixed in master.

**Comment by mmaguigan-dti** [comment]
Ah, right you are, my apologies -- I based my issue off of the NuGet package.

This issue was fixed in 061bd89dea2b3693b44a41f5a13519ab51dcf839. Closing this ticket.
