### ISSUE TITLE
Router&Dealer connect twice failed when set Options.Identity

### ISSUE THREAD

**Issue by RazgrizHsu** [zeromq/netmq#361]
i create two Testing method,
different only on settings of Options.Identity
but second testing never success ( blocking on receive )

This testing success..

		public void TestReconnect_RouterAndDealer()
		{
			using ( var context = NetMQContext.Create() )
			using ( var server = context.CreateRouterSocket() )
			{
				var addres = "tcp://127.0.0.1:17878";

				// just making sure can bind on both addresses
				using ( var client1 = context.CreateRequestSocket() )
				using ( var client2 = context.CreateRequestSocket() )
				{
					server.Bind( addres );

					client1.Connect( addres );
					client2.Connect( addres );

					Thread.Sleep( 100 );

					// we should be connected to both server
					client1.Send( "1" );
					client2.Send( "2" );

					// the server receive from both
					server.SkipFrame();
					server.SkipFrame();
					Debug.WriteLine( "receive:" + server.ReceiveFrameString() );
					server.SkipFrame();
					server.SkipFrame();
					Debug.WriteLine( "receive:" + server.ReceiveFrameString() );
				}

				// unbind second address
				Thread.Sleep( 100 );

				using ( var client1 = context.CreateRequestSocket() )
				using ( var client2 = context.CreateRequestSocket() )
				{
					client1.Options.DelayAttachOnConnect = true;
					client1.Connect( addres );

					client2.Options.SendTimeout = TimeSpan.FromSeconds( 2 );
					client2.Options.DelayAttachOnConnect = true;

					client2.Connect( addres );

					client1.Send( "3" );
				}

				server.SkipFrame();
				server.SkipFrame();
				Debug.WriteLine( "receive:" + server.ReceiveFrameString() );
			}
		}

But this never success..

		public void TestReconnect_RouterAndDealerFailWhenSettingIdentity()
		{
			using ( var context = NetMQContext.Create() )
			using ( var server = context.CreateRouterSocket() )
			{
				var addres = "tcp://127.0.0.1:17878";

				// just making sure can bind on both addresses
				using ( var client1 = context.CreateRequestSocket() )
				using ( var client2 = context.CreateRequestSocket() )
				{
					server.Bind( addres );
					client1.Options.Identity = NetworkOrderBitsConverter.GetBytes( (Int64)Thread.CurrentThread.ManagedThreadId );
					client1.Connect( addres );
					client2.Options.Identity = NetworkOrderBitsConverter.GetBytes( (Int64)Thread.CurrentThread.ManagedThreadId );
					client2.Connect( addres );

					Thread.Sleep( 100 );

					// we should be connected to both server
					client1.Send( "1" );
					client2.Send( "2" );

					// the server receive from both
					server.SkipFrame();
					server.SkipFrame();
					Debug.WriteLine( "receive:" + server.ReceiveFrameString() );
					server.SkipFrame();
					server.SkipFrame();
					Debug.WriteLine( "receive:" + server.ReceiveFrameString() );
				}

				// unbind second address
				Thread.Sleep( 100 );

				using ( var client1 = context.CreateRequestSocket() )
				using ( var client2 = context.CreateRequestSocket() )
				{
					client1.Options.Identity = NetworkOrderBitsConverter.GetBytes( (Int64)Thread.CurrentThread.ManagedThreadId );
					client1.Options.DelayAttachOnConnect = true;
					client1.Connect( addres );

					client2.Options.Identity = NetworkOrderBitsConverter.GetBytes( (Int64)Thread.CurrentThread.ManagedThreadId );
					client2.Options.SendTimeout = TimeSpan.FromSeconds( 2 );
					client2.Options.DelayAttachOnConnect = true;

					client2.Connect( addres );

					client1.Send( "3" );
				}

				server.SkipFrame();
				server.SkipFrame();
				Debug.WriteLine( "receive:" + server.ReceiveFrameString() );
			}
		}

it's bug?

**Comment by somdoron** [comment]
you now that the two sockets have the same identity? the behavior for this
is unexpected. Change one of the client identities

**Comment by drewnoakes** [comment]
@RazgrizHsu, are you satisfied with @somdoron's solution? If so, let's close this issue. Thanks!
