### ISSUE TITLE
netMq and unity 5.1.1 : use of bufferPool make unity freeze

### ISSUE THREAD

**Issue by bbdb68** [zeromq/netmq#364]
when activating the bufferPool on NetMQ within unity 5.1, unity freezes during execution,

it worked fine in 5.0.2 (and allowed execution without memory allocation)

**Comment by bbdb68** [comment]
note : I am using net mq from asset store

**Comment by somdoron** [comment]
Can you provide more details about where its get stuck? Netmq is using wcf
buffer pool, you might want to provide your own.

**Comment by bbdb68** [comment]
the application starts, output errors about null references, but I cannot see the first one, because when I stop the application, the editor freezes and I have to kill it.

the first lines of my code are

 AsyncIO.ForceDotNet.Force(); // necessary to allow clean reconnection
  BufferPool.SetBufferManagerBufferPool( 10, 1024);
  m_context = NetMQContext.Create();
....

thanks for your quick answer.

**Comment by bbdb68** [comment]
by diabling the update step of my application, I was able to see the first error. Is it IndexOufOfRangeException, in TakeBuffer (cannot copy the stack trace since unity is freezed

**Comment by drewnoakes** [comment]
TakeBuffer is a method on WCF's BufferManager, and it takes a single int
parameter, size.

https://github.com/zeromq/netmq/blob/master/src/NetMQ/BufferPool.cs#L58

Can you find out what this value is during your crash? A longer stack trace
would be useful too -- even if you have to take a screenshot.
