### ISSUE TITLE
MultithreadedService Sample not working with inproc

### ISSUE THREAD

**Issue by ThatDud3** [zeromq/netmq#370]
https://raw.githubusercontent.com/zeromq/netmq/master/src/Samples/Multithreading/Multithreaded%20Service/MultithreadedService/Program.cs

Switching from _tcp://_ to **_inrpoc://**_ throws
**Exception on WorkerRoutine: Exception of type 'NetMQ.EndpointNotFoundException' was thrown.**

_QuickFix:_ Moving queue.Start(); before creation of WorkerRoutine threads helps and it works for both tcp:// and inporc://

it seems to me that tcp socket is created/bound even before we start the QueueDevice but pipes aren't?

**Comment by drewnoakes** [comment]
Want to put a pull request together with the fix you identified?

**Comment by ThatDud3** [comment]
I'm not sure if that is the proper way to do it.. what if queue.Start(); succeeds but thread creation fails? - queue will crash/overflow after first few thousand messages.
I think worker threads should be created before queue.Start();
alas that only works for tcp:// and fails for inproc:// and I lack the knowledge to fix it the right way (it should work the same way as tcp://)
