### ISSUE TITLE
IpcAddress calculated port is not portable.

### ISSUE THREAD

**Issue by montoyaedu** [zeromq/netmq#374]
compiling a server for a 64bit architecture and a client for a 32bit architecture, returns a different result at this line:

https://github.com/zeromq/netmq/blob/bc6cc44e53f0f377aa7fc74a55205761116a49af/src/NetMQ/Core/Transports/Ipc/IpcAddress.cs#L41

So, the calculated port is not the same and ipc protocol does not work.

**Comment by drewnoakes** [comment]
We can easily make a new hashing function for strings which performs identically across architectures.

Before doing so, might this cause (worse) breakages for existing users of the library?

**Comment by montoyaedu** [comment]
I fear that it will break any staging/production code but those staging/production applications will break anyway if one or more counterparts change hardware platform or even .NET compiler. We solved by using tcp://... protocol and using a custom hashing function as you advised for calculating port numbers. For now it is ok.

**Comment by drewnoakes** [comment]
I agree. The temptation is to fix this, but it's not clear that it won't
break existing applications.

If we reimplemented the hash function of either 32 or 64 bit BCL strrings
exactly in our code, then at least it'll break fewer clients. This could
roll out in a major release, with suitable caveat.

@somdoron, do you have a view on this?

**Comment by montoyaedu** [comment]
Another possible solution could be:

Add a configuration parameter [EnablePortableHashFunction] that by default will be set to false (at least for a few years or for a few major releases from now. We can deprecate this default immediately by stating that in future it will be true. In this way, we can use it for newer versions without breaking old applications.

**Comment by somdoron** [comment]
too late to join..

I think we should fix this and put a message on the homepage. I think ipc is rarely used with NetMQ (and not documented)
