### ISSUE TITLE
Xamarin support

### ISSUE THREAD

**Issue by fynman** [zeromq/netmq#378]
Dear,

  Is it possible to install NetMQ in a Visual Studio Xamarin Android project? I get the following error message while trying to install with Nuget:

Could not install package 'AsyncIO 0.1.17.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v5.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Thanks,
Bart

**Comment by somdoron** [comment]
Just try to compile both netmq and asyncio from master.

AsyncIO is at http://github.com/somdoron/asyncio

**Comment by somdoron** [comment]
closing this, as far as I know netmq runs on android with unity
