### ISSUE TITLE
Dependencies on JetBrains.Annotations and AsyncIO

### ISSUE THREAD

**Issue by bipinprasad** [zeromq/netmq#379]
Please remove dependecy on AsyncIO and JetBrains.Annotations in C# source code distribution (alternatively, include documentation on where to download sources for those packages).

**Comment by drewnoakes** [comment]
These dependencies are sourced via NuGet and are specified in `packages.json` which is included in the source code. It's not possible to remove these dependencies, so you will have to use NuGet to source them. Visual Studio does this automatically, and you can use `nuget.exe` on other environments/platforms to do the same manualle.

**Comment by isaacllopisaracil** [comment]
Could you explain why these dependencies cannot be removed, and what it means for us in terms of licensing?

**Comment by somdoron** [comment]
AsyncIO is completion port library NetMQ is using, the license is MPL 2.0.

Regarding JetBrains.Annotations I think it can be removed, anyway it is
only for development time to help with Resharper.

**Comment by isaacllopisaracil** [comment]
The license dpendency of the JetBrains library dependency is something that will prevent me of using NetMQ as it is not a standard lesser license but especial for JetBrains products. The less dependencies you have the best.

When will this one be removed, if it will? Otherwise I'm bound to use the default 0MQ binding.

-----Original Message-----

**Comment by somdoron** [comment]
You can actually use it right now without the JetBrains reference. Just
don't include the file when using in production.

**Comment by somdoron** [comment]
I will try to release today a version without the reference.

**Comment by somdoron** [comment]
Checkout https://www.nuget.org/packages/NetMQ/3.3.2.1

Let me know if this work for you.

**Comment by isaacllopisaracil** [comment]
Whoa, removed dependency in a couple of hours. You guys rock. Thanks Doron!

**Comment by drewnoakes** [comment]
Can this be closed now?

**Comment by somdoron** [comment]
I think we can close this.
