### ISSUE TITLE
Feature Request: allow Context disposal even if it has sockets

### ISSUE THREAD

**Issue by ashic** [zeromq/netmq#384]
Currently, if a context has created sockets, and they're doing things (or are even idle), attempts to Dispose() the context without disposing its sockets causes things to stall (see https://github.com/zeromq/netmq/issues/383 ). This is a minimal repro:

```
 class Program
    {
        static void Main(string[] args)
        {
            using (var client = new Client("tcp://127.0.0.1:7777"))
            {
                var cancel = new CancellationTokenSource();
                Task.Factory.StartNew(()=> client.Start(cancel.Token), TaskCreationOptions.LongRunning);
                Console.ReadLine();
                cancel.Cancel();
                //Process.GetCurrentProcess().Kill();
            }
        }
    }

    public class Client : IDisposable
    {
        private readonly string _endpoint;

        public Client(string endpoint)
        {
            _endpoint = endpoint;
            _ctx = NetMQContext.Create();
        }

        public void Start(CancellationToken token)
        {
            {
                _socket = _ctx.CreateRequestSocket();
                _socket.Options.Linger = TimeSpan.Zero;
                
                Thread.Sleep(1000);
                //_socket.Connect(_endpoint);

                while (!token.IsCancellationRequested)
                {
                    //_socket.SendMessage(new NetMQMessage(new[] { new NetMQFrame("This is my request") }));
                    Thread.Sleep(100);
                    //var msg = _socket.ReceiveMessage();
                    //Console.WriteLine("Received {0}", msg.First.ConvertToString());
                    Console.WriteLine("Received");
                }

            }
        }

        private bool _disposed;
        private readonly NetMQContext _ctx;
        private NetMQSocket _socket;

        public void Dispose()
        {
            if (_disposed) return;
            _disposed = true;
            _ctx.Dispose();
        }
    }
```
It would be good if there were an option to terminate the context - sockets and all - via Dispose (or some other method). As object disposal / finalizer threads can't be controlled in .NET, it'd remove a lot of ceremony around disposal.

**Comment by ashic** [comment]
It appears that the stall is caused by the following line in NetMQ.Core.Ctx:

```
   var found = m_termMailbox.TryRecv(-1, out command);
```
It's waiting for the reaper thread to come in and kill the socket, but that doesn't seem to happen.

**Comment by ashic** [comment]
Digging further, it appears that Ctx sends CommandType.Stop to the socket, but nothing on any ZObject (IOThread, Reaper, or SocketBase) has their ProcessStop() called.

**Comment by iiwaasnet** [comment]
```csharp
class Program
    {
        static void Main(string[] args)
        {
            using (var client = new Client(@"tcp://127.0.0.1:7777"))
            {
                Task.Factory.StartNew(()=> client.Start(), TaskCreationOptions.LongRunning);
                Console.ReadLine();
                cancel.Cancel();
            }
        }
    }
    public class Client : IDisposable
    {
        private readonly string _endpoint;
        private raedonly CancellationTokenSource cancel;

        public Client(string endpoint)
        {
            cancel = new CancellationTokenSource();
            _endpoint = endpoint;
            
        }

        public void Start()
        {
            using(var _ctx = NetMQContext.Create())
            {
                using(var _socket = _ctx.CreateRequestSocket())
                {
                    _socket.Options.Linger = TimeSpan.Zero;

                    Thread.Sleep(1000);
                    //_socket.Connect(_endpoint);

                    while (!token.IsCancellationRequested)
                    {
                        //_socket.SendMessage(new NetMQMessage(new[] { new NetMQFrame("This is my request") }));
                        Thread.Sleep(100);
                        //var msg = _socket.ReceiveMessage();
                        //Console.WriteLine("Received {0}", msg.First.ConvertToString());
                        Console.WriteLine("Received");
                    }
                 }
            }
        }

        private bool _disposed;
        private readonly NetMQContext _ctx;
        private NetMQSocket _socket;

        public void Dispose()
        {
            if (_disposed) return;
            cancel.Cancel();
            _disposed = true;           
        }
    }```

**Comment by ashic** [comment]
Yes...I know disposing the socket will fix it, but a context can be shared across many threads, and it might not always be possible to use a using block. 

The code in NetMQ.Core.Ctx looks like it's sending outstanding sockets Stop commands, which are not being processed. It looks like that should be taking care of this issue. However the command is sent, but not processed. We can solve it in the application using a using block, or getting more tricksy depending on usage. But solving this / having the ability to choose to dispose held sockets automatically would be helpful to users, no?

**Comment by iiwaasnet** [comment]
Dispose your sockets always in the same place and thread where you create them. Make a simple wrapper class, implementing IDisposable, around context. Register wrapper class with IoC and let it be disposed when the whole app dies, by disposing the IoC container.

**Comment by ashic** [comment]
Thanks. I'm fully aware of the current scenario and limitations. 

.NET disposal is not guaranteed to be on a specific thread. If the wrapper object is being disposed, there's no guarantee of disposal happening on the same thread. If there are many threads, this can be noticeable, specially when things like Rx are used. 

I know the current scenario and recommendations. That's why this is a feature request :)

**Comment by iiwaasnet** [comment]
But according to what I suggested, only context will be disposed in the *unknown* thread, which is completely OK. Before that, all sockets are disposed in their own threads.

**Comment by somdoron** [comment]
I think when call dispose on context everything should close, also this
suppose to be the behavior , however it has some limitation. As you
mentioned context send stop to sockets, however if the socket is not used
the socket will never get the stop command. On most zeromq bindings the
context is obsolete and only one context is used (and never shutdown),
maybe we can go that direction. Anyway I won't be able to take a look at
the coming month as I have limited access to computer. Writing from a taxi
at Guatemala :-)

**Comment by ashic** [comment]
@iiwaasnet It'll work...mostly. But I can see a scenario where it might not. Say code is in the using block (just entered for example), and Dispose gets called from another thread. That'll trigger Context.Dispose() without the thread for the socket having exited the using block. That situation would likely trigger a hang. - I could be wrong on this, but I'll try to replicate when I get a mo.

@somdoron : Glad you see it the same way. Have fun in Guatemala :)

**Comment by somdoron** [comment]
@ashic I'm interesting to hear your thoughts about removing the Context, take a look at following PR:
https://github.com/zeromq/netmq/pull/423

So now you just don't have context anymore, if you didn't dispose a socket and exit the program the program will just exit as NetMQ IO thread is background thread.
