### ISSUE TITLE
Length parameter is not used correctly in SendFrame

### ISSUE THREAD

**Issue by AlekseiOhotnik** [zeromq/netmq#385]
The usage of length parameter in new version (3.3.2.1) of NetMQ for method SendFrame causes exception when passing larger buffer than length. It seems like a typo.
Right now:
Buffer.BlockCopy(data, 0, msg.Data, 0, data.Length);
Should be:
Buffer.BlockCopy(data, 0, msg.Data, 0, length);

**Comment by somdoron** [comment]
Can you provide a pull request?

**Comment by drewnoakes** [comment]
Would be great to have a unit test in the PR too :)

**Comment by AlekseiOhotnik** [comment]
Pull request #386 created
