### ISSUE TITLE
PUB/SUB message filtering behaviour

### ISSUE THREAD

**Issue by aohotnik** [zeromq/netmq#387]
I have a following setup:

PUB that sends messages and uses a content attribute to create a topic frame followed by payload frame. SUB sockets subscribe to specific topics.
pub.Send("TopicA", sendmore = true);
pub.Send(payload, sendmore = false);
sub1.subscribe("TopicA);
sub2.subscribe("TopicB);

I would like to send a ping message to all the subscibers so PUB can detect stale connections and cleanup and SUBs to be able to act if ping is not arriving.

Issue:
Tried sending empty frame first with ping message followed in payload frame. Doesn't reach subscribers. I assume because of filtering set by subs. Should not it have reached subs as message doesn't specify filter?

My only way out of this right now is to send pings through a special topic, but this is up to the client to sub to. If clients connect and for example kill the process won't it create a stale connection for a while if PUB has no message for them on their subbed topic? Any other way to achieve what I described apart from tcp keep alives?

Edited: I had problem reading frames with incorrect alignment/order, removed other issues apart from pinging.

**Comment by eric-b** [comment]
If your client use a wrapper around sub socket, which I suppose is the case if you want to manage internally a ping, you can add the special ping topic to the subscribed topics in the wrapper... It is what I did.

**Comment by AlekseiOhotnik** [comment]
Not going to work for my issue unfortunately. Endpoint is public and client code is not locally owned. Bindings for ZeroMQ could also be for any language.

**Comment by somdoron** [comment]
The best solution IMO is what you mentioned, make the subscriber subscribe to the keep alive topic.

Regarding your question of socket being kept alive, don't worry about that, NetMQ is using IOCP so the  dead socket is not going to make a problem.

Few more options:

You can use manual subscriptions (http://somdoron.com/2014/12/token-pubsub/).
1. Client must use xsub
2. Client send a token or a message with all topics
3. Server decide on the actual topics each client gets, so just make sure to include keep alive topic
4. Client will receive everything the server decide.
