### ISSUE TITLE
persistence?

### ISSUE THREAD

**Issue by unruledboy** [zeromq/netmq#389]
is there any solution for persistence?

I am using push/pull, the message will get lost if the worker is not running.

**Comment by eric-b** [comment]
There is no persistence mechanism in zmq. It would degrade its performance.

There has been an option "SWAP" to allow to exceed the high water mark limit, but it has been deprecated. 

There is another project [PZQ](https://github.com/mkoppanen/pzq/wiki/An-Introduction-To-PZQ), type "man in the middle" (C++ sources to build), which aims to serve the same purpose. I don't know if it works well but I suppose it should be compatible with netmq.


If the publisher pushes message before the worker get launched, messages will be persisted in memory until the worker is ready to process them (with high water mark limit). If the publisher is stopped before worker can process its messages, pending messages will get lost. There is an option to delay the shutdown of sockets until all pending messages are sent but it is not very usable in my opinion (option "Linger" delay which is infinite by default).

I think if you need message persistence, "reliability" characteristics and the like, ZMQ is probably not the best solution in your use case.

**Comment by unruledboy** [comment]
You are right. I did some search, read some articles, comparisons, zeromq is really good at performance, but regarding persistence, there is no mature solution, at least not for .net that I can find.

I guess there is no perfect solution, either you can have performance, or persistence, or good support.

The bottom line is to have reliable biz data processing, no missing a single request.

I will have to do more homework, thanks a lot for the quick and detail reply.

cheers.

**Comment by eric-b** [comment]
I also think it is performance vs reliability.
When I need reliability, I use MSMQ which works really well if message length is always less than 4MB. Also, for Push/Pull pattern, it is very similar to zmq API.

**Comment by sgf** [comment]
Implement WAL log mode and use timer to write to disk in batches.
I am afraid this requires .net developers to write an extension library themselves.
