### ISSUE TITLE
SendMoreFrameEmpty cannot be chained

### ISSUE THREAD

**Issue by cstlaurent** [zeromq/netmq#390]
Hi, 

I just found out while trying to write some router socket code that the `IOutgoingSocket.SendMoreFrameEmpty` cannot be chained since it does not return the Socket like other `SendMoreFrame` methods. 

I'm creating a pull request to fix this issue.

**Comment by drewnoakes** [comment]
Is there a performance cost associated with chainable APIs? I know that `StringBuilder` has this and in general it's used in so-called builder patterns, but there is potentially a cost associated with pushing the return value. I suppose the JIT could optimise this away. This needs some investigation as the send APIs  are on the critical path for message throughput.

**Comment by cstlaurent** [comment]
Well, even if there is a minor performance hit, I don't think this is related to performance issue since the `SendMoreFrame*` was clearly designed as a chainable API, even the current comment on the method says it: 
> Send more frame, another frame must be sent after this frame. Use to chain Send methods.

There already is a `SendFrameEmpty` which is the non-chainable equivalent. Also all other `SendMoreFrame*` return the `IOutgoingSocket` so I think it is probably just a miss. Here are the other signatures:

````

`public static IOutgoingSocket SendMoreFrame([NotNull] this IOutgoingSocket socket, [NotNull] byte[] data)
`public static IOutgoingSocket SendMoreFrame([NotNull] this IOutgoingSocket socket, [NotNull] byte[] data, int length)
`public static IOutgoingSocket SendMoreFrame([NotNull] this IOutgoingSocket socket, [NotNull] string message)
````

One of the main use case for this chainable method would be to create a response from a Router socket. This will use the `SendMoreFrameEmpty` in the middle of the chain:

**What you have to do now**
````
args.Socket.SendMoreFrame(identity).SendMoreFrameEmpty();
args.Socket.SendFrame(message);
````

**What will be possible after my change**
````
args.Socket.SendMoreFrame(identity).SendMoreFrameEmpty().SendFrame(message);
````

**Comment by somdoron** [comment]
I agree

**Comment by drewnoakes** [comment]
Thanks for the detailed clarification. I didn't twig that the current (and relatively new) send methods were chainable anyway.

**Comment by somdoron** [comment]
The old ones was chainable too :-)
