### ISSUE TITLE
Binary Star Reactor

### ISSUE THREAD

**Issue by dshulepov** [zeromq/netmq#392]
Is there an implementation or a plan to implement a Binary Start Reactor for .NET ?
I'm reffering to http://zguide.zeromq.org/page:all#Binary-Star-Reactor

**Comment by somdoron** [comment]
No, but it will be great if you can port it and send a pull request.

**Comment by dshulepov** [comment]
Ok. I've looked at Java port (https://github.com/zeromq/jeromq), thinking I could find the latest implementation of binary star reactor there, but couldn't find it. Seems like it's only mentioned in the examples. 
If you do know that it's implemented somewhere in the Java port please point me.
Else I would start with porting this http://zguide.zeromq.org/java:bstar first into my solution and later will gladly contribute if you guide me where to put the file, how to name etc.

**Comment by somdoron** [comment]
I guess it is only in the example.

**Comment by dshulepov** [comment]
I finally got time to put together this BinaryStart. I've started first to port it as is, but then I though that it fits nicely into the concept of Device and this is how we plan to use it in the project.
I have a draft version of BinaryStartDevice in my fork and I'd like to get your oppinion on that before I continue polishing it and covering with tests (which would be a hell).
So, currently my main question is how to how it to you and get your opinion ? It's a bit early for a pull request, but I don't want to rework everything when it's done if I took a wrong turn.

I also have couple of concerns about the implementation:
1) Using a Request socket (which might seem an obvious choice if you don't realise how the thing works) is not an option, because one of the devices, the one in the passive state, should drop the client messages. But the Request socket has a state machine inside, which does not allow dropping the message, it request a response to be sent. For now I decided to throw in the AddVoter, but may be I just should always use the router with not ability to change it, just fire an event on client message (when not droped). What do you think?

2) Firing an even on receiving a message on voter socket and allowing the user code to handle it seems like a good idea. And this is what is allowed now. But if you think cearfully, it could become a problem if one will use some heavy message processing (like going to db). We run the even handlers in the same thread which runs the poller with sockets and timer. So a long working client even handler code might easily prevent the device of sending it's state and the other device will decide to do a failover and become active. I don't see a proper way to gard against it for now.

**Comment by somdoron** [comment]
Following are my thoughts:

1. Use dealer-router or dealer-dealer, avoid using request-response sockets.
2. Try to make a pull request on the API only (stub classes), we can
discuss it on the PR, once we are happy with the API continue to do the
rework and everything. Make a small example (or test)  on how to use the
API.
