### ISSUE TITLE
Question about multiple messages from router to dealer

### ISSUE THREAD

**Issue by buybackoff** [zeromq/netmq#399]
The docs say and the code shows clearly that a `NetMQMessage` is transmitted entirely, so that the first and the last frame are available on a client simultaneously. I need to send multiple messages from router in reply to a dealer message so that each message is actually pushed to the wire. The simplest test works (below), but I cannot find docs saying that this is supported behavior. However, the Guide says that:

>The REQ-REP socket pair is in lockstep. The client issues zmq_send() and then zmq_recv(), in a loop (or once if that's all it needs). Doing any other sequence (e.g., sending two messages in a row) will result in a return code of -1 from the send or recv call.

and I used to assume the same is true for ROUTER-DEALER.

Is this an implementation detail that the test works, or it is a part of the pattern contract/definition? I have looked through the implementation of XSend method in the router and there is nothing that could forbid multiple messages and there is no `FiniteStateMachineException` like in Req/Rep. Will that work with ZeroMQ on another side of the wire, or it is specific to NetMQ?

This test prints out the server message twice:

```
        [Test]
        public void TwoMessagesFromRouterToDealer() {
            using (var context = NetMQContext.Create())
            using (var poller = new Poller())
            using (var server = context.CreateRouterSocket())
            using (var client = context.CreateDealerSocket()) {
                var port = server.BindRandomPort("tcp://*");
                client.Connect("tcp://127.0.0.1:" + port);
                poller.AddSocket(client);
                client.ReceiveReady += Client_ReceiveReady;
                byte[] clientId = Encoding.Unicode.GetBytes("ClientId");
                client.Options.Identity = clientId;

                const string request = "Client request";

                const string response = "Server response";

                client.SendFrame(request);

                byte[] serverId = server.ReceiveFrameBytes();
                Assert.AreEqual(request, server.ReceiveFrameString());

                // two messages in a row, not frames
                server.SendMoreFrame(serverId).SendFrame(response);
                server.SendMoreFrame(serverId).SendFrame(response);

                poller.PollTillCancelled();
            }
        }

        private void Client_ReceiveReady(object sender, NetMQSocketEventArgs e)
        {
            var strs = e.Socket.ReceiveMultipartStrings();
            foreach (var str in strs)
            {
                Console.WriteLine(str);
            }
        }
```
Thanks!

**Comment by somdoron** [comment]
With DEALER and ROUTER you are not limited as in REQ_REP.

So if I understand correctly, just send multiple messages to same serverId.
