### ISSUE TITLE
Topic bytes cannot start with 0 or 1

### ISSUE THREAD

**Issue by buybackoff** [zeromq/netmq#403]
Re: the discussion in #401 
Topic cannot start with 0 or 1. E.g. if I use a Guid 16 bytes as a topic, there is a 1/128 chance that it won't work correctly. I cannot come up with a simple solution. One idea is to require that subscribe/unsubscribe message contain a single frame, and a normal message always contains more than one frame. And then to check `.HasMore` property. But this conflicts with the ZeroMQ behavior.
With offsets I could always prefix a topic by any value other than 0-2, without additional copy. Should I go this way and do not try to make any further changes in XPub?

**Comment by somdoron** [comment]
I'm not sure what the problem is...

1. ZeroMQ subscription is always one frame. So that doesn't violate zeromq.
2. You can start a subscrption or a topic with 0/1 this will work as it will be prefixed.
3. The only issue is when you want to send a multi-part message from XSub to XPub, just prefix each frame with 2, that will solve it.

**Comment by buybackoff** [comment]
When I subscribe to a topic 0xxx or 1xxx, it will be prefixed and become 10xxx or 11xxx. But then when I send a message via `publisher.Send()`, the first frame is a topic, it will be 0xxx/1xxx and interpreted as a unsubscribe/subscribe command. Broadcast will work, but normal pub/sub could break here, couldn't it?

**Comment by somdoron** [comment]
no, XPub to XSub doesn't need to be prefixed, the XSub doesn't check that, just regular messages.
Only from XSub to XPub message need to be prefixed.

**Comment by buybackoff** [comment]
So when XSub sends a subscription, it will be prefixed and look like 10xxx or 11xxx, but then what will happen if XSub sends a message with a topic 0xxx or 1xxx. Such messages will look like (un)subscribe to the XPub socket.

**Comment by somdoron** [comment]
I'm not following...

User have to prefix any message from XSub to XPub.
If XSub sends a message with a topic 0xxx user will prefix it with 2 so it will be 20xxx

**Comment by buybackoff** [comment]
I am not talking about broadcast anymore, just normal pub/sub. Please look at [this line](https://github.com/zeromq/netmq/blob/master/src/NetMQ.Tests/XPubSubTests.cs#L472) - what will happen if we have `sub1.SendFrame(new byte[] { 0 }, true);` instead of `sub1.SendFrame(new byte[] { (byte)'A' }, true);`?

With Guids, it could be `sub1.SendFrame(myGuid.ToByteArray(), true);` and a guid could have 0/1 as its first byte.

**Comment by somdoron** [comment]
That violate XSub, any XSub messages must be prefixed, even Guides. If you don't prefix unexpected behavior will happen.

**Comment by somdoron** [comment]
So in your case just prefix it with 2 or 3 (if you enabled broadcast and don't want it to be broadcast)

**Comment by somdoron** [comment]
Also take a look at following commits and issue from zeromq, it can happen in NetMQ as well both for the Manual solution and your new Broadcast:

https://github.com/zeromq/libzmq/issues/1568
https://github.com/zeromq/libzmq/commit/8fd71d631d740a558b56456e08b55574c19ef761
https://github.com/zeromq/libzmq/commit/64ffda90d2e3ccc66d0bb9fa2d83d85be21813a2

**Comment by buybackoff** [comment]
Subscriptions are quite rare, but for broadcast that could be a real issue. However, as we discussed the issue about setting `m_lastPipeIsBroadcast = false` and `m_lastPipe = null`, if `pulisher.Receive()` and `publisher.Send()` happen in the same place inside `ReceiveReady` event, it should not be possible that another pipe could jump in between.

**Comment by somdoron** [comment]
it can if you received a lot of broadcast messages in same time.
XReadActivated will be called multiple times always changing the m_lastPipe before any Receive operation being called. This is way m_lastPipe must be set a at the XReceive and not at XReadActivated.

**Comment by buybackoff** [comment]
Thanks for the explanation! As the main use case for broadcast is high frequency IPC/LAN exchange between multiple XSubs, I now understand that the current version is probably broken. How could we fix this? Same way as in libzmq with a queue of pipes?

**Comment by somdoron** [comment]
Yes

**Comment by buybackoff** [comment]
There is a bug if broadcast is used together with manual publisher. When the second frame starts with 0 or 1, [this if](https://github.com/zeromq/netmq/blob/master/src/NetMQ/Core/Patterns/XPub.cs#L172) is true. Will add a variable `thisPipeIsBroadcast` that is set to true if [that if condition](https://github.com/zeromq/netmq/blob/master/src/NetMQ/Core/Patterns/XPub.cs#L172) was true.

In general, I think that broadcast is not stable yet. I am trying to build a message bus using it, and some subtle issues like this arise. Will post the entire example later this week when everything will work.
