### ISSUE TITLE
Poller PollTillCancelledNonBlocking/Dispose not thread-safe

### ISSUE THREAD

**Issue by eric-b** [zeromq/netmq#409]
In few scenarios, I have an ObjectDisposedException throwned by the poller thread at line 465 `isStoppedEvent.Reset()`.

I think there is a thread-safety issue in the PollWhile method, at leat before reaching the `while (condition())` (line 483). The exception is really difficult to reproduce because it depends on timing and probably the computer used. Unfortunately, it appears consistently on the same machine in the same scenario.

Consider the following steps (all in the same thread):

- create a socket.
- create a poller with the socket in its constructor.
- invoke `poller.PollTillCancelledNonBlocking()`.
- very shortly after: release the poller (via `poller.Dispose()`).
- release the socket.

`Poller.Dispose` succeed but there is an exception in the poller thread `PollWhile` method. My program observe `AppDomain.CurrentDomain.UnhandledException` and I see this exception :

	System.ObjectDisposedException: Safe handle has been closed
	at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
	at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
	at Microsoft.Win32.Win32Native.ResetEvent(SafeWaitHandle handle)
	at System.Threading.EventWaitHandle.Reset()
	at NetMQ.Poller.PollWhile(Func`1 condition)
	at NetMQ.Poller.PollTillCancelled()
	at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	at System.Threading.ThreadHelper.ThreadStart()

The problem is `Dispose` already released `m_isStoppedEvent` when `PollWhile` tries to reset the signal.

**Comment by eric-b** [comment]
There is also another issue possible:

	ObjectDisposedException: Cannot access a disposed object.
	Object name: 'Poller is disposed'.
	   at NetMQ.Poller.PollWhile(Func`1 condition)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.ThreadHelper.ThreadStart()

It's the same scenario: `Dispose` invoked after `PollTillCancelledNonBlocking` but before `PollWhile`.


Here is test repro:

    [TestFixture]
    public sealed class CorePollerTests
    {
        private Exception _bgThreadEx;

        [Test]
        public void CreateStartAndDisposeFast()
        {
            _bgThreadEx = null;
            Action test = () =>
            {
                AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;
                try
                {
                    using (var ctx = NetMQContext.Create())
                        using (var socket = ctx.CreatePullSocket())
                        {
                            socket.Bind("ipc://test");
                            using (var poller = new Poller(socket))
                            {
                                poller.PollTillCancelledNonBlocking();
                            }
                        }
                }
                finally
                {
                    AppDomain.CurrentDomain.UnhandledException -= CurrentDomain_UnhandledException;
                }
            };

            test.BeginInvoke(test.EndInvoke, null).AsyncWaitHandle.WaitOne();
            Assert.That(_bgThreadEx, Is.Null, "Unhandled Exception: {0}", _bgThreadEx); 
        }

        private void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            _bgThreadEx = (Exception)e.ExceptionObject;
        }
    }

**Comment by somdoron** [comment]
Can you give this fix a test:

https://github.com/somdoron/netmq/tree/PollerStartIssue

**Comment by eric-b** [comment]
Thank you very much for this fast fix.

The aforementioned test succeeds and I will test this version on my real use case monday at work. After reviewing your code, I'm pretty confident. 

Also I'm grateful to discover your elegant solution. A question I ask myself while reading Switch.cs: 
Should we not use `Interlocked.CompareExchange(ref m_status, 2, 2)` to read the status ?
If .NET 4.5 was used, `Volatile.Read(ref m_status)` would be more explicit for the same result.

**Comment by somdoron** [comment]
You actually don't need Interlocked to read a 32bit variable, however now
you mention it we can just use volatile, as no one is competing on the
variable, we just want to make sure when changing the value other threads
will get it, so volatile will do it. I will change it.

**Comment by c-rack** [comment]
Closed by #410

**Comment by eric-b** [comment]
Thanks for your feedback. 
FYI, the fix works well in my real case, as expected.

Thank you again.

**Comment by yhan** [comment]
is this fix included in the latest available nuget package? i.e. NetMQ 3.3.2.4-beta ?

**Comment by somdoron** [comment]
Not yet... Will release new beta this week.

**Comment by yhan** [comment]
thank you @somdoron
