### ISSUE TITLE
Application hangs when trying to clear down - am I missing something?

### ISSUE THREAD

**Issue by gitn00b1337** [zeromq/netmq#411]
Hi, my code never ends on cleanup and leaves the app hanging. I have made a sample application for an easy copy & paste to a console app. Am I missing something? Many thanks. Please note, I had a different issue which seems to have been solved recently, so instead of using the latest nuget version I am using the most recent github code (grabbed today)

    class Program
    {
        static volatile bool cancel;

        static void Main(string[] args)
        {
            using (var context = NetMQContext.Create())
            {
                var r1 = context.CreateRouterSocket();
                var r2 = context.CreateRouterSocket();
                r1.Options.Identity = Encoding.Unicode.GetBytes("s1");
                r2.Options.Identity = Encoding.Unicode.GetBytes("s2");
                r1.Bind("tcp://127.0.0.1:5555");
                r2.Connect("tcp://127.0.0.1:5555");

                r1.ReceiveReady += (s, e) =>
                {
                };
                r2.ReceiveReady += (s, e) =>
                {
                    var msg = new List<byte[]>();
                    e.Socket.TryReceiveMultipartBytes(ref msg);
                    var lastItem = Encoding.Unicode.GetString(msg[msg.Count - 1]);
                    //Assert.AreEqual(lastItem, "hello");
                };

                var timer = new NetMQTimer(TimeSpan.FromMilliseconds(500));
                timer.Elapsed += (sender, evArgs) =>
                {
                    evArgs.Timer.Enable = !cancel;

                    if (!cancel)
                    {
                        var msg = new List<byte[]>();
                        msg.Add(Encoding.Unicode.GetBytes("s2"));
                        msg.Add(new byte[0]);
                        msg.Add(Encoding.Unicode.GetBytes("hello"));
                    }
                };

                var poller = new Poller();
                poller.AddSocket(r1);
                poller.AddSocket(r2);
                poller.AddTimer(timer);

                poller.PollTillCancelledNonBlocking();

                var startTime = DateTime.Now;

                while (!cancel)
                {
                    // timeout
                    if (DateTime.Now > startTime.AddMinutes(1))
                    {
                        cancel = true;
                        poller.RemoveTimer(timer);

                        if (poller.ContainsSocket(r1))
                            poller.RemoveSocket(r1);

                        if (poller.ContainsSocket(r2))
                            poller.RemoveSocket(r2);

                        if (poller.IsStarted)
                            poller.CancelAndJoin();

                        poller.Dispose();
                    }
                }
            }
        }
    }

**Comment by somdoron** [comment]
You also have to dispose the sockets. Also note, poller is not thread safe, so adding ad removing after calling PollTillCancelledNonBlocking is unsafe

**Comment by gitn00b1337** [comment]
Thanks for getting back to me - that has fixed this issue. Just out of curiosity - if all send methods from sockets are within a poll timer, like above, then there will not be any socket threading issues?

**Comment by somdoron** [comment]
Right.

Also take a look at NetMQQueue. The enqueueing side is thread safe and you
can attach it to poller and dequeue. You can use that safely send from any
thread.

**Comment by gitn00b1337** [comment]
Yeah I already have. Baby steps :) thank you for your time

**Comment by gitn00b1337** [comment]
Just been using NetMQ - I like it but I thought I'd mention currently there's no way to access the underlying queue methods... so for my stuff I've added to it for .Count. I think it would be a lot more useful if the underlying queue methods were available, such as contains, count, etc.

**Comment by somdoron** [comment]
Can you make a pull request?

**Comment by gitn00b1337** [comment]
Done finally. I am new to github so took a bit of googling to get it up. Let me know if ive done something wrong and I'll change

**Comment by somdoron** [comment]
I see you committed the changes to your repository. Now you need to make a pull request to the zeromq/netmq repository. Click the pull requests on this page and create new one from your repository

**Comment by gitn00b1337** [comment]
Done
