### ISSUE TITLE
ResponseSocket leaking memory

### ISSUE THREAD

**Issue by TiagoOliveiraMarques** [zeromq/netmq#416]
Hi,

I was using netmq to implement basic RPC functionality with Request/Response Socket pairs.
What I found was that ResponseSocket was leaking memory per request.

The code use to benchmark is similar as the one in [here](http://netmq.readthedocs.org/en/latest/request-response/), but sending 1000 requests sequentially.

Memory Analysis:
![capture](https://cloud.githubusercontent.com/assets/9203181/12017174/76144ba4-ad4b-11e5-84ee-d484b66b5b92.PNG)

As you can see, even after garbage collection, 1000 byte arrays are held in memory.

**Comment by somdoron** [comment]
Which version are you using?

**Comment by TiagoOliveiraMarques** [comment]
Version 3.3.2.2

**Comment by TiagoOliveiraMarques** [comment]
Complete source code which shows the issue (based on the HelloWorld example in the source).

```csharp
using System;
using NetMQ;

namespace HelloWorld
{
    internal static class Program
    {
        private static void Main()
        {
            Console.Title = "NetMQ HelloWorld";

            using (var context = NetMQContext.Create())
            using (var server = context.CreateResponseSocket())
            {
                server.Bind("tcp://localhost:5556");
                

                while (true)
                {
                    for (int i = 0; i < 1000; i++)
                    {
                        using (var client = context.CreateRequestSocket())
                        {
                            client.Connect("tcp://localhost:5556");

                            client.Send("Hello");

                            Console.WriteLine("From Client: {0}", server.ReceiveFrameString());

                            server.Send("Hi Back");

                            Console.WriteLine("From Server: {0}", client.ReceiveFrameString());
                            
                        }
                        
                    }
                    

                    Console.WriteLine();
                    Console.Write("Press any key to continue...");
                    Console.ReadKey();
                }
                
            }
        }
    }
}
```

The issue only happens if I create a new RequestSocket per request.

**Comment by somdoron** [comment]
Can you tell which object is holding the reference to the byte array?

**Comment by TiagoOliveiraMarques** [comment]
Using dotmemory profiler showed all arrays are held by a pinning handle. 
Maybe some native call?

**Comment by somdoron** [comment]
That helps, I will try to find it.

**Comment by somdoron** [comment]
It might be to the fact that it is takes time to dispose a socket (calling
dispose just sending a request to dispose).

Can you try and dispose the context as well before doing the memory check?
When context is disposed you guaranteed all resources are disposed.

I think it is only an issue of delayed cleaning.

On another subject, creating a socket on request is expensive and not
recommended. It is better to create a dealer and send multiple requests.

**Comment by TiagoOliveiraMarques** [comment]
But shouldn't the context be alive while the server is running?

**Comment by somdoron** [comment]
Yes, I just want to check if its time issue, you can also sleep for few
seconds.

**Comment by TiagoOliveiraMarques** [comment]
So the updates:
- I have split the application into two separate processes, one for client, one for server for better debugging.

- As far as I know, the client is not leaking. The server leaks in the same way as before.

- Trying to dispose the context before disposing the server will make the thread block in Ctx.Terminate, waiting for the sockets to close.

**Comment by somdoron** [comment]
So there was a bug in AsyncIO version 0.1.17.0, try to upgrade to 0.1.18.0.

Should solve this.

**Comment by TiagoOliveiraMarques** [comment]
Problem solved with the update. 
Thank you.
