### ISSUE TITLE
Example from the readme not working with Mono 4.x (Linux)

### ISSUE THREAD

**Issue by timothyparez** [zeromq/netmq#418]
The example code from the readme, modified to write the comments to the screen

```
using System;
using NetMQ;

namespace TestApp
{
	class MainClass
	{
		public static void Main (string[] args)
		{
			using (var context = NetMQContext.Create())
			using (var server = context.CreateResponseSocket())
			using (var client = context.CreateRequestSocket())
			{
				Console.WriteLine("Bind the server to a local TCP address");
				server.Bind("tcp://localhost:5556");

				Console.WriteLine("Connect the client to the server");
				client.Connect("tcp://localhost:5556");

				Console.WriteLine("Send a message from the client socket");
				client.SendFrame("Hello");

				Console.WriteLine("Receive the message from the server socket");
				string m1 = server.ReceiveFrameString();
				Console.WriteLine("From Client: {0}", m1);

				Console.WriteLine("Send a response back from the server");
				server.SendFrame("Hi Back");

				Console.WriteLine("Receive the response from the client socket");
				string m2 = client.ReceiveFrameString();
				Console.WriteLine("From Server: {0}", m2);
			}

			Console.ReadLine ();
		}
	}
}
```

Works fine on Linux with Mono 3.2 but not with Mono 4.3.  
I've tested this on multiple machines with the same result

The output of the application with Mono 3.2:

> Bind the server to a local TCP address
> Connect the client to the server
> Send a message from the client socket
> Receive the message from the server socket
> From Client: Hello
> Send a response back from the server
> Receive the response from the client socket
> From Server: Hi Back

The output of the application with Mono 4.3:
> Bind the server to a local TCP address
> Connect the client to the server
> Send a message from the client socket
> Receive the message from the server socket

Basically it never gets past `string m1 = server.ReceiveFrameString();`

**Comment by timothyparez** [comment]
![image](https://cloud.githubusercontent.com/assets/2060470/12069830/0aabb9a4-b08b-11e5-967a-14662d4831a8.png)

The image shows the output of the same application, on the same computer with different mono versions.

**Comment by somdoron** [comment]
It also works on mono version 4.2.1.

Did you install the 4.3.2 version from source code or used a different
repository?
Latest version I get from ubuntu is 4.2.1.

**Comment by timothyparez** [comment]
I usually get and compile mono directly from the github repository.

**Comment by somdoron** [comment]
As NetMQ is working with latest mono stable version you think it is worth
investing the time now or waiting for next mono stable release? do you work
with mono source code version on production as well?

**Comment by timothyparez** [comment]
I'm fine with using the release version in production. And then we can revisit this with the next release.
If and when it comes up we'll have an "aha!" moment.

**Comment by timothyparez** [comment]
Just compiled the release version from source and installed it on the test machine and it works.  
Keep this open or close it?

**Comment by somdoron** [comment]
So it was very specific version? If so I think we can close it.

**Comment by timothyparez** [comment]
Closed, tied to a specific version of Mono.
