### ISSUE TITLE
Unity crashing on ReceiveFrameString

### ISSUE THREAD

**Issue by MathieuBarbier** [zeromq/netmq#430]
Hello,
I'm trying to translate this python script https://github.com/pupil-labs/pupil/wiki/Pupil-Capture#receiving-data-with-your-own-app to C# in Unity. 
My app crashes when I press A to test the receive frame string. I have no error message. The app just freezes and I have to kill the process. 

public class PupilReceiver : MonoBehaviour {

	NetMQContext ctx;
	NetMQSocket server;

	void Start ()
	{
		AsyncIO.ForceDotNet.Force();
		ctx = NetMQContext.Create ();
		server = ctx.CreateSocket (ZmqSocketType.Sub); 
		server.Connect("tcp://127.0.0.1:5555");

		Debug.Log ("Connect to server " + server.HasIn);
	}
	 
	void Update()
	{	
		if (Input.GetKey (KeyCode.A) && server!=null) {
			string replyMsg = server.ReceiveFrameString();
			Debug.Log (replyMsg);			
		}
	}

	void OnApplicationQuit()
	{
		server.Dispose();
		ctx.Dispose();
	}
}

Thanks.

**Comment by somdoron** [comment]
Your code will block forever as you are not subscribe to any topic. 

User ctx.CreateSubscriberSocket instead of CreateSocket.

Call subscribe to any topic on the socket for testing. Make sure the publisher publish messages.

ReceiveFrameString is blocking, so you might want to use TryReceiveFraemString

**Comment by MathieuBarbier** [comment]
Thanks for your quick reply. 
It works perfectly now ! Thanks again. 

Here is my code for those who look for the solution : 
public class PupilReceiver : MonoBehaviour {

	NetMQContext ctx;
	NetMQ.Sockets.SubscriberSocket server;

	void Start ()
	{
		AsyncIO.ForceDotNet.Force();
		ctx = NetMQContext.Create ();
		server = ctx.CreateSubscriberSocket(); 
		server.Subscribe ("norm_pos");
		server.Connect("tcp://127.0.0.1:5000");
	}
	 
	void Update()
	{	
		if (Input.GetKey (KeyCode.A)) {			
			string replyMsg = "";
			if(server.TryReceiveFrameString(out replyMsg)){
				Debug.Log (replyMsg);			
			}
		}
	}

	void OnApplicationQuit()
	{
		server.Dispose();
		ctx.Dispose();
	}
}

**Comment by somdoron** [comment]
Just for curiosity when does Update is being called? is it something like
30 times a second?

I suggest you might loop through all messages when you update is called.
something like:

while (server.TryReceiveFrameString(out replyMsg)) {
Debug.Log(replyMsg);
}

**Comment by WizzardMaker** [comment]
Unity gets called every frame, from 20 - 3789 times per second, FixedUpdate gets called a given fixed amount

**Comment by MathieuBarbier** [comment]
Update is called every frame in Unity and FixedUpdate is called every physic frame in Unity. 
I'll try to modify the script to get all messages as you suggested Somdoron. Thanks.

**Comment by somdoron** [comment]
Can we close this?
