### ISSUE TITLE
Messages not getting sent in Unity

### ISSUE THREAD

**Issue by MikeFair** [zeromq/netmq#440]
I am having a strange situation using the tcp transport in Unity where despite successfully completing the underlying tcp connections, no messages are actually being sent over the network.  

I can see all the connections via netstat and detect all the connection setup traffic via the network inspector (WireShark in this case) and if I replace the tcp transport with the inproc transport everything works fine (except for the obvious limitation of only connecting to Sockets within the same Unity process), so the code structure itself seems fine. 

It appears that any Socket sending data to a Socket hosted by Unity is triggering something that prevents the tcp transport from writing the message to the wire.

Also, I have NetMQ Sockets that connect within the Unity process, from Unity to an external C# application, from the external C# app to Unity, and within the external C# application.  These are all Push/Pull type Sockets and like I said, I can see via NetStat that all these Sockets successfully get their connections established.  The traffic happening within the external C# application is working just fine (messages are received and the traffic itself can be seen in WireShark).  It's all other traffic involving the Unity Sockets that's being queued up.

I've also tested using direct Udp and Tcp System.Net.Sockets code and that works just fine within Unity and between Unity and Non-Unity applications; so it's not a general problem of firewalls or other network inhibiting factors.

I have forced AsyncIO to use DotNet in all cases.  I am using the ASyncIO.Unity project in all cases (though I have also tried the other project builds too).

I have tried the libraries from the latest stable NetMQ/ASyncIO on Nuget, the latest prereleases available on Nuget, and the latest GitHub sources, and the behavior is always the same.

From the Debugger, I can see is that the HasOut parameter on all Sockets attempting to Send to/from Unity is always true after the first send.  Tracing through the Send code seems to suggest that the messages are continuing to queue up in the pipe and never get sent out on the wire; but the NetMQ code itself believes it has successfully written and flushed the Pipe.  Which to me implies something going on in AsyncIO.

Is there something more I can check or do to get these messages onto the wire?

Thanks
PS I am using Windows 7 64-bit, Unity 5.3.1f1, and Visual Studio 2015

**Comment by somdoron** [comment]
Which version are you using? What are the socket types? What zeromq flavor
do you use on the server side?

**Comment by somdoron** [comment]
Also, can you make minimal code that reproduce?

**Comment by MikeFair** [comment]
I am using Windows 7 64-bit, Unity 5.3.1f1, and Visual Studio 2015; 
I've tried the latest stable, one back from the latest, and the latest prerelase available from nuget as well as compiled from the latest source (2016-01-16) using .Net 3.5, Unity 3.5 full module, and Unity 3.5 subset as the FrameWorks;
the Socket types were Pair, Push/Pull, Pub/Sub, and Req/Rep Sockets. 
The same NetMQ libraries were used for the external C# application as for Unity in each test.
(Sorry about overtrimming those details out of the initial post. :) )

---

For minimal code to reproduce, use the code pasted in #324 and attach it as a C# Script Component to a new empty gameObject in a new Unity Project (you technically can just attach it to the main camera gameObject, but a new empty gameObject seems cleaner).  

You'll need to provide an outside Rep/Req Socket to service the connection.  If someone could tell me a combination of NetMQ/AsyncIO libraries that works with the #324 code and the latest Unity I can likely go from there.

In case it's related, I'm also encountering the "hang on context dispose" that others reported.

---

Last night I also started creating a minimal code base to replicate the intraUnity socket tests (which I'll post later tonight).  This time the Sockets wouldn't even connect to each other (I might have been changing too much and gotten some library versions crossed); the external C# application (Pull Socket) could connect to the Unity Push Socket, but no data was sent.

I used code very close to #324 that places both the server and the client Sockets inside Unity using two different gameObjects; and instead of putting everything in the Start() routine, it creates the Sockets (Push/Pull) in the Start() routines and then uses TryReceiveMultipartMessage and TrySendMultipartMessage in the Update() routines.

The server pushes an incrementing counter converted to a string as a NetMQMessage.

The libraries were the latest from master on GitHub compiled using the .Net 3.5 Framework as the target.


---

Lastly, in case anyone needs/wants to know how to get started with Unity here; the NetMQ/AsyncIO DLL libraries need to be added to the Assets folder of the Unity project (they can be in subfolders).   Unity will detect these libraries automatically whenever you make changes to the Assets subtree.

Be sure the project has marked "Development Build" and "Script Debugging", and is set to output for PC, Mac, Linux output (File->Build Options...); you can use the "Build and Run" button to bring up the app in a separate Player (this way if/when the application hangs you can kill the player process and leave the Unity Editor with the project running).  You can use Ctrl+b to launch using the player after this has been set the first time.  

In Visual Studio use the Debug -> Attach to Unity Debugger menu option and wait for/select the separate player not the Editor.  The player will be listening on port 56XXX that's separate from the Editor's port, and will show up as Windows Player in the popup dialog.  If it doesn't show up, you can use netstat to find the port and manually type in the IP/Port.

**Comment by somdoron** [comment]
@MikeFair following gist worked for me with external C# application

https://gist.github.com/somdoron/6f9184092f16624c65de

**Comment by somdoron** [comment]
@MikeFair what zeromq stack do you use on the server?

**Comment by MikeFair** [comment]
@somdoron I used the NetMQ Stack on the server side (external C# app).
What version of Unity are you using and what versions/project files of NetMQ/AsyncIO did you use and what was the compile target for that Gist?

**Comment by MikeFair** [comment]
@somdoron 

Thanks for the help.

That Gist is working for me using the latest prerelease of NetMQ and AsyncIO 0.1.18.0.
The Unity application still hangs on exit but one step at a time.

So that just leaves the Unity <-> Unity communications.

I put this on another gameObject and tried using it instead of the external app:

    using UnityEngine;
    using NetMQ;
    using NetMQ.Sockets;
    using AsyncIO;

    public class NetMQPublishCount : MonoBehaviour
    {
        private NetMQContext m_context;
        private PublisherSocket m_publisher;

        private int msgCount;

        // Use this for initialization
        void Start()
        {
            ForceDotNet.Force();

            m_context = NetMQContext.Create();
            m_publisher = m_context.CreatePublisherSocket();
            m_publisher.Bind("tcp://127.0.0.1:55561");

            msgCount = 0;
            Debug.Log("Bound");
        }

        // Update is called once per frame
        void Update()
        {
            string message;

            Debug.Log("Publisher Update");
            
            msgCount++;
            if (msgCount % 200 == 0) {
                NetMQMessage mqMsg = new NetMQMessage();
                mqMsg.Append("Text");
                mqMsg.Append(msgCount.ToString());
                m_publisher.TrySendMultipartMessage(mqMsg);
            }
        }
    }


I could see the network connections established in netstat between the objects, I could see the app executing the TrySend, but it seemed like everything just stayed in the publisher socket's queue; the subscriber never received any messages and m_publisher.HasOut was always true after the first send.

**Comment by somdoron** [comment]
@MikeFair ignore the HasOut, it is always true for publisher.

Anyway for me everything worked perfectly including inside communication and closing the app. I updated my gist.

https://gist.github.com/somdoron/6f9184092f16624c65de

**Comment by somdoron** [comment]
By the way my NetMQ version is 3.3.2.2

**Comment by MikeFair** [comment]
> By the way my NetMQ version is 3.3.2.2

And the ASyncIO version is 0.1.18.0 I assume?

**Comment by somdoron** [comment]
Yes.

**Comment by MikeFair** [comment]
@somdoron 

Thanks for looking into this with me.
The updated Gist fails to pass messages between the gameObjects using TCP on my laptop (and the application does hang on quit despite the Dispose() calls; I can't help but feel these are related). 

I placed the NetMQ 3.3.2.2 and AsyncIO 0.1.18.0 DLLs in the Asset tree.  

I also added a second Pull Socket to simultaneously connect to a Push Socket in the external C# application bound to a different port.  Messages from the external C# app are received, while messages from the other gameObject are not.  I can still see the network connections via netstat established for both connections.

Since I'm not seeing the expected traffic in WireShark, and tracing shows that SendFrame() copied the message and queued it for delivery, I'm assuming the packets are still queued up on the publisher's side (as opposed to queued on the Subscriber's incoming queue but not triggering a receive).  

I am using Unity 5.3.1f1 64-bit; what about you?

I remember being required to add the JetBrains.Annotations library from nuget to the project at some point when I was custom building from source.  While I'm not using my own compiled libraries any more, could there be libraries or versions of libraries outside of NetMQ/ASyncIO I need to look at or need to add to the Assets folder?  

Any ideas?
Is there an object or something else on the publisher I can inspect to try and figure out what's not happening?

Thanks

**Comment by somdoron** [comment]
Can you make a full gist with all of your assets? I will try to run it over
on my machine.

**Comment by MikeFair** [comment]
Ok, here's the Gist:
https://gist.github.com/MikeFair/af73415f19ade2be806c

Pub/Sub on 55561 internal to Unity; Push/Pull on 55562 between outside C# app and Unity.
Just attach to an empty game object (they add a TextMesh component; move themselves to make the text visible, and update the text on message send/receive).

**Comment by somdoron** [comment]
So I was able to reproduce the issue. Seems that you cannot bind NetMQSocket on unity. But I'm still checking it.

**Comment by MikeFair** [comment]
Great find! Any update here?

Here's what I can add about it:

1) It's seems limited to TCP; binding with inproc works
2) The Socket does bind at the OS level and will accept connections (you
can see it in Netstat)

I didn't try binding each socket and then explicitly connecting them to
each other.

**Comment by InvertedAcceleration** [comment]
Any updates on this?  @MikeFair did you get it sorted?

**Comment by MikeFair** [comment]
No I haven't.

I started to trace the code but wasn't able to find the breakpoint where a
listening socket gets accepted to see if I could determine why the event
seemed to just get lost.  I haven't followed up again since that debug
session.  I'll have to get back to this with some fresh eyes. :)

I also took some time to work on contributing a shared memory based IPC
module to use with NetMQ because that's how I wanted it to work anyway.  I
have some standalone test code that proved a concept I had, but nothing
integrated into NetMQ just yet.

**Comment by MikeFair** [comment]
> Any updates on this? @MikeFair <https://github.com/MikeFair> did you get
> it sorted?
>

I still haven't resolved anything, but I do have some more information.

I fired up WireShark and I can see the traffic and data being sent and
acknowledged over the network.  So the packets are making it from one
socket to the other, but none of the TryReceive methods are returning any
results during the Update loop on the object.

Also, the moment I attach the Visual Studio debugger to the WindowsPlayer,
the traffic stops entirely.  It's feeling more and more like the Unity
engine itself is somehow sucking up the packets before NetMQ has a chance
to get at them.

**Comment by MikeFair** [comment]
Update!

I found a bug that meant incoming messages to the Unity subscriber Socket
in Unity wasn't printing the messages to the TextMesh on the object in the
UI. The messages were coming in, they just weren't being printed.

Unity was not swallowing the messages when I was watching them pass with
WireShark. The messages were received, I just wasn't seeing the results.

Things also seemed to get better after I compiled my own DotNet35 version
of the libraries.

Using pub/sub sockets I can now Bind and Connect both into and out of Unity
just like any other program as expected.

I haven't tried any other Socket Types yet.

There's still a two issues:

1)
Connecting the debugger still triggers NetMQ to stop transmitting the
messages.  Sorry about any confusion this caused.

2)
Unity still crashes on exit, regardless of what I close or dispose of (or
when).  So far I've only tried basic pub/sub sockets; none of the other
socket types.

3)
I'm still not sure what, if anything, this means for the packages available
from NuGet.  Only that compiling from GitHub for the Net35 target worked.

Thanks all!

**Comment by aventurella** [comment]
I am having a similar issue. When I run Unity in the editor, all the sockets connect just fine and do their thing. When I got to build for windows x86_64 and I run the resultant application, my Sub socket never receives anything from the Pub socket. Again if I run the same in the Unity editor, it all works. It's only when publishing that it fails to work properly.
