### ISSUE TITLE
How to close ResponseSocket safely?

### ISSUE THREAD

**Issue by my20050804** [zeromq/netmq#443]
I always met error below:
2016-01-22 12:18:16,330 NetMQ.TerminatingException: CheckContextTerminated - yes, is terminated.
   在 NetMQ.Core.SocketBase.CheckContextTerminated()
   在 NetMQ.Core.SocketBase.TrySend(Msg& msg, TimeSpan timeout, Boolean more)
   在 NetMQ.NetMQSocket.TrySend(Msg& msg, TimeSpan timeout, Boolean more)
   在 NetMQ.OutgoingSocketExtensions.Send(IOutgoingSocket socket, Msg& msg, Boolean more)
   在 NetMQ.OutgoingSocketExtensions.SendFrame(IOutgoingSocket socket, String message, Boolean more)
   在 NetMQ.OutgoingSocketExtensions.SendMoreFrame(IOutgoingSocket socket, String message)
   在 Horse3.WinServer.Forms.MainForm.ThreadResponse()

My code like that:
        private void ThreadResponse()
        {
            try
            {
                using (ResponseSocket responseSocket = new ResponseSocket())
                {
                    responseSocket.Bind(ConfigUtil.ResponseServer);

```
                while (true)
                {
                    try
                    {
                        NetMQMessage msg = responseSocket.ReceiveMultipartMessage();
                        string key = msg[0].ConvertToString();
                        byte[] data = msg[1].Buffer;

                        string result = ResponseHandler.Instance.HandleResponse(key, data);

                        responseSocket.SendMoreFrame("1").SendFrame(result);
                    }
                    catch (MessageException me)
                    {
                        responseSocket.SendMoreFrame("0").SendFrame(me.Message);
                    }
                    catch (Exception ex1)
                    {
                        responseSocket.SendMoreFrame("0").SendFrame(ex1.ToString());
                    }
                }
            }
        }
        catch (Exception ex2)
        {
            LogUtil.Error(ex2.ToString());
        }
    }
```

**Comment by MikeFair** [comment]
Based on the LogTrace something has caused the default global context to get terminated during one of the SendMoreFrame() calls.  

What happens if instead of using the new ResponseSocket() method of making Sockets; create a global NetMQContext and use the m_context.CreateResponseSocket() call instead?

Does the Context still get terminated?

**Comment by somdoron** [comment]
It means you closed the context, the context must live for long as the last
socket.

**Comment by MikeFair** [comment]
@Doron,

The code snippet used "new ResponseSocket()" to create the socket; I
thought I understood that to use a static class context.  In which case how
could the context get closed?

**Comment by somdoron** [comment]
I missed that. You are right...

**Comment by my20050804** [comment]
Thanks all.
I don't close the context, just close the form as user click "X" on the form.
I use the latest library it recommends using "new" keyword, do I must downgrade the library version?

**Comment by MikeFair** [comment]
Try Adding a Catch Block for NetMQ.TerminatingException and Dispose of the socket in the thread.

    catch (TerminatingException te)
    {
        responseSocket.Dispose();
        break;
    }

It might be the Socket is already disposed so all you have to do is break;

**Comment by somdoron** [comment]
where do you call the responseSocket.Dispose? or when in the life-cycle of the application?

The context termination is during process exit event. I might

**Comment by my20050804** [comment]
it seems can not use try-catch. there is no code to call "Dispose".  
when the form loading, I create a thread to hold the "while(true)" loop, and just close the form.

**Comment by somdoron** [comment]
Ok, so you close the application without terminating the backend thread first?
So this is why you get the exception... you can just catch it and ignore, anyway I would suggest doing a gracefully shutdown.

But the an interesting issue, what do you think should be the behavior?
