### ISSUE TITLE
problem: NetMQ is full of obsolete code

### ISSUE THREAD

**Issue by somdoron** [zeromq/netmq#450]
So the API is full of obsolete code, IMO that confusing and not elegant.

Suggested solution:
* Maintain NetMQ3-x repository with obsolete code
* This repository will become NetMQ4, with new nuget package
* We will remove obsolete code from NetMQ4 repository
* We will cherry pick bug fixes for NetMQ3-x
* NetMQ will be beta for sometime, after that we cannot delete methods
* Anything we remove from NetMQ4 we need to mark as obsolete in NetMQ3-x and provide the alternative

**Comment by dalebrubaker** [comment]
+1
1. Personally I would like it to be C# 6 but targeting .Net 4.0 and compilable using the free visual studio community edition.
2. Is this a good time to plan ahead for a .Net 4.5 version? E.g. with the AsyncSocket from your blog.

**Comment by sharpe5** [comment]
+1.

I'm all for that, I did note that there was a lot of obsolete API calls, which made the learning curve a bit more difficult.

I also have a few bugfixes to contribute, as well as a very nice RX wrapper that could be an incentive to upgrade to NetMQ4.

**Comment by sachabarber** [comment]
sharpe5

I am all for using Rx on top of this, that would make it it very cool indeed (I am a massive fan of RX)

**Comment by somdoron** [comment]
I will start remove obsolete code soon.

**Comment by sharpe5** [comment]
As part of this, it might be an idea to go through any blogs that are under our control, and update them to make sure they use non-obsolete calls. This means that new users can instantly download the latest stable version, then dive in and get positive feedback immediately.

One of the problems MongoDB experienced is that they radically changed their API from v1.9 to v2.0 (mostly for the better), but 95% of the blogs still used the old calls which wouldn't compile. I have a lot of C# experience, but nothing was documented, and it took me a while to literally guess what changes to make to actually get it to compile and work.

**Comment by sharpe5** [comment]
@sachabarber 

I've created a drop-in replacement for ISubject<T>. It lazily instantiates a publisher or a subscriber on demand, then tranfers everything using Protobuf.

Sample call:
```

	var p = new SubjectNetMQ<int>(zeroMqAddress: "tcp://localhost:56000");
	p.Subscribe(o =>
	{
		Console.Write($"Hello, world! {o}\n");
	});
	p.OnNext(4);
```

**Comment by drewnoakes** [comment]
@sharpe5 a PR sounds good. Perhaps you can add a new sample project with this code, as it seems you'll be adding dependencies upon other NuGet packages (Rx/Protobuf).

**Comment by somdoron** [comment]
I want to start extension project to NetMQ, so we can have something like
NetMQ.RX or NetMQ.Security.

I have the organization name NetMQ so we can put everything there.
Of course it is recommended to use C4.1.

**Comment by sharpe5** [comment]
@drewnoakes Ok, I will add a dedicated sample project.

I would be interested in feedback, I have only been working with the NetMQ API for a few days. The difference between ZeroMQ and Tibco is enlightening: Tibco is riddled with bugs and memory leaks, has the most Byzantine API you can imagine, and also loses messages randomly under high load.

**Comment by sharpe5** [comment]
Just read this post. I agree, I think its probably better to add an extension project, in order to avoid adding dependencies for RX and Protobuf (and potentially other serialization methods). Its going to be a week or so before I can upload anything, so we have time to think about it.

**Comment by somdoron** [comment]
Let me know when you have a project ready, we can move it to the NetMQ
organization.

I suggest following C4.1 which we use for NetMQ.

http://rfc.zeromq.org/spec:22
