### ISSUE TITLE
Problem: PGM and/or EPGM doesn't work on Mono

### ISSUE THREAD

**Issue by vadian** [zeromq/netmq#452]
I would like to start a conversation on the feasibility of supporting PGM or EPGM on Mono.  NetMQ is in my opinion a great platform for network discovery for IoT, and a crossplatform reliable multicast would definitely help this use case.

If this is something that sounds feasible, I'd be happy to help contribute to a solution, but I'm unsure if the changes required would be something the project would like to move towards.

**Comment by somdoron** [comment]
Why not using NetMQBeacon?
Take a look at the beacon docs http://netmq.readthedocs.org/en/latest/beacon/

I like the idea but it is going to be hard, NetMQ is using microsoft implementation of PGM coming with MSMQ 3.0.

We can try and use openpgm on linux, but I'm afraid it is not an easy task:
https://code.google.com/p/openpgm/

One important point, I think NetMQ should stay 100% C#, it is one of the reason the project is popular. So if we are going to use openpgm it should not ship with NetMQ, more like a prerequisite on the machine. The same way we are using MS-PGM.

**Comment by vadian** [comment]
I definitely agree with you on staying 100% C#.  It was a major draw to me as well.  The beacon looks like it could definitely offer a solution to my particular problem, and honestly looks like the right solution to what I'm trying to build.  

Really, abstracting the bus class into something similar to a broadcast pub/sub socket (with the additional requirement of the discovery listener) would fulfill all the roles of PGM.  Perhaps my time would be better spent building the Bus example into the code, so that a user just needs to create the bus with a port and go, and handle all the discovery behind the scenes?  Something similar to this at the user level:

BusSocket socket = new BusSocket(1337);
socket.Subscribe("messages");
socket.SendMoreFrame("messages").SendFrame("hello");

What are your thoughts?  Headed in a good direction, or unneeded complexity?

**Comment by somdoron** [comment]
take a look at the Zyre project, it is doing exactly that.

I suggest it would be a different project under the NetMQ repository. Maybe NetMQ.Zyre assembly with different nuget package.

https://github.com/zeromq/zyre

**Comment by dalebrubaker** [comment]
@vadian, this week I began working on NetMQ.Zyre. I like the fact that it is written to a standard http://rfc.zeromq.org/spec:36 and that we already have Zyre (C), Pyre (Python) and Jyre (Java). I have barely begun, and I am rather new to NetMQ, and I can't promise how much quickly it will process. My direction is the same as @somdoron says, NetMQ.Zyre assembly with different nuget package.

**Comment by vadian** [comment]
@somdoron : That sounds like a wonderful approach.  At first glance, it appears that what I want to build mirrors NetMQ.Zyre to the point of duplication.

@dalebrubaker : I'd love to help. :)

**Comment by dalebrubaker** [comment]
I'll try to do a pull request into NetMQ  later today. I was going to do more of this on private, but the spirit of zeromq is public, which I like. I don't know how this works where we need to keep this in a development branch for a while but still be public.
@vadian  I'll be very happy for your help. BTW  chapter 8 of zeromq guide is about Zyre philosophy. http://zguide.zeromq.org/page:all#toc229

**Comment by somdoron** [comment]
@dalebrubaker you can do everything on NetMQ master, no need for branch.

Just make a pull request with the initial NetMQ.Zyre project.

**Comment by vadian** [comment]
Awesome, I'll start by reading up on that and the spec today.  Should I fork off of you or NetMQ master?

**Comment by dalebrubaker** [comment]
Fork NetMQ/master.

**Comment by dalebrubaker** [comment]
@vadian, you probably saw that I did submit the first pull request this evening. I wanted to start with the zproto message class, then I planned to "copy" the pattern from zeromq/Zyre (how are your C skills? -- mine are rusty) and also zeromq/jyre. But jump right in however you like. I probably won't get back to this until Friday or later.

**Comment by vadian** [comment]
I'm a bit rusty with my C as well, but I can still read patterns fairly well.  My Java is stronger - I'd have better luck templating off Java than C.  It'll be a day or two before I really have time to dedicate, but working on the message class first sounds good to me.

**Comment by MikeFair** [comment]
@vadian 

In case you weren't aware: https://github.com/zeromq/jyre
