### ISSUE TITLE
False positive high-watermark check in Pipe class

### ISSUE THREAD

**Issue by vordoom** [zeromq/netmq#459]
Loss of messages is observed while using PUB/SUB exchange pattern under load over network (avg. rate: 6000 messages per second, high watermark: 100000). I did some investigation, but might be wrong with conclusions as not a netMQ expert, so please correct me if I am wrong here :) 

It seems like current implementation of high-watermark verification in `Pipe` class may lead to false positive results. Thus wrong assumption on actual buffer capacity switches pipe to blocked state (which reject new writes and lead to unnecessary loss of messages).

Actual high-watermark verification (in `CheckWrite` method) is based on a difference between `m_numberOfMessagesWritten` and `m_peersMsgsRead`, where:
- `m_numberOfMessagesWritten` - is a total number of message written;
- `m_peersMsgsRead` - a **copy** of total number of message read, which is periodically updated via `SendActivateWrite`.

Currently updates of `m_peersMsgsRead` are controlled by `m_lowWatermark` which is often "too late" and brings to wrong assumptions on actual buffer capacity (and further block the pipe). Increasing the rate of updates helps to reduce a chance of false-positive verifications.  

Below I try to illustrate a situation where write (_blue line_) is 25% faster than read (_green line_), so buffer will be eventually occupied. Actual buffer usage can be illustrated as an interval between blue and green lines, while _red line_ shows maximum buffer capacity. So it will be totally occupied when green line crosses red line, which is absolutely fine.

The bad thing here is a _pink line_, which is a "copy of total number of message read value" that is updated periodically. Red line starts crossing it much earlier and thus demonstrates those false positive checks that bring pipe into blocked state.

![image](https://cloud.githubusercontent.com/assets/8515163/12690696/6351f54c-c6f6-11e5-86d2-0aaa3046b86a.png)

I totally understand that having `m_peersMsgsRead` in sync with actual value is impossible due to enormous performance penalty. Still it would be really great to have means to control its "updates rate" (e.g. via configuration). Current implementation with `m_lowWatermark` does not give much space for external adjustments. 

Again want to mention that I do not see netMQ infra in big picture, so could be wrong here. Your comment are very-very welcome :)

P.S. Also want to say that we have already tested relevant code changes and got no messages loss (within original environment and data flow).

**Comment by somdoron** [comment]
That sound interesting. You can add socket option to control it. Why not making a PR with the change?

**Comment by vordoom** [comment]
I am on it. Will publish it soon.

**Comment by vordoom** [comment]
Published a pull request https://github.com/zeromq/netmq/pull/469

**Comment by somdoron** [comment]
Merged :-)

**Comment by vordoom** [comment]
Thank you! :)

**Comment by somdoron** [comment]
Depends if people needs it, but anyway zeromq is very welcoming. Just make the problem you are solving clear and make a pull request.
