### ISSUE TITLE
Router-Dealer pattern issue, is it a bug?

### ISSUE THREAD

**Issue by my20050804** [zeromq/netmq#463]
The server side is Router, the client side is Dealer. I set DealerSocket's Identity as a fixed value so that the server can push data by the identity to client. It works well, but if I close the client and re-open client using same identity, it can connect but can't receive any message from server, I must close both of server and client and re-open all. Hover, If I change the dealersoket's identity everytime, it works.
[NetMQ_Router_Dealer.zip](https://github.com/zeromq/netmq/files/115184/NetMQ_Router_Dealer.zip)

Is it a bug?

**Comment by my20050804** [comment]
Can anyone help on this? Many thanks!

**Comment by somdoron** [comment]
I'm testing this

**Comment by somdoron** [comment]
So NetMQ by default ignore duplicate peers, if you actually will wait enough time between restarts this shouldn't happen.

On zeromq there is a feature called router handover, which in case of duplicate identifies handover the peer to the latest pipe.

Take a look at the implementation here:
https://github.com/zeromq/libzmq/blob/master/src/router.cpp#L470.

I suggest you port the feature to NetMQ.

Another option which I recommend is not to use the identity feature, instead have small handshake mechanism:
* Client send login message
* Server saves mapping between the generated routing id (identity) and the client id.
* If server received a message from unknown client and error is sent to the client
* If client receive error client need to relogin

That way everytime you open the client the client needs to login, if client silently relogin and send a message, clients gets error and should relogin

**Comment by gtemgoua** [comment]
I agree completely with @somdoron on this. I am using the same Router-Dealer communication in my project now and this is my flow:
1. Server (Router) starts and wait for client to connect
2. Client (Dealer) starts and connects to server but also Client send a Message "IM Ready" to server: The goal of this message to the server is to unwrap the identity of the client so it can be re-used to send data back to.

**Comment by my20050804** [comment]
Many thanks!

**Comment by dalebrubaker** [comment]
I think I need the router handover option for the Zyre implementation, so I'll take a pass at adding it.

**Comment by somdoron** [comment]
Just ported the handover feature
