### ISSUE TITLE
Hard to track NuGet releases with source

### ISSUE THREAD

**Issue by linnet** [zeromq/netmq#464]
It is currently quite hard to identify the specific source used for the NuGet releases. It would be very helpful with either a tag or a source release on GitHub.

**Comment by drewnoakes** [comment]
I agree tagging would be good. @somdoron, do you agree? If so I'll start tagging any future build I push to NuGet.

Also, on the topic of prerelease build which are currently made manually, it's possible to use AppVeyor as a source for NuGet. If we were to do that, then every build would be available publicly, though only visible if you add the AppVeyor URL to your NuGet configuration. So, pros and cons.

**Comment by somdoron** [comment]
I wonder if we can use the release management of github, so every time we
make a release on github it will make a tag (that already happen) and will
release a nuget version.

What do you think?

**Comment by drewnoakes** [comment]
#875 should help. It'll embed the Git hash into the binary, and allow debugging directly into the library source for consumers of the package.
