### ISSUE TITLE
XSub SubscribeToAnyTopic invalid ZmqSocketOption of Subscribe

### ISSUE THREAD

**Issue by Sn3b** [zeromq/netmq#466]
Hi,

I'm experiencing with the XPub/XSub example found here: http://netmq.readthedocs.org/en/latest/xpub-xsub/

All works well, but I was wondering if it was possible to have the broker's (Intermediary's) XSub socket subscribe to any topic?

I tried the following:

``` csharp
using (var xpubSocket = new XPublisherSocket("@tcp://127.0.0.1:1234"))
using (var xsubSocket = new XSubscriberSocket("@tcp://127.0.0.1:5678"))
{
    Console.WriteLine("Intermediary started, and waiting for messages");

    // proxy messages between frontend / backend
    var proxy = new Proxy(xsubSocket, xpubSocket);

    xsubSocket.SubscribeToAnyTopic();
    xsubSocket.ReceiveReady += ( o, a ) =>
    {
        // do something
    };

    // blocks indefinitely
    proxy.Start();
}
```

But I get an exception: Options.SetSocketOption called with invalid ZmqSocketOption of Subscribe.

What does it mean?

Thanks!

Seb :)

**Comment by somdoron** [comment]
The thing about xsub is that you only use it when you want to forward subscriptions. If you just want to subscribe to evertything use Sub.

Anyway if you still want to do that, send byte array of size of 1 with the byte set to 1 (not ascii 1, just 1).

Something like so:

```csharp
xsubSocket.SendFrame(new byte[] {1});
```

**Comment by Sn3b** [comment]
Well the idea is that I indeed want to do it just like in the example as I intend to use the broker as a sort of server that both pub and sub will connect to. The broker should forward the messages, but I wanted to also maybe log the messages that get through the broker, is that possible?

**Comment by somdoron** [comment]
Yes, but you don't need the XSub if you subscribe to all, just use sub, you can do it manually without a proxy, and then log the messages.

using (var pubSocket = new PublisherSocket("@tcp://127.0.0.1:1234"))
using (var subSocket = new SubscriberSocket("@tcp://127.0.0.1:5678"))
{
    subSocket.SubscribeToAll();
    Console.WriteLine("Intermediary started, and waiting for messages");

    while (true) 
    {
        Msg msg;
        msg.InitEmpty();
        subSocket.Receive(ref msg);

        // TODO: log the message here

        pubSocket.Send(ref msg, msg.HasMore);
    }

    // blocks indefinitely
    proxy.Start();
}

**Comment by Sn3b** [comment]
Ok I will try that, thanks! :)

**Comment by somdoron** [comment]
You only need xsub and xpub if you want to forward the subscriptions. If you subscribe to all you don't need that.
