### ISSUE TITLE
Problem: NetMQ on NuGet is out of date

### ISSUE THREAD

**Issue by dalebrubaker** [zeromq/netmq#480]
https://www.nuget.org/packages/NetMQ/
shows the latest pre-release built was NetMQ 3.3.3-rc4	67	Friday, January 29, 2016
It would help me a lot to have the newer stuff (particularly the NetMQBeacon changes).
Is NuGet creation manual, or does Team City just create it as an artifact?
Thanks.

**Comment by somdoron** [comment]
Currently manual. we also need to port the changes to
https://github.com/NetMQ/NetMQ3-x.

I will try to do it today

**Comment by dalebrubaker** [comment]
This has been fixed. Thanks to @somdoron
