### ISSUE TITLE
Publisher using PGM crashes when I unplug the Ethernet cable and send a message

### ISSUE THREAD

**Issue by joaoantunes** [zeromq/netmq#481]
Hi,

I'am trying to implement a Pub/Sub and after looking for the different alternatives, I've chosen the PGM, because the Reliable offered (out of the box) seems to fit to my requisites.

I've made some simple tests and all seems to be working, except when I created a Publisher, sent some messages, then unplugged the Ethernet and tried to sent another message and it crashed :(

When using TrySendFrame extension when there was no internet, I was expecting to received a False instead. I've also tried to use Timeout but the result was the same.
My application can't crash if it tries to send a message but it was not possible, I can lose the message, but the program can't crash.

Any suggestion how I should address this problem? I would like to graciously handle the fact that the message was not possible to be sent.

A similar thing happened when I tried to create a publisher without having internet.

I've tried the same with the subscriber and it worked well, but subscribers only Poll for new messages so it is a different case. 

Thanks for your attention :)

Obs: I've made the tests on the Stable 3.3.2.2 version and the last one 3.3.3-rc4.

Here is a sample code for 3.3.3-rc4 version:

```
private const int MEGA_BIT = 1024;
private const int META_BYTE = 1024;

        static void Main(string[] args)
        {
            try
            {
                using (var pub = new PublisherSocket())
                {
                    pub.Options.MulticastHops = 2;
                    pub.Options.MulticastRate = 40 * MEGA_BIT; // 40 megabit
                    pub.Options.MulticastRecoveryInterval = TimeSpan.FromMinutes(10);
                    pub.Options.SendBuffer = META_BYTE * 10; // 10 megabyte

                    pub.Connect("pgm://239.0.0.225:5554");

                    string input = null;
                    while ((input = Console.ReadLine()) != "quit")
                    {
                        if (pub.TrySendFrame(input))
                        {
                            Console.WriteLine(string.Format("Message: {0} was sent\n", input));
                        }
                        else
                        {
                            Console.WriteLine(string.Format("Message: {0} was not sent\n", input));
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception: " + ex.ToString());
            }

            Console.WriteLine("Press enter to terminate...");
            Console.ReadLine();
        }
```
![pgmunplugtest](https://cloud.githubusercontent.com/assets/224836/12916275/fb6bdb56-cf28-11e5-92e2-42af2bc29187.png)

**Comment by somdoron** [comment]
So probably unhandled exception. Do you want to try to make a pull request?
It is probably in pgm sender class.

**Comment by joaoantunes** [comment]
Well I can try to "dive in" NetMQ code and try to find out the issue. I'm not yet very familiar with the code.

**Comment by xnramx** [comment]
I've the same issue. 

Today, I was debugging and I think the socket exception isn't being handled. 

I created a "TerminatingException" exception but after that nothing more happens, even if the connection comes back. 

I think the problem is in PgmSender.cs on line 87 and/or 183. 

@somdoron: Can you help us?

**Comment by somdoron** [comment]
So what behavior do think is right? just dropping all messages while the connection is down?

**Comment by somdoron** [comment]
@xnramx @joaoantunes can you please test following fix:
https://github.com/somdoron/NetMQ3-x/tree/PGM

**Comment by joaoantunes** [comment]
@somdoron I got the code from the fix #500 and I think some strange stuff started to happen.

Now sometimes it gives the error about a "bind" that is already made. I know that in TCP I can only bind a socket to a port, but on PGM I'm not sure how it works, but from what I've seen the netmq code both "Connect" or "Bind" that netmq pgm api offers are using Binds. Is this true?

ATM I'm using on netmq connect for Publishers and binding for Subscribers all to the same PGM IP & Port. Probably I'm doing something wrong and this can't be done, but previously it was working and I was able to have multilple subscribers and multiple publishers
If i wish to have multiple subscribers and multiple publishers what should I do?

Another thing that I don't know is if the messages are being sent or not when I use TrySend, because is always returning "True" even if the message is not sent. I think the write behavior was to receive a false, if it was not possible to be sent on that moment, or between the timeout that was defined.If that happened I could for example Try to send X times, if it failed I could destroy the Publisher and create a new one. Another alternative is the publisher to fire an event saying that is faulted.

**Comment by somdoron** [comment]
So regarding the first problem, can you make small code that reproduce? you should be able to bind multiple times.

Regarding TrySend, TrySend only tell you if the message was sent to the background io thread (aka watermark is not reached), but it cannot tell you if the message was sent on the wire, NetMQ (and zeromq) was not designed that way. PGM is semi reliable, so you might loose messages from time to time. Anyway if you want full reliable you have to implement it yourself above NetMQ.

Regarding loosing messages in current implementation, only when network is down you should loose some messages (not all of them), mainly the one the socket tried to send now. I might be able to solve that and make sure you won't loose at all.

**Comment by joaoantunes** [comment]
Here are some examples:

[Publisher.txt](https://github.com/zeromq/netmq/files/157459/Publisher.txt)
[Subscriber.txt](https://github.com/zeromq/netmq/files/157460/Subscriber.txt)

I've used them as console apps and started multiple instances, at the same machine.

Regarding the reliability, I knew that netmq & zmq were not reliable, but I was expecting that PGM was a little more reliable, thats why I was picking it instead of normal TCP pub/sub. I am okey with loosing messages while network is down, if when the network is up the publisher will work normally. I'm only afraid that publisher will be broken "forever" and after a network crash all messages will stop being delivered. I saw that you've introduced exponential backoff on connect, so if the network is down for a long period, I will lose the messages for a long period too after the connection is restored, since the timer to reconnect will be damn huge.

About the Binds&Connects on netmq PGM, is the same to use Bind or Connect? Or is there any difference? I know that in TCP is different.

**Comment by somdoron** [comment]
only if highwatermark is reached you will loose messages.

Regarding the exception, which exception do you get? does it happen on subscriber or publisher?

**Comment by joaoantunes** [comment]
both

2016-03-03 19:13 GMT+00:00 Doron Somech <notifications@github.com>:

**Comment by joaoantunes** [comment]
While I was trying to reproduce the exception I made a test with the following configuration:

3 Subscribers Binding to -> pgm://239.0.0.200:5554
3 Publishers Connecting to -> pgm://239.0.0.200:5554

![pubsubtestingmultiplepublishers](https://cloud.githubusercontent.com/assets/224836/13524961/2cffa42e-e1f6-11e5-8e82-3bbf495abf08.png)

Only one of the publisher seems to effectively delivery the messages or the subscribers only can receive from one publisher. Any idea why this is happening?

**Comment by joaoantunes** [comment]
Can the issue be reopened? Or I can create a new one, with the new cases that appear after the fix.
Would like to help more, but not sure how. 

Thank you for your attention to this matter

**Comment by xnramx** [comment]
I've tested it and works, but the subscribers never reconnected again. I have to implement HB on Subscribers (close and open a new socket)?

**Comment by somdoron** [comment]
I think that is a bug as well. Creating a new socket works?

**Comment by xnramx** [comment]
With disconnect and connect it works.
