### ISSUE TITLE
Can't Create Two Publishers using ipc: In Different Processes - Throws Exception

### ISSUE THREAD

**Issue by damonwildercarr** [zeromq/netmq#483]
A single publisher/subscriber seems to work great. Unfortunately I have multiple processes, each with publish and subscribe capability. I'm trying to use NetMQ as a desktop-wide message bus.

I was hoping to use ipc: but it on launching the second process and trying to create and bind a publisher socket (all to the same ipc: location) I get an exception of type 'NetMQ.NetMQException' - Unknown Error (0xffffffff). If I only have a single process running as a publisher it works great. For example, I have process A and process B - launching A as a publisher works - when I launch B it throws an exception. If I close A and launch B it works. On then launching A it throws same exception.

Is there a limitation of only a single publisher when using ipc: ? I'm going to test with tcp: to the local host address and see if that gets around this issue. Is there a setting I am missing to allow multiple publishers to the same ipc: location?

**Comment by somdoron** [comment]
There is a bug with ipc if you use different Platform type (x86/64).

Anyway just use tcp, ipc in netmq is just tcp.

**Comment by damonwildercarr** [comment]
Unfortunately same issue with tcp: using tcp://localhost:12345. Works great until the second publisher process is loaded.

I'm creating a PublisherSocket once in each process and keeping it around. Perhaps that is my mistake? In many of the code samples these sockets are created and destroyed for each publish event. The issue there is (based on my previous issue reported) I don't want to suffer a 500ms delay between each send. I want to initialize the socket once.

Here is the listener code (runs on dedicated background thread):

 using (var subSocket = new SubscriberSocket())
                {
                    subSocket.Connect("tcp://localhost:12345");

                    Thread.Sleep(500);

                    subSocket.Subscribe("excel");

                    while (IsListening)
                    {
                        try
                        {
                            string messageTopicReceived = subSocket.ReceiveFrameString();
                            string messageReceived = subSocket.ReceiveFrameString();

                            OnMessageRecieved(messageReceived);
                        }
                        catch (Exception ex)
                        {
                            OnMessageRecieved("Error " + ex.Message);
                        }


                    }
                }

Here is the publisher code:

        private PublisherSocket pubSocket;
         
        // this is called from constructor
        private void InitializePublisher()
        {

            try
            {
                
                pubSocket = new PublisherSocket(); 
                pubSocket.Bind("tcp://localhost:12345");  // CRASHES SECOND PROCESS
            }
            catch (Exception ex)
            {
                var messageBoxText = ex.Message;

                if (ex.InnerException != null)
                    messageBoxText += Environment.NewLine + ex.InnerException.Message;

                MessageBox.Show(messageBoxText);
            }
        }



Thanks,
Damon

**Comment by somdoron** [comment]
Not sure I understand, are you trying to bind twice? Bind is exclusive, so
you cannot use same port on same machine

**Comment by damonwildercarr** [comment]
Got it. Perhaps my approach is flawed? I'm trying to have multiple publishers and multiple subscribers all on the same channel. Basically an event bus on a PC that multiple processes can leverage for IPC. Everything is loosely coupled. Publishers have no knowledge of subscribers and vice versa.

Is there anything in ZeroMQ/NetMQ that helps me facilitates this?

**Comment by somdoron** [comment]
Two options, broker or broker less. For broker less take a look at the
Beacon example from docs. Also you can use zyre. For broker,  use the
devices. You find more info in the zeromq guide.

**Comment by dalebrubaker** [comment]
FWIW, I'm very close to having NetMQ.Zyre done. It will be the C# implementation of http://rfc.zeromq.org/spec:36. You can use headers and group names for exchanging information between publishers and subscribers, but the implementation is strictly per the 36/ZeroMQ Realtime Exchange Protocol standard. I hope to get it up onto github in a few days, and into NuGet next week.

**Comment by damonwildercarr** [comment]
Awesome - thanks guys. I have some reading to do  :-).
