### ISSUE TITLE
ROUTER socket stops receiving messages

### ISSUE THREAD

**Issue by iiwaasnet** [zeromq/netmq#485]
Hi all,

I have a server ROUTER socket (RouterMandatory set to TRUE), which at some point in time stops receiving messages. I guess, this is due to HWM reached. Nevertheless, when the client is restarted, the server ROUTER socket still refuses to process any incoming message.
But, when RouterMandatory is set to FALSE, server ROUTER socket seem to be able to recovery after  faulty state due to HWM. Are these two settings (HWM and RouterMandatory) bound in some way?

**Comment by somdoron** [comment]
They are not bound. Are you using identifier for the client sockets? Can
you make an example?

**Comment by iiwaasnet** [comment]
Client and Server connect via ROUTER-ROUTER, both set Identifiers for their sockets. Actually, communication is quite tricky, I will try to have a simple example to reproduce the problem. But I can tell for sure, that if I set RouterMandatory to FALSE, Server socket is able to recover after HWM when client stops flooding it with messages.

**Comment by somdoron** [comment]
If you not using identities does itc still happen?

**Comment by iiwaasnet** [comment]
I didn't try not using identities, otherwise the message routing wont work.

**Comment by somdoron** [comment]
Is it router to router?

**Comment by iiwaasnet** [comment]
Yes, ROUTER-ROUTER.

**Comment by somdoron** [comment]
just ported the router handover feature, can you test with handover set to true? (the PR is still open at the moment)

**Comment by somdoron** [comment]
@iiwaasnet I think I know what the issue, when using router with mandatory, when recipient doesn't exist it might just block. So when using mandatory I suggest using TrySend.

**Comment by iiwaasnet** [comment]
Thanks for reply! I had the same feeling and I fixed it exactly like you suggested: TrySendMultipartMessage() :) I was just not sure if it was the only reason, hence the setup I encountered this problem was quite complicated.
I think, this is resolved now.

**Comment by somdoron** [comment]
I might have a fix that will throw the exception, however it is still recommended to use the non blocking method.

**Comment by iiwaasnet** [comment]
Non-blocking is perfect for me. Should I close the issue or you will do it after you add the fix?

**Comment by somdoron** [comment]
just added a PR to fix this. If you can test this it will be great

**Comment by iiwaasnet** [comment]
OK, I will!
