### ISSUE TITLE
A unit test fails when run in isolation

### ISSUE THREAD

**Issue by dalebrubaker** [zeromq/netmq#487]
I'm puzzled about this one. All unit tests in the SocketTests.cs file run successfully if I run all of them at once. And if I run both CheckTryReceive() and CheckTrySend() together, they succeed. But if I run CheckTrySend() by itself it fails on the Assert.IsFalse().

        [Test]
        public void CheckTrySend()
        {
            using (var router = new RouterSocket())
            using (var dealer = new DealerSocket())
            {
                var port = router.BindRandomPort("tcp://127.0.0.1");
                router.Options.Linger = TimeSpan.Zero;

                dealer.Options.SendHighWatermark = 1;
                dealer.Options.Linger = TimeSpan.Zero;
                dealer.Connect("tcp://127.0.0.1:" + port);

                Thread.Sleep(100);

                Assert.IsTrue(dealer.TrySendFrame("1"));
                Assert.IsFalse(dealer.TrySendFrame("2"));
            }
        }

**Comment by somdoron** [comment]
This test is problematic, it actually can fail. a better way to test it is to have a dealer, connect it, but never bind the server (or even creating it).

**Comment by dalebrubaker** [comment]
So when I do this test, it also fails: Perhaps TrySendFrame() succeeded just because the message  went into a buffer, even though there is nothing on the other end of the pipe? I'm trying to grasp what is the expected behavior. Thanks.

 [Test]
        public void CheckTrySendFails()
        {
            using (var dealer = new DealerSocket())
            {
                dealer.Options.SendHighWatermark = 1;
                dealer.Options.Linger = TimeSpan.Zero;
                dealer.Connect("tcp://127.0.0.1:55555");

                Thread.Sleep(100);

                var success = dealer.TrySendFrame("2");
                Assert.IsFalse(success);
            }
        }

**Comment by somdoron** [comment]
Send twice, the second should fail.

**Comment by dalebrubaker** [comment]
Fixed by merge pull request #488
