### ISSUE TITLE
A question for PUB/SUB pattern

### ISSUE THREAD

**Issue by my20050804** [zeromq/netmq#496]
I saw the document said, It will be filtered data at client side when using PUB/SUB pattern, My question is if there is large data needing to push to several clients, but only few clients need to receive the special data, will it waste the bandwidth? And become low efficiency?

**Comment by somdoron** [comment]
I guess the document is out of date, PUB/SUB filtering is happening on publisher side. Only when using PGM transport filtering is done on the subscriber side

**Comment by my20050804** [comment]
Understood, many thanks!

**Comment by drewnoakes** [comment]
@my20050804 where did you read this? Perhaps we can have it corrected.
