### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by ZOXEXIVO** [zeromq/netmq#497]
We already have some .NET Core projects and we need this lib!

**Comment by somdoron** [comment]
Did you try to compile to .net core? What is the gap?

**Comment by tobi-tobsen** [comment]
I quickly checked and we are not too far away: 94.36 % of Netmq works for the .NET Core (Cross-platform),Version=v5.0. The remaining 6% are mostly IPAddress resolution and cryptography related. 
![portability](https://cloud.githubusercontent.com/assets/1068154/13379186/63f46472-de1f-11e5-927f-adfb570cc261.png)

**Comment by tobi-tobsen** [comment]
If we go this route I strongly suggest to limit using conditional compilation #if's but instead using partial classes (also suggested by these guys: https://blogs.msdn.microsoft.com/dotnet/2016/02/10/porting-to-net-core/) 

> Sharing source code is much easier in case you want to adapt your code by using #if. However, you want to make sure that you don’t create spaghetti code by littering the source with #if conditions. Try to centralize code that handles differences as much as possible. Another neat trick is to use partial classes where one part of the class is in the shared project while another part is provided by the platform specific project.

**Comment by drewnoakes** [comment]
This tool might be useful: https://github.com/microsoft/dotnet-apiport

I re-worked some `System.Security.Cryptography` code for [another open source project](https://github.com/drewnoakes/cassette) to support .NET Core and actually the .NET Core APIs were nicer.

**Comment by somdoron** [comment]
I think we can move the security to new repository, named NetMQ.Security and remove it from the NetMQ project. It will make it easier.

**Comment by msnelling** [comment]
We're planning the migration of our project to .NET Core and NetMQ is a critical component. We have a view to running our services on Linux, how will NetMQ handle this, doesn't Async.IO have a dependency on Windows?

**Comment by somdoron** [comment]
AsyncIO works on linux as well.
I think converting NetMQ to .Net Core should be possible. I think the big problem now is the security namespace, I thought of removing it to it's own project

**Comment by peske** [comment]
One loud "PLUS ONE" for .NET Core build!

Thanks guyz

**Comment by pantonis** [comment]
+1 for .net core version

**Comment by MattWherry** [comment]
+1 from me too.

**Comment by somdoron** [comment]
my experience with dotnet core is that is not yet ready, mainly the visual studio integration issue.

If anyone have an experience and want to help we should start with AsyncIO...

**Comment by peske** [comment]
@somdoron: I'm not sure what you exactly mean when saying that "dotnet core is not yet ready", but I can tell you two things from my experience:

1. It is true that there's a lot confusing around dotnet core (targets, platforms, dozens of monikers, etc.). It is true that creating and building dotnet core project in Visual Studio is still bit tricky (multitargeting, referencing dotnet core projects from "regular" projects, etc.) But it is also true that few days ago Microsoft released dotnet core 1.0 **release** version, and Visual Studio 2015 Update 3 that specifically targets issues related to dotnet core... So chances are that things will be stable now.

2. I've started using dotnet core months ago (with prereleases, betas, previews, etc.), and already have several dotnet core projects (libraries) in production.

3. A lot of other projects already include dotnet core version. One that is (in a way) related to NetMQ is [Google Protobuf](https://github.com/google/protobuf). Actually they started with dotnet core long time ago. So, for example, at the moment I have several projects based on Google Protobuf / NetMQ, and the only reason these are not dotnet core ready is NetMQ.

So is it dotnet core ready? I don't know. There's no doubt that with maturity it'll become better, but the question is should we wait some _perfect_ stage in dotnet core, or should we start now and evolve with it?

Again here's one strong +1 to start right now.

If you decide to start with dotnet core version I can jump in and help with my experience (if needed).

Thanks

**Comment by peske** [comment]
Btw. about Visual Studio 2015 Update 3: DON'T UPGRADE YET! See [my comment in this post](https://blogs.msdn.microsoft.com/visualstudio/2016/06/27/visual-studio-2015-update-3-and-net-core-1-0-available-now/#comment-182675), as well as other comments there for more details.

**Comment by somdoron** [comment]
@peske my problem is that now i'm working on making AsyncIO dotnet core version which uses the project.json which as I understand is going to be removed...

**Comment by somdoron** [comment]
I just released new version of AsyncIO to nuget which support .net core.
NetMQ is next.

It is all bases on project.json, when dropped we would need to go back to csproj, which should support multi target.

**Comment by peske** [comment]
I haven't heard that Microsoft gives up on project.json, but I'm not too surprised either. .NET team already showed many times that they're actually not sure where they go. All craziness with targets and monikers (more than 20 in one moment) is the best example. Obviously they are still learning to swim in open-source world...

Anyway, changing the format of project file itself should not be too problematic (and definitely not the show stopper). Once the code targets appropriate APIs, changing project file shouldn't take more than few minutes, right?

Finally it's good to hear that "NetMQ is next"! Thanks for that!

Any estimation (rough) on timelines?

Thanks again

**Comment by chris-ray** [comment]
+1 for .NET Core. Just started experimenting with this library with the goal of running it in production on linux. Would be awesome to start that out with a .NET Core version. Thanks for your work!

**Comment by masaeedu** [comment]
@somdoron I believe the Visual Studio tooling will deal with automatically upgrading project.json + xproj to the improved msbuild projects.

**Comment by somdoron** [comment]
@peske hopefully this week

**Comment by somdoron** [comment]
Dotnet core support is almost here, just need to figure out why some tests fails.

The repository is here:

https://github.com/somdoron/netmq/commits/DotNetCore2

Also if someone can help with this:

http://stackoverflow.com/questions/38294286/dev-dependency-with-dotnet-core?noredirect=1#comment64005913_38294286

**Comment by somdoron** [comment]
available on nuget:
https://www.nuget.org/packages/NetMQ/4.0.0.1-rc1

**Comment by masaeedu** [comment]
@somdoron Awesome work! I was wondering if it would be possible to compile this using a lower version `netstandard`? There is a very narrow range of platforms that support `netstandard1.6`, so lowering your `netstandard` version will allow a greater number of projects and packages to use this library (e.g. .NET 4.6.1 can only target up to `netstandard1.5`).

**Comment by peske** [comment]
@somdoron Thanks dude!

But I partly agree with @masaeedu (not about netstandard version, but about .NET full support). In my experience it is better to have separate builds for .NET Core and .NET full. For this purpose in my project.json files I always have the following:

```
"dependencies": {
},
"frameworks": {
    "net461": {
        "dependencies": {
        },
        "buildOptions": {
            "define": [ "NET461" ]
        }
    },
    "netstandard1.6": {
        "imports": "dnxcore50",
        "dependencies": {
            "NETStandard.Library": "1.6.0",
            "System.Runtime.Loader": "4.0.0"
        },
        "buildOptions": {
            "define": [ "DOTNETCORE", "NETSTANDARD1_6" ]
        }
    }
}
```

This way you'll get two separate builds, and you have defined conditional compilation constants so that you can use different code when necessary. For example:

```
#if DOTNETCORE
    System.Runtime.Loader.AssemblyLoadContext.Default.Resolving += ...;
#else
    AppDomain.CurrentDomain.AssemblyResolve += ...;
#endif
```

I suggest adding the similar thing.

**Comment by somdoron** [comment]
@peske that is already happening, the nuget package supports .net35, .net40 and .netstandard1.6

@masaeedu I see no harm if it only project.json change, can you check and make a pull request?

**Comment by peske** [comment]
@somdoron True, but net461 is missing.

**Comment by peske** [comment]
Anyway, it'll be resolved once .NET 4.6.2 is released.

**Comment by masaeedu** [comment]
@somdoron I'll test it out. It looks like AsyncIO builds properly with `nestandard1.3`, having some issues wrestling nunit though.

@peske I don't think adding one target for every full platform is necessary or desirable. You should do this only in cases where you actually need to rely on functionality available in the full framework. In cases where the API surface supplied by `netstandard` is sufficient, you should just target that, and platform specific frameworks like full .NET or Windows phone etc. will be able to use your library just fine.

**Comment by somdoron** [comment]
@peske should net4.6.2 works with net4.0?

@masaeedu dotnet4.0 and .netstandard are not 100% equal with features...

**Comment by peske** [comment]
@masaeedu You might be right. If NetMQ does not use any of post-4.0 features - it's not needed. But as far as I know there's significant difference between .NET 4.0 and .NET 4.5.2 (especially with TPL), as big as between 3.5 and 4.0 (if not bigger).

**Comment by peske** [comment]
@somdoron Yes, it'll work with 4.0 of course. 

Sorry for spamming - I'll stop. Thanks man!

**Comment by masaeedu** [comment]
@somdoron I've PR-ed https://github.com/somdoron/AsyncIO/pull/10, need that to be published to nuget before I can do the same for netmq.

**Comment by somdoron** [comment]
Will publish later today

**Comment by somdoron** [comment]
@masaeedu pushed

**Comment by masaeedu** [comment]
@somdoron Ok, good news is it builds, bad news is one of the tests is failing: specifically `NetMQ.Tests.SocketTests.ReconnectOnRouterBug`. Not sure if it might be something to do with my machine. I'll PR anyway, see how appveyor build turns out.

**Comment by chris-ray** [comment]
I get this error on ubuntu 14.04. Works on windows.

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'kernel32.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at AsyncIO.Windows.UnsafeMethods.CreateIoCompletionPort(IntPtr fileHandle, IntPtr existingCompletionPort, IntPtr completionKey, UInt32 numberOfConcurrentThreads)
   at AsyncIO.Windows.CompletionPort..ctor()
   at AsyncIO.CompletionPort.Create()
   at NetMQ.Core.Utils.Proactor..ctor(String name)
   at NetMQ.Core.IOThread..ctor(Ctx ctx, Int32 threadId)
   at NetMQ.Core.Ctx.CreateSocket(ZmqSocketType type)
   at NetMQ.NetMQSocket..ctor(ZmqSocketType socketType, String connectionString, DefaultAction defaultAction)
   at server.Program.Main(String[] args)

Any ideas?

**Comment by somdoron** [comment]
I will check it...

**Comment by chris-ray** [comment]
thanks @somdoron . This is a digital ocean droplet. Using latest "NetMQ": "4.0.0.3-rc3".

Just tried the docker "FROM microsoft/dotnet:onbuild" and confirmed I get the same error.

**Comment by somdoron** [comment]
@chris-ray invert condition in AsyncIO, just released a new version here:

https://www.nuget.org/packages/AsyncIO/0.1.23

I will release new nuget version of NetMQ when the PR will be merged, but you can work with it now if you upgrade the AsyncIO version

**Comment by somdoron** [comment]
@chris-ray new NetMQ with latest AsyncIO:

https://www.nuget.org/packages/NetMQ/4.0.0.4-rc4

**Comment by chris-ray** [comment]
Ok that got past that one, thanks. Now I get another error "operation not supported" Can open new thread, though, if you prefer.

Unhandled Exception: NetMQ.NetMQException: Exception of type 'NetMQ.NetMQException' was thrown. ---> System.Net.Sockets.SocketException: Operation not supported
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at NetMQ.Core.Transports.Tcp.TcpListener.SetAddress(String addr)
   --- End of inner exception stack trace ---
   at NetMQ.Core.Transports.Tcp.TcpListener.SetAddress(String addr)
   at NetMQ.Core.SocketBase.Bind(String addr)
   at NetMQ.NetMQSocket..ctor(ZmqSocketType socketType, String connectionString, DefaultAction defaultAction)
   at server.Program.Main(String[] args)

**Comment by masaeedu** [comment]
@chris-ray Would be helpful to see the code to see what kind of socket you're instantiating and binding. You're right though, should open a new issue for this.

**Comment by chris-ray** [comment]
@masaeedu no problem. Opened Issue #586

**Comment by somdoron** [comment]
@chris-ray fixed here:
https://www.nuget.org/packages/NetMQ/4.0.0-rc5

**Comment by llrosa** [comment]
Reopening old thread: 
Any thoughts if NetMQ.Security is supported by .NET Core?

**Comment by slyons** [comment]
Any updates on this @somdoron ?
