### ISSUE TITLE
Track XPub subscribers by a custom ID

### ISSUE THREAD

**Issue by buybackoff** [zeromq/netmq#499]
While working with XPub and broadcast option I committed several months ago, I need a way to track identity of subscribers who send broadcast and other messages to XPub. Also, I need to add some authentication and authorization. In my fork I added a [property](https://github.com/buybackoff/netmq/blob/feature_broadcast/src/NetMQ/Msg.cs#L473) to `Msg`, which stores a custom object reference [inside automic counter](https://github.com/buybackoff/netmq/blob/feature_broadcast/src/NetMQ/Core/Utils/AtomicCounter.cs#L55) (because Msg is a struct and often passed by value, while the counter is on the heap). The overhead of this is a null pointer when the feature is not used.

But then in XPub I could [add a sender pipe as an attachment](https://github.com/buybackoff/netmq/blob/feature_broadcast/src/NetMQ/Core/Patterns/XPub.cs#L359) to a message and then use it as a key to some dictionary in my code. E.g. I could create a ConditionalWeakTable and save custom info for each subscriber, e.g. auth status.

Would you accept this or suggest another way to track subscribers identities while using XPub?

**Comment by somdoron** [comment]
I think this is hack, you can use the manual subscribing feature together with the subscriber sending the identity on every broadcast message.

Anyway if you want to make the PR I suggest some stuff:
* You don't have to save it, you can provide GetLastPipe option that return the pipe of the user send the Msg, it will make it cleaner.
* I suggest not using Pipe but integer with internal mapping.

**Comment by buybackoff** [comment]
I do not trust subscribers. On connect they must send a private-key-signed confirmation that what they say they are actually matches to a known public key. Then I assign each pipe/subscriberId a verified identity, but do not require each message to be signed after that to save on signing and message size. On subsequent messages the first frame is an identity and I compare it with the verified identity of that pipe.

I do not get your first bullet. On which object GetLastPipe should be implemented?

Pipe is used as an object type, it is not accessible outside of NetMQ. Internal mapping just adds complexity.

**Comment by somdoron** [comment]
make new NetMQ socket option, like you did with XPublisherBroadcast. On XPub everytime you get a message update the LastPipe option. 

I suggest not using the pipe but some kind of idea, you can keep the idea on the pipe like identity property. So maybe instead of LastPipe use LastSubscriberId.

to sum it up:
* Create new option called LastSubscriberId
* On pipe create new property called SubscriberId
* On xpub.XAttachPipe set the Pipe.SubscriberId
* On xpub.XRecv update the LastSubscrierId (through m_option.LastSubscriberId = pipe.SubscriberId)

I think this is it

**Comment by buybackoff** [comment]
Implemented in #514
