### ISSUE TITLE
在Xp中使用出现“无法在 DLL“kernel32.dll”中找到名为“GetQueuedCompletionStatusEx”的入口点”的错误

### ISSUE THREAD

**Issue by hdxhan** [zeromq/netmq#501]
在WinXp中使用出现“无法在 DLL“kernel32.dll”中找到名为“GetQueuedCompletionStatusEx”的入口点”的错误，库不能运行，怎么解决呢

**Comment by somdoron** [comment]
Try to compile AsyncIO from source. Someone make a commit to fix the bug.
The commit:
https://github.com/somdoron/AsyncIO/commit/5bdf1dc6ced51b8aa06a26cd3f2bb10561dbefb8

You can build from here:
https://github.com/somdoron/AsyncIO

I will also try to release a new version of asyncio soon

**Comment by drewnoakes** [comment]
Is this issue still valid? The AsyncIO code in question has been released since.
