### ISSUE TITLE
Performance enhancements

### ISSUE THREAD

**Issue by eginder** [zeromq/netmq#502]
I wanted to see if I could improve performance by using pre-allocated NetMQMessage objects and just manipulate the frames with NetMQMessage.RemoveFrame() and NetMQMesssage.Push().  I wrote a little tester and to my surprise it's actually faster to just allocate new message object than to re-use preallocated message objects (in a circular array for example) and change the payload in the frames.  What is the reason for this?  And is there any other way to speed things up?

**Comment by jwjosefy** [comment]
It may be faster, but, what about memory use?

2016-03-10 16:38 GMT-03:00 Eric Ginder <notifications@github.com>:

**Comment by drewnoakes** [comment]
Avoid allocations altogether and reuse a Msg object, passing it to the
send/receive methods by ref. You can also look into using pooled byte[]
objects, as there's some support for that.

**Comment by eginder** [comment]
**drewnoakes**:  
> _Avoid allocations altogether and reuse a Msg object, passing it to the
> send/receive methods by ref._

I actually did what you suggested but like I said, this was actually slower than just allocating new NetMQMessage objects.  The performance hit comes in when you start removing and adding frames. There is no direct way to manipulate the data inside the frames so I was removing frames and adding them back in (with new data).  Maybe an access method to directly change the bytes inside the frames would be nice....???? (not sure if this is safe to do)

**Comment by drewnoakes** [comment]
I was suggesting completely avoiding use of NetMQMessage. Did you try that?

**Comment by somdoron** [comment]
I'm with @drewnoakes, the best performance is not using multipart at all. Try to serialize everything to one buffer and user Msg directly. The question is, do you really need this performance?

**Comment by MikeFair** [comment]
@somdoron 

Perhaps a NetMQ Multipart frame can be made into an interface?

That way folks can provide a  more performant framing system (I'm thinking shared memory or zero-copy type systems that the developer writes themselves) then pass in a custom object and NetMQ can send it.  Just document what functional needs of the framework are from the class.  (Like IEnumerable; and NetMQ will destroy it (or the app has to check for the "sent" flag before destroying it; etc.)?

**Comment by drewnoakes** [comment]
Interesting idea. Can't you already achieve this using extension methods
though, backed by the ref Msg try send/receive methods?

**Comment by somdoron** [comment]
Sounds nice, as @drewnoakes said, we can have this as part as an extension, anyway I think the interface should be the following:

```csharp
interface IMultipart 
{
   bool TryGetNext(ref Msg msg);
}
```

The reason not to use IEnumerator is just for the performance of using ref instead of structure copy.

**Comment by drewnoakes** [comment]
@somdoron are you proposing making `NetMQMessage` implement `IMultipart`? Would there be any other implementations by types currently in the library?

This interface seems nice and I've started implementing it in the lib just to see how it feels.

The existing extension methods for sending `NetMQMessage` carry over well (would we have to keep the `NetMQMessage` versions too?).

Receiving custom multipart message types will require another approach. I'm wondering if we allow users to provide factories how much boilerplate would be saved. If you have any ideas it'd be good to hear them. Experimenting with that a bit now too.

**Comment by drewnoakes** [comment]
Actually looking at this a little more, `IMultipart` becomes stateful on an iterator's progress which prohibits concurrent iterations.

**Comment by somdoron** [comment]
So concurrent iteration is not going to work. Regarding receiving, I don't have a good idea here.
I'm not a big fan of the NetMQMessage or multiplart at all, so it is just a suggestion.

I do have an idea for a new receive method (a little unrelated):

```csharp
// Will use the provided buffer if large enough (or null), will create new one if not.
void ReceiveBytes(this NetMQSocket socket, ref byte[] buffer, out size)
```

So that way we can minimize the allocation and reuse one buffer.

**Comment by drewnoakes** [comment]
I actually have a custom multipart type in a project of mine. I'll experiment a little at some point, if not today.

I like that interface. Probably needs `out bool more` as well.

You have a point about multipart messages. It's a useful concept, but it can be created in user code if needed. Having it in the base library introduces too much complexity and prohibits offering thread-safe APIs with good performance. Do I remember correctly that client/server sockets don't allow multipart, or did I make that up?

**Comment by somdoron** [comment]
You are remembering correctly, and it is also thread safe

**Comment by drewnoakes** [comment]
...but we need ZMTP v3 first, right?

**Comment by somdoron** [comment]
Yes...
