### ISSUE TITLE
Problem: XPub/XSub doesn't support multi-part messages starting with 1 or 0

### ISSUE THREAD

**Issue by buybackoff** [zeromq/netmq#504]
XSub drops such frames. E.g. if I want to send an `Int64 = 0L` as a second or later frame, it is interpreted as unsubscribe.

Solution: check if the first message `hasMore` and disable the first byte [comparison](https://github.com/zeromq/netmq/blob/master/src/NetMQ/Core/Patterns/XSub.cs#L177) with 1/0 on subsequent messages, reset when  `hasMore = false` (i.e. on the last message).

We had the same issue with broadcast and added a special logic [here](https://github.com/zeromq/netmq/blob/master/src/NetMQ/Core/Patterns/XPub.cs#L170).

**Comment by somdoron** [comment]
Do you also need to fix something on the subscriber side?
Anyway until now sending multipart from xsub to xpub was kind of not supported. Anyway feel to make a PR. This actually do work on libzmq so you can take a look there.

**Comment by buybackoff** [comment]
It was very easy to fix, will send a PR later. I did it after #503 locally and need to cherry pick the changes... The pattern is similar to `m_hasMoreIn` for subscribers and `m_hasMoreOut` for publishers.
