### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by gthvidsten** [zeromq/netmq#509]
I'm trying to send a large object (~75MB) through NetMQ. The first time it is sent just fine. The second time I get an OutOfMemoryException in NetMQ.dll.

The large object is first serialized with Newtonsoft.JSON then sent using the following (simplified) code:

```
var context = NetMQContext.Create();
var serialized = Newtonsoft.JsonConvert.SerializeObject(myLargeObject);
NetMQSocket publish = context.CreatePublisherSocket();
publish.Send(serialized, Encoding.Unicode);
```

The exception occurs on the final line of code.

NetMQ version 3.3.2.2 (from NuGet)

**Comment by somdoron** [comment]
You probably exceeding .net maximum bytearray size. Try to split the
message. The exception is probably from the encoding message. Try to encode
it yourself and see if you get an exception

**Comment by gthvidsten** [comment]
The .Net maximum bytearray size is close to 2GB, so a 75MB object (even JSON serialized) should be well within the limits.
I also tried to see if the Encoding is what causes it, and it is not:

```
byte[] bytes = Encoding.Unicode.GetBytes(serialized);
publish.Send(bytes);
```

`Send(bytes)` is still throwing an OutOfMemoryException.

**Comment by drewnoakes** [comment]
Do you get a stack trace? Can you repro this with the debugger attached and break on exceptions enabled?

**Comment by gthvidsten** [comment]
No stacktrace because Visual Studio can't display additional data when it's an OutOfMemoryException.

**Comment by somdoron** [comment]
Netmq actually allocate same size buffer and copy. So I suggest using Msg
directly. Are you enabling the buffer pooling?

**Comment by gthvidsten** [comment]
How do I enable buffer pooling?
And could you give an example of using Msg?

**Comment by migelU** [comment]
IMHO you got LOH (large object heap) fragmentation. 
.NET has 2 heap  - one of them for small objects (less than ~80Kb) and Garbage collector compact it during removing 'dead' objects. Second heap never compacted by GC and so address space get fragmented. 
I reccommend you avoid using such large objects in memory  - use Stream model  and send it over network by small chunks of the data with the header described this chunk  i.e orderNo, chunk size, and EOF sign .

**Comment by drewnoakes** [comment]
Or allocate a single byte[] that's large enough to store all your messages,
and reuse it (in a threadsafe way). You can do this with the Msg class,
even if you need multi frame messages.

**Comment by somdoron** [comment]
I suggest doing the following:

```csharp
Msg msg = new Msg();
msg.InitGC( Encoding.Unicode.GetBytes(serialized));
publish.Send(ref msg);
msg.Close();
```
