### ISSUE TITLE
Intermittent failure with switching sockets

### ISSUE THREAD

**Issue by msykora** [zeromq/netmq#517]
Hello,

we are using NetMQ 3.3.2.2 and use a proprietary SASL protocol for establishing a session through a simple handshake. In order for the client to connect without knowledge  of servers socketId, for handshake client uses a dealer socket, in the last handshake message the server creates a unique sessionId and sends it to the client to use as socket identity (it also sends its socket id). The client then disposes the dealer socket, creates a router socket with the sessionId identity, and sends all further messages to the server via this router socket, while the server expects messages only from that sessionId socket for the remainder of the session.
This is all nice, except that we get intermittent errors where the first message from the router socket comes to the server with the wrong 1st frame, an unknown identity. I debugged this VERY thoroughly before writing here, and I am very certain the message is sent from the new client router socket and it has the right identity, but the server receives a message with the old identity in the 1st frame, the only conclusion that is left is a race condition bug in NetMQ. This problem happens rarely, sometimes once out of 20 or more sessions, that's the worst part, it's not easily reproducible, and I spent all of today trying to reproduce it with bare sockets, so I can give you example code to demonstrate it, in vain... Can you imagine a bug in the server socket where a message comes from the same IP but a different socket with a different identity, but it somehow still gets attributed to the old identity?

Thank you,
Martin

**Comment by msykora** [comment]
Actually, this seems to be sporadically happening even between our NetMQ client and the JeroMQ server, so I think the bug could be on the client socket side... From my log it's clear that I created the new router socket with the correct identity, but when I send a message from it,what is received on the server doesn't correspond, the first frame is not my client socket id but the id of the older, now disposed dealer socket... As said, it's very intermittent, I wish I could provide easy sample code to demonstrate...

**Comment by somdoron** [comment]
By any chance do you set the identity after calling connect?

**Comment by somdoron** [comment]
Also can you provide the code you are using right now?

**Comment by msykora** [comment]
Yes, I am setting it after connect, so that can cause some race condition? It won't be a problem for me to set it before, I will try that, thank you!
As for code, unfortunately it's our production code I can't post it, I was trying to put together an example with bare NetMQSockets where it can be replicated, but it proved really hard...

**Comment by somdoron** [comment]
Anyway, I think it will work consistently if you set the identity before the connect.

**Comment by msykora** [comment]
Yes, I can't reproduce it anymore when I set identity before connecting, thank you!
