### ISSUE TITLE
Linger default is 0 vs ZeroMQ's -1

### ISSUE THREAD

**Issue by buybackoff** [zeromq/netmq#518]
This [page](http://api.zeromq.org/2-1:zmq-setsockopt) and the [guide](http://zguide.zeromq.org/page:all) say that the default linger value is infinite, while in NetMQ the default is zero 0. Given that ZeroMQ documentation is the source of truth and the only detailed documentation available (NetMQ's [tells nothing](https://readthedocs.org//search/?q=linger&check_keywords=yes&area=default&project=netmq&version=latest&type=file) about the linger option), it was a surprise to find it as zero after some very weird bugs on clients disconnect.

Should we set the default to infinity as in ZeroMQ?

Update: my bugs didn't disappear after explicit linger option. But in general, shouldn't all defaults and API match the guide? And the only differences be specific to NetMQ?

**Comment by somdoron** [comment]
It is actually changed on version 4, so anything you are creating from Context will use infinity and anything you are using without a socket (ctor directly) is using 0. We should update the docs as well.

**Comment by buybackoff** [comment]
Is this in line with ZMQ upstream master? Because The Guide is called *The* for a reason.

**Comment by somdoron** [comment]
Kind of, CZMQ also changed the default linger to zero.

**Comment by buybackoff** [comment]
Nice, then this is not an issue.
