### ISSUE TITLE
Upgrade build to use Visual Studio 2014

### ISSUE THREAD

**Issue by pcalin** [zeromq/netmq#520]
It would be nice to be able to use C# 6 syntax.

**Comment by somdoron** [comment]
Do you mean inside NetQM code? I don't see a reason why not.

**Comment by drewnoakes** [comment]
I made a PR for this eight months ago (#366), but at the time C# 6 was considered too new and that it might make it too hard for people to contribute to the project.

That PR doesn't merge any more, but I'm happy to run the same operations through R# to migrate the project.

**Comment by pcalin** [comment]
I accidentally pushed some C# 6 code with my last PR and build failed. I had to roll back the C# 6 code. Hence why my point is about the build process not being able to build C# 6 code. 

It would be nice if we can
