### ISSUE TITLE
System.Net.Sockets.SocketException "A non-blocking socket operation could not be completed immediately" / Socket error code 10035

### ISSUE THREAD

**Issue by general-tycoon** [zeromq/netmq#525]
Occasionally, during a deployment of our infrastructure (which consists of a bunch of windows services all talking to each other with NetMQ SecureChannel) we get the following error:

```
System.Net.Sockets.SocketException

A non-blocking socket operation could not be completed immediately
  at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at NetMQ.Core.Mailbox.TryRecv(Int32 timeout, Command& command)
   at NetMQ.Core.SocketBase.ProcessCommands(Int32 timeout, Boolean throttle)
   at NetMQ.Core.SocketBase.GetSocketOptionX(ZmqSocketOption option)
   at NetMQ.NetMQSocket.GetSocketOptionX[T](ZmqSocketOption option)
   at NetMQ.NetMQSocket.get_HasIn()
```

The SocketException error code is `10035` which appears to be:

> Resource temporarily unavailable.
> This error is returned from operations on nonblocking sockets that cannot be completed immediately, for example recv when no data is queued to be read from the socket. It is a nonfatal error, and the operation should be retried later. It is normal for WSAEWOULDBLOCK to be reported as the result from calling connect on a nonblocking SOCK_STREAM socket, since some time must elapse for the connection to be established.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx

I'm using 3.3.2.4-beta. I don't see a change to this area in v4.

Thoughts?

**Comment by somdoron** [comment]
Any chance you are using the socket from multiple threads? it seems like a race condition.

Even if you wrap the socket with lock it doesn't help if you are using it within a poller (which is not locking the socket when accessing). Also if you add the socket to poller you cannot change it not from the poller thread.

**Comment by general-tycoon** [comment]
Yup, I think that was the problem. In my recent refactor to use SecureChannel I missed a couple spots and wasn't using the Scheduler in all places. 

Should have known. Thanks.
