### ISSUE TITLE
Client/Server Socket  Types

### ISSUE THREAD

**Issue by Farzammolkara** [zeromq/netmq#527]
Dear contributors,
I'm using ZeroMQ in an MMO game project. We've just finished implementing the first prototypes in console application and we used Client/Server Socket types. To use the codes in the client (which uses unity3d) we decided to use the netmq as it supports the .Net 3.5.
Unfortunately I've found that the new socket types(client/server) has not been implemented in the netmq yet.
Kindly, could you tell me if there is a plan to add them to the library and what is your suggestion for me in the current situation? Should I switch to other socket types?

Thank you guys all for the great effort,
Farzam

**Comment by somdoron** [comment]
It great to hear you are using the Server/Client framework.

To implement client/server in NetMQ we first have to implement ZMTP v3, I don't think it will happen in the near future.

**Comment by optimus-code** [comment]
Hey, I was just wondering since its 4 years on whether we are any further along with this? The Client/Server socket types would be ideal for my use case.

**Comment by somdoron** [comment]
Good timing, yes, we gave client server. Although it is still not on nuget. Will releasebit as prerelease tomorrow
