### ISSUE TITLE
Exception when bind fails and monitor is attached

### ISSUE THREAD

**Issue by igvk** [zeromq/netmq#528]
If we create a socket and attach a monitor to it, and then bind fails (in this example due to port already in use), we get a null reference exception in MonitorEvent.Write() due to m_addr == null.
Example code:

                using (NetMQSocket netServerSocket = new ResponseSocket())
                using (NetMQSocket netPublisherSocket = new PublisherSocket())
                using (NetMQPoller netServerPoller = new NetMQPoller { netServerSocket, netPublisherSocket })
                using (NetMQMonitor netServerMonitor = new NetMQMonitor(netServerSocket, "inproc://srv.inproc", SocketEvents.All))
                using (NetMQMonitor netPublisherMonitor = new NetMQMonitor(netPublisherSocket, "inproc://pub.inproc", SocketEvents.All))
                {
                    netServerSocket.ReceiveReady += NetServerReceive;
                    netServerSocket.ReceiveReady += NetPublisherReceive;
                    netServerMonitor.BindFailed += NetServerMonitorBindFailed;
                    netServerMonitor.AttachToPoller(netServerPoller);
                    netPublisherMonitor.BindFailed += NetPublisherMonitorBindFailed;
                    netPublisherMonitor.AttachToPoller(netServerPoller);
                    netServerSocket.Bind("tcp://localhost:10000");
                    netPublisherSocket.Bind("tcp://localhost:10000");
                    netServerPoller.Run();
                }
`

**Comment by somdoron** [comment]
Do you want to provide a pull request to fix this?

**Comment by igvk** [comment]
I didn't yet look at fixing this.

**Comment by igvk** [comment]
The proposed solution is simply checking m_addr for null.
Here is the diff:
```
--- MonitorEvent.cs.orig
+++ MonitorEvent.cs
@@ -65,7 +65,7 @@
 
         public void Write([NotNull] SocketBase s)
         {
-            int size = 4 + 1 + m_addr.Length + 1; // event + len(addr) + addr + flag
+            int size = 4 + 1 + (m_addr?.Length ?? 0) + 1; // event + len(addr) + addr + flag
 
             if (m_flag == ValueInteger)
                 size += 4;
@@ -77,12 +77,16 @@
             ByteArraySegment buffer = new byte[size];
             buffer.PutInteger(Endianness.Little, (int)m_monitorEvent, pos);
             pos += 4;
-            buffer[pos++] = (byte)m_addr.Length;
 
-            // was not here originally
+            if (m_addr != null)
+            {
+                buffer[pos++] = (byte)m_addr.Length;
+
+                // was not here originally
 
-            buffer.PutString(m_addr, pos);
-            pos += m_addr.Length;
+                buffer.PutString(m_addr, pos);
+                pos += m_addr.Length;
+            }
 
             buffer[pos++] = ((byte)m_flag);
             if (m_flag == ValueInteger)
```
