### ISSUE TITLE
Could not load file or assembly 'AsyncIO

### ISSUE THREAD

**Issue by nathvi** [zeromq/netmq#530]
Not sure if this is an internal issue with the codebase, but here's what's happening. 

I had some code :
SubSocket = context.CreateSubscriberSocket();

That was working. Now when I pull latest from NuGet, I get this error.

"NetMQ.dll

Additional information: Could not load file or assembly 'AsyncIO, Version=0.1.18.0, Culture=neutral, PublicKeyToken=44a94435bd6f33f8' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

I tried manually installing the AsyncIO NuGet package, but I keep getting this error. Any suggestions?

**Comment by drewnoakes** [comment]
Probably an internal error. Maybe you're using different versions of NetMQ in different referenced assemblies. At any rate, this is a dynamic linker problem, and that's much more likely down to your environment rather than some aspect of the code or package. What version of NetMQ are you using? Can you give the contents of your `packages.config` file?

**Comment by nathvi** [comment]
When I go to the NuGet package manager, it shows NetMQ Installed as 3.3.2.2,
and installed as 3.3.2.1.

AsyncIO Installed is 0.1.18 and version is 0.1.17.

Here's the packages.config file:

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AsyncIO" version="0.1.18.0" targetFramework="net452" />
  <package id="NetMQ" version="3.3.2.2" targetFramework="net452" />
</packages>

**Comment by nathvi** [comment]
I uninstalled netmq nuget package, as well as the asynchio package in two of my projects, and re downloaded them. the packages.config files are showing this as the package.config file:
[packages.txt](https://github.com/zeromq/netmq/files/231840/packages.txt)

As you can see the asynchio is not version 0.1.18.0. And I'm getting the same runtime error. 

"Additional information: Could not load file or assembly 'AsyncIO, Version=0.1.18.0, Culture=neutral, PublicKeyToken=44a94435bd6f33f8' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

**Comment by nathvi** [comment]
I had to manually update the asynchio package, and now everything works fine. Still needs to be fixed on the NetMQ's side of the NuGet package managment side, but this is a quick fix.

**Comment by awb99** [comment]
I am using Nuget to get NetMQ reference. And I also have the same issue.

Basicylly the current NetMQ needs AsyncIO 0.1.25.0 but the automatically fetched AsyncIO
library form Nuget is currently 0.1.61.0. This breaks the DLL bindings. I should not break
it, as this is still the same major version.

I tried fixing it via this app.config setting (but it did not work).

```
	<runtime>
		<assemblyBinding>
			<dependentAssembly>
				<assemblyIdentity name="AsyncIO" publicKeyToken="44a94435bd6f33f8" culture="neutral" />
				<bindingRedirect oldVersion="0.1.25.0" newVersion="0.1.61.0" />
			</dependentAssembly>
		</assemblyBinding>
	</runtime>
```	

The issue should be reopened.
