### ISSUE TITLE
Make original NetMQSocket available in NetMQMonitorSocketEventArgs

### ISSUE THREAD

**Issue by igvk** [zeromq/netmq#531]
Why not make original socket, passed to NetMQMonitor.Handle() also available in NetMQMonitorSocketEventArgs?
This way, it would be possible to use it, e.g. possibly sending messages based on connect events.

**Comment by somdoron** [comment]
I think the sender is the NetMQSocket.

But anyway, it doesn't break anything so feel free to make a PR

**Comment by igvk** [comment]
The sender is socket of NetMQMonitor, not the original socket that is monitored.
There are also other usability issues with NetMQMonitor - for example, it's possible to know what endpoint is connected, but impossible to get any such info on disconnection, because the socket is already disconnected.
