### ISSUE TITLE
Using ip address does not work to bind publisher. Using "localhost" does work to bind publisher.

### ISSUE THREAD

**Issue by nathvi** [zeromq/netmq#534]
Right now I'm creating a publisher wrapper class, whose constructor looks like this:
[Publisher.txt](https://github.com/zeromq/netmq/files/235331/Publisher.txt)

I have a subscriber that is listening on my computer, and when I call the constructor like so:
Publisher publisher = new Publisher(context, publisherPort, "localhost", 1000, errorLogger, infoLogger);

Everything works fine. however, when I change the call to include my ip address instead of "localhost" I get nothing back from the subscriber when I send something from the publisher.... any thoughts?

**Comment by drewnoakes** [comment]
Can you bind to 127.0.0.1?

**Comment by somdoron** [comment]
It seems you are confusing connect and bind, so if you bind the publisher you need to connect the subscriber to the publisher address.

You can also do it the other way around, just bind on the subscriber and connect on publisher.

**Comment by nathvi** [comment]
I'm still not understanding... Sorry. I am binding on the publisher, and connecting on the subscriber.
My method calls only work if I have "localhost" instead of my real ip. Is this even possible?

**Comment by somdoron** [comment]
When binding you can use. Localhost/*/any interface ip.

When connecting you should use the ip of the bound machine.

**Comment by nathvi** [comment]
@somdoron, When I construct the publisher in that fashion I get an error:

"An unhandled exception of type 'System.Net.Sockets.SocketException' occurred in System.dll
Additional information: No such host is known"


I'm calling the code like this.
Publisher publisher = new Publisher(context, 12345, "Localhost/*/10.10.10.424", 1000, errorLogger, infoLogger);

The ip I posted isn't my real ip.

**Comment by somdoron** [comment]
Not all the string, the slash was just to show the option.

Try to put only * or only the ip.

The ip have to be the ip of ghe machine the code is running on.

**Comment by nathvi** [comment]
using just the * inside the string works. Using just the ip address, does not work, when instantiating the publisher object.

**Comment by somdoron** [comment]
Are you sure it is the ip address of the machine the code running on? Is it
ethernet of wifi? Does the network connected?

**Comment by somdoron** [comment]
By the way of you are binding on interface ip you also have to connect to that ip and cannot use localhost

**Comment by nathvi** [comment]
@somdoron, That was it! I was using "localhost" when connecting on my subscriber, and using the literal ip address when binding my publisher! Thank you so much!
