### ISSUE TITLE
Can't create NetMQQueue type.

### ISSUE THREAD

**Issue by nathvi** [zeromq/netmq#537]
I've tried creating the type "NetMQQueue<T>" to no avail. I'm able to create NetMQContext and other types fine. I decompiled the NetMQ .dll, and still wasn't able to find it. What am I doing wrong here? 

The motivation to create a NetMQQueue<T> came from the read the docs. 
http://netmq.readthedocs.org/en/latest/queue/

**Comment by somdoron** [comment]
Which version? What exveption? Compilation? Can you upload code?

**Comment by nathvi** [comment]
I'm running version 3.3.2.2. Which is the latest stable from NuGet I think.
The code I used was just a simple pub sub, and then attempted to create a NetMQQueue  via someting like:
NetMQQueue  queue = new ....

And VS didn't show that NetMQQueue was a valid datatype. I'm thinking the version I'm running doesn't have this type, as I have already decompiled the source dll, and found nothing inside the source with this datatype.

**Comment by somdoron** [comment]
Yes, try to use one of the prerelease, I will release new version tomorrow

**Comment by nathvi** [comment]
Shouldn't the documentation be updated, or at least indicate what version of NetMQ is being used? This can be very confusing if this information is not provided when trying to look at examples. Maybe there is some indication of version, but I didn't see any.

**Comment by somdoron** [comment]
It should, there is no indication right now regarding which version the doc are for. However I think it is a lot to manage. Can you think of automate solution?

**Comment by nathvi** [comment]
I would just require all examples to indicate what version of NetMQ it was run against before accepting them into the main project.

**Comment by somdoron** [comment]
@nathvi I released yesterday a new stable version which include the NetMQQueue

**Comment by nathvi** [comment]
Thanks! I'll close this issue, since I know what the specific problem was. General documentation will probably have to be discussed another time :)
