### ISSUE TITLE
c# side 'bind' throws exception when python side has a socket open and is trying to send

### ISSUE THREAD

**Issue by djmarcus1** [zeromq/netmq#538]
I have a C# server and a python client.

The simple sequence that fails:

[1] I start the C# server; bind works
[2] I start the client. It connects to server (on same machine)
[3] Client repeatedly performs this every 10 seconds

[3.a] Create context
[3.b] Create a REQ socket using the newly created context
[3.c] send() a simple string to server
[3.d] recv() a response
[3.e] close(linger=NONE) the socket
[3.f] term() the context

After I verify that this works for a while, I intentionally kill the server process.

I wait a few seconds (yes, I even tried waiting 20 minutes).
I then restart the server.

Now, the server throws an exception trying to 'bind' to the same port that worked before:

```
NetMQ.NetMQException with underlying socket error
   at AsyncIO.Windows.Socket.Bind(IPEndPoint localEndPoint)
   at NetMQ.Core.Transports.Tcp.TcpListener.SetAddress(String addr)
```

My guess is that the client is hanging on the 'send' (since the server went away). This must keep something in Windows about the port to say that it is in-use (because of the client).

If I kill the client process, the server process works the next time I restart it.

I thought that the server client starting sequence didn't matter.

To be honest I can't tell if this is a ZMQ python issue, a Net ZMQ problem or a general ZMQ problem.

Perhaps the solution is to do (on the client side) a send() and recv() with a timeout and if a timeout is detected, continue with close socket, and term() context.

Any ideas how to do that? Or how to otherwise solve my problem?

-Thanks in advance
David

**Comment by somdoron** [comment]
I'm not sure it is related to the client. When you restart the server, you mean the process? any chance the process is hanging and doesn't really closed?

Did you dispose the server socket server when the application exit?

Can you include the code of the server?

**Comment by djmarcus1** [comment]
The client process is a separate window process (running my python script). When I kill it (using Windows Task Manager, or click on the red-x on the top corner of the cmd window) it goes away completely.

Until I kill the client process, each time I try to bring up the server side (C# process, it dies at the attempt to bind to the port). I can do this any number of times, the result is the same... the bind fails.

However, as soon as I kill the python process (the client) and it goes away, the next time I bring up the C# side the bind to the port succeeds.

So it appears as if the client is holding on to something that prevents the server from binding.
