### ISSUE TITLE
Using InProc address

### ISSUE THREAD

**Issue by thierry-github** [zeromq/netmq#540]
Hi, working with .NET 4.5.2, NetMQ 4.0.0.0 

i' m trying to do build a RPC style messaging application.
On the server side (workers) i'm facing an issue when trying to connect a **QueueDevice ** instance wich uses an inproc address  (inproc://workers) as backendBindAddress.(DeviceMode.Threaded)

Creating  queueDevice works fine but when i try to connect a worker using DealerSocket i get the following Exception : NetMQ.EndPointNotFoundException.

On client side, i use RequestSocket connected to RouterSocket (for loadbalancing). Client are connected to router with InProc address and it works fine.

is this an issue or the case is just not supported ?

Thanks.

**Comment by somdoron** [comment]
can you make minimal code that reproduce?
