### ISSUE TITLE
Links broken in netmq\docs\introduction.md

### ISSUE THREAD

**Issue by opedroso** [zeromq/netmq#546]
Links like "[receiving and sending](receiving-sending)", "[request-response](request-response)", "[Message](message)", "[**Request-reply**](request-response)","[**Pub-sub**](pub-sub)" go to github.com 404 page when clicked on.
The generated link seems to be missing ".md".

**Comment by somdoron** [comment]
can you send a PR?

**Comment by opedroso** [comment]
Rechecked today and the links have been fixed.

**Comment by opedroso** [comment]
Hi Doron,

I filed that issue back on May 6.
Seems like somebody has fixed those links already, since I tried them today
and they are fine.

I closed the issue.
Osiris
