### ISSUE TITLE
pub-sub pattern: subscriber receives invalid data

### ISSUE THREAD

**Issue by greendimka** [zeromq/netmq#551]
NetMQ Version: 3.3.3.1

I have created a very simple server (PublisherSocket), which in a loop sends out current time's milliseconds as string via SendFrame.
And also created a very simple client (SubscriberSocket), it receives frames and prints them out through logger.

But there is a **bug**. The first message received by client is different from what the server has sent. You can see it in attached image:

![netmq bug](https://cloud.githubusercontent.com/assets/2776617/15355222/c1ddc1da-1cf1-11e6-85e3-9e3684f892c9.png)

In attached file ([DemoServerAndClient.zip](https://github.com/zeromq/netmq/files/270164/DemoServerAndClient.zip)) you will find a server and a client code (both in VB) which demonstrate how everything is coded. If you want to use the code in projects to run it, add NLog reference to your projects.

**Comment by greendimka** [comment]
Just for the sake: after making a scrrenshot I have tried to run my code several times more - client always receives first message not as it was sent from server.

**Comment by iiwaasnet** [comment]
I have a question:

```
msg = Now.Millisecond
Log.Info("Publishing '{0}'...", msg)
pub.SendMoreFrame("x").SendFrame(Now.Millisecond) << why not the msg???
Log.Info("[OK] Published '{0}'.", msg)
```

**Comment by greendimka** [comment]
Ooops, maybe this is a source of a problem. Let me check it.

**Comment by greendimka** [comment]
Yes, yes, this was the source of the problem.
Ahhhh, sorry for taking your time on such a stupid bug :)
