### ISSUE TITLE
The bus sample does not compile

### ISSUE THREAD

**Issue by mabra** [zeromq/netmq#552]
Hi !

There are two wrong statements - at least, after I made them to appear like I thought, it works :-)
line31 must be: >Address = $"tcp://{name}:{port}";<
line 59 must be: >return ((Name != null ? Name.GetHashCode() : 0) \* 397) ^ Port;<
Additionally, there are two unrelated $ characters in the file - easy to remove.
But the latter was the reason, why I have not updated the source - might be,
there are some generators at work ??

Hope, this helps.
And thanks for the goot example !!!

Manfred

**Comment by somdoron** [comment]
No, just send a pull request

**Comment by mabra** [comment]
Ok - done.
 
br++Manfred

**Comment by somdoron** [comment]
I dont see a PR yet

**Comment by mabra** [comment]
Hi !
 
I've never made a pull-request on github - just don't know.
This was another reason, I created an issue. Would probably
help, if I get a little help here ...
 
My change is this:
 
https://github.com/zeromq/netmq/compare/master...mabra:patch-1?expand=1
 
br++Manfred

**Comment by dalebrubaker** [comment]
FYI, this change is just reverting some C# 6.0 stuff which compiles in Visual Studio 2015. No objection, of course, but hopefully most people will soon migrate. :)

**Comment by drewnoakes** [comment]
@mabra much of the code in the solution uses C# 6 language features. For the most part, they're easy to downgrade to earlier versions of the language, as see in your PR.

Most importantly the compiled libraries available on NuGet all work with .NET Framework versions 3.5 and later.

**Comment by drewnoakes** [comment]
As C# 6 has been out for nearly two years now, I'll close this. 

If the consensus is that we should use earlier versions of C# in sample code, we can reopen this.
