### ISSUE TITLE
Unhandled exception in NetMQ.Core.Transports.TcpListener.InCompleted

### ISSUE THREAD

**Issue by woj-b** [zeromq/netmq#557]
Hi,

I'm using a router->dealer socket set-up for a multithreaded RPC server - not been able to reproduce the problem every time, but getting the above exception multiple times a day, using version 3.3.3.1. 

Also - are PDB files for the dlls published anywhere?

Cheers

**Comment by somdoron** [comment]
Can you compile from latest code and try? the repository for 3.3.3.1 is here:

https://github.com/NetMQ/NetMQ3-x

You would also be able to include the pdb.
