### ISSUE TITLE
ReceiveReady was not fired for StreamSocket

### ISSUE THREAD

**Issue by wmjordan** [zeromq/netmq#559]
I was trying to develop asynchronous socket application.
I attempt to use the `ReceiveReady` event, but it was never fired.
Is it a bug or is there any workaround for this?

``` csharp
var q = new StreamSocket("@tcp://localhost:10000");
q.ReceiveReady += (s, a) => {
    Console.WriteLine("some data received.");
};
```

**Comment by somdoron** [comment]
what do you have on the other side?

**Comment by wmjordan** [comment]
The other side was also a `StreamSocket`, sending raw TCP data packets.
It seemed that the `ReceiveReady` event would be fired only for ZeroMQ protocol but not for raw TCP data.

**Comment by MikaelFerland** [comment]
@wmjordan Do you have something like this somewhere?
` var q = new StreamSocket("@tcp://localhost:10000");`
 `var poll = new NetMQPoller();`
 `poll.Add(q);`
 `poll.RunAsync();`

**Comment by wmjordan** [comment]
@MikaelFerland Yep, I had that type of code.

**Comment by generik0** [comment]
Any update on this. I am having the same issue with a Router

**Comment by somdoron** [comment]
@generik0 I think it is a different issue. In your case you didn't attach the router to a poller.
