### ISSUE TITLE
NetMQ Exception of type TooManyOpenSockets

### ISSUE THREAD

**Issue by eleran** [zeromq/netmq#560]
Hi,

I'm getting exception of too many open sockets when i try to create RequestSocket object.
I have pool of RequestSocket as ready objects for use. When all of them are in use i create new object and dispose when done.
On high volume of requests, i get this exception in Ctx.cs file in CreateSocket method.
I have noticed that default max socket is set to 1024,
Why am i getting this exception and is it safe to increase the default?
How can i increase the default without recompile the library?

Thanks.

**Comment by somdoron** [comment]
You can set the MaxSockets in NetMQConfig or NetMQContext. Make sure you do it before creating any sockets.
