### ISSUE TITLE
Error in NetMQ.3.3.2.2 Bind(string addr) call

### ISSUE THREAD

**Issue by nathvi** [zeromq/netmq#563]
I have a Publisher wrapper, that I included in the attached file. 
[Publisher.txt](https://github.com/zeromq/netmq/files/321081/Publisher.txt)

When I try and make a new instance of this object, I get an error when executing the line in the constructor:
PubSocket.Bind("tcp://" + ipToPublishTo + ":" + PortToPublishOn);

I get the very... specific error... 
{"Exception of type 'NetMQ.NetMQException' was thrown."}

I traced into the NetMQ code, and method signature is:
public void Bind(string addr)
where addr value = "tcp://10.10.10.121:12345"

The exception is being thrown on this bit of code:
try
                {
                    listener.SetAddress(str2);
                    this.m_port = listener.Port;
                    addr = $"tcp://{str2.Substring(0, str2.IndexOf(':'))}:{this.m_port}";
                }

when control tries to execute the listener.SetAddress(str2); line.

Am I missing anything here?

**Comment by somdoron** [comment]
are you sure the 10.10.10.121 ip address is a local ip address?
Can you try * instead?
