### ISSUE TITLE
Sending messages "Full speed" on a DEALER gives several errors

### ISSUE THREAD

**Issue by joaoantunes** [zeromq/netmq#566]
This is one of the errors that occur when I try to send a lot of messages on a DEALER and receive "at the time" (using a poller socket).  
![tryrecvassert](https://cloud.githubusercontent.com/assets/224836/16301527/b87a28a0-393d-11e6-8786-48be987094a6.png)

I've made a simple code to replicate this issue.
If I put a sleep between each Send, I don't get any errors.
The error sometimes is different and doesn't occur at "TryRecv"

Here is the code: 

```
public class Program
{
    private static SemaphoreSlim semaphore = new SemaphoreSlim(1);

    static void Main(string[] args)
    {
        const string hostAddress = "tcp://localhost:5555";
        var timeOut = TimeSpan.FromMilliseconds(5000);
        var msgToSend = 5000;
        var msgReceived = 0;

        var request = new NetMQMessage();
        request.Push("teste");      // request
        request.Push("XPTO");       // serviceName
        request.Push("MDPC01");     // client version
        request.PushEmptyFrame();   // to emulate a REQ

        using (var poller = new NetMQPoller())
        using (var broker = new RouterSocket())
        using (var client = new DealerSocket(hostAddress))
        {
            broker.Bind(hostAddress);
            broker.ReceiveReady += (s, e) =>
            {
                var msg = e.Socket.ReceiveMultipartMessage();
                if (msg.FrameCount != 5)
                    throw new Exception("Message with wrong frames");

                e.Socket.SendMultipartMessage(msg); // echo!
            };

            var timer = new NetMQTimer(timeOut);
            timer.Elapsed += (s, e) =>
            {
                Console.WriteLine("Timeout!");
                semaphore.Release();
            };

            client.ReceiveReady += (s, e) =>
            {
                timer.EnableAndReset();

                var received = e.Socket.ReceiveMultipartMessage();
                msgReceived++;
            };

            poller.Add(timer);
            poller.Add(broker);
            poller.Add(client);
            poller.RunAsync();

            for (int i = 0; i < msgToSend; i++)
            {
                client.SendMultipartMessage(request);
                //Thread.Sleep(5); // No error will occur if sleep between messages exists, but doesn't make sense to use this
            }

            semaphore.Wait(); // If no messages are received during "timeOut" period, then it will resume!
            Console.WriteLine($"Messages received: {msgReceived}");
            Console.ReadLine();
        }
    }
```

Am I doing something wrong? Is this the correct way to Send & Receive, "at the same time", on a DEALER socket?

**Comment by joaoantunes** [comment]
I've been trying different ways in order to not get those error messages.

So instead of sending the message immediately, I put all the "outgoing requests" into a buffer and wait for **SendReady** to be called.
When the **SendReady** event is called, I try to send all the requests that I can, until one fails. I tracked the ones that were not sent and I only try to send them later whenever **SendReady** event is called again. To send the messages I've used the  **TrySendMultipartMessage** instead of **SendMultipartMessage**. 

This seems to solve the issues that I was getting before! :)

Not sure if this has something to do with SendHighWaterMark & ReceiveHighWaterMark, but I tried to change those values during the tests and the results were similar.

I only wonder if this is the right approach or there is a simpler way to achieve the same result.

Here is the code example:

         static void Main(string[] args)
         {
            const string hostAddress = "tcp://localhost:5555";
            var timeOut = TimeSpan.FromMilliseconds(5000);
            var msgToSend = 100000;
            var msgReceived = 0;
            var msgSent = 0;
            var outGoingRequests = new List<NetMQMessage>();

            var request = new NetMQMessage();
            request.Push("teste");      // request
            request.Push("XPTO");       // serviceName
            request.Push("MDPC01");     // client version
            request.PushEmptyFrame();   // to emulate a REQ

            using (var poller = new NetMQPoller())
            using (var broker = new RouterSocket())
            using (var client = new DealerSocket(hostAddress))
            {
                Console.WriteLine($"Expected messages to be received: {msgToSend}");

                broker.Bind(hostAddress);
                broker.ReceiveReady += (s, e) =>
                {
                    var msg = e.Socket.ReceiveMultipartMessage();
                    if (msg.FrameCount != 5)
                        throw new Exception("Message with wrong frames");

                    e.Socket.SendMultipartMessage(msg); // echo!
                };

                var timer = new NetMQTimer(timeOut);
                timer.Elapsed += (s, e) =>
                {
                    Console.WriteLine($"Messages sent: {msgSent}");
                    Console.WriteLine($"Messages received: {msgReceived}");
                    var messagesLeftToReceive = msgToSend - msgReceived;
                    if (messagesLeftToReceive == 0)
                    {
                        Console.WriteLine($"All {msgToSend} messages were received");
                    }
                    else
                    {
                        Console.WriteLine($"Messages to receive left : {messagesLeftToReceive}");
                    }
                };

                client.ReceiveReady += (s, e) =>
                {
                    var received = e.Socket.ReceiveMultipartMessage();
                    msgReceived++;
                };

                client.SendReady += (s, e) =>
                {
                    if (outGoingRequests != null && outGoingRequests.Count > 0)
                    {
                        var nItemsToRemove = 0;
                        foreach (var item in outGoingRequests)
                        {
                            if (!e.Socket.TrySendMultipartMessage(item))
                            {
                                // Message was not sent for some reason... 
                                // so I need to wait for another SendReady signal! 
                                break; 
                            }
                            nItemsToRemove++;
                            msgSent++;
                        }
                        outGoingRequests.RemoveRange(0, nItemsToRemove);
                    }
                };

                for (int i = 0; i < msgToSend; i++)
                {
                    outGoingRequests.Add(request);
                }

                poller.Add(timer);
                poller.Add(broker);
                poller.Add(client);
                poller.RunAsync();

                Console.ReadLine();
            }
        }

**Comment by somdoron** [comment]
I'm not sure about this,  it is nice usage of the send ready though.

The watermark is there to protect you against eating all your memory, you
just bypass thw protection, if you don't care about this protection just
disable the send highwater mark (set to zero).  You can also increase it to
a sense number.

**Comment by joaoantunes** [comment]
Do you know any alternatives to send messages on a **Dealer** whenever is possible without getting "asserts"? 

It is the wanted behavior to have those asserts if I'm only polling for receiving and sending on a **Dealer** ?

**Comment by somdoron** [comment]
The thing is, what behavior do you want your system to do when you are sending too much messages, following are the available behaviors:

1. Drop the new messages - Just use TrySend
2. Block until can send again - Call the Blocking Send
3. Queue all messages - Set the SendHighwatermark to zero

You need to pick the behavior that suits you, I usually suggest one of the first two, preferably the first. But it  is up to you.

What you used before is the third option, you just queue everything on a queue outside of NetMQ, but you can just also queue it on NetMQ with SendHighwatermark set to zero

**Comment by joaoantunes** [comment]
Option 2 seems to be the more appropriate.

I've started using the option "2." in the first example, since I don't want to queue outside of NetMQ, when there is a pre-build system on NetMQ for that.

The problem is that using that option, **TryRecv** gives asserts that crash the application, as you can see in the image. If you run the code sample you can check it. Sometimes it gives others errors, so it seems option 2 is not working properly.

**Comment by somdoron** [comment]
Sorry,  missed the assert,  any chance you are using the socket from multiple threads?  Maybe sending from one thread and receiving on another?

**Comment by somdoron** [comment]
So in your example the client is sending from the main thread but receiving on the poller thread, that is not supported

**Comment by joaoantunes** [comment]
Ok cool thanks for that tip :). Didn't knew it was on a different socket.

Now I have a similar problem because I'm not disposing the socket on the same poller thread.
What is the best approach to achieve it? Do you have any examples?

So first:
