### ISSUE TITLE
Foreground thread created by NetMQPollar

### ISSUE THREAD

**Issue by sjaini44u** [zeromq/netmq#568]
Even after killing my application , i see a foreground thread is running of my app.
In NetMQPollar, i see RunAsync method starts polling by creating new Thread in way :-
new Thread("NetMQPollar")   :- This creates foreground thread . 
Need to set isbackground property for this thread. This is kind of bug.

**Comment by drewnoakes** [comment]
Sounds like you're not tearing down your resources properly. Be sure to dispose all `IDisposable` NetMQ types in the reverse order they're created.

I don't think changing the threads to have `IsBackground = true` is a good idea. Just clean up properly so things can shut down cleanly.
