### ISSUE TITLE
Allow beacon ReceiveReady handler to be registered after beacon is added to poller

### ISSUE THREAD

**Issue by masaeedu** [zeromq/netmq#571]
### Environment

```
NetMQ Version: 4.0.0-beta
Operating System: Win 8 x64
.NET Version: .NET 4.6.1
```
### Expected behaviour

A ReceiveReady handler registered on a NetMQBeacon should work correctly even if it is registered after the NetMQBeacon has been added to a poller.
### Actual behaviour

The handler is never fired (even though you can receive beacon messages using the blocking `Receive` method).
### Steps to reproduce the behaviour
1. Instantiate a NetMQBeacon
2. Instantiate a NetMQPoller and add the beacon to the poller
3. Start the NetMQPoller
4. Add an event handler to the beacon's ReceiveReady event handler list
### Additional info

Other socket types work correctly if a ReceiveReady handler is attached after the socket is added to a poller. From what I can make of the source code this is due to each socket type's implementation of EventsChanged.

If you instantiate a NetMQBeacon however, and add it to a poller _before_ registering an event handler,  the event handler is never fired. I'm assuming there is something wrong with the EventsChanged implementation of NetMQBeacon, although I haven't dug deep enough to figure out what it is.

**Comment by somdoron** [comment]
It might be for also not registering to the event from the Poller thread.

Anyway you think you can provide a pull request?

**Comment by masaeedu** [comment]
I'll take a crack at it this week, primary hurdle is understanding the test infrastructure. I'm getting a 502 on http://netmq.readthedocs.io/, and "Service Unavailable" at http://netmq.readthedocs.org/, have the docs been migrated somewhere?
