### ISSUE TITLE
NetMQ.FaultException: Cannot close an uninitialised Msg.

### ISSUE THREAD

**Issue by lianghugg** [zeromq/netmq#572]
### Environment

```
NetMQ Version:    3.3.31
Operating System: win7 x64
.NET Version:     4.0
```
### Expected behaviour

NetMQ.FaultException: Cannot close an uninitialised Msg.
   at NetMQ.Msg.Close()
   at NetMQ.Core.Transports.V2Encoder.MessageReady()
   at NetMQ.Core.Transports.V2Encoder.Next()
   at NetMQ.Core.Transports.EncoderBase.GetData(ByteArraySegment& data, Int32& size, Int32& offset)
   at NetMQ.Core.Transports.StreamEngine.BeginSending()
   at NetMQ.Core.Transports.StreamEngine.Handle(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Transports.StreamEngine.FeedAction(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Transports.StreamEngine.ActivateOut()
   at NetMQ.Core.SessionBase.ReadActivated(Pipe pipe)
   at NetMQ.Core.Pipe.ProcessActivateRead()
   at NetMQ.Core.ZObject.ProcessCommand(Command cmd)
   at NetMQ.Core.IOThread.Ready()
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by somdoron** [comment]
It is usually because you are using the Socket from multiple threads

**Comment by answerfly** [comment]
Dear somdoron, I met the same NetMQ.FaultException. I have make a pub-sub demo and did some pressure test. There were two threads in my client. One thread did the "recieve" operation  and the other did the "SubscriberSocket.subscribe" operation every 3 seconds with 1000 different subscribes. I want to ask whether the operations to the SubscriberSocket must be done in one thread?  If so ,how can I do when I want to change the subscriber frequently while the  SubscriberSocket receive the data from the Pub server at the same time.  
Thanks a lot.

**Comment by somdoron** [comment]
@answerfly you are using the socket from multiple threads, which is not allowed.

Try to use the subscriber socket from one thread, I suggest taking a look at NetMQQueue to do that.

**Comment by muhamadahsan** [comment]
Hi, I am using NetMQ version 3.3.3.4. I have inproc queues and binding the ReceiveReady event (and using poller to start the socket).  I am getting the following exception while receiving the message in the event:
`NetMQ.FaultException: Cannot close an uninitialised Msg.
   at NetMQ.Msg.Close()
   at NetMQ.ReceivingSocketExtensions.ReceiveFrameString(IReceivingSocket socket, Encoding encoding, Boolean& more)
   at NetMQ.ReceivingSocketExtensions.ReceiveFrameString(IReceivingSocket socket)`

There is only one module subscribed to this event and that initializes only once at system startup... So, no more threads....
Any idea or suggestion to fix this?

**Comment by somdoron** [comment]
can you include the code?
If it is an inproc socket, someone is sending the messages, is this happen from multiple threads maybe?

**Comment by muhamadahsan** [comment]
@somdoron: But the exception in coming on receive end.

**Comment by somdoron** [comment]
doesn't matter, the message get closed by the pushing side

**Comment by somdoron** [comment]
in inproc that is the same message object between sender and receiver

**Comment by somdoron** [comment]
@muhamadahsan which socket types do you use? both for sender and receiver

**Comment by muhamadahsan** [comment]
**For Inbound:**
`var socket = new PairSocket(">inproc://temp-queue");
                // Binding on receive event.
                socket.ReceiveReady += ReceiveReady;

                // Initializing poller.
                poller = new NetMQPoller { socket };`

And in ReceiveReady:
`// Receiving message.
                var receivedMessage = e.Socket.ReceiveFrameString();`

**For Outbound:**
`var socket = new PairSocket("@inproc://yemp-queue");
                // Sending mesage
socket.SendFrame(SerializeToJson(message));

**Comment by somdoron** [comment]
does the sending happen from multiple threads?

**Comment by muhamadahsan** [comment]
@somdoron: What is the recommendation if someone need in multi-threaded application? Should the socket object be created in every send and receive? Should I use lock statement? Or something else?

**Comment by somdoron** [comment]
https://netmq.readthedocs.io/en/latest/queue/

**Comment by MonishaSyam** [comment]
I got the same issue NetMQ.FaultException: Cannot close an uninitialised Msg. 
In our code we are using subscriberSocket from multiple threads. I don't know how to change this to NetMQ Queue. Could you please help?
This is my code
 public AlarmStateChangeNotifier(string ipAddress, int portNo, NotificationHandlerDelegate
           notificationHandlerDelegate, RecoveryHandlerDelegate doRecoveryDelegate)
        {
            _ipAddress = ipAddress;
            _portNo = portNo;
            _notificationHandlerDelegate = notificationHandlerDelegate;
            var pubsubServerUrl = string.Format("tcp://{0}:{1}", ipAddress, portNo);
            _subscriberSocket = new SubscriberSocket();
            _subscriberSocket.Options.ReceiveHighWatermark = 0;
            _subscriberSocket.Connect(pubsubServerUrl);
            _notificationHandlerDelegate = notificationHandlerDelegate;
            _doRecoveryDelegate = doRecoveryDelegate;
            _tokenSource = new CancellationTokenSource();
            _token = _tokenSource.Token;
            _backgroundTask = Task.Factory.StartNew(Update, _token);

        }
private void Update()
{
   while (true)
   {
     var messageReceived = _subscriberSocket.ReceiveFrameString();
   }
}				

 public void Subscribe(IEnumerable<string> alarmNames)
{
  foreach (var alarm in alarmNames)
   {
                //Topic name is prefixed with #. This is done to distingush topic and value on 'Update'. 
                var topic = "#" + $"{alarm}";
                _subscriberSocket.Subscribe(topic);
   }
}
