### ISSUE TITLE
Poller thread of SubscriberSocket crashes when publisher is being restarted

### ISSUE THREAD

**Issue by samushenkov** [zeromq/netmq#581]
### Environment

```
NetMQ Version: the latest stable verstion from nuget / master branch.
Operating System: Win 10 / Win 7
.NET Version: 4.5
```
### Actual behaviour

**Poller thread crashes with next exception:**

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at NetMQ.Core.Patterns.Utils.ArrayExtensions.Swap[T](List`1 items, Int32 index1, Int32 index2)
   at NetMQ.Core.Patterns.Utils.Distribution.Activated(Pipe pipe)
   at NetMQ.Core.Patterns.XSub.XWriteActivated(Pipe pipe)
   at NetMQ.Core.SocketBase.WriteActivated(Pipe pipe)
   at NetMQ.Core.Pipe.ProcessActivateWrite(Int64 msgsRead)
   at NetMQ.Core.ZObject.ProcessCommand(Command cmd)
   at NetMQ.Core.SocketBase.ProcessCommands(Int32 timeout, Boolean throttle)
   at NetMQ.Core.SocketBase.GetSocketOption(ZmqSocketOption option)
   at NetMQ.Core.Utils.Selector.Select(SelectItem[] items, Int32 itemsCount, Int64 timeout)
   at NetMQ.NetMQPoller.Run()
   at SubTest.Program.PerformPolling(Object obj) in D:\Source\Test\PubSubTest\SubTest\Program.cs:line 55
### Steps to reproduce the behaviour

I'm new at using ZeroMQ so my example can contain some errors. Here is a code for client I am using: 

```
static void Main()
{
    using (var subscriber = new SubscriberSocket("tcp://127.0.0.1:9002"))
    {
        subscriber.ReceiveReady += (sender, args) =>
        {
            args.Socket.SkipMultipartMessage();
        };

        using (var queue = new NetMQQueue<Tuple<bool, string>> ())
        {
            queue.ReceiveReady += (sender, args) =>
            {
                var subscription = args.Queue.Dequeue();
                if (subscription.Item1)
                {
                    subscriber.Subscribe(subscription.Item2);
                }
                else
                {
                    subscriber.Unsubscribe(subscription.Item2);
                }
            };

            using (var poller = new NetMQPoller())
            {
                poller.Add(subscriber);
                poller.Add(queue);

                Task.Factory.StartNew(PerformPolling, poller);
                Task.Factory.StartNew(PerformSubscriptions, queue);

                Console.ReadKey();
            }
        }
    }
}

private static void PerformPolling(object obj)
{
    var poller = obj as NetMQPoller;
    if (poller != null)
    {
        try
        {
            poller.Run();
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex);
        }
    }
}

private static void PerformSubscriptions(object obj)
{
    var queue = obj as NetMQQueue<Tuple<bool, string>>;
    if (queue == null)
    {
        return;
    }

    for (var index = 0; index < 2000; ++index)
    {
        queue.Enqueue(Tuple.Create(true, $"topic/{index}/"));
    }

    Console.WriteLine("Subscription complete");
}
```

For host I use XPublisherSocket to count subscriptions.

**First issue**
1) Start host (XPublisherSocket)
2) Start client (SubscriberSocket)
-- For now everything works fine (publisher received all 2000 subscriptions)
3) Stop host (XPublisherSocket)
4) Start host (XPublisherSocket)
-- And here after several subscriptions (about 1000) client's poller thread crashes.

**The another problem I faced is when I start host and client in reversed order**
1) Start client (SubscriberSocket)
2) Start host (XPublisherSocket)
-- Here publisher receives only 1000 subscriptions and that is all. I tried to play with HWM but looks like it doesn't affect subscription logic and works only for receive / send operations.

Also I have one more question about subscriptions using SubscriberSocket. Can I call subscribe/unsubscribe methods from the thread other then receiving one (maybe using some locks)? I have read that it is allowed to work with socket only from one thread, that is why I am using NetMQQueue to add / remove subscriptions.

Thank you in advance.

**Comment by somdoron** [comment]
Regarding missing subscriptions, because you send more than 1000 you need to increase the subscriber SendHighWatermark, so if you have 2000 subscriptions increase it to 2000.
You can also increase the Publisher ReceiveHighWatermark to 2000.

You are right about the thread usage, your usage of NetMQQueue is correct.

I'm checking regarding the other issue

**Comment by asamushenkov** [comment]
As I mentioned above I tried to increase HWM and didn't help me.
I use next options:
```
// For subscriber (it will send the subscription to the publisher, right?)
subscriber.Options.SendHighWatermark = 3000;
```

```
// For publisher
publisher.Options.ReceiveHighWatermark = 3000;
```

And here is code for publisher:

```
static void Main()
{
    using (var publisher = new XPublisherSocket("tcp://127.0.0.1:9002"))
    {
        publisher.Options.ReceiveHighWatermark = 3000;
        publisher.ReceiveReady += (sender, args) =>
        {
            var message = args.Socket.ReceiveFrameBytes();

            Console.WriteLine("Message received {0} for topic {1}", message[0], Encoding.ASCII.GetString(message, 1, message.Length - 1));
        };

        using (var poller = new NetMQPoller())
        {
            poller.Add(publisher);
            // poller.Add(queue);

            Task.Factory.StartNew(PerformPolling, poller);
            // Task.Factory.StartNew(PerformPushing, queue);

            Console.ReadKey();
        }
    }
}

private static void PerformPolling(object obj)
{
    var poller = obj as NetMQPoller;
    if (poller != null)
    {
        poller.Run();
    }
}
```

Thank you for fast reply.

**Comment by somdoron** [comment]
you need to set the watermark before calling connect.
So don't use connection strings, use the connect method instead.

**Comment by asamushenkov** [comment]
Oh. It makes sense. Thank you.

**Comment by asamushenkov** [comment]
It solved the problem subscriptions and also fixed exception in first case (looks like it is somehow connected with HWM).

**Comment by somdoron** [comment]
cool, I still think there is a bug there, the exception should not happen

**Comment by asamushenkov** [comment]
Totally agree with you. In our case client just stopped receiving data when host was restarted (sometimes there were more then 1000 subscriptions collected during some uptime). We used something like Task.Factory.StartNew(() => poller.Run()) to start the poller without try-catch block inside, so there were no logs that something went wrong.
