### ISSUE TITLE
Link broken for beacon example 

### ISSUE THREAD

**Issue by nathvi** [zeromq/netmq#590]
### Environment

```
NetMQ Version:    NA
Operating System: NA
.NET Version:     NA
```
### Expected behaviour

Should navigate to link.
### Actual behaviour

Return a 404 not found error
### Steps to reproduce the behaviour

Go to the link [https://github.com/zeromq/netmq/blob/master/src/Samples/Beacon/BeaconDemo/Bus.cs](url)

**Comment by somdoron** [comment]
Can you fix and send a PR?

**Comment by nathvi** [comment]
I'm not sure how I would fix it... Sorry.

**Comment by nathvi** [comment]
Nice template for the question btw.

**Comment by nathvi** [comment]
@somdoron , this is still broken.

**Comment by drewnoakes** [comment]
Where is the broken link?

On this page, the link is correct:

https://github.com/zeromq/netmq/blob/master/docs/beacon.md

It links to:

https://github.com/NetMQ/Samples/blob/master/src/Beacon/BeaconDemo/Bus.cs
