### ISSUE TITLE
An exception with StreamSocket

### ISSUE THREAD

**Issue by lidanger** [zeromq/netmq#593]
### Environment

```
NetMQ Version:    3.3.3.4  and 4.0.0 rc5
Operating System: Windows 10 Home Edition, 10.0.10586
.NET Version:     4.0
```
### Actual behaviour

  When using StreamSocket and NetMQPoller or NetMQProactor as a server, it gives an exception like this:

  System.Net.Sockets.SocketException (0x80004005): 无法立即完成一个非阻止性套接字操作(A non blocking socket operation could not be completed immediately)。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 NetMQ.Core.Mailbox.TryRecv(Int32 timeout, Command& command)
   在 NetMQ.Core.SocketBase.ProcessCommands(Int32 timeout, Boolean throttle)
   在 NetMQ.Core.SocketBase.GetSocketOption(ZmqSocketOption option)
   在 NetMQ.Core.Utils.Selector.Select(SelectItem[] items, Int32 itemsCount, Int64 timeout)
   在 NetMQ.NetMQPoller.Run()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()
### Steps to reproduce the behaviour

  Run the server as follows, and use multiple traditional tcp clients to test.  

```
    // 服务器
string endPoint = string.Format("tcp://*:{0}", nPort);
server = new StreamSocket("@" + endPoint);
server.ReceiveReady += Server_ReceiveReady;

// 异步模型
//proactor = new NetMQProactor(server,
//    (socket, message) => ProcessMessage(socket, message));

// 轮询器
poller = new NetMQPoller();
poller.Add(server);

poller.RunAsync();
```

**Comment by somdoron** [comment]
I will check it out

**Comment by lidanger** [comment]
Seems OK after I try-catch the code like this:
try
 {
    isItemAvailable = m_selector.Select(m_pollSet, m_pollSet.Length, timeout);
 }
 catch { }

Nothing happened during 3 hours tests.
