### ISSUE TITLE
Adding option to disable PGM multicast loopback?

### ISSUE THREAD

**Issue by DSolimano** [zeromq/netmq#595]
### My problem:

PGM multicast loopback seems to be problematic - see zeromq mailling list messgaes 

http://grokbase.com/t/zeromq/zeromq-dev/127t25hcex/zmq-mcast-loop-with-pgm
http://grokbase.com/t/zeromq/zeromq-dev/098tcvew7m/multiple-udp-sender-receiver-on-same-machine-bug-fix

And in fact it was completely removed from ZeroMQ - https://zeromq.jira.com/browse/LIBZMQ-104

I was surprised to find, however, that with the below libraries, Multicast loopback works fine on Windows 7, and there doesn't seem to be a way to disable it.  I've attached a sample program below (needs to be run as admin).  
### Proposed solution:

I think we should either disable it completely, matching ZeroMQ, or to add a socket option to disable it.  Happy to work on a pull request for either/both, if this all makes sense.
### Environment

```
NetMQ Version:    3.3.3.1
Operating System:  Windows 7
.NET Version:     4.6.1
```
### Expected behaviour

There's an option to disable multicast loopback, in the style of ZMQ_MCAST_LOOP from http://api.zeromq.org/2-1:zmq-setsockopt
### Actual behaviour

Can't find such an option in the source - https://github.com/zeromq/netmq/blob/master/src/NetMQ/Core/Options.cs
### Steps to reproduce the behaviour

private class Tester
    {
        NetMQPoller poller;
        NetMQTimer timer;
        public Tester()
        {
            poller = new NetMQPoller();

```
        //SetUpRealProxy();
        //SetUpDummyProxy();
        SetUpDummyMulticast();

        timer = new NetMQTimer(new TimeSpan(0, 0, 5));
        timer.Elapsed += Timer_Elapsed;
        poller.Add(timer);

        poller.RunAsync();
        Console.ReadLine();
        poller.Dispose();

        if (null != wrangler)
        {
            wrangler.Dispose();
        }

    }

    private void SetUpDummyMulticast()
    {
        sub = new SubscriberSocket();
        sub.Connect("pgm://232.1.1.1:9601");
        sub.SubscribeToAnyTopic();
        sub.ReceiveReady += Sub_ReceiveReady;
        poller.Add(sub);

        pub = new PublisherSocket();
        pub.Connect("pgm://232.1.1.1:9601");
        poller.Add(pub);
    }
```

private void Sub_ReceiveReady(object sender, NetMQSocketEventArgs e)
            {
                var strings = e.Socket.ReceiveMultipartStrings();
                Console.WriteLine("IN Sub_ReceiveReady");
                foreach(var s in strings)
                {
                    Console.WriteLine(s);
                }
            }

```
        private void Timer_Elapsed(object sender, NetMQTimerEventArgs e)
        {
            Console.WriteLine("In Timer_Elapsed");

            if (null != pub)
            {
                pub.SendFrame("DSOL.Tick.IBM", true);
                pub.SendFrame("100", false);
            }
            else
            {
                pari.Pub.SendFrame("DSOL.Tick.IBM", true);
                pari.Pub.SendFrame("100", false);
            }
        }
}
```

This prints

In Timer_Elapsed
IN Sub_ReceiveReady
DSOL.Tick.IBM
100
In Timer_Elapsed
IN Sub_ReceiveReady
DSOL.Tick.IBM
100

 . . .

**Comment by somdoron** [comment]
Fell freeto add a pull request,  though the default behavior should not
change IMO,  netmq is using msmq pgm aka ms-pgm. Check if there is an
option to disable loopback

**Comment by DSolimano** [comment]
Excellent, I'll dig in and see what I can find.

**Comment by tobi-tobsen** [comment]
There doesn't seem to be an [option ](https://msdn.microsoft.com/de-de/library/windows/desktop/ms738591(v=vs.85).aspx )to disable loopback and [others are searching](http://stackoverflow.com/questions/10150114/how-to-disable-loopback-in-a-windows-pgm-socket) for it too.

However, maybe one can use [RM_DEL_RECEIVE_IF](https://msdn.microsoft.com/en-us/library/windows/desktop/ms739175(v=vs.85).aspx) to disable receiving on the loopback (I haven't tried it but since @DSolimano wanted to help, maybe it's worth a shot).

That said, I am not even sure the initial problem of "only the first local receiver can bind" persists in the windows pgm implementation (haven't got the time to try it) nor do I know it the statement 
> Leaving multicast loop-back enabled when it is not required can have a negative impact on performance.
 is true for msmq pgm when there are no local receivers.

**Comment by DSolimano** [comment]
@tobi-tobsen you may very well be right that this isn't needed.  I hit the same wall you found and am a bit stumped at the moment. But, I remember having to figure out how to turn on loopback when I first started using clrzmq, and being depressed when it was removed.  I suppose my next step will be to see what clrzmq was doing and going from there.

**Comment by DSolimano** [comment]
Was able to do some research, and clrzmq IS able to successfully disable loopback on windows, so zeromq, doing the heavy lifting, does this in pgm.socket.cpp
```

        // Multicast loopback disabled by default
        const int multicast_loop = 0;
        if (!pgm_setsockopt (sock, IPPROTO_PGM, PGM_MULTICAST_LOOP,
              &multicast_loop, sizeof (multicast_loop)))
        goto err_abort;
```

Whereas asyncio is doing this

`this.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.MulticastLoopback, value ? 1 : 0);`

I think it's the difference between IPPROTO_PGM and SocketOptionLevel.IP that's causing the issue . . . more research is needed, aka building my own AsyncIO and seeing what I can get done.  Hopefully I don't need to reach into my bag of interop tricks, because I don't think I remember any of them.

**Comment by DSolimano** [comment]
Another note to myself - pgm_setsockopt ultimately resolves to a call down to setsockopt like so

`retval = setsockopt (s, IPPROTO_IP, IP_MULTICAST_LOOP, (const char*)&optval, sizeof(optval));`

looking at https://github.com/steve-o/openpgm/blob/c486940c41185d390ae75763d2ecc4c388851b9c/openpgm/pgm/sockaddr.c.  So the above .NET call appears to be correct . . . further debugging needed.

**Comment by somdoron** [comment]
Also note, NetMQ is using MS-PGM and zeromq is using openpgm. So you might want to check if it even possible to disable loopback with MS-PGM.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms740125(v=vs.85).aspx
