### ISSUE TITLE
Using Poller Instead an Infinite Loop Questions

### ISSUE THREAD

**Issue by peske** [zeromq/netmq#597]
Usual pattern in ZeroMQ guide is to create an infinite loop, and to send / receive within the loop. Something like:

```
while (true)
{
    socket.Receive...
    socket.Send...
}
```

NetMQ implements NetMQPoller as "event-driven reactor" which kinda offers simpler pattern to accomplish the same:

```
NetMQSocket socket = new ...
NetMQPoller poller = new NetMQPoller({ socket });
socket.ReceiveReady += MyReceiveHandler;

poller.Run();
```

I have a few questions regarding the second approach:

1. Does using the poller instead of an infinite loop introduces any significant overhead (performance penalties)? If not, is it justifiable to conclude that we can always use the second approach, even with only one socket?
2. Are all poller events executed from the same thread? Can we freely send / receive / connect / disconnect, etc. from event handler body?
3. Are there any code examples that demonstrate how we can "inject" a message that should be sent in the second pattern from above? Also examples for SendReady event?

Thanks!

**Comment by peske** [comment]
Well, more or less I've found the answers [here](http://netmq.readthedocs.io/en/latest/poller/) and [here](http://stackoverflow.com/questions/37051913/performance-impact-of-using-netmq-poller). So I'm closing this.

**Comment by somdoron** [comment]
For others who might concern
1. Netmqpoller performance are might not as good as infinite loop,  however poller can be tweaked to yield very good performance. 
2. Yes,  it is safe, poller is using one thread to invoke all handlers. 
3. I'm not sure I understand the which example you want.  Regarding send ready,  it is very rare to actually need it.  In general when you send a lot of messages in a point your call to send get blocked and you reach the send high watermark you want to use send ready to avoid blocking.
