### ISSUE TITLE
Dependency problems at runtime

### ISSUE THREAD

**Issue by LGuyDev** [zeromq/netmq#600]
### Environment

```
NetMQ Version:    3.3.d.4
Operating System:  Windows 10 Pro
.NET Version:     4.5.1
Visual Studio 2013
```

I get the following error at runtime from the statements:

```
            reqSocket = new RequestSocket();
            reqSocket.Connect("tcp://127.0.0.1:5099");
```

Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

However, the same code works just fine in another project in the same solution.  Both projects have the same references and using statements.  How can I fix this?

**Comment by somdoron** [comment]
Both project use same .net framework?
That pretty weird, does is also happen with NetMQ4?

**Comment by LGuyDev** [comment]
Both projects are in the same solution and target 4.5.1.

Can I just use the Nuget console to install NetMQ 4 straightaway?

Thanks!

**Comment by LGuyDev** [comment]
Same result using NetMQ 4 and starting over with a new solution.  The
second project in the solution generates the error I pasted in the first
post here.

**Comment by LGuyDev** [comment]
My bad.  I reinstalled the package across all projects in the solution and
it worked without a hitch.  Thanks for responding so quickly.

**Comment by drewnoakes** [comment]
Closing as the problem was resolved.
