### ISSUE TITLE
Can't get NetMQBeacon to send more than 253 UTF-16 chars

### ISSUE THREAD

**Issue by nathvi** [zeromq/netmq#601]
### Environment

```
NetMQ Version:    3.3.3.4
Operating System:  Windows 10
.NET Version:     4.5.2
```
### Expected behaviour

```
Able to transmit and receive a UTF-16 string of char length greater than or equal to 254 chars
(508 bytes or greater in my estimation)
```
### Actual behaviour

```
Only able to transmit and recieve a UTF-16 string of char length less than or equal to 253 chars
(506 bytes or greater in my estimation)
```
### Steps to reproduce the behaviour

Try to publish a UTF-16 string with a char count OVER 253, using the NetMQBeacon

**Comment by nathvi** [comment]
Looks like the buffer used to receive the udp frame in the NetMQBeacon is limited by
`UdpFrameMax = 255;`

Is there a reason why this is 255? Can I increase this?

**Comment by drewnoakes** [comment]
255 is a safe and possibly slightly conservative limit. As you increase it, you run into the chance that packets may be dropped or fragmented. Various sources online seem to suggest a size of around 500 bytes _should_ be ok, but I'm not an expert on this and there are differing opinions out there from my brief research into the issue.
