### ISSUE TITLE
Only NetMQContext works, RequestSocket doesn't

### ISSUE THREAD

**Issue by rfire01** [zeromq/netmq#602]
I downloaded netmq to my VS using nuget, and I have a problem with request\response socket.

When I use "NetMQContext.Create()", I get a message that it is a old concept, and I can create sockets by using RequestSocket().

But when I try to use it I get an error "The Type or namespace name 'RequestSocket' could not be found"

**Comment by somdoron** [comment]
make sure you are using the name space NetMQ.Sockets

**Comment by rfire01** [comment]
You are right.
I couldn't find anywhere that used this namespace, so it didn't came to my mind.

Thank you.
