### ISSUE TITLE
VS2015 Can't resolve Nuget dependencies.

### ISSUE THREAD

**Issue by matthew798** [zeromq/netmq#607]
### Environment

```
NetMQ Version: master as of 08/29/2016   
Operating System: windows 10
.NET Version: 4.5,4,3.5,2    
```
### Expected behaviour

Nuget restores the required packages and the build completes
### Actual behaviour

VS throws the following errors:

_Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore. NetMQ_          

(this error repeats for all projects except NetMQ and NetMQ3.5)
_Error occurred while restoring NuGet packages: Error reading 'C:\Users\Matthew\Desktop\netmq-master\src\Performance\remote_lat\project.json' at line 11 column 23 : TODO: unknown keyword platform_
### Steps to reproduce the behaviour

Open the SLN file in VS2015 and attempt to compile the NetMQ3.5 project (Release, Any CPU)

**Comment by somdoron** [comment]
you should use the NetMQ-Core.sln if you are using VS2015 with Update 3

**Comment by drewnoakes** [comment]
@matthew798 I take it your problem was resolved. Let us know if not. Closing for now.
