### ISSUE TITLE
Missing source file

### ISSUE THREAD

**Issue by matthew798** [zeromq/netmq#608]
### Environment

```
NetMQ Version:  latest as of 08/29/2016  
Operating System: windows 10
.NET Version: 3.5     
```
### Expected behaviour

VS2015 compiles the NetMQ dll
### Actual behaviour

When compiling only the NetMQ3.5 project, visual studio throws the following error:
Source file 'C:\Users\Matthew\Desktop\netmq-master\src\NetMQ\Core\Utils\Selector.cs' could not be found.    NetMQ3.5    C:\Users\Matthew\Desktop\netmq-master\src\NetMQ\CSC     
### Steps to reproduce the behaviour

Open the solution file and attempt to build NetMQ35

**Comment by Mystfit** [comment]
Removing Selector.cs from the project allows the build to continue, but it halts with a new error.
````    10>NetMQPoller.cs(34,26): error CS0246: The type or namespace name 'NetMQSelector' could not be found (are you missing a using directive or an assembly reference?) [c:\Code\netmq-latest\src\NetMQ\NetMQ3.5.csproj]````

**Comment by somdoron** [comment]
oops, I changed the file name and forgot the NetMQ35.

You should remove the Selector.cs and add NetMQSelector.cs from the src directory.

can you make a pull request?

**Comment by Mystfit** [comment]
Will do. I just moved onto the next error now.

```` ErrorCS1061 'AsyncSocket' does not contain a definition for 'GetAcceptedSocket' and no extension method 'GetAcceptedSocket' accepting a first argument of type 'AsyncSocket' could be found (are you missing a using directive or an assembly reference?)

Error	CS7036 There is no argument given that corresponds to the required formal parameter 'socket' of 'AsyncSocket.Accept(AsyncSocket)' ````

**Comment by somdoron** [comment]
oops, my fault again...

I'm using the project.json and need to remember to go and update the csproj.

Anyway you need to upgrade asyncio to 0.1.26

by the way, if you are latest visual studio update 3 you can just open NetMQ-Core and compile. It compiles to dotnet 3.5 as well.

**Comment by somdoron** [comment]
you can just edit the packages.NetMQ3.5.config and run nuget restore

**Comment by Mystfit** [comment]
Updated to the latest AsyncIO (had to update the tests packages as well to stop them downloading the old one) but now receive this message when compiling the NetMQ solution (not core).

`Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.` 

I added that section to project.json but it suddenly couldn't find the AsyncIO assembly anymore. I attempted to uninstalled and reinstall the nuget package from inside VS but it's still unavailable. 

Removing the packages folder, removing the runtimes section and restoring the nuget packages gets the packages back in place, but puts me back at the '"runtimes": { "win": { } }' error.

I did manage to successfully compile the NetMQ-Core solution which is helpful. I'm actually going to try and get it working in Unity so I can try and debug why issue https://github.com/zeromq/netmq/issues/526 is still happening when ` NetMQConfig.Cleanup()` is called.

**Comment by somdoron** [comment]
This is issue with latest visual studio update 3, if the project.json exist you cannot compile the csproj.

**Comment by drewnoakes** [comment]
#648 will fix this, so long as you're able to use VS2017.
