### ISSUE TITLE
 a non-blocking socket operation could not be completed immediately

### ISSUE THREAD

**Issue by GuojieLin** [zeromq/netmq#609]
### Environment

```
NetMQ Version:    3.3.3.4/4.0.0-rc5 
Operating System: win10
.NET Version:     4.0
```
### Actual behaviour
1. 2016-09-05 15:05:39.755:  无法立即完成一个非阻止性套接字操作。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 NetMQ.Core.Utils.Signaler.Recv()
   在 NetMQ.Core.Mailbox.TryRecv(Int32 timeout, Command& command)
   在 NetMQ.Core.SocketBase.ProcessCommands(Int32 timeout, Boolean throttle)
   在 NetMQ.Core.SocketBase.TryRecv(Msg& msg, TimeSpan timeout)
   在 NetMQ.NetMQSocket.TryReceive(Msg& msg, TimeSpan timeout)
   在 NetMQ.ReceivingSocketExtensions.Receive(IReceivingSocket socket, Msg& msg)
   在 NetMQ.ReceivingSocketExtensions.ReceiveMultipartMessage(IReceivingSocket socket, Int32 expectedFrameCount)
2. 2016-09-05 15:05:59.999:  无法立即完成一个非阻止性套接字操作。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 NetMQ.Core.Utils.Signaler.Recv()
   在 NetMQ.Core.Mailbox.TryRecv(Int32 timeout, Command& command)
   在 NetMQ.Core.SocketBase.ProcessCommands(Int32 timeout, Boolean throttle)
   在 NetMQ.Core.SocketBase.TrySend(Msg& msg, TimeSpan timeout, Boolean more)
   在 NetMQ.NetMQSocket.TrySend(Msg& msg, TimeSpan timeout, Boolean more)
   在 NetMQ.OutgoingSocketExtensions.Send(IOutgoingSocket socket, Msg& msg, Boolean more)
   在 NetMQ.OutgoingSocketExtensions.SendFrame(IOutgoingSocket socket, Byte[] data, Int32 length, Boolean more)
   在 NetMQ.OutgoingSocketExtensions.SendMultipartMessage(IOutgoingSocket socket, NetMQMessage message)
### Steps to reproduce the behaviour

i want to implemete asynchronously socket，the socketexception error code is 10035.and the probability is 0.3%.
using (RouterSocket frontend = new RouterSocket("tcp://127.0.0.1:15557"))
            {
                while (true)
                {
                    try
                    {
                        NetMQMessage message = frontend.ReceiveMultipartMessage();
                        Task.Factory.StartNew(() =>
                        {
                            try
                            {
                                //do something
                                lock (frontend)
                                {
                                    frontend.SendMultipartMessage(returnMessage);
                                }
                            }
                            catch (Exception exception)
                            {
                                //catch exception 
                            }
                        });
            }  
            catch (Exception exception)
            {
                     //catch exception 
            }
      }
}

**Comment by somdoron** [comment]
You are using the socket from two separate threads,  which is not allowed.  You can just use NetMQPoller for that usage

**Comment by GuojieLin** [comment]
i use the proxy implemete it,like this
 using (RouterSocket frontend = new RouterSocket("tcp://127.0.0.1:12345"))
            {
                using (DealerSocket backend = new DealerSocket("@inproc://backend"))
                {
                    Proxy proxy = new Proxy(frontend, backend);
                    proxy.Start();
                }
}
private static void StartProxyWork(string connectAddress, int count,Action<NetMQSocket,NetMQMessage> processMessage)
        {
            for (int i = 0; i < count; i++)
            {
                Thread thread = new Thread(() =>
                {
                    using (DealerSocket dealerSocket = new DealerSocket(connectAddress))
                    {
                        while (true)
                        {
                            NetMQMessage message = dealerSocket.ReceiveMultipartMessage();
                            processMessage(dealerSocket, message);
                        }
                    }
                });
                thread.IsBackground = true;
                thread.Start();
            }
        }
**and it works well but i don't understand how to use NetMQPoller ，**
i found some document ，at https://github.com/zeromq/netmq/blob/master/docs/poller.md;
and here :http://netmq.readthedocs.io/en/latest/router-dealer/
but i think  it's not right for me
could you show me a sample about NetMQPoller ?

**Comment by GuojieLin** [comment]
i think i understand what you said.i try to do this
```
 using (NetMQSocket frontend = new RouterSocket(socketListen))
            {
                using (NetMQPoller poller = new NetMQPoller() { frontend })
                {
                    try
                    {
                        frontend.ReceiveReady += ReceiveReady;
                        poller.Run();
                    }
                    catch (Exception exception)
                    {
                            //catch exception
                    }
                }
            }
private static async void ReceiveReady(object sender, NetMQSocketEventArgs netMqSocketEventArgs)
        {
            try
            {
                NetMQMessage message = null;
                if (netMqSocketEventArgs.Socket.TryReceiveMultipartMessage(TimeSpan.FromMilliseconds(receivedoutime),ref message))
                {
                    await DoSomeThinig(message);// Task.Run(Aciont); and await 
                    //lock (objlock)//should i lock here?
                    {
                        netMqSocketEventArgs.Socket.SendMultipartMessage(message);
                        netMqSocketEventArgs.Socket.Options.Linger = TimeSpan.Zero;
                    }
                }
                else
                {
// do something 
                }
            }
            catch (Exception exception)
            {
                            //catch exception
            }
        }
```

**Comment by miaodadao** [comment]
I use ActionBlock to drive NetMQ send messages, and ActionBlock can make sure only one send active in some thread, "System.Net.Sockets.Socketexception 10035" also.

**Comment by KamranShahid** [comment]
> You are using the socket from two separate threads, which is not allowed. You can just use NetMQPoller for that usage

I have also faced same issue. I were using MajorDomo sample and what i tried under mBroker clas is to start worker/client processing asynchronously on separate thread.
Is it still not supported to use same socket on multiple threads?
