### ISSUE TITLE
How to use netmq like JS ? (feature question )

### ISSUE THREAD

**Issue by lion117** [zeromq/netmq#610]
### Environment

```
NetMQ Version:    4.0
Operating System: Win7
.NET Version:   4.5
```
### Expected behaviour

Hi, I applied  **netZMQ  req-rep patten**  for Desktop application
The default API  **RequestSocket.RequestResponseStringWithRetry** would cause GUI blocked as network disconnect or something unexpected occured . 
I wanna use ZMQ like  js in web development. which would **not block GUI thread** , at the same, i could assign **callback function** when  req-rep had been done . 

As I noticed netmq provide a api which support callback function , but netmq did not complete it . 
![default](https://cloud.githubusercontent.com/assets/3996029/18263042/5a554868-7439-11e6-87f4-5eb6bdc08897.png)

Are there any way to do like  JS ?

**Comment by drewnoakes** [comment]
For non-blocking (async) receives, use `NetMQPoller` and `ReceiveReady` or use `TryReceive*` methods on sockets.
