### ISSUE TITLE
Why does the XPub / XSub example miss the first few messages...

### ISSUE THREAD

**Issue by Rico501** [zeromq/netmq#612]
### Environment

```
NetMQ Version:    3.3.3.4
Operating System: Windows 10 Pro
.NET Version:     4.6.1
```

http://netmq.readthedocs.io/en/latest/xpub-xsub/

**Comment by drewnoakes** [comment]
It takes a little time for the subscription request to be processed. I know it's been quite a while since you asked this, but do you recall whether you were missing messages if there was a delay between the subscription and the publisher's sends?
