### ISSUE TITLE
SocketException  - A non-blocking socket operation could not be completed - Message queue ->Dealer <-> Router

### ISSUE THREAD

**Issue by blackhill** [zeromq/netmq#615]
### Environment

    NetMQ Version:   3.3.3.4
    Operating System: Win10
    .NET Version: 4.5.2

### Actual behaviour
I have a SocketException when the number of clients pushing to the queue is growing.
Exception message : "A non-blocking socket operation could not be completed"

Can I get this exception because the socket's send buffer is full? I am sending a lot of messages without Thread.Sleep.

### Code example

![error](https://cloud.githubusercontent.com/assets/1117282/18521474/88a54bea-7aac-11e6-81f0-09d620ed4242.png)

**Comment by somdoron** [comment]
You are using the dealer socket from two threads, which is not allowed.

You are using it both from the Main thread and the new poller thread you are starting...

Take a look at NetMQQueue, it might help you. It's a safe multi-publisher-single-consumer queue, which you can also add to Poller. That way you can push messages from multiple threads and queue them on the NetMQPoller and immediately send them to the Socket.
