### ISSUE TITLE
Examples are missing

### ISSUE THREAD

**Issue by danielcrenna** [zeromq/netmq#616]
In the documentation, for example, the link for the Beacon example:

http://netmq.readthedocs.io/en/latest/beacon/

Refers to this link that does not exist (and it appears there is no Samples directory in the repo)

https://github.com/zeromq/netmq/blob/master/src/Samples/Beacon/BeaconDemo/Bus.cs

**Comment by somdoron** [comment]
we moved the examples to another repository, it here:

https://github.com/NetMQ/Samples

Do you want to make a Pull Request to the documentation to fix the link?
