### ISSUE TITLE
TryReceiveFrameString(TimeSpan.FromSeconds(1000), out frame) will eventually hang if in a while loop.

### ISSUE THREAD

**Issue by MaratPurnyn** [zeromq/netmq#617]
### Environment

```
NetMQ Version:    3.3.3.4
Operating System:  Windows 7 Professional 64-bit
.NET Version:     4.5.1
```
### Expected behaviour

The line will wait for 1000 ms before continuing on. If in a while loop, TryReceiveFrameString() will be called until loop end conditions are met.
### Actual behaviour

After 3 iterations of the loop TryReceiveFrameString() will hang until a string is sent.
### Steps to reproduce the behaviour

Run a task that creates a ResponseSocket that runs TryReceiveFrameString() in a while() loop with a if statement in the loop that checks for a cancelation token (or something else).
Run a task RequestSocket that sends a message once and ends.

TryReceiveFrameString() will hang after 3 iterations.

**Comment by MaratPurnyn** [comment]
I found another method of doing what I wanted to using NetMQPoller, however I feel like this is still an issue.

**Comment by drewnoakes** [comment]
Can you make a small code example that exhibits this behaviour? It may be
that something else is going on. It the wait can be shorter (100ms or less)
then a unit test would be good.
