### ISSUE TITLE
ZMQ.Poller(router, dealer, null) continuously eats CPU after certain period of time even no messages are coming

### ISSUE THREAD

**Issue by sjaini44u** [zeromq/netmq#618]
I am using ZMQ java library for async communication. I am using Router dealer pattern . Request reply works fine for some time. But after handling bunch of requests, i see ZMQ.Proxy method is causing continuous CPU usage, also GC activity starts behaving abnormally. Continuous volatility in GC along with 50% of CPU usage. Request reply is still working fine but CPU usage is a concern
I am writing this after profiling application with JProfiler and JVisualVM. There is nothing else which is causing this behavior. 

Is this known issue ?

**Comment by NimaAra** [comment]
You do realize that you have opened the issue on the `NetMQ` project which is the _.NET_ implementation of the library and not _Java_.
