### ISSUE TITLE
NetMqPoller.Dispose blocks indefinitely

### ISSUE THREAD

**Issue by ylexus** [zeromq/netmq#619]
### Environment

```
NetMQ Version:    3.3.3.4
Operating System: Win 7
.NET Version:    4.5
```
### Expected behaviour

```
            SubscriberSocket socket = new SubscriberSocket();
            NetMQPoller poller = new NetMQPoller { socket };
            socket.Connect(connection);
            socket.Subscribe("");
            socket.ReceiveReady += OnSocketReceiveReady;
            poller.RunAsync();
```

The messages get processed and everything works fine. 

However I need to have a reconnect functionality in my app. So to disconnect I call 

```
                poller.Dispose();
```

(on same thread that created all the objects in the first place). 

Problem is, this call blocks.

I tried removing the socket from the poller first and managed to get through Dispose, but looks like removing sockets must be done on the thread the poller runs on which I have no control over. 

What is the simplest way of properly destroying the poller and the socket in my case?

**Comment by somdoron** [comment]
Dispose should work, also calling remove from another thread is allowed if you are using NetMQ that is build for .Net 4.

Regarding the blocking, it can be because the handling of ReceiveReady of the socket. When you break all with visual studio where does the Poller thread stuck?

**Comment by somdoron** [comment]
Also you can try and call stop before dispose

**Comment by somdoron** [comment]
By the way, the Dispose must not  be called from the Poller thread, from poller thread you can call Stop and then Dispose. 

It is a bug..

**Comment by ylexus** [comment]
You were right, it was a deadlock in OnSocketReceiveReady. Maybe a documentation on Dispose could be updated to warn about its dependency on all the handlers exiting.

**Comment by drewnoakes** [comment]
Just got bitten by this. Agree we should extend the docs. Do you think it's reasonable to throw an exception when calling Dispose on the poller thread, to identify the problem to the developer?

**Comment by somdoron** [comment]
Sounds good

**Comment by drewnoakes** [comment]
Code on master now throws if you call dispose from the poller thread. Closing this.
