### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by awb99** [zeromq/netmq#620]
Is authentication implemented in NetMQ?

**Comment by jwjosefy** [comment]
No, it's not implemented into NetMQ. You may very well plug your own
authentication method on the messages you are working with.

Consider using JWT (JSON Web Tokens) - https://jwt.io/
It's damn simple and straightforward to use. There's already libraries on
Nuget implementing this.

Otherwise, NetMQ and ZeroMQ are frameworks to care about the transport
layer, and only that.

Best,
J.W.

Em qui, 13 de out de 2016 às 17:05, awb99 <notifications@github.com>
escreveu:

**Comment by awb99** [comment]
I see.   Is there  a way how to close a connection?  So say I do a challenge / response authentication..  And if this fails the server closes the connection. Can I do  whitelist to accept connections?  Any way how a pub socket can wait in publishing data until it has been authenticated?

**Comment by forteco** [comment]
I am planning of implementing a token based permisisoning system based on this example :+1: http://somdoron.com/2014/12/token-pubsub/

But what I don't get is, if the publisher only sends data to the correct client. Or if one really would have to encrypt all data that is sent via the publisher, so that only authenticate clients can access the data. 

I did read that zmq publisher does publish to ALL connected clients ALL subscribed data.

**Comment by somdoron** [comment]
If you do it correctly,  only to the correct clients.

**Comment by forteco** [comment]
@somdoron: so in your token-pubsub solution, if there are two different clients connected to the same server via tcp, and they subscribe to 2 differnent instruments, then they should NOT get the instruments subscribed by the other client?  I believe with an older verion of the c zmq engine, it would have sent it on the wire. And only the library would not show it. So Net MQ is different in this regards then...

**Comment by somdoron** [comment]
Both in libzmq and netmq you need to enable manual subscriptions.
Instruments wont arrive if not allowed

**Comment by forteco** [comment]
@somdoron 1000 thanks!!

**Comment by jwjosefy** [comment]
Would you please tell how to enable manual subscriptions? Tks!

Em sex, 14 de out de 2016 08:45, Doron Somech <notifications@github.com>
escreveu:

> Both in libzmq and netmq you need to enable manual subscriptions.
> Instruments wont arrive if not allowed
>

**Comment by somdoron** [comment]
Read here http://somdoron.com/2014/12/token-pubsub/

**Comment by awb99** [comment]
@somdoron  Since nobody made a RPC library for NetMQ, I hacked a RabbitMQ RPC library, to use NetMQ:  https://github.com/awb99/NetMQ.RPC

A simple calculator service accessible via RPC via NetMQ Request/Response sockets.

**Comment by somdoron** [comment]
Very cool,  let me know if you want to move it to netmq organization on github:

Github.com/netmq

**Comment by awb99** [comment]
@somdoron I would be honored!   But please keep in mind, that I quickly hacked the project..

**Comment by somdoron** [comment]
Will give you a permission later today,  also take a look at
https://github.com/somdoron/NetMQ.High

You might learn some relevant patterns.

**Comment by awb99** [comment]
Do you have Skype?  I would like to discuss some ides for the rpc library

**Comment by somdoron** [comment]
Yes, it is somdoron.

Also you can contact me by email at:

somdoron AT gmail DOT com

**Comment by npendlington** [comment]
Is it worth reconsidering this issue?
I am attempting to write a client for a server that is not in my control. It utilises zmq's plain text authentication.
http://api.zeromq.org/master:zmq-plain
See also [ZMQ_PLAIN_USERNAME] [ZMQ_PLAIN_PASSWORD], and [ZMQ_ZAP_DOMAIN] sections in http://api.zeromq.org/master:zmq-setsockopt, which are relevant to my requirements.

**Comment by somdoron** [comment]
That effort is ongoing and will probably be implemented in a month (during the zeromq hackathon)

**Comment by Schaubli** [comment]
Is there any news on plain username & password authentication being implemented? Wanted to use it to connect to a publisher on the same network but unfortunately it does not seem to be available for .net yet. 
I even thought about implementing the client-side of plain authentication in netmq myself, following [this description](https://rfc.zeromq.org/spec/24/) in the docs but I'm not sure, if I could do it.

Anything else the subscriber has to do for plain authentication except adding username and password to the hello message?

>That effort is ongoing and will probably be implemented in a month (during the zeromq hackathon)

**Comment by Schaubli** [comment]
@somdoron Any update on plain authentication?

**Comment by ahrycej** [comment]
Was authentication added to netmq?

**Comment by vkandrin123456** [comment]
Are there any plans to add authentication?
