### ISSUE TITLE
Missing NetMQPoller.ContainsSocket(NetmqSocket)

### ISSUE THREAD

**Issue by MartijnWoudstra** [zeromq/netmq#621]
I am trying to update my NetMQ. Since NetMQScheduler and Poller are obsolete, i am trying to use 
NetMQPoller. This method does not contain a ContainsSocket method to check if a socket is connected. 

The following code should fix it.

`public boolean ContainsSocket(NetMQSocket socket)
        {
            return m_sockets.Contains(socket)
        }
`

A pull request is also provided

**Comment by drewnoakes** [comment]
To test whether a socket is contained within the poller, the `m_pollinSockets` must be queried on the poller thread. However any thread could call the `Contains` method.

One solution is to introduce `ContainsAsync` which would return a `Task<bool>`.

Making any `Contains` method block for the poller thread seems like opening the possibility for deadlocks.
