### ISSUE TITLE
NNanoMsg integration

### ISSUE THREAD

**Issue by lucmichalski** [zeromq/netmq#624]
Hi guys,

Hope you are all well !

I was wondering if u planned in the roadmap to add Nanomsg to NetMQ ? The respondent/surveyor pattern would be great for distributed requests.

Found this quick attempt for Unity3D: https://plus.google.com/+GregQuincey/posts/WsXgHC4h2PP

Would be awesome !

Cheers,
L.

**Comment by somdoron** [comment]
We can add the specific pattern to netmq, maybe even for zeromq.

**Comment by lucmichalski** [comment]
@somdoron,

It would be awesome, here are an example and blog post from a guy working with the OSRM team.
- https://daniel-j-h.github.io/post/distributed-search-nanomsg-bond/
- https://github.com/daniel-j-h/DistributedSearch

The surveyor pattern would be awesome for Google VR or Web Camera based apps, it would be really useful to lower the energy consumption. (eg. on iOS https://github.com/reqshark/nanomsg.ios/tree/examples)

Ps. ZeroMq and Nanomsg were coded by @sustrik (http://250bpm.com/blog:4)

Cheers,
L.
