### ISSUE TITLE
Mechanism for handling subscription

### ISSUE THREAD

**Issue by cemremengu** [zeromq/netmq#626]
Is there anyway to handle what to do once a subscriber connects to a publisher ?

I want to replay messages once a subscriber connects to my service.

**Comment by somdoron** [comment]
Yes, take a look at the WelcomeMessage property on Publisher.

Or read here:

http://somdoron.com/2015/09/reliable-pubsub/

**Comment by cemremengu** [comment]
Great thanks @somdoron !
