### ISSUE TITLE
Out-of-process actor support ?

### ISSUE THREAD

**Issue by cemremengu** [zeromq/netmq#627]
In [this ](https://netmq.readthedocs.io/en/latest/actor/) example,  the actor is an in-process one. Is there a way to bind an actor to port listening for external (out-of-process) messages ?

**Comment by somdoron** [comment]
No, the protocol is too simple for out of process support.

**Comment by somdoron** [comment]
you can just wrap it with another socket for out of process support

**Comment by cemremengu** [comment]
thanks a bunch @somdoron
