### ISSUE TITLE
SubscriberSocket exception when connection to LAN broadcast address

### ISSUE THREAD

**Issue by brus** [zeromq/netmq#628]
### Environment

```
NetMQ Version:    NetMQ 4.0.0-rc5
Operating System: Win 10
.NET Version:     .NET Framework 4.5
```
### Expected behaviour

NetMQ library should handle error scenarios gracefully.
### Actual behaviour

When I try to connect SubscriberSocket to the network Broadcast address, unhandled exception is thrown in the library.
### Steps to reproduce the behaviour

I will provide come sample.

```
class Program
{
    static void Main(string[] args)
    {
        SubscriberSocket socket = new SubscriberSocket("tcp://10.0.5.255:9100");

        Console.WriteLine("Press any key to finish ...");
        Console.ReadKey();
    }
}
```

When I run the console application internal exception is thrown.
Stack trace:

```text
NetMQ.NetMQException: Exception of type 'NetMQ.NetMQException' was thrown.
   at NetMQ.Core.Transports.Tcp.TcpConnector.OutCompleted(SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.IOObject.OutCompleted(SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

This only happens when network broadcast address is used. If I use any other address 10.0.5.0 - 10.0.5.254 everything is ok.

**Comment by somdoron** [comment]
Can you make a pull request? 
also, we can just try to avoid using broadcast addresses...

**Comment by brus** [comment]
Hi,

I have a problem with building a code after I download it from github.
I'm wondering if there is some kind of Developer guide document which describes how to get the project running (build and run unit tests) on clean machine?

List of errors on build:
Error	CS0006	Metadata file 'C:\data\projekti\open source\netmq\src\NetMQ\bin\Debug\NetMQ.dll' could not be found	NetMQ.SimpleTests	C:\data\projekti\open source\netmq\src\Performance\NetMQ.SimpleTests\CSC	1	Active
Error	CS0006	Metadata file 'C:\data\projekti\open source\netmq\src\NetMQ\bin\Debug\NetMQ.dll' could not be found	NetMQ.Tests	C:\data\projekti\open source\netmq\src\NetMQ.Tests\CSC	1	Active
Error	CS0006	Metadata file 'C:\data\projekti\open source\netmq\src\NetMQ\bin\3.5\Debug\NetMQ.dll' could not be found	NetMQ3.5.Tests	C:\data\projekti\open source\netmq\src\NetMQ.Tests\CSC	1	Active
Error	CS0006	Metadata file 'C:\data\projekti\open source\netmq\src\NetMQ\bin\Debug\NetMQ.dll' could not be found	local_lat	C:\data\projekti\open source\netmq\src\Performance\local_lat\CSC	1	Active
Error	CS0006	Metadata file 'C:\data\projekti\open source\netmq\src\NetMQ\bin\Debug\NetMQ.dll' could not be found	local_thr	C:\data\projekti\open source\netmq\src\Performance\local_thr\CSC	1	Active
Error	CS0006	Metadata file 'C:\data\projekti\open source\netmq\src\NetMQ\bin\Debug\NetMQ.dll' could not be found	remote_lat	C:\data\projekti\open source\netmq\src\Performance\remote_lat\CSC	1	Active
Error	CS0006	Metadata file 'C:\data\projekti\open source\netmq\src\NetMQ\bin\Debug\NetMQ.dll' could not be found	remote_thr	C:\data\projekti\open source\netmq\src\Performance\remote_thr\CSC	1	Active
Error		Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.	NetMQ			
Error		Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore.	NetMQ3.5			
Error		Error occurred while restoring NuGet packages: Error reading 'C:\data\projekti\open source\netmq\src\Performance\local_thr\project.json' at line 11 column 23 : TODO: unknown keyword platform			0	
Error		Error occurred while restoring NuGet packages: Error reading 'C:\data\projekti\open source\netmq\src\Performance\remote_thr\project.json' at line 11 column 23 : TODO: unknown keyword platform			0	
Error		Error occurred while restoring NuGet packages: Error reading 'C:\data\projekti\open source\netmq\src\NetMQ.Tests\project.json' at line 20 column 23 : TODO: unknown keyword platform			0	
Error		Error occurred while restoring NuGet packages: Error reading 'C:\data\projekti\open source\netmq\src\Performance\remote_lat\project.json' at line 11 column 23 : TODO: unknown keyword platform			0	
Error		Error occurred while restoring NuGet packages: The process cannot access the file 'C:\data\projekti\open source\netmq\src\NetMQ\project.lock.json' because it is being used by another process.			0	
Error		Error occurred while restoring NuGet packages: Error reading 'C:\data\projekti\open source\netmq\src\Performance\NetMQ.SimpleTests\project.json' at line 15 column 23 : TODO: unknown keyword platform			0	
Error		Error occurred while restoring NuGet packages: Error reading 'C:\data\projekti\open source\netmq\src\Performance\local_lat\project.json' at line 11 column 23 : TODO: unknown keyword platform			0	
Error		Error occurred while restoring NuGet packages: Error reading 'C:\data\projekti\open source\netmq\src\NetMQ.Tests\project.json' at line 20 column 23 : TODO: unknown keyword platform			0

**Comment by drewnoakes** [comment]
@brus, the project's been updated to VS2017 so (assuming you have that IDE, or Rider) you shouldn't have any build problems any more.

Is there a valid scenario for subscribing to a network broadcast address, or should we just throw in such cases? Is there a .NET API for identifying whether an endpoint is a broadcast address?
