### ISSUE TITLE
Configure AppVeyor build to produce package artifacts

### ISSUE THREAD

**Issue by samcragg** [zeromq/netmq#629]
I'm making use of a local build of NetMQ that includes the changes made in the [Expose internal selector class](https://github.com/zeromq/netmq/commit/f90d675454dd4b36882c4032525d207556620063) commit (I ported some C code to C# that made use of the selector), however, I'm about to share my project so would like a way of others getting hold of the library.

It was discussed in #342 to have an auto deploy to NuGet, which would be ideal, but in the interim would it be possible to get the build to output to the [Artifacts](https://ci.appveyor.com/project/somdoron/netmq-2bhss/build/1.0.59/artifacts) on AppVeyor so I could at least get them to download an official (but development quality) build?

Thanks

**Comment by drewnoakes** [comment]
FYI 4.0.0.1 is now on NuGet.

https://www.nuget.org/packages/NetMQ/

It might still be worth getting artifacts from AppVeyor builds.
