### ISSUE TITLE
Uncaught exception when receiving "bad" data (from non-0mq application)

### ISSUE THREAD

**Issue by examinus-** [zeromq/netmq#632]
### Environment (unrelated in this problem I believe)

    NetMQ Version:    3.3.3.4, 4.0.0.1-rc1, 4.0.0.0-rc5, and manually built from latest commit (52c91fb)
    Operating System: Win7 Pro x64, Windows Server 2012 R2 (x64)
    .NET Version:     4.6.2 (unrelated I believe)
    IDE:           VS2013 Pro, also tried with VS2015 Pro trial version

### Expected behaviour
   I think bad/broken data should be dropped either silently or with some kind of event/signalling in case applications want to log this.
   

### Actual behaviour
   Random uncaught "Exception" (OutOfMemoryException, OverflowException, ...) in NetMQPoller thread crashing the server application.
   I believe the place where the Exceptions happen is irrelevant.

### Steps to reproduce the behaviour
   

1. Starting a server with a Router socket (Response socket gave the same problems, I didn't try others) and a Poller on it.
2. Separate program is connecting to the server socket, sending random data then disconnecting (repeating every few seconds, data size is also random - longer than 64k)

### Source of the problem:
   NetMQ.Core.Transports.V1Decoder:

        private bool EightByteSizeReady()
        {
            m_tmpbuf.Reset();

            //  8-byte payload length is read. Allocate the buffer
            // for message body and read the message data into it.
            long payloadLength = m_tmpbuf.GetLong(Endian, 0);

            // There has to be at least one byte (the flags) in the message).
            if (payloadLength == 0)  // <- attention here
            {
                DecodingError();
                return false;
            }

Due to the nature of the data (being random, not originating from other 0MQ applications, the payloadLength CAN be negative, which means the condition needs to check for that too:

       private bool EightByteSizeReady()
        {
            m_tmpbuf.Reset();

            //  8-byte payload length is read. Allocate the buffer
            // for message body and read the message data into it.
            long payloadLength = m_tmpbuf.GetLong(Endian, 0);

            // There has to be at least one byte (the flags) in the message).
            if (payloadLength <= 0)  // <- all exceptions gone
            {
                DecodingError();
                return false;
            }

- Can anyone verify that this change doesn't "break" the normal behaviour of the library? 
      I did run (very little) tests and didn't find any problems...

Servers that are "open" to the Internet and need to run 24/7 should suffer from these problems the minimum possible...

Unrelated: 
    I had a lot of problems to manually build the project after clean checkouts (couldn't restore nuget packages, missing referenced (source) file, c#6.0 support was not working on my pc, etc.) so I do not want to make a PR.
   Because of this I ended up removing all subprojects except NetMQ, and "redoing" the sln+csproj files, as well as "translating" all the new c#6.0 features...

**Comment by michal-ordelt** [comment]
https://github.com/NetMQ/NetMQ3-x/pull/8

I have NetMQ with this change, running since I created the pull request. I did not notice any 'break' in normal behavior.

**Comment by examinus-** [comment]
Oh, I forgot to check the v3 repo... but it's good that someone else has the same problem/solution.

Until this is included in the official package, we will have to keep using our custom build...

Thank you @michal-ordelt
