### ISSUE TITLE
Subscriber using bind and pgm crashes after unplugging cable when Publisher is on the same host.

### ISSUE THREAD

**Issue by leguanjoe** [zeromq/netmq#636]
### Environment

    NetMQ Version:    3.3.3.4 and 4.0.0-rc5
    Operating System:  Windows 7
    .NET Version:     4.6.2

### Expected behaviour
Either nothing or a possibility to catch the exception.

### Actual behaviour
System.Net.Sockets.SocketExeption in AsyncIO.dll 

### Steps to reproduce the behaviour
Hi,
I know that this might seem like an odd configuration, but I'm bound to some restrictions on my project.
This is my adapted test publisher:

```
using System;
using NetMQ;
using NetMQ.Sockets;

namespace PGMPubTest
{
    class Program
    {
        private const int MEGA_BIT = 1024;
        private const int MEGA_BYTE = 1024;

        static void Main(string[] args)
        {
            using (var pub = new PublisherSocket())
            {
                pub.Options.MulticastHops = 2;
                pub.Options.MulticastRate = 40 * MEGA_BIT; // 40 megabit
                pub.Options.MulticastRecoveryInterval = TimeSpan.FromMinutes(10);
                pub.Options.SendBuffer = MEGA_BYTE * 10; // 10 megabyte

                pub.Connect("pgm://172.16.1.1;239.0.0.200:5554");

                string input = null;
                while ((input = Console.ReadLine()) != "quit")
                {
                    try
                    {
                        if (pub.TrySendFrame(input))
                        {
                            Console.WriteLine(string.Format("Message: {0} was sent\n", input));
                        }
                        else
                        {
                            Console.WriteLine(string.Format("Message: {0} was not sent\n", input));
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("Exception: " + ex.ToString());
                    }
                }
            }
        }
    }
}
```

This is the Subscriber:
```
using NetMQ;
using NetMQ.Sockets;
using System;

namespace PGMSubTest
{
    class Program
    {
        private const string SUBSCRIBE_TOPIC_COMMAND = "s";
        private const string UNSUBSCRIBE_TOPIC_COMMAND = "u";
        private const int MEGA_BIT = 1024;
        private const int MEGA_BYTE = 1024;

        public static void Main(string[] args)
        {
            using (var sub = new SubscriberSocket())
            {
                sub.Options.ReceiveBuffer = MEGA_BYTE * 10;
                sub.Bind("pgm://172.16.1.1;239.0.0.200:5554");

                var poller = new NetMQPoller();
                poller.Add(sub);
                sub.ReceiveReady += (s, e) =>
                {
                    HandleOnReceiveMessage(e);
                };
                poller.RunAsync();
                Console.WriteLine("Write \"quit\" to exit");
                Console.WriteLine("");
                Console.WriteLine("Write \"s [topic]\" to subscriber a topic");
                Console.WriteLine("Write \"u [topic]\" to unsubscriber a topic");
                Console.WriteLine("");
                string input;
                while ((input = Console.ReadLine()) != "quit")
                {
                    var separatorIX = input.IndexOf(' ');
                    if (separatorIX == -1)
                    {
                        Console.WriteLine("Command not valid! Please use \" \" to separate command from the message");
                    }
                    else
                    {
                        ProcessCommand(sub, input, separatorIX);
                    }
                }
            }
            Console.ReadLine();
        }

        private static void HandleOnReceiveMessage(NetMQSocketEventArgs e)
        {
            Console.WriteLine("messageReceived= {0}", e.Socket.ReceiveFrameString());
        }

        private static void ProcessCommand(SubscriberSocket sub, string input, int separatorIX)
        {
            var command = input.Substring(0, separatorIX);
            var message = input.Substring(separatorIX + 1, (input.Length - 1) - separatorIX);
            switch (command)
            {
                case SUBSCRIBE_TOPIC_COMMAND:
                    sub.Subscribe(message);
                    break;
                case UNSUBSCRIBE_TOPIC_COMMAND:
                    sub.Unsubscribe(message);
                    break;
                default:
                    Console.WriteLine("Command not supported!");
                    return;
            }
            Console.WriteLine("Command processed!\n");
        }
    }
}

```
Both have to run on the same host for the exception to occur and the Subscriber needs to be bound to a specific NIC e.g:  pub.Connect("pgm://172.16.1.1;239.0.0.200:5554");. After starting both applications, subscribing to a topic and sending messages I unplug the cable. When I now send a message, the Subscriber still seems to receive something, or is at least triggered, since  GetMultipleQueuedCompletionStatus in Proactor.cs->Loop() returns true. OperationType is Receive and Incompleted() in PgmSession.cs is called where bytesTransferred == 0 and Error() is called so that the session gets disposed. When I send a Second message, again GetMultipleQueuedCompletionStatus in Proactor.cs->Loop() returns true, OperationType is Accept and Incompleted() of PgmListener is called. This leads to InitOptions() where trying to set the receive interface throws the unhandled SocketException "An invalid argument was supplied" in AsyncIO.Windows.Socket.SetSocketOption.
Here is the part of the PgmSocket where the exception occurs: (starting at line 159)

```
         // set the receive interface on the listener and receiver
            if (m_pgmSocketType == PgmSocketType.Listener || m_pgmSocketType == PgmSocketType.Receiver)
            {
                if (m_pgmAddress.InterfaceAddress != null)
                {
                    Handle.SetSocketOption(PgmLevel, RM_ADD_RECEIVE_IF, m_pgmAddress.InterfaceAddress.GetAddressBytes());
                }
            }
```

I know that Net.Sockets can be bound to a Socket even when the cable is unplugged (if it was once plugged in and the NIC has been initialized). Does anybody see a similar possibility here?

If I put a try catch block around this specific SetSocketOption, the first message is still lost when the cable is unplugged (since the socket gets disposed) but all following messages are received. But I loose the binding and in addition, a Listener with an unplugged cable at the beginning does not throw an exception on pub.Bind("pgm:/...) anymore, which might be wanted in other cases. 

Any ideas how to fix this?

**Comment by leguanjoe** [comment]
I've come up with a solution and will send a pull request, soon. Basically I've added an if-case in PgmListener.cs InCompleted(), which checks if RemoteEndPoint equals IntefaceAddress and then tries to set the Socket option, if it fails, the cable is still unplugged and the socket will be disposed and Accept() is called.

**Comment by leguanjoe** [comment]
Update: Subscribers on different hosts also crash at the same point after the cable is plugged in again and data is send immediately. Since the crash has the same issue (trying to bind to a socket wich is not ready (yet)), I will add a fix to my pull request.

**Comment by somdoron** [comment]
can we close this?

**Comment by leguanjoe** [comment]
yes
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 22.01.17, 14:56, Doron Somech <notifications@github.com> schrieb:

  
    
      can we close this?
