### ISSUE TITLE
Compatible with ZeroMQ 4.2.0?

### ISSUE THREAD

**Issue by beevik** [zeromq/netmq#641]
I couldn't find an answer in the README or other documentation, so I'm asking here.

Is the current release of NetMQ compatible with other endpoints running ZeroMQ 4.2?  I'm planning to write a server in C++ using 4.2, but I want to know if a NetMQ-based client will be compatible with it before I begin.

Thanks.

**Comment by somdoron** [comment]
Yes. But NetMQ doesnt support curve

**Comment by beevik** [comment]
Ok thanks.
