### ISSUE TITLE
Powershell Examples

### ISSUE THREAD

**Issue by carlskii** [zeromq/netmq#645]
Hi,

Is there any chance of providing some simple PowerShell examples?

**Comment by chuckmoore55** [comment]
Hi Carlskii,

I've attached:
1) a PowerShell netmq test-script ("test_netmq"), with file-extension changed to something GitHub will accept, we use to verify its basic functionality after network/application changes.
2) a screen-shot of the test-script functioning as a server
3) a screen-shot of the test-script functioning as a client

To run it: (using, say, your $env:TEMP directory)
1) download script and change file-extension back to '.ps1'
2) copy into the same directory 'NetMQ.dll' and 'AsyncIO.dll' (I suggest V3.3.3.4 or thereabouts)
3) start a PowerShell session, 'cd' to where the test-script is, then run the test-script with role 'server' (see screenshot)
4) start another PowerShell session, 'cd' to where the test-script is, then run the test-script with role 'client'

If my copy/pasting didn't work, please let me know and I'll cut/paste the test-script's text into a message.

Chuck
------------------------------------------------------------------------------------------
![client](https://cloud.githubusercontent.com/assets/5016286/24057835/0a2942fe-0b06-11e7-9587-1a3d726db582.png)
![server](https://cloud.githubusercontent.com/assets/5016286/24057836/0a29eaba-0b06-11e7-8971-9c4d4877f533.png)
[test_netmq.ps1.txt](https://github.com/zeromq/netmq/files/851460/test_netmq.ps1.txt)

**Comment by carlskii** [comment]
Thanks, eventually found time to try this. This is the output.

```
PS C:\Program Files\Venafi\Scripts\AdaptableCA> .\netmq.ps1 -role 'client'
role: client
msg: test msg
address: 127.0.0.1
port: 5556
protocol: tcp
usepolling: False
workarea: 
Unable to find type [netmq.netmqcontext].
At C:\Program Files\Venafi\Scripts\AdaptableCA\netmq.ps1:39 char:13
+ $_context = [netmq.netmqcontext]::create()
+             ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (netmq.netmqcontext:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
new-object : Cannot find type [netmq.sendreceiveoptions]: verify that the assembly containing this type is loaded.
At C:\Program Files\Venafi\Scripts\AdaptableCA\netmq.ps1:40 char:24
+ $_sendreceiveoptions = new-object netmq.sendreceiveoptions            ...
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
 
initiating role CLIENT
You cannot call a method on a null-valued expression.
At C:\Program Files\Venafi\Scripts\AdaptableCA\netmq.ps1:58 char:9
+       { $_socket = $_context.createrequestsocket()                    ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\Program Files\Venafi\Scripts\AdaptableCA\netmq.ps1:59 char:9
+         $_socket.connect( $_connection_string )                       ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Error: Unable to send message to server
```

**Comment by chuckmoore55** [comment]
Hi,

At first glance, it looks like whatever the 'add-type -path ( $pwd.path + '\netmq.dll' )' line actually loaded was not sufficient to allow the creation of a 'context'. You might want to use the 'get-member' cmdlet to investigate what is available for the particular version of netmq (that was) loaded. I'll help as best my time allows.
Chuck

**Comment by drewnoakes** [comment]
I think @chuckmoore55's script is using NetMQ 3.x, and @carlskii is using 4.x. The `NetMQContext` class is no longer in use.

Instead you can just new up the socket directly.
