### ISSUE TITLE
NetMQ Async/Await?

### ISSUE THREAD

**Issue by fholm** [zeromq/netmq#647]
I've noticed there isn't any async/await API, and I'm currently trying to integrate NetMQ 4.0 into an existing backend which is built completely on async/await. I found one blog post from @somdoron but it seems to use an outdated API with NetMQContext and NetMQScheduler which doesn't exist in the library version I'm using at least.

Is there any more recent documentation or examples of using NetMQ with async/await? I realize this is not really an "issue", more like a feature request or a request for more documentation.

**Comment by drewnoakes** [comment]
Sounds like you're reading docs for v3. Please check out the migration guide for v4.

https://github.com/zeromq/netmq/wiki/Migrating-to-v4

It's mostly the same, but a few classes were merged, renamed, and the context is no longer needed.

**Comment by fholm** [comment]
@drewnoakes hi, yes you are right! I've found partially what I needed, but I'm still at a loss on how to setup the poller properly. My case is this, if it helps:

* I have one "Pull" socket which I need to receive data from (async)
* I have several "Push" sockets which I need to send data through for further processing in the backend (these are you just round-robin-ed by indexing through an array, since all works they do is 100% identical, i.e. just forwarding data to the correct node on the backend).

Now, sending through the push socket seems to go something like this:

```
Task.Factory.StartNew(() => socket.SendFrame(data), CancellationToken.None, TaskCreationOptions.None, poller);
```

But I have no idea how to go about receiving data from the pull socket through the poller? There is an "NetMQPoller.Add" method which takes a socket and a callback, but there's no documentation around this - is this for registering a socket with the poller and the callback for received data? I can of course fairly easily wrap the PullSocket in it's own thread it's own task completion source, etc. but it seems like if this stuff already exists somewhere it'd be silly to re-implement it in a probably sub-optimal way.

If anyone can point me in the correct direction and I get a working example I'd happily write up something for the documentation and do a PR to make this easier for people in the future.

**Comment by drewnoakes** [comment]
The overload that accepts a socket and callback is for `System.Net.Sockets.Sockets` (i.e. not a NetMQ socket type). It's probably not what you want. You should just add your `PullSocket` and `PushSocket` directly.

Have you read any documentation or examples about the `ReceiveReady` event?

In a nutshell, once you add a receiving socket (i.e. `PullSocket`) to the poller, and the poller is running, then the socket's `ReceiveReady` event fires whenever you can receive from the socket without blocking.

**Comment by somdoron** [comment]
You can find some examples here:

https://github.com/somdoron/NetMQ.High

**Comment by somdoron** [comment]
By the way, NetMQ has async/await mow
