### ISSUE TITLE
Should we move to VS2017?

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#648]
Now that VS2017's out, should we move to it?

Benefits would be:

- Ability to target multiple platforms with simpler csproj files, and a single solution/build
- Ability to use some C# 7 stuff (though without changing the public API, for now at least)

Any thoughts?

**Comment by somdoron** [comment]
I only hope Rider support new csproj file.

Other than that I'm for it.

**Comment by drewnoakes** [comment]
I didn't realise Rider wasn't there yet. Jura suggests initial support should be released any day in the next EAP: https://youtrack.jetbrains.com/issue/RIDER-3777

I migrated [another project](https://github.com/drewnoakes/metadata-extractor-dotnet) recently and the experience was relatively smooth. Will put a PR together for this too.

**Comment by drewnoakes** [comment]
Do we need to explicitly target `monoandroid60`? I'm not familiar with Mono/Xamarin development, and I don't have the tools installed (they're about 30GB in size IIRC). I'm getting compile errors due to this.

Seems Xamarin are moving towards .NET Standard support.

https://blog.xamarin.com/net-standard-library-support-for-xamarin/
