### ISSUE TITLE
NetMQ Performance Profiling issue

### ISSUE THREAD

**Issue by abhijitparkhi1983** [zeromq/netmq#653]
### Environment

    NetMQ Version:    version 4
    Operating System: Windows 7 Professional
    .NET Version:   4.6.1 
    Tool for code Profiling: YourKit Profiler 2017.02-b53
    Code Profiled: **ROUTERbrokerDEALERworkers** project from the sample codes at **https://github.com/NetMQ/Samples** 

### Expected behavior:

Not sure if this is a expected behavior. But according to my understanding, it should not consume 65% of Time for processing. 

### Actual behaviour

65% of the total processing time is taken by **NetMQ.Core.Utils.Proactor.Loop()**

### Steps to reproduce the behavior:
Run YourKit Profiler 2017.02-b53 on the **ROUTERbrokerDEALERworkers.exe** for **CPU Tracing** option.

**Comment by somdoron** [comment]
This is the method of the background IO that do all the work.

I'm not sure I understand the measurement, was it active 65% of processing time sounds reasonable, the question is does processing time includes idle time?

Anyway if I understand that correctly it sounds ok

**Comment by abhijitparkhi1983** [comment]
@somdoron  Thanks for a quick reply.

I guess its the Processing Time taken by  NetMQ.Core.Utils.Proactor.Loop() in the overall application processing time.

When we run the Visual Studios Profiler on the sample using **Performance Wizard** option and **CPU Sampling** method, we get  **Hot Path** which indicates that Function Name **NetMQ.Core.Utils.Proactor.Loop()**, Function Name **NetMQ.Core.Utils.Poller.Loop()** and 
Function Name **NetMQ.NetMQConfig.OnCurrentDomainOnProcessExit(object,class System.EventArgs)**  shows **33%** under the **Inclusive Samples%** column.

I am comparatively new to Profiling and belive that this 33% is the execution time taken in the total execution time required for running the sample using profiler.

Am I missing on some thing

**Comment by somdoron** [comment]
What load?  the NetMQ.NetMQConfig.OnCurrentDomainOnProcessExit suggest you are running the application for very short time.

Also, which NetMQ version are you running?

**Comment by abhijitparkhi1983** [comment]
I am using the Version 4 for NetMQ.

Yes the sample application provided is a very small application so the application will run for a short time. 

The NetMQ.NetMQConfig.OnCurrentDomainOnProcessExit suggest you are running the application for very short time.:  But then what does the value **33%** under the Inclusive Samples% column suggests ?

Can you please let me know what do u mean by **What load?**. Dint get it.

**Comment by somdoron** [comment]
OnCurrentDomainOnProcessExit tear down the resource netmq uses, for very short live application that making sense, also for the Poller.Loop.

Regarding the what load, how busy is the process during this time, how many sockets, messages, etc... Anyway profiling very short live process is hard. Use the profiler timeline to not include the setup and tear down of the process.

Also, for what purpose is this? are you suffering from performance? in a short live process?

**Comment by abhijitparkhi1983** [comment]
**_Our Scenario:_**
We are using NetMQ lib for a two way communication between two applications. We would like to leverage the facilities provided by NetMQ like asynchronous message queues.

On one side we have a .NET Based application which uses NetMQ for sending several thousand JSONs to the receiver (a java application) and the receiver in turn sends back a response to each of the sent JSON's.

On the .NET application side, we are using **DealerSocket** of NetMQ for creating the required socket.
We are creating a pool of 4 such DealerSocket's which sends the mentioned JSON files on 4 threads.
When we start the application, we initialize this pool of 10 DealerSocket's and call the **.Connect** method on each of these DealerSocket.

When the JSONs are ready to be sent, we serialize it them to NetMQ.Msg and send the  NetMQ.Msg using **.Send** method of the DealerSocket. In the same flow we also call the **.TryReceive**  method for reading the response from the java receiver application.

Once all the JSON's are sent, we call **Disconnect** method on all the pooled DealerSocket's and dispose them as well.

**_Sampling Performance:_**

1.  1000 JSONs creation + serialization and sending JSON and receiving response over 10 sockets: 
          - 21% for the actual JSON creation + socket pool creation and serialization.
          - **29% of total time taken by **NetMQ.Core.Utils.Proactor.Loop()**
          - **29% of total time taken by **NetMQ.Core.Utils.Poller.Loop()**
          - Remaining 21 % for few other tasks together. 
          - **Socket Details:** 
                 **Open: 12**
                 **Close: 2**
2.  2000 JSONs creation + serialization and sending JSON and receiving response over 10 sockets: 
          - 25% for the actual JSON creation + socket pool creation and serialization.
          - **33% of total time taken by **NetMQ.Core.Utils.Proactor.Loop()**
          - **33% of total time taken by **NetMQ.Core.Utils.Poller.Loop()**
          - Remaining 8 % for few other tasks together.
          - **Socket Details:** 
                 **Open: 16**
                 **Close: 5**

Please let me know if you require any further information. I will try running the Profiler by excluding settingup and tear down mechanism.

**Comment by somdoron** [comment]
And you suffer from any performance issues?  The numbers are making sense, the background IO threads are the one taking processing time. 

With netmq/zeromq you dont really need multiple coonections, you can use one dealer,  but your protocol will have to be async.  The only reason to have multiple sockets is if you want to serialize on all cores.
