### ISSUE TITLE
AsyncIO  doesn`t support by Windows XP (2003)  in old version

### ISSUE THREAD

**Issue by imiyu** [zeromq/netmq#654]
### Environment

    NetMQ Version:    4.0
    Operating System: xp
    .NET Version:     4.0

### Expected behaviour
update AsyncIO 
https://github.com/somdoron/AsyncIO/commit/5bdf1dc6ced51b8aa06a26cd3f2bb10561dbefb8

**Comment by somdoron** [comment]
can you make a pull request?
