### ISSUE TITLE
Removing from a poller and disposing

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#656]
Consider:

```csharp
poller.Remove(socket);
socket.Dispose();
```

This code is fine if you run it from the poller thread, however if you run it from another thread there is a race. The poller will queue the removal of the socket, which will happen asynchronously. The socket will be disposed synchronously. Therefore there's a good chance of an `ObjectDisposedException` against the socket in the short time before the poller removes it.

The current workaround is:

```csharp
new Task(() => {
    poller.Remove(socket);
    socket.Dispose();
}).Start(poller);
```

I'm wondering if we can make this a bit nicer by making the `Run` method public:

```csharp
poller.Run(() => {
    poller.Remove(socket);
    socket.Dispose();
});
```

Or even:

```csharp
poller.RemoveAndDispose(socket);
```

**Comment by somdoron** [comment]
I like both...

**Comment by mrausch** [comment]
I would be very grateful if this makes it into a release soon ;)
