### ISSUE TITLE
For long running applications, Exception of type 'NetMQ.NetMQException' was thrown with TooManyOpenSockets error code.

### ISSUE THREAD

**Issue by abhijitparkhi1983** [zeromq/netmq#658]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: Windows 7
    .NET Version:    4.6.1 

### Steps to reproduce the behaviour
We have a application where we are using NetMQ's **DealerSocket** to communicate between two sources.
We have created a Class having a **DealerSocket** as instance member like below:
```
public class NetMQRequestor : IDisposable
    {
        private readonly DealerSocket clientSocket;
        private readonly string connectionString;

        public NetMQRequestor(string connString, JsonData msgBuilder)
        {
                clientSocket = new DealerSocket();
                connectionString = connString;
                clientSocket.Connect(connString);
        }

        public byte[] SendMessage(Msg msgPool)
        {
            clientSocket.Send(ref msgPool, false);

            //Receive Response
            bool isRevd = clientSocket.TryReceive(ref msgPool, TimeSpan.FromSeconds(10));

            if (!isRevd || msgPool.Data == null)
            {
                throw new Exception("Error in receiving Response. Value of isRevd is false or received Data is null");
            }

            return msgPool.Data;
        }

        public void Dispose()
        {
            clientSocket?.Disconnect(connectionString);
            clientSocket?.Dispose();
            GC.SuppressFinalize(this);
        }
    }
```
We create a **ObjectPool** of the above **NetMQRequestor** class using following code: 

```
public class ObjectPool<T>
    {
        private readonly ConcurrentBag<T> objects;
        private readonly Func<T> objectGenerator;

        public ObjectPool(Func<T> objectGenerator)
        {
            if (objectGenerator == null)
                throw new ArgumentNullException("objectGenerator");

            objects = new ConcurrentBag<T>();
            this.objectGenerator = objectGenerator;
        }

        public List<T> GetObjects()
        {
            if (objects.Count > 0)
                return objects.ToList();

            objects.Add(objectGenerator());
            return objects.ToList();
        }

        public T GetObject()
        {
            T item;
            return objects.TryTake(out item)
                ? item
                : objectGenerator();
        }

        public void PutObject(T item)
        {
            objects.Add(item);
        }
    }

   public class NetMQObjectPoolManager
    {
        private readonly ParallelOptions parallelOptions;
        private readonly ObjectPool<NetMQRequestor> netMqObjectPool;

        public NetMQObjectPoolManager(string connectionString, int maxDegreeOfParallelism)
        {
            parallelOptions = new ParallelOptions { MaxDegreeOfParallelism = maxDegreeOfParallelism };

            netMqObjectPool = new ObjectPool<NetMQRequestor>(() => new NetMQRequestor(connectionString));

            for (int i = 0; i < parallelOptions.MaxDegreeOfParallelism; i++)
            {
                netMqObjectPool.PutObject(new NetMQRequestor(connectionString));
            }
       }
       public NetMQRequestor GetAvailableNetMQRequestorFromThePool()
       {
            return netMqConnection .GetObject();
       }
       public void Dispose()
        {
                foreach (var netMqConnection in netMqObjectPool .GetObjects())
                {
                    netMqConnection.Dispose();
                }
        }
    }
```

Where the **maxDegreeOfParallelism** value represents the maximum number of **NetMQRequestor** objects (i.e. maximum number of **DealerSocket**) to be created in the pool. 
We do the first handshake request using a separate **NetMQRequestor (i.e. a separate DealerSocket)** object. Using this handshake request, we get the actual **connectionString** to start communication on for the **NetMQRequestor** objects in the  ObjectPool.

**Our assumption:**
With every **DealerSocket.Connect(connectionString)** call, **Only one socket will be created**. 
Therefore if in the above case, if **maxDegreeOfParallelism** value is 10, with the ObjectPool in place, **only 10 sockets would be created which will be reused** till the **NetMQObjectPoolManager's Dispose** is called.  

### Expected behaviour
Only Limited Number of Sockets should be created based on the **maxDegreeOfParallelism** value.

### Actual behaviour
For long running applications, Exception of type 'NetMQ.NetMQException' was thrown with TooManyOpenSockets error code.

**Comment by oocpawel** [comment]
Hello,
Maybe You should use RouterSocket to connect with source and behind it DealerSocket to deliver requests to workers? I am using that model, and in the end I have one TCP connection and internal multiple InProc connections to Workers.

So it should looks like this: 
DEALER =>(TCP)=> ROUTER=>DEALER => (INPROC) => DEALER(Or other socket, I am using here RESPONSE socket)

**Comment by abhijitparkhi1983** [comment]
@oocpawel 

Thanks for your reply. If I understand it right, the RouterSocket is supposed to be used in conjunction with the DealerSocket where in the RouterSocket sits on the server and the the various client DealerSockets communicate with the servers RouterSocket.

With this understanding, I am not able to get what you are trying to say. Can you share some code?
Or may be some link which will help me in understanding your view in a better way.

**Comment by abhijitparkhi1983** [comment]
@somdoron, Can you please give me some input on this??
We are using a RouterDealer pattern where in the RouterSocket is in a java server application and DelearSocket is getting created in the C# client application. 
The communication between client and server cannot be asynchronous in our scenario.

So in the C# application, as mentioned by @oocpawel, I do not think we can have any RouterSocket
I can share the entire code where i am getting this error. 
Please assist.

**Comment by oocpawel** [comment]
Well every time that you are creating this thing:
![2017-04-18_1344](https://cloud.githubusercontent.com/assets/3284247/25129166/22ed9ac4-243d-11e7-8811-c23159bf8a1d.png)

You are creating 3 TCP connections. I have making something like this in my application, but for hundred of sockets (Not Dealer Sockets but Requests Sockets but I think You could use my workaround in Your project), and it was simply throwing TooManyOpenSockets error on Debian-Mono and Windows .Net Core (it was fine on Windows .Net Framework, but maybe it is clearing sockets much more faster)

as a workaround I have made something like this:
![2017-04-18_1347](https://cloud.githubusercontent.com/assets/3284247/25129285/9d6fabf2-243d-11e7-9919-e8e7fecd5850.png)

and right now it is working like a charm. This Router-Dealer conjunction looks like this:

`public class IpcCollectorDevice 
{
        private NetMQPoller _poller;
        private RouterSocket _frontendSocket;
        private DealerSocket _backendSocket;
        private readonly string _backEndAddress;
        private readonly string _frontEndAddress;
        private readonly ManualResetEvent _semaphoreStart = new ManualResetEvent(false);
        private readonly Thread _collectorThread;

        public IpcCollectorDevice(string frontEndAddress, string backEndAddress)
        {
            _backEndAddress = ">" + backEndAddress; //connect address
            _frontEndAddress = "@" + frontEndAddress; //bind address

            _collectorThread = new Thread(DoWork) { Name = "IPC Collector Device Thread" };
        }

        public void Start()
        {
            _collectorThread.Start();
            _semaphoreStart.WaitOne();
        }

        public void Stop()
        {
            _poller.Stop();
        }

        private void DoWork()
        {
            try
            {
                _poller = new NetMQPoller();

                using (_frontendSocket = new RouterSocket(_frontEndAddress))
                using (_backendSocket = new DealerSocket(_backEndAddress))
                {
                    _backendSocket.ReceiveReady += OnBackEndReady;
                    _frontendSocket.ReceiveReady += OnFrontEndReady;

                    _poller.Add(_backendSocket);
                    _poller.Add(_frontendSocket);

                    _semaphoreStart.Set();

                    _poller.Run();
                }
            }
            catch (Exception e)
            {
                Logger.Fatal("Unhandled error in IPC Collector Device Thread, Thread is closing.", e);
            }
        }

        private void OnBackEndReady(object sender, NetMQSocketEventArgs e)
        {
            NetMQMessage message = _backendSocket.ReceiveMultipartMessage();
            _frontendSocket.SendMultipartMessage(message);
        }

        private void OnFrontEndReady(object sender, NetMQSocketEventArgs e)
        {
            NetMQMessage message = _frontendSocket.ReceiveMultipartMessage();
            _backendSocket.SendMultipartMessage(message);
        }

    }`

So there is one thread which is resending every messasge from inproc connections to one TCP connection. I am using it for Synchronous calls and Aynchronous calls too. This  IpcCollectorDevice  is only to use one TCP.

**Comment by abhijitparkhi1983** [comment]
@oocpawel 
Thanks for the inputs. Looks interesting. Will try your code and will let you know soon
