### ISSUE TITLE
Missing xml docs on nuget package 4.0.0.1

### ISSUE THREAD

**Issue by AbirAtur** [zeromq/netmq#660]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System:  Windows
    .NET Version:     4.5/3.5

### Expected behaviour
Navigating to NetMQ dll should display xml summaries for types\members. 
it seems they are not packaged with 4.0.0.1. (but they are packaged with 3.x)

**Comment by drewnoakes** [comment]
Seems [`NetMQ.csproj`](https://github.com/zeromq/netmq/blob/master/src/NetMQ/NetMQ.csproj#L23) is missing the following from the opening `<PropertyGroup>`:

```xml
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
```

Can you make a pull request?

**Comment by AbirAtur** [comment]
done. please note that only when this option was added, the xml file was generated:
`<GenerateDocumentationFile>true</GenerateDocumentationFile>`

thanks

**Comment by drewnoakes** [comment]
Nice.

These will be in the next release.
