### ISSUE TITLE
Should NetMQPoller.Remove(Socket) throw if the socket is already disposed?

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#663]
### Current behaviour

If a socket in the poller has been disposed, then `the `poller.Remove(ISocketPollable)` method will not throw. 

A disposed NetMQ socket in the poller can cause errors. `Select` operations internal to the poller may trigger `ObjectDisposedException`. It is not safe to have a disposed socket in the poller.

It is easy to get into that state, as discussed in #656. User code removes the socket from the poller, then disposes it:

```csharp
poller.Remove(socket);
socket.Dispose();
```

Problems related to this state may be quite infrequent, but may crash the program or log errors at exit.

Debugging these errors is hard because it is not obvious that `poller.Remove` can run asynchronously if not called from the poller thread, so it seems like a bug in NetMQ that the poller still contains the socket.

### Possible behaviour

We should make it easier to avoid getting into this state, as discussed in #656. However we can also help detect this state as soon as the bug is introduced.

Once detected, should we throw an exception? This would be the clearest way of getting a developer's attention, but it might start throwing exceptions in code that currently appears to work, because of the nature of the race condition. Personally I'd appreciate finding out, though not in production.

```csharp
public void Remove(ISocketPollable socket)
{
    if (socket == null)
        throw new ArgumentNullException(nameof(socket));
    if (socket.IsDisposed)
        throw new ArgumentException("Must not be disposed.", nameof(socket));
    CheckDisposed();

    Run(() =>
    {
        // Ensure the socket wasn't disposed while this code was waiting to be run on the poller thread
        if (socket.IsDisposed)
            throw new InvalidOperationException(
                $"{nameof(NetMQPoller)}.{nameof(Remove)} was called from a non-poller thread, " +
                "so ran asynchronously. " +
                $"The {socket.GetType().Name} socket being removed was disposed while the remove " +
                $"operation waited to start on the poller thread. Use {nameof(RemoveAndDispose)} " +
                "instead, which will enqueue the remove and dispose to happen on the poller thread.");

        socket.Socket.EventsChanged -= OnSocketEventsChanged;
        m_sockets.Remove(socket.Socket);
        m_isPollSetDirty = true;
    });
}
```

I can put a PR together for this, but want to hear whether introducing this new exception is a good idea or not.

It'd also require adding `ISocketPollable.IsDisposed`.

**Comment by drewnoakes** [comment]
I edited the post to fix a few errors.

**Comment by somdoron** [comment]
I think it is a good idea.

**Comment by jasells** [comment]
I am still seeing this issue.  This code:

````
poller.Remove(socket);
socket.Dispose();
````

Cause an ```ObjectDisposedException``` error to throw on the poller's thread from ```SocketBase.CheckDisposed()```, and kill my unit test runtime.  

There needs to be some better syncing on ```Poller.Remove()``` so that it blocks the the poller's thread and/or the caller of ```Remove()``` such that the ```Remove``` does not return until that socket is _actually_ removed from the poller's internal list.  This is the issue as it is currently written. 

I would argue that ```CheckDisposed()``` should return a bool so that poller can not try to access that socket, and avoid throwing the exception.

I can't find a path to calling ```Socket.Dispose()``` after it has been passed to ```Poller.Add(Socket)``` that doesn't throw.
