### ISSUE TITLE
Determining if a Subscriber Connect() actually connected

### ISSUE THREAD

**Issue by Necrolis** [zeromq/netmq#673]
Is there any reliable way other than receiving actual data to determine if a `Connect()` call on a `SubscriberSocket` actually connected to a publisher? 

Point of this is to tell if the remote endpoint actually exists or is available, rather than assuming the absence of data means there was an issue (because it might not). This is especially helpful when the endpoints/publisher one connects to are dynamic.

**Comment by steamrolla** [comment]
See @somdoron's post [here](http://somdoron.com/tag/netmq-pubsub/) on using a Welcome Message.

**Comment by Necrolis** [comment]
Seems to be just what I needed, thanks!
