### ISSUE TITLE
Subscribe or Unsubscribe while receiving 

### ISSUE THREAD

**Issue by chrischandler25** [zeromq/netmq#679]
I would like to be able to add and remove subscriptions from my subscriber socket while it is actively receiving. 

I'm essentially trying to create a basic and lightweight pub sub system, and it's essential that subscriptions can be changed dynamically. I can't find any examples of this in sample code, as it is always assumed that subscriptions are known up front. 

My question is around the threading of this. I have set it up using a dedicated thread to create the socket and sit in a receive loop, which works well, but as receive is blocking, I have no way of then adding a subscription, even if I can dispatch it to that thread (via blocking queue etc). 

Using a poller seemed like an option, but if started with runasync, the receive events come on a different thread, so I'm concerned that any subscribe or Unsubscribe calls on the creation thread violate the no-sharing principle. 

The only option I can currently see is putting a timeout on the (try) receive call, and in that loop checking whether there are pending subscription or Unsubscribe requests, but this is not ideal as it doesn't seem all that efficient, and could result in a delay up to the timeout period in applying subscription changes. 

Any advice would be greatly appreciated. 

Regards 
Chris Chandler

**Comment by AbirAtur** [comment]
you can use an NetMQActor which is used to communicate with the receiving thread of the subscriber and the main thread of your application to handle subscribe\unsubscribe.
take a look at these examples:
https://github.com/somdoron/NetMQ.High/blob/master/src/NetMQ.High/Worker.cs
& 
https://github.com/somdoron/NetMQ.High/blob/master/src/NetMQ.High/Engines/WorkerEngine.cs

the WorkerEngine is basically the poller thread that receives the messages
and the Worker is the actor class that handles register requests (on different threads) which is similar to subscribe\unsubscribe for your example.

**Comment by somdoron** [comment]
Also read about NetMQQueue, which can also help interacting with a poller.
