### ISSUE TITLE
Unity + NetMQ  collapse

### ISSUE THREAD

**Issue by xwscyy** [zeromq/netmq#684]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: win10 64bit
    .NET Version:     3.5

### Expected behaviour
Unity app publish message,winform app subscribe message.

### Actual behaviour
1) Unity app publish message with no error,but winform app can't recevice the message.

2) Code like this "var rq = new NetMQ.Sockets.PushSocket();" will stuck,also “requestSocket” and "responsesSocket“.

But all is normal in .net application(like winform).

Anyone help me?

**Comment by valkjsaaa** [comment]
I just went a long way to figure this problem out.

[Check this](https://github.com/valkjsaaa/Unity-ZeroMQ-Example)

The key is to have `AsyncIO.ForceDotNet.Force();` before you start and `NetMQConfig.Cleanup();` before you end.
