### ISSUE TITLE
NuGet xml documtent needed

### ISSUE THREAD

**Issue by miaodadao** [zeromq/netmq#685]
Please add xml format document into the NuGet package, this is very helpful for beginner.
Thank you.

**Comment by drewnoakes** [comment]
Do you mean the API documentation? That is already included, though might not be for older package versions.

https://github.com/zeromq/netmq/blob/master/src/NetMQ/NetMQ.csproj#L27

What version are you using? Or are you talking about something else?

**Comment by Camuvingian** [comment]
API documentation (XML) which provides descriptive text for methods/properties etc. via intellisence was working in V4.0.0.0-beta. But the update to V4.0.0.1 causes the XML documentation via intellisense to disappear.

**Comment by c1gdoyle** [comment]
Same XML documentation seems to be missing from V4.0.0.1 but is available in later pre-release versions.
