### ISSUE TITLE
TCP sockets not getting released when disposing of PublisherSocket

### ISSUE THREAD

**Issue by sicoboy** [zeromq/netmq#688]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: 
    .NET Version:     4.5.2

### Expected behaviour
I expect the TCP sockets to be released when disposing a PublisherSocket

### Actual behaviour
TCP sockets dont get released until application is terminated

### Steps to reproduce the behaviour
From the following code I expect disposing of a publisher socket to release all the TCP ports it has taken when Connect is called

        PublisherSocket publisherSocket;
        
        private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
        {
            if (publisherSocket == null)
            {
                publisherSocket = new PublisherSocket();
                publisherSocket.Connect($"tcp://127.0.0.1:{6500}");
            }

        }

        private void ButtonBase1_OnClick(object sender, RoutedEventArgs e)
        {
            if (publisherSocket != null)
            {
                publisherSocket.Dispose();
                publisherSocket = null;
            }
        }

When looking at TCP sockets being used using TCPView, a number of sockets are still in use even after disposing of the publisherSocket.

These TCP sockets only get released when the application exits.

Any ideas?

**Comment by drewnoakes** [comment]
Try setting the TCP keepalive time to zero.

**Comment by sicoboy** [comment]
I tried changing the keepalive value.. it seemed to make no difference

**Comment by ciottied** [comment]
Same here.
With 3.x version  and NetMQContext everything worked, but with new version 4.x closing/disposing sockets is a nightmare.
I ended up modifying my application in order to never close/reopen sockets, except at startup/shutdown

**Comment by drewdb** [comment]
is there any solution for this? i didn't see this thread and posted as well using the PGM Subscriber is not released properly on dispose. Sometimes the socket does have to be closed and reopened due to other things.

**Comment by sicoboy** [comment]
I never found a solution to this.
We refactored so that publisher is kept open for the duration of the application. Which isnt really ideal

**Comment by drewdb** [comment]
No not ideal at all. We unfortunately have to close and reopen a new Subscriber socket when the wireless access point gets stuck passing packets on. Only solution is to close the app and start it again. Less than ideal. Be great if someone has a solution to this? I would have thought that disposing the socket would release it as well.

**Comment by mgara** [comment]
Hello,
Can we reopen this bug ?

**Comment by SenseYang** [comment]
Hi, please reopen this bug. I observed same behavior; the process will simply hang when socket.Dispose() is called.
