### ISSUE TITLE
VS2017 compile issues

### ISSUE THREAD

**Issue by drewdb** [zeromq/netmq#689]
### Environment

    NetMQ Version:    latest download
    Operating System: W7
    .NET Version:     4

### Expected behaviour
To compile in VS2017

### Actual behaviour
VS2017 shows that is fails to retrieve (all) packages from https://www.myget.org/F/cefsharp-2272/findpackagesbyid.

this happens for all of them

### Steps to reproduce the behaviour

open solution in VS2017. VS then tries to load packages. also if i try to manually update them via package manager

**Comment by drewnoakes** [comment]
Why does that URL mention CefSharp? Are you sure your NuGet environment is set up properly?

**Comment by drewdb** [comment]
Not sure? it opens many other apps. just comes back with 404 trying to get libries from cefsharp-2272
also tried to compile another one that failed on the same cefsharp. like it's blocked or something?

**Comment by drewdb** [comment]
I thought this one would be an easy one to solve?

**Comment by drewnoakes** [comment]
It doesn't seem to be a problem with this solution, at first appearances. Can you build other solutions that use NuGet packages?

NetMQ doesn't use CefSharp. I don't know why you should be having trouble with it here.

**Comment by drewdb** [comment]
Yes i can. i'm trying to build it directly from the download. No changes. I know that CefSharp is something else but i can't know if NetMQ uses some other packages found there?

**Comment by drewdb** [comment]
this is a grab of VS nuget settings from opening NetMQ.
![netmq newget](https://user-images.githubusercontent.com/29468693/28670898-0e3233d0-731e-11e7-9037-5b51d8afd2c9.png)

**Comment by drewdb** [comment]
your mentioning that nothing should be found in cefsharp led me to delete it from nuget manager and it worked. i don't normally use VS (maybe for these reasons) but no idea how that got there. only downloaded the community edition?

thanks anyway. i was sure it could be solved with some communication :)

**Comment by drewnoakes** [comment]
Glad you got it working. NetMQ only uses packages found on nuget.org.
