### ISSUE TITLE
Broken Intellisense Descriptions with v4.0.0.1 - Working in v4.0.0-beta

### ISSUE THREAD

**Issue by Camuvingian** [zeromq/netmq#694]
### Environment

    NetMQ Version: v4.0.0.1 
    Operating System: Windows 10 x64
    .NET Version: .NET 4.6.1

### Expected behaviour

In older version of the API (v4.0.0-beta for example), we were presented with XML documentation for methods/properties et al. Take @somdoron 's fantastic samples project found at https://github.com/NetMQ/Samples. When you build we are using v4.0.0-beta and intellisense shows descriptions:

![netmq](https://user-images.githubusercontent.com/4823601/29611468-83ddbd2a-87f5-11e7-9789-04112baf6fcd.png)

### Actual behaviour

Now, upgrade the samples project to v4.0.0.1, we now have the same method displaying intellisense without the XML descriptions:

![netmqf](https://user-images.githubusercontent.com/4823601/29611664-3fd237cc-87f6-11e7-971b-5a0c81a828f9.png)

### Steps to reproduce the behaviour

Merely download the samples project from https://github.com/NetMQ/Samples. Build. See intellisense descriptions. Then, update the NuGet pacages from v4.0.0-beta to v4.0.0.1, then you will see the descriptions disappear.

**Comment by somdoron** [comment]
Weird... closing/opening Visual Studio?
I'm actually using rider... and not on windows...

**Comment by Camuvingian** [comment]
No, opening and closing makes no difference. This happens in both VS2015 and VS2017.

**Comment by drewnoakes** [comment]
If you download the .nupkg files and have a look inside (they're ZIP files), do they both have the documentation XML file inside? Perhaps the build process changed. Would check myself but short on time today.

**Comment by Camuvingian** [comment]
I can take a look but where are these files? They do not seem to be located in the netmq-master directory...

**Comment by drewnoakes** [comment]
https://www.nuget.org/packages/NetMQ

Select the package then click "manual download" to download the file directly from nuget.org.
