### ISSUE TITLE
NetMQPoller.NetMQSynchronizationContext silently swallows async exceptions

### ISSUE THREAD

**Issue by jklw** [zeromq/netmq#697]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: Windows 7
    .NET Version:     4.7

### Expected behaviour

The program below should print "Exception in poller thread: ..." and then crash the main thread.

### Actual behaviour

The threading works correctly, but the program exits normally with this output:

```
Poller thread is 29
SC[1]: NetMQ.NetMQPoller+NetMQSynchronizationContext
Poller received: NetMQMessage[AsyncThrow]
SC[2]: NetMQ.NetMQPoller+NetMQSynchronizationContext
Doing work on thread 4
Back on thread 29; throwing
SC[1]: NetMQ.NetMQPoller+NetMQSynchronizationContext
Poller received: NetMQMessage[Quit]
Normal exit
```

### Steps to reproduce the behaviour

See example code below. I've tracked the problem down to the following:

The `throw` statement ends up calling [AsyncMethodBuilderCore.ThrowAsync](https://referencesource.microsoft.com/#mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs,223b5f320d791728); the relevant line is:

                    // Post the throwing of the exception to that context, and return.
                    targetContext.Post(state => ((ExceptionDispatchInfo)state).Throw(), edi);

Then: https://github.com/zeromq/netmq/blob/b1d54dea0ab2ecce7206b16cc20f2bfa80557141/src/NetMQ/NetMQPoller.cs#L695-L700

I think `NetMQPoller` then stores the exception in the posted Task instead of letting the exception propagate up in the poller thread. But the Task's exception isn't observed by anyone.

### Example code
    public class NetMQPollerTests
    {
      public void Test()
      {
        PairSocket.CreateSocketPair(out var socket1, out var socket2);

        var poller = new NetMQPoller {socket1};

        var pollerTask = Task.Factory.StartNew(
          () => Main(socket1, poller),
          CancellationToken.None,
          TaskCreationOptions.LongRunning,
          TaskScheduler.Default);

        socket2.SendFrame("AsyncThrow");
        Thread.Sleep(5000);
        socket2.SendFrame("Quit");

        pollerTask.Wait();

        Console.WriteLine("Normal exit");
      }

      void Main(PairSocket socket1, NetMQPoller poller)
      {
        Console.WriteLine("Poller thread is " + Thread.CurrentThread.ManagedThreadId);

        socket1.ReceiveReady +=
          (sender,
           args) =>
          {
            Console.WriteLine("SC[1]: "+SynchronizationContext.Current);
            ReceiveReady(socket1, poller);
          };

        try
        {
          poller.Run();
        }
        catch (Exception e)
        {
          Console.WriteLine("Exception in poller thread: " + e);
          throw;
        }
      }

      static async void ReceiveReady(PairSocket socket1, NetMQPoller poller)
      {
        var msg = socket1.ReceiveMultipartMessage();
        Console.WriteLine("Poller received: " + msg);

        string str = msg[0].ConvertToString();

        if (str == "AsyncThrow")
        {
          Console.WriteLine("SC[2]: "+SynchronizationContext.Current);

          await Task.Run(
            () =>
            {
              Console.WriteLine("Doing work on thread " + Thread.CurrentThread.ManagedThreadId);
            });

          Console.WriteLine(
            "Back on thread " + Thread.CurrentThread.ManagedThreadId + "; throwing");

          // Note: The issue exists regardless of whether we throw here or in the background worker above
          throw new InvalidOperationException("Test");
        }

        if (str == "Quit") poller.Stop();
      }
    }

**Comment by simonholt** [comment]
Isn't this the expected behaviour of an async void method?  If you throw the exception **before** the await then I'd expect the poller to fail as you describe, but after the await the exception will be lost because there's no way to await it.

**Comment by jklw** [comment]
I think `SynchronizationContext.Post` (which is used by async void) is supposed to let any exceptions propagate up on the target thread; otherwise there would be no way to observe them. I wrote an analogous example with WPF's `DispatchSynchronizationContext` below (it throws and catches the exception both for `Startup` and `Startup2`).

But yeah, async void is messy, so maybe there should be some way to set up a `Task`-returning handler for `ReceiveReady` (`Socket.SetAsyncReceiveReady(Func<NetMQSocketEventArgs,Task> func)`? With a better name)

```cs
using System;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Threading;

namespace ConsoleApp1
{
  class Program
  {
    [STAThread]
    static void Main(string[] args)
    {
      var app = new Application();

      app.Startup += Startup;
      //app.Startup += Startup2;

      try
      {
        app.Run();
      }
      catch (Exception e)
      {
        Console.WriteLine("Caught: " + e);
      }
    }

    static async void Startup(object sender, StartupEventArgs e)
    {
      Console.WriteLine("On thread "+Thread.CurrentThread.ManagedThreadId);

      await Task.Run(
        () =>
        {
          Console.WriteLine("Doing work on thread " + Thread.CurrentThread.ManagedThreadId);
        });

      Console.WriteLine(
        "Back on thread " + Thread.CurrentThread.ManagedThreadId + "; throwing");

      throw new InvalidOperationException("Test");
    }

    // Or use the SynchronizationContext directly
    static void Startup2(object sender, StartupEventArgs e)
    {
      Console.WriteLine("On thread "+Thread.CurrentThread.ManagedThreadId);

      var sc = SynchronizationContext.Current;

      Trace.Assert(sc is DispatcherSynchronizationContext);

      Task.Run(
        () =>
        {
          Console.WriteLine(
            "Doing work on thread " + Thread.CurrentThread.ManagedThreadId);

          sc.Post(
            _ =>
            {
              Console.WriteLine(
                "Back on thread " + Thread.CurrentThread.ManagedThreadId + "; throwing");

              throw new InvalidOperationException("Test");

            },
            null);
        });

    }
  }
}

```

**Comment by simonholt** [comment]
According to https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

> With async void methods, there is no Task object, so any exceptions thrown out of an async void method will be raised directly on the SynchronizationContext that was active when the async void method started.

So I think you're right, and I've learned a little bit more about the behaviour of SynchronizationContext! :)

**Comment by somdoron** [comment]
@jklw Do you want to send a PR?

**Comment by somdoron** [comment]
I think we should have another NetMQQueue inside poller for SynchronizationContext actions and use that instead of tasks queue. We can then just call the action and the exception will propagate.
