### ISSUE TITLE
how subscrib more frame

### ISSUE THREAD

**Issue by daconglee** [zeromq/netmq#701]
I have a PublisherSocket send data as :
 pub.SendMoreFrame("1").SendFrame("A.MSG.XXXXX");
 pub.SendMoreFrame("1").SendFrame("B.MSG.XXXXX");
 pub.SendMoreFrame("2").SendFrame("A.MSG.XXXXX");
 pub.SendMoreFrame("2").SendFrame("B.MSG.XXXXX");// i want subscriber
 pub.SendMoreFrame("2").SendFrame("C.MSG.XXXXX");
 pub.SendMoreFrame("1").SendFrame("B.MSG.XXXXX");
 
how subscriber 2 B.MSG.XXXXX

sub1.Subscribe("2"); ?
sub1.Subscribe("2,B.MSG");?

**Comment by somdoron** [comment]
Subscription in NetMQ and ZeroMQ is prefixed based and only on the first frame.

So subscription 2 match any string that starts with 2
You cannot match on the second frame, which means in your case you will get message which the first frame starts with 2

**Comment by somdoron** [comment]
Bottom line, just subscribe for "2"

**Comment by daconglee** [comment]
thank you
