### ISSUE TITLE
Contents of netMQ library version 4.0.0.1 in nuget repo has changed

### ISSUE THREAD

**Issue by joras** [zeromq/netmq#713]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: 
    .NET Version:     

### Expected behaviour

One version in nuget should be immutable, fixes should be deployed with version change.

### Actual behaviour

Contents of nuget package 4.0.0.1 has changed. More specifically, the AsyncIO dependency was 1.18 but now it is suddenly 1.26. I cannot track it back when it happened, but in my dev machine cache I have a package with dependency to 1.18 but freshly downloaded version has 1.26.

Additionally, if I look a the nuget config of 4.0.0.1 tag it is also 1.18. https://github.com/zeromq/netmq/blob/4.0.0.1/src/NetMQ/packages.NetMQ.config

**Comment by somdoron** [comment]
I dont think it is possible to change nuget version. Anyway nuget fetch
latest version of dependency.
