### ISSUE TITLE
System.Net.Sockets.SocketException in SubscriberSocket over PGM

### ISSUE THREAD

**Issue by mikepmiller** [zeromq/netmq#716]
### Environment

    NetMQ Version: v4.0.0.156-pre
    AsyncIO Version: v0.1.40
    Operating System: Windows 7
    .NET Version: 4.7.1

### Expected behaviour
SubscriberSocket receiving data over PGM over a LAN shouldn't crash due to SocketException when trying to Receive data.

### Actual behaviour
My client will run for long stretches (hours) at a time without an incident.  Occasionally, the application will crash due to a SocketException.  The stack trace is below.  The message on the exception is "An existing connection was forcibly closed by the remote host".

Exception Info: System.Net.Sockets.SocketException
   at AsyncIO.Windows.Socket.Receive(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags)
   at NetMQ.Core.Transports.Pgm.PgmSession.BeginReceive()
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

### Steps to reproduce the behaviour
Unfortunately this is an intermittent issue.  The only thing I've found that seems at all relevant is described in this link: https://stackoverflow.com/questions/7201862/an-existing-connection-was-forcibly-closed-by-the-remote-host

I'm happy to provide any additional details that might be helpful.

Thanks very much!
Mike

**Comment by mikepmiller** [comment]
I believe the below is a solution.  I apologize if I'm way off base here!  In /Core/Transports/Pgm/PgmSession.cs, in the `BeginReceive` method starting on line 68, the `m_handle.Receive` call can throw a SocketException with code 10054 [1].

Analogously to the code in `BeginSending` (line 206) of `PgmSender.cs`, I wrapped the call to `AsyncSocket.Receive` as follows:

```
public void BeginReceive()
{
    m_data.Reset();
    try
    {
        m_handle.Receive((byte[])m_data);
    }
    catch (SocketException ex)
    {
        // For a UDP datagram socket, this error would indicate that a previous 
        // send operation resulted in an ICMP "Port Unreachable" message.
        if (ex.SocketErrorCode == SocketError.ConnectionReset)
            Error();
        else
            throw NetMQException.Create(ex.SocketErrorCode, ex);
    }
}
```

I'm not sure if this is a perfect solution, because it seems that some data could be lost if the publisher is still pushing data while the subscriber is re-initializing.  Does anyone know if the SocketError.ConnectionReset can simply be suppressed?

Thanks for any feedback!
Mike

[1]  See the note at WSAECONNRESET at [WSARecv function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms741688(v=vs.85).aspx): _For a UDP datagram socket, this error would indicate that a previous send operation resulted in an ICMP "Port Unreachable" message._

**Comment by mikepmiller** [comment]
Just wanted to provide some follow-up on this.  I'm still not sure if it's a perfect solution, but it is effective.  During testing (before I had identified the work-around), I was running 4 clients total (2 each on 2 separate client machines), averaging 2-3 crashes per day total.  After the fix, I've deployed to 25+ clients spread across 10+ machines with zero crashes.

Thanks!
Mike

**Comment by drewnoakes** [comment]
I'm not deeply familiar with the PGM code but your results sound promising. Can you put together a PR? If anyone sees a problem with this, can they chime in?

**Comment by mikepmiller** [comment]
PR should be done.  Let me know if there are any issues.

Thanks!
Mike
