### ISSUE TITLE
can not bind remote IP address ？

### ISSUE THREAD

**Issue by naranakula** [zeromq/netmq#718]
### Environment

    NetMQ Version:    
    Operating System: 
    .NET Version:     

### Expected behaviour
 ok  ：  new PublisherSocket(“tcp://127.0.0.1:9600”)
 error：new PublisherSocket(“tcp://192.168.1.23:9600”)
 local machine is 192.168.1.13
 
I want send message to remote machine! 
i can not set remote ip or machine name.
help us....

**Comment by drewnoakes** [comment]
You can only bind local IP addresses.

Can you use a `SubscriberSocket` on the remote machine, and have it connect to this one?
