### ISSUE TITLE
Cannot install NetMQ when Newtonsoft.Json or Serilog.Sinks.Console is installed.

### ISSUE THREAD

**Issue by aventurella** [zeromq/netmq#729]
### Environment

    NetMQ Version: 4.0.0.1    
    Operating System: Mac
    .NET Version:  Net Core 2.0.0

### Expected behaviour
Able to install NetMQ via NuGet on Visual Studio Mac  7.3.2 (build 12) for a .NET Core Console Application

### Actual behaviour
Cannot install NetMQ via NuGet on Visual Studio Mac 7.3.2 (build 12) for a .NET Core Console Application

### Steps to reproduce the behaviour

If you install `NetMQ` (4.0.0.1) by itself, it installs just fine. What follows is what we have observed where we cannot make it install or when we can. It's effectively down to 3 dependencies, that when any is installed `NetMQ` fails to install.

Those 3 dependencies are:

- `Serilog.Sinks.Console` (3.1.1)
- `Newtonsoft.Json` (10.0.3)
- `System.Console` (4.3.0)

No idea why. They DO, however, install just
fine if we install `Microsoft.AspNetCore.All` (2.0.0) first.

We get around it by just installing `Microsoft.AspNetCore.All` even though we don't make use of it in our console app.

We **CAN NOT** install `NetMQ` (4.0.0.1) if we install these:

    - `Newtonsoft.Json` (10.0.3)

**OR**

    - `Serilog` (2.6)
    - `Serilog.Sinks.Console` (3.1.1) <--- Console specifically

**OR**

    - `System.Console` (4.3.0)

We **CAN** install `NetMQ (4.0.0.1)` if we only install

    - `Serilog` (2.6)
    - !! NO Newtonsoft.Json !!
    - !! NO Serilog.Sinks.Console !!
    - !! NO System.Console !!

**OR**

    - `Serilog` (2.6)
    - `Serilog.Sinks.File` (4.0.0)
    - !! NO Serilog.Sinks.Console !!
    - !! NO Newtonsoft.Json !!
    - !! NO System.Console !!

**OR**

    - `Serilog` (2.6)
    - `Serilog.Sinks.File` (4.0.0)
    - !! NO Serilog.Sinks.Console !!
    - !! NO Newtonsoft.Json !!
    - !! NO System.Console !!
    - `Microsoft.Extensions.Configuration` (2.0.0)
    - `Microsoft.Extensions.Configuration.CommandLine` (2.0.0)
    - `Microsoft.Extensions.Configuration.Ini` (2.0.0)

**Comment by aventurella** [comment]
Running though the dependencies of `System.Console` since it looked like it had the fewest and installing each one then trying to install NetMQ and repeating for each one. It looks like 

- `System.IO` (4.3.0) 

Is the one that prevents NetMQ from installing.

**Comment by aventurella** [comment]
Ok!

Better solve.. If I directly install

- `System.Net.NetworkInfomation` (4.3.0) 

as one of my project's primary dependencies, I don't need to install `Microsoft.AspNetCore.All` AND `NetMQ` will install with all of the other things (Serilog.Sinks.Console, Newtonsoft, etc)

**Comment by furoraest** [comment]
Since core 2.1 is released, is the issue anymore relevant?
I have used NetMQ with core 2.1 with and without Newtonsoft.Json packages and it has given no problem.
