### ISSUE TITLE
Is it possible to use inproc transport in different AppDomains?

### ISSUE THREAD

**Issue by dds72** [zeromq/netmq#736]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: Windows 10
    .NET Version:     4.6.1

### Expected behaviour

Inproc transport is working inside one process with many AppDomains

### Actual behaviour

Every AppDomain has it's own Ctx instance with Enpoints, which means that inproc transport can be used only inside one AppDomain.

### Steps to reproduce the behaviour

Create any sockets in different AppDomains and try to connect.

Is there any proper way to share one context between different appdomains?

**Comment by dds72** [comment]
Found in mailing list that it is not possible.
Maybe it would be nice to have shared memory, memory mapped files or named pipes transport for such cases?

**Comment by drewnoakes** [comment]
Is TCP on the local loopback not fast enough for your needs?

**Comment by dds72** [comment]
Thanks. Looks like it is enough after benchmarks.
