### ISSUE TITLE
Router and memory leak

### ISSUE THREAD

**Issue by jlcorr69** [zeromq/netmq#737]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: Windows 7 SP1
    .NET Version:     .Net Standard 2.0 (library)/ .Net Framework 4.6 (exe using library)

### Expected behaviour
The objects in memory should be stable.

### Actual behaviour
Objects in memory/memory raise up indefinitely.

### Steps to reproduce the behaviour
The server bind a router FrontEnd socket to a given IP Address, and bind a dealer BackEnd socket to an inproc endpoint.
Several threads (5 for example) are launched, each one creating a dealer socket connected to the inproc endpoint: that way we can manage several requests in parallel.
Then a proxy is created to relay messages between FrontEnd and BackEnd socket.
A heartbeat mechanism is in place.
![image](https://user-images.githubusercontent.com/16443650/38364481-3598069e-38d9-11e8-84c7-eb60b580b3c4.png)
Those instances seem relative to the router:
![image](https://user-images.githubusercontent.com/16443650/38364640-c492d3ce-38d9-11e8-8607-f921ced5b36b.png)

On client side Dealer sockets are created and disconnected-disposed regularly to listen asynchronously to server answers (we create/delete them in order to handle any disconnection silently) => the more dealers are created on client side, the more memory raise up on server side. I suspect some reference is kept in the router, but may be i am doing something wrong (disconnect and dispose the dealer on client side is not enough?)

**Comment by blackboxlogic** [comment]
@jlcorr69, You closed this issue, maybe because you found a solution? We are seeing the same issue and would like to know what you found.

**Comment by jlcorr69** [comment]
Well on our side, the heartbeat mechanism in place was causing too much disconnections/reconnections.
Since we fixed it and use ~always the same dealer socket everything is more stable.

Anyway, from my point of view, there's a memory leak in the netmq router, noticeable if using the same socket is not an option for you.

**Comment by mvburgh** [comment]
Has this been worked out? I'm seeing the same issue

**Comment by somdoron** [comment]
Can you do a memory profile of the app? showing which object is causing the issue?
Also, can you reproduce the issue with a minimalistic code?

**Comment by mvburgh** [comment]
![image](https://user-images.githubusercontent.com/8941351/54089769-d7f1fc80-436c-11e9-837d-45cd2ab83508.png)

my code is already minimalistic; only a RequestSocket and ResponseSocket.
I'm creating a RequestSocket per few seconds based on the requests from a Web Controller

**Comment by mvburgh** [comment]
Do you require any further information? I have looked through my code again but i'm disposing all objects nicely. Is there a workaround that i can use at this moment in time?

**Comment by Svisstack** [comment]
![image](https://user-images.githubusercontent.com/864295/63580344-e50a4d00-c594-11e9-82a3-4a0d0fce2e1e.png)

Same problem here.

**Comment by somdoron** [comment]
@svistack which sockets are you using?

**Comment by Svisstack** [comment]
_Continuation in #788_

**Comment by Svisstack** [comment]
#788
