### ISSUE TITLE
PDF version of NetMQ's Read The Docs

### ISSUE THREAD

**Issue by sivabudh** [zeromq/netmq#738]
Is there a way to get the PDF version of https://netmq.readthedocs.io/en/latest/ ?

I would love to be able to print it out and go through each page offline.

Thank you!

**Comment by moreal** [comment]
Originally, ReadTheDocs seems able to build PDF version. But sadly, it doesn't support with MkDocs options. Please see [Build Process - ReadTheDocs]. So IMO you can print them with your browser.

[Build Process - ReadTheDocs]: https://docs.readthedocs.io/en/stable/builds.html#mkdocs
