### ISSUE TITLE
dotnet core InitPool, XPub/Publish, and reference counting leading to bad data race condition

### ISSUE THREAD

**Issue by livermana** [zeromq/netmq#739]
### Environment

    NetMQ Version:   4.0.0.1
    Operating System: Windows 7
    .NET Version:  .net core

### Expected behaviour
Two topics are being sent,  "Logging_test" and "TestTopic"
topicMessage.InitPool(topicLength);
topicMessage.Put(topic, 0, topicLength);
 _publisher.Send(ref topicMessage, true);
topicMessage.Close();

payloadMessage.InitPool(payloadLength);
_publisher.Send(ref payloadMessage, false);
payloadMessage.Close();

Expect that only those topics and a payload would be sent. This happened the vast majority of the time, until it didn't, usually under load. 

### Actual behavior

On the receiving end, I would get the proper values 99.99% of the time, but sometimes I would get a topic that didn't match its size. 
IE: expected "Logging_test\n" but would receive "TestTopic\nest\n sometimes. with a size of 15 instead of 10.
Reason seemed to be the reference counting on the msg structure. Basically the "data" would go back into the pool before the msg was actually freed up.   

note, using InitGC this did not happen at all, which further lead me to believe it was the reference counting

### Steps to reproduce the behavior

send/receive from a pub/sub with a small topic/payload in rapid succession, create dictionaries to look at unique keys received.  Create load by doing other things within the send process. 

### Possible steps to correct the issue (or at least what worked for me)

I can setup a pull request but want to make sure I am barking up the right tree.
I have made two small modifications that have seemed to correct the issue. 
In, src/NetMQ/Msg.cs
``` csharp
            public void AddReferences(int amount)
        {
            if (amount == 0)
            {
                return;
            }

            if (MsgType == MsgType.Pool)
            {
                if (IsShared)
                {
                    m_refCount.Increase(amount);
                }
                else
                {
                    m_refCount.Increase(amount); //<=change from set to Increase. as that seems to be with the main function is for.
                    Flags |= MsgFlags.Shared;
                }
            }
        }
```
in src/NetMQ/Core/Patterns/Utils/Distribution.cs
``` csharp
        private void Distribute(ref Msg msg)
        {
            // If there are no matching pipes available, simply drop the message.
            if (m_matching == 0)
            {
                msg.Close();
                msg.InitEmpty();

                return;
            }

            if (msg.MsgType != MsgType.Pool)
            {
                for (int i = 0; i < m_matching; ++i)
                {
                    if (!Write(m_pipes[i], ref msg))
                    {
                        --i; //  Retry last write because index will have been swapped
                    }
                }

                msg.Close();
                msg.InitEmpty();

                return;
            }

	//when a msg is created, it actually has zero references, as it doesn't count its own reference. 
	//add to the current based off the number of copies we had to create.  add to the reference so that
	//when the class counter hits zero we can return the buffers.
            msg.AddReferences(m_matching); //<== modified here to remove the -1, as it didn't seem to line up with the msg structure atomiccounter as it starts at zero, with only copies having a reference count.

            // Push copy of the message to each matching pipe.
            int failed = 0;
            for (int i = 0; i < m_matching; ++i)
            {
                if (!Write(m_pipes[i], ref msg))
                {
                    ++failed;
                    --i; //  Retry last write because index will have been swapped
                }
            }
            if (failed != 0)
                msg.RemoveReferences(failed);

            // Detach the original message from the data buffer. Note that we don't
            // close the message, as the original message doesn't count as a reference. we want to init here, in case they "close" so it doesn't manipulate the counter.
            msg.InitEmpty(); 
        }
```

**Comment by Amarok79** [comment]
I'm able to reproduce the issue with a small sample application and can confirm that @livermana's changes fix the race condition.

NetMQ Version: 4.0.0.1 or latest version from GitHub
Operating System: Windows 10
.NET Version:  .NET Framework 4.7.1

**Subscriber**

	var sub = new SubscriberSocket();
	sub.Connect("tcp://localhost:11111");
	sub.SubscribeToAnyTopic();
	
	Int32 count = 0;
	while (true)
	{
		var msg = sub.ReceiveMultipartMessage();

		var topic = msg.Pop();
		var length = msg.Pop().ConvertToInt32();
		var content = msg.Pop().ConvertToString(Encoding.UTF8);

		if (!topic.IsEmpty)
			Console.WriteLine("unexpected frame 1");
		if (length < 1 || length > 8192)
			Console.WriteLine("unexpected frame 2");
		if (!content.Equals(new String('A', length), StringComparison.Ordinal))
			Console.WriteLine("unexpected frame 3");

		count++;
		if (count % 1000 == 0)
			Console.Write(".");
	}

**Publisher**

	BufferPool.SetCustomBufferPool(new ArrayPoolBufferPool());
	
	var que = new NetMQQueue<Action<IOutgoingSocket>>(1000);
	var pub = new PublisherSocket();
	var pol = new NetMQPoller();

	pub.Options.Linger = TimeSpan.Zero;
	pub.Options.SendHighWatermark = 5000;

	que.ReceiveReady += (Object sender, NetMQQueueEventArgs<Action<IOutgoingSocket>> e) => {
		var action = e.Queue.Dequeue();
		action(pub);
	};

	pol.Add(que);
	pol.Add(pub);
	pol.RunAsync();

	que.Enqueue(x => {
		((PublisherSocket)x).Bind("tcp://*:11111");
	});

	Thread.Sleep(3000);

	var random = new Random();
	for (Int32 i = 0; i < 100000; i++)
	{
		que.Enqueue(x => {

			var length = random.Next(1, 8193);
			var text = new String('A', length);
			var bytes = Encoding.UTF8.GetBytes(text);

			var msg1 = new Msg();
			msg1.InitEmpty();
			x.Send(ref msg1, true);
			msg1.Close();

			var msg2 = new Msg();
			msg2.InitPool(4);
			msg2.Put((Byte)(length >> 24), 0);
			msg2.Put((Byte)(length >> 16), 1);
			msg2.Put((Byte)(length >> 8), 2);
			msg2.Put((Byte)(length >> 0), 3);
			x.Send(ref msg2, true);
			msg2.Close();

			var msg3 = new Msg();
			msg3.InitPool(bytes.Length);
			msg3.Put(bytes, 0, bytes.Length);
			x.Send(ref msg3, false);
			msg3.Close();
		});
		//Console.WriteLine(length);
	}

	Thread.Sleep(50000);
	pub.Close();

**Buffer Pool**

Uses ArrayPool<T> from System.Buffers.

	public sealed class ArrayPoolBufferPool :
		IBufferPool
	{
		public void Dispose()
		{
		}

		public void Return(Byte[] buffer)
		{
			ArrayPool<Byte>.Shared.Return(buffer);
		}

		public Byte[] Take(Int32 size)
		{
			return ArrayPool<Byte>.Shared.Rent(size);
		}
	}

**Steps to Reproduce**

- Start 4 subscriber processes (console application)
- Start 1 publisher process (console application)
- One subscriber usually receives all messages without corruption, printing dots onto the console
- The other subscribers receive partly corrupted messages, resulting in "unexpected frame" messages printed to the console

**Comment by somdoron** [comment]
Great, can you make a pull request?
