### ISSUE TITLE
Is there a ZeroMQ C++ equivalent for NetMQPoller?

### ISSUE THREAD

**Issue by sivabudh** [zeromq/netmq#743]
I just love the API of NetMQ poller as shown here:

https://netmq.readthedocs.io/en/latest/poller/

I'm sorry to be asking about ZeroMQ's C++ libraries on a C# repo, but since NetMQ documentation is probably the most complete (besides the official C version), I figured I should try asking.

How can I get the same "poller" functionality in C++? Specifically, I'm looking for `ReceiveReady` in C++.  

Otherwise, I have to implement something like a `while(true)` on my `REP` socket. Pseudocode below:

```
Create a timer to call some function every X milliseconds
Do a non-blocking `recv(socket);`
Check if error / or returned `received_data.length` is 0
If no error / or `received_data.length` > 0, then process the message
```
Note: I'm handling a single socket so I think `zmq_poll` is overkill (?).

Thank you.

**Comment by somdoron** [comment]
Yes you do (I wrote it :)). It is a new API inside libzmq.

Take a look at zmq_poller in libzmq.

**Comment by kurdybacha** [comment]
and you have a C++ wrapper in cppzmq `zmq::poller_t` and more advance zmq::active_poller_t`

**Comment by sivabudh** [comment]
@kurdybacha Thanks. It would help so much if there were concrete examples somewhere on the internet, but I haven't been able to find one yet. =(

**Comment by drewnoakes** [comment]
@sivabudh sounds like a good thing to share once you work it out :)

**Comment by sivabudh** [comment]
Believe me, @drewnoakes, I wish I had the time. 😢  And it's sad for me to say this, but right now I'm prototyping my application in gRPC and I'm really liking it over ZeroMQ due to its simplicity.

**Comment by sivabudh** [comment]
For what it's worth, this is the prototype. 
https://github.com/C0D1UM/grpc-qt-example

I love how gRPC can do server-side streaming RPC. The [doc](https://grpc.io/docs/tutorials/basic/c.html) describes it as follows:



> A server-side streaming RPC where the client sends a request to the server and gets a stream to read a sequence of messages back. The client reads from the returned stream until there are no more messages. As you can see in our example, you specify a server-side streaming method by placing the stream keyword before the response type.


```
// Obtains the Features available within the given Rectangle.  Results are
// streamed rather than returned at once (e.g. in a response message with a
// repeated field), as the rectangle may cover a large area and contain a
// huge number of features.
rpc ListFeatures(Rectangle) returns (stream Feature) {}
```
