### ISSUE TITLE
Pub/Sub Documentation error

### ISSUE THREAD

**Issue by dev-nextprogress** [zeromq/netmq#747]
### Environment

    NetMQ Version:    N/A
    Operating System: N/A
    .NET Version:     N/A

### Actual behaviour

On the pub/sub documentation sample, the publisher is documented like this:
pubSocket.Bind("tcp://localhost:12345");

But this only works when subscribers run also on localhost.
If I am not mistaken, to actually be able to serve multiple remote clients, it should be:
pubSocket.Bind("tcp://*:12345");

(asterisk instead of localhost)
See also http://zguide.zeromq.org/cs:wuserver

**Comment by fscopel** [comment]
I want to second this. I had been trying to get PUB/SUB working on a Xamarin Forms app for a couple days and the issue with `SubscriberSocket` not responding was actually on a server. I had set it up with `pubSocket.Bind("tcp://localhost:5555");`, once I changed it to `pubSocket.Bind("tcp://*:12345");`  the `SubscriberSocket` started responding.

**Comment by drewnoakes** [comment]
@dev-nextprogress, @fscopel please review #758 and verify whether it addresses the problem you encountered.
