### ISSUE TITLE
RouterSocket stops responding after a while

### ISSUE THREAD

**Issue by codewzrd** [zeromq/netmq#750]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: Windows Server 2014
    .NET Version:     .NET 4.7

### Issue

I have a Windows Service that is accepting requests from a .NET Web API. 
The service instantiates a RouterSocket so that it can receive many messages from the web api layer and forwards it onto our internal system. The internal system returns a response which is sent back to the web service layer which forwards the response to the client.

Here is the code

    private RouterSocket _socket;

    public void StartServer()
    {
        _socket = new RouterSocket();
        _socket.Bind(_netmqConnStr);

        while (_listening)
        {
            var msg = _socket.ReceiveMultipartMessage();

            var identity = msg.Pop().ConvertToString();
            var x = msg.Pop().ConvertToString(); // empty frame
            var data = msg.Pop().ConvertToString();

            _logger.Debug($"Incoming Message - Identity: {identity}, Data: {data}"); // I see logs for a while then nothing!

            ForwardMessage(identity, data);
        }
    }
        public async Task SendMessage(string identity, int errorCode, string response)
        {
                NetMQMessage message = new NetMQMessage();
                message.Append(System.Text.Encoding.ASCII.GetBytes(identity));
                message.AppendEmptyFrame();
                message.Append(errorCode);
                message.Append(response);

                _socket.SendMultipartMessage(message);

                _logger.Debug(String.Format("Send to WebAPI - Error code: {0}, Response: {1}", errorCode, response));
        }

From the WebAPI, I connect to the Windows Service (running on the same server) using this code:

        public async Task<IHttpActionResult> Post(MyModel inputModel)
        {
            using (var requestSocket = new RequestSocket())
            {
                requestSocket.Options.Identity = System.Text.Encoding.ASCII.GetBytes(GetUniqueID());

                try
                {
                    requestSocket.Connect(Constants.BackEndAddress);
                }
                catch(Exception e)
                {
                    _logger.Error(e);
                    return InternalServerError();
                }

                NetMQMessage message = new NetMQMessage();
                message.Append(JsonConvert.SerializeObject(inputModel));

                try
                {
                    requestSocket.SendMultipartMessage(message);
                }
                catch(Exception e)
                {
                    _logger.Error($"Unable to submit message to Windows Service: {soupMsg}");
                     return InternalServerError(new Exception("Unable to foward your message."));
                }

                if (!requestSocket.TryReceiveMultipartMessage(TimeSpan.FromSeconds(5), ref message))
                {
                    _logger.Error("Did not receive a response from the Windows Service in the time allotted.");
                    return InternalServerError(new Exception("Did not receive a response from the gateway in the time allotted."));
                }

                var errorCode = message.Pop().ConvertToInt32();
                var result = message.Pop().ConvertToString();
                var status = false;

                    _logger.Info(result);

                    switch (errorCode)
                    {
                        case 0:
                            return BadRequest(result);
                        case 1:
                            return Ok();
                        default:
                            return InternalServerError(new Exception("Unknown error"));
                    }
                }
            }
        }

Using Postman's Collection Runner (two instances to simulate 2 customers), I try to send 1000 messages every second. When I start sending messages in I see the Incoming Message logged to the database.

After a while I stop seeing the Incoming Message log entries. I get an error from the web api that I did not get a response in a timely manner `TryReceiveMultipartMessage(TimeSpan.FromSeconds(5)`. I don't get an exception when calling SendMultipartMessage from the API layer.

Why is the Windows Service not receiving the messages but the API thinks that it sent the message successfully?

**Comment by codewzrd** [comment]
To add to the above issue...

@somdoron, What happens when the RouterSocket gets messages that it cannot send to the client? Either the client disconnected or the message retrieved from an internal service did not originate from this server?

I have 2 web servers with the above setup (so 2 Windows Services) running. The internal service sends data to both servers but only one will need to return the data back to the web client.

**Comment by sircuri** [comment]
We have the same issue, but since we switched over to the 4.0.0.197-pre pre-release version we witnessed the following exception (we haven't changed anything in the code yet):

`Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at NetMQ.Core.Patterns.Utils.ArrayExtensions.Swap[T](List`1 items, Int32 index1, Int32 index2)
at NetMQ.Core.Patterns.Utils.FairQueueing.Attach(Pipe pipe)
at NetMQ.Core.Patterns.Router.XReadActivated(Pipe pipe)
at NetMQ.Core.SocketBase.ReadActivated(Pipe pipe)
at NetMQ.Core.Pipe.ProcessActivateRead()
at NetMQ.Core.ZObject.ProcessCommand(Command cmd)
at NetMQ.Core.SocketBase.ProcessCommands(Int32 timeout, Boolean throttle)
at NetMQ.Core.SocketBase.TryRecv(Msg& msg, TimeSpan timeout)
at NetMQ.NetMQSocket.TryReceive(Msg& msg, TimeSpan timeout)
at NetMQ.ReceivingSocketExtensions.TryReceiveMultipartMessage(IReceivingSocket socket, TimeSpan timeout, NetMQMessage& message, Int32 expectedFrameCount)
at CGM.Common.Commands.ZMQ.ReceiveAndReplyAsyncService.MainLoop(RouterSocket server)`

Searching the Internet about this type of exception might indicate network loss and restore events.
It is possible that the latest stable release 4.0.0.1 did not throw any exceptions and silently died causing the program to no longer respond to new messages.

**Comment by somdoron** [comment]
This happens when you use the socket from multiple threads.

**Comment by sircuri** [comment]
Then I hope we have fixed it recently by using the MQPoller on a MQQueue object to detect messages from other tasks/threads. We missed the part that NetMQ sockets are not thread-safe :)

Thanks

**Comment by goforgold** [comment]
Hi @somdoron 

I am also new to NetMQ as well as ZMQ itself.

What is the best way to send message from different threads to one RouterSocket. I need to send messages using RouterSocket based on the events triggered by different threads.

I understand the concept of MQPoller which solves the thread safety issue when reading messages.

My question is how to use NetMQQueue to send message on RouterSocket or RouterDealer object from different threads?

The example given here confuses me as it is sending message on Receive_Ready event which doesn't seem to make sense for my use case. I need to send message independently to specific client (DealerSocket) with the help of Identity.

**Comment by somdoron** [comment]
NetMQQueue is thread safe for enqueueing.

So you can have multiple threads enqueueing and one thread dequeuing and sending it using the dealer socket.

**Comment by goforgold** [comment]
Thanks @somdoron for prompt response.

Actually, this example confusing me

```
using (var queue = new NetMQQueue<ICommand>())
using (var poller = new NetMQPoller { queue })
{
    queue.ReceiveReady += (sender, args) => ProcessCommand(queue.Dequeue());
    poller.RunAsync();
    // Then, from various threads...
    queue.Enqueue(new DoSomethingCommand());
    queue.Enqueue(new DoSomethingElseCommand());
}
```

1. Where is Socket defined here?
2. In my case my socket is attached with Poller object. Do I need to add a Queue object to my existing poller as well?
