### ISSUE TITLE
NetMQ AddressAlreadyInUseException

### ISSUE THREAD

**Issue by pnrajesh** [zeromq/netmq#753]
### Environment

    NetMQ Version: 4.0.0.1
    Operating System: Server 2012
    .NET Version:  .NET Framework 4.7

### Issue
Have been noticing the application randomly crashing with NetMQ.AddressAlreadyInUseException with the below information:

> _NetMQ.AddressAlreadyInUseException at
>  NetMQ.Core.Transports.Tcp.TcpConnector.OutCompleted (System.NetSockets.SockerError, Int32) at
>  NetMQ.Core.Utils.Proactor.Loop()_

The application uses **ROUTER** type to receive data (from another application that runs in the same machine), PUB-SUB types for internal processing of data, and **DEALER** type to send data (to another application that runs in a different machine). Each of the NETMQ sockets also use **NetMQPoller** and **NetMQQueue** to manage reception/sending of data.

A couple of seconds before the application crashes, we noticed an Event Log entry with the below data:

> TCP/IP failed to establish an outgoing connection because the selected local endpoint was recently used to connect to the same remote endpoint. This error typically occurs when outgoing connections are opened and closed at a high rate, causing all available local ports to be used and forcing TCP/IP to reuse a local port for an outgoing connection. To minimize the risk of data corruption, the TCP/IP standard requires a minimum time period to elapse between successive connections from a given local endpoint to a given remote endpoint.

### Questions
1. No other application running on that machine opens/closes Sockets frequently. It looks like NETMQ is what is triggering the frequent socket open/close. We have not observed any network level failures between the machines, but have not eliminated it yet. What could be causing the NETMQ to do repeated retries? Would changing "NetMQ.SocketOptions.ReconnectInterval" help? Are there any other options related to this behavior?

2. Application only uses NetMQPoller and not NetMQProactor. The exception trace shows it being from the Proactor.Loop. Why is it so?

3. Any suggestions to identify the root cause/resolve it?

Regards,
Rajesh

**Comment by dnallicus** [comment]
There was a windows patch in July with a bug that caused ephemeral ports to be reused, which can cause this error. Did you install updates to the machine lately?

**Comment by dnallicus** [comment]
This was the update, it caused a lot of issues with netmq and EWS for us.

https://social.technet.microsoft.com/Forums/office/en-US/64fc8bf1-f26f-4498-8fef-6ebe7982fb11/july-updates-huge-problems-with-closing-ports-and-services?forum=winserver8gen
