### ISSUE TITLE
License update to project

### ISSUE THREAD

**Issue by retslig** [zeromq/netmq#755]
I was hoping the project owner would consider updating the project license to use spdx identifier for the "GNU LESSER GENERAL PUBLIC LICENSE" license. Your license in the github api only shows as "Other".
See https://api.github.com/repos/zeromq/netmq/license for your current license.
Also note your current license committed in the repo is already "GNU LESSER GENERAL PUBLIC LICENSE" https://github.com/zeromq/netmq/blob/master/COPYING.LESSER
This is no change to the license at all, but then allows anyone using the github license API to get an exact match of the licensed used and not have to use any string magic to come up with your license.

If your unfamiliar with SPDX see spdx.org.

Pretty sure this can be done in your settings somewhere. Here is an example of your API json and your
spdx_id is null.
{
"name": "COPYING.LESSER",
"path": "COPYING.LESSER",
"sha": "afab572debb5c88ab76ecca750c9b549e2fc78f5",
"size": 8363,
"url": "https://api.github.com/repos/zeromq/netmq/contents/COPYING.LESSER?ref=master",
"html_url": "https://github.com/zeromq/netmq/blob/master/COPYING.LESSER",
"git_url": "https://api.github.com/repos/zeromq/netmq/git/blobs/afab572debb5c88ab76ecca750c9b549e2fc78f5",
"download_url": "https://raw.githubusercontent.com/zeromq/netmq/master/COPYING.LESSER",
"type": "file",
"content": "ICAJICAgICAgICAgR05VIExFU1NFUiBHRU5FUkFMIFBVQkxJQyBMSUNFTlNF\nCiAgICAgICAgICAgICAgICAgICAgICAgVmVyc2lvbiAzLCAyOSBKdW5lIDIw\nMDcKCiBDb3B5cmlnaHQgKEMpIDIwMDcgRnJlZSBTb2Z0d2FyZSBGb3VuZGF0\naW9uLCBJbmMuIDxodHRwOi8vZnNmLm9yZy8+CiBFdmVyeW9uZSBpcyBwZXJt\naXR0ZWQgdG8gY29weSBhbmQgZGlzdHJpYnV0ZSB2ZXJiYXRpbSBjb3BpZXMK\nIG9mIHRoaXMgbGljZW5zZSBkb2N1bWVudCwgYnV0IGNoYW5naW5nIGl0IGlz\nIG5vdCBhbGxvd2VkLgoKCiAgVGhpcyB2ZXJzaW9uIG9mIHRoZSBHTlUgTGVz\nc2VyIEdlbmVyYWwgUHVibGljIExpY2Vuc2UgaW5jb3Jwb3JhdGVzCnRoZSB0\nZXJtcyBhbmQgY29uZGl0aW9ucyBvZiB2ZXJzaW9uIDMgb2YgdGhlIEdOVSBH\nZW5lcmFsIFB1YmxpYwpMaWNlbnNlLCBzdXBwbGVtZW50ZWQgYnkgdGhlIGFk\nZGl0aW9uYWwgcGVybWlzc2lvbnMgbGlzdGVkIGJlbG93LgoKICAwLiBBZGRp\ndGlvbmFsIERlZmluaXRpb25zLiAKCiAgQXMgdXNlZCBoZXJlaW4sICJ0aGlz\nIExpY2Vuc2UiIHJlZmVycyB0byB2ZXJzaW9uIDMgb2YgdGhlIEdOVSBMZXNz\nZXIKR2VuZXJhbCBQdWJsaWMgTGljZW5zZSwgYW5kIHRoZSAiR05VIEdQTCIg\ncmVmZXJzIHRvIHZlcnNpb24gMyBvZiB0aGUgR05VCkdlbmVyYWwgUHVibGlj\nIExpY2Vuc2UuCgogICJUaGUgTGlicmFyeSIgcmVmZXJzIHRvIGEgY292ZXJl\nZCB3b3JrIGdvdmVybmVkIGJ5IHRoaXMgTGljZW5zZSwKb3RoZXIgdGhhbiBh\nbiBBcHBsaWNhdGlvbiBvciBhIENvbWJpbmVkIFdvcmsgYXMgZGVmaW5lZCBi\nZWxvdy4KCiAgQW4gIkFwcGxpY2F0aW9uIiBpcyBhbnkgd29yayB0aGF0IG1h\na2VzIHVzZSBvZiBhbiBpbnRlcmZhY2UgcHJvdmlkZWQKYnkgdGhlIExpYnJh\ncnksIGJ1dCB3aGljaCBpcyBub3Qgb3RoZXJ3aXNlIGJhc2VkIG9uIHRoZSBM\naWJyYXJ5LgpEZWZpbmluZyBhIHN1YmNsYXNzIG9mIGEgY2xhc3MgZGVmaW5l\nZCBieSB0aGUgTGlicmFyeSBpcyBkZWVtZWQgYSBtb2RlCm9mIHVzaW5nIGFu\nIGludGVyZmFjZSBwcm92aWRlZCBieSB0aGUgTGlicmFyeS4KCiAgQSAiQ29t\nYmluZWQgV29yayIgaXMgYSB3b3JrIHByb2R1Y2VkIGJ5IGNvbWJpbmluZyBv\nciBsaW5raW5nIGFuCkFwcGxpY2F0aW9uIHdpdGggdGhlIExpYnJhcnkuICBU\naGUgcGFydGljdWxhciB2ZXJzaW9uIG9mIHRoZSBMaWJyYXJ5CndpdGggd2hp\nY2ggdGhlIENvbWJpbmVkIFdvcmsgd2FzIG1hZGUgaXMgYWxzbyBjYWxsZWQg\ndGhlICJMaW5rZWQKVmVyc2lvbiIuCgogIFRoZSAiTWluaW1hbCBDb3JyZXNw\nb25kaW5nIFNvdXJjZSIgZm9yIGEgQ29tYmluZWQgV29yayBtZWFucyB0aGUK\nQ29ycmVzcG9uZGluZyBTb3VyY2UgZm9yIHRoZSBDb21iaW5lZCBXb3JrLCBl\neGNsdWRpbmcgYW55IHNvdXJjZSBjb2RlCmZvciBwb3J0aW9ucyBvZiB0aGUg\nQ29tYmluZWQgV29yayB0aGF0LCBjb25zaWRlcmVkIGluIGlzb2xhdGlvbiwg\nYXJlCmJhc2VkIG9uIHRoZSBBcHBsaWNhdGlvbiwgYW5kIG5vdCBvbiB0aGUg\nTGlua2VkIFZlcnNpb24uCgogIFRoZSAiQ29ycmVzcG9uZGluZyBBcHBsaWNh\ndGlvbiBDb2RlIiBmb3IgYSBDb21iaW5lZCBXb3JrIG1lYW5zIHRoZQpvYmpl\nY3QgY29kZSBhbmQvb3Igc291cmNlIGNvZGUgZm9yIHRoZSBBcHBsaWNhdGlv\nbiwgaW5jbHVkaW5nIGFueSBkYXRhCmFuZCB1dGlsaXR5IHByb2dyYW1zIG5l\nZWRlZCBmb3IgcmVwcm9kdWNpbmcgdGhlIENvbWJpbmVkIFdvcmsgZnJvbSB0\naGUKQXBwbGljYXRpb24sIGJ1dCBleGNsdWRpbmcgdGhlIFN5c3RlbSBMaWJy\nYXJpZXMgb2YgdGhlIENvbWJpbmVkIFdvcmsuCgogIDEuIEV4Y2VwdGlvbiB0\nbyBTZWN0aW9uIDMgb2YgdGhlIEdOVSBHUEwuCgogIFlvdSBtYXkgY29udmV5\nIGEgY292ZXJlZCB3b3JrIHVuZGVyIHNlY3Rpb25zIDMgYW5kIDQgb2YgdGhp\ncyBMaWNlbnNlCndpdGhvdXQgYmVpbmcgYm91bmQgYnkgc2VjdGlvbiAzIG9m\nIHRoZSBHTlUgR1BMLgoKICAyLiBDb252ZXlpbmcgTW9kaWZpZWQgVmVyc2lv\nbnMuCgogIElmIHlvdSBtb2RpZnkgYSBjb3B5IG9mIHRoZSBMaWJyYXJ5LCBh\nbmQsIGluIHlvdXIgbW9kaWZpY2F0aW9ucywgYQpmYWNpbGl0eSByZWZlcnMg\ndG8gYSBmdW5jdGlvbiBvciBkYXRhIHRvIGJlIHN1cHBsaWVkIGJ5IGFuIEFw\ncGxpY2F0aW9uCnRoYXQgdXNlcyB0aGUgZmFjaWxpdHkgKG90aGVyIHRoYW4g\nYXMgYW4gYXJndW1lbnQgcGFzc2VkIHdoZW4gdGhlCmZhY2lsaXR5IGlzIGlu\ndm9rZWQpLCB0aGVuIHlvdSBtYXkgY29udmV5IGEgY29weSBvZiB0aGUgbW9k\naWZpZWQKdmVyc2lvbjoKCiAgIGEpIHVuZGVyIHRoaXMgTGljZW5zZSwgcHJv\ndmlkZWQgdGhhdCB5b3UgbWFrZSBhIGdvb2QgZmFpdGggZWZmb3J0IHRvCiAg\nIGVuc3VyZSB0aGF0LCBpbiB0aGUgZXZlbnQgYW4gQXBwbGljYXRpb24gZG9l\ncyBub3Qgc3VwcGx5IHRoZQogICBmdW5jdGlvbiBvciBkYXRhLCB0aGUgZmFj\naWxpdHkgc3RpbGwgb3BlcmF0ZXMsIGFuZCBwZXJmb3JtcwogICB3aGF0ZXZl\nciBwYXJ0IG9mIGl0cyBwdXJwb3NlIHJlbWFpbnMgbWVhbmluZ2Z1bCwgb3IK\nCiAgIGIpIHVuZGVyIHRoZSBHTlUgR1BMLCB3aXRoIG5vbmUgb2YgdGhlIGFk\nZGl0aW9uYWwgcGVybWlzc2lvbnMgb2YKICAgdGhpcyBMaWNlbnNlIGFwcGxp\nY2FibGUgdG8gdGhhdCBjb3B5LgoKICAzLiBPYmplY3QgQ29kZSBJbmNvcnBv\ncmF0aW5nIE1hdGVyaWFsIGZyb20gTGlicmFyeSBIZWFkZXIgRmlsZXMuCgog\nIFRoZSBvYmplY3QgY29kZSBmb3JtIG9mIGFuIEFwcGxpY2F0aW9uIG1heSBp\nbmNvcnBvcmF0ZSBtYXRlcmlhbCBmcm9tCmEgaGVhZGVyIGZpbGUgdGhhdCBp\ncyBwYXJ0IG9mIHRoZSBMaWJyYXJ5LiAgWW91IG1heSBjb252ZXkgc3VjaCBv\nYmplY3QKY29kZSB1bmRlciB0ZXJtcyBvZiB5b3VyIGNob2ljZSwgcHJvdmlk\nZWQgdGhhdCwgaWYgdGhlIGluY29ycG9yYXRlZAptYXRlcmlhbCBpcyBub3Qg\nbGltaXRlZCB0byBudW1lcmljYWwgcGFyYW1ldGVycywgZGF0YSBzdHJ1Y3R1\ncmUKbGF5b3V0cyBhbmQgYWNjZXNzb3JzLCBvciBzbWFsbCBtYWNyb3MsIGlu\nbGluZSBmdW5jdGlvbnMgYW5kIHRlbXBsYXRlcwoodGVuIG9yIGZld2VyIGxp\nbmVzIGluIGxlbmd0aCksIHlvdSBkbyBib3RoIG9mIHRoZSBmb2xsb3dpbmc6\nCgogICBhKSBHaXZlIHByb21pbmVudCBub3RpY2Ugd2l0aCBlYWNoIGNvcHkg\nb2YgdGhlIG9iamVjdCBjb2RlIHRoYXQgdGhlCiAgIExpYnJhcnkgaXMgdXNl\nZCBpbiBpdCBhbmQgdGhhdCB0aGUgTGlicmFyeSBhbmQgaXRzIHVzZSBhcmUK\nICAgY292ZXJlZCBieSB0aGlzIExpY2Vuc2UuCgogICBiKSBBY2NvbXBhbnkg\ndGhlIG9iamVjdCBjb2RlIHdpdGggYSBjb3B5IG9mIHRoZSBHTlUgR1BMIGFu\nZCB0aGlzIGxpY2Vuc2UKICAgZG9jdW1lbnQuCgogIDQuIENvbWJpbmVkIFdv\ncmtzLgoKICBZb3UgbWF5IGNvbnZleSBhIENvbWJpbmVkIFdvcmsgdW5kZXIg\ndGVybXMgb2YgeW91ciBjaG9pY2UgdGhhdCwKdGFrZW4gdG9nZXRoZXIsIGVm\nZmVjdGl2ZWx5IGRvIG5vdCByZXN0cmljdCBtb2RpZmljYXRpb24gb2YgdGhl\nCnBvcnRpb25zIG9mIHRoZSBMaWJyYXJ5IGNvbnRhaW5lZCBpbiB0aGUgQ29t\nYmluZWQgV29yayBhbmQgcmV2ZXJzZQplbmdpbmVlcmluZyBmb3IgZGVidWdn\naW5nIHN1Y2ggbW9kaWZpY2F0aW9ucywgaWYgeW91IGFsc28gZG8gZWFjaCBv\nZgp0aGUgZm9sbG93aW5nOgoKICAgYSkgR2l2ZSBwcm9taW5lbnQgbm90aWNl\nIHdpdGggZWFjaCBjb3B5IG9mIHRoZSBDb21iaW5lZCBXb3JrIHRoYXQKICAg\ndGhlIExpYnJhcnkgaXMgdXNlZCBpbiBpdCBhbmQgdGhhdCB0aGUgTGlicmFy\neSBhbmQgaXRzIHVzZSBhcmUKICAgY292ZXJlZCBieSB0aGlzIExpY2Vuc2Uu\nCgogICBiKSBBY2NvbXBhbnkgdGhlIENvbWJpbmVkIFdvcmsgd2l0aCBhIGNv\ncHkgb2YgdGhlIEdOVSBHUEwgYW5kIHRoaXMgbGljZW5zZQogICBkb2N1bWVu\ndC4KCiAgIGMpIEZvciBhIENvbWJpbmVkIFdvcmsgdGhhdCBkaXNwbGF5cyBj\nb3B5cmlnaHQgbm90aWNlcyBkdXJpbmcKICAgZXhlY3V0aW9uLCBpbmNsdWRl\nIHRoZSBjb3B5cmlnaHQgbm90aWNlIGZvciB0aGUgTGlicmFyeSBhbW9uZwog\nICB0aGVzZSBub3RpY2VzLCBhcyB3ZWxsIGFzIGEgcmVmZXJlbmNlIGRpcmVj\ndGluZyB0aGUgdXNlciB0byB0aGUKICAgY29waWVzIG9mIHRoZSBHTlUgR1BM\nIGFuZCB0aGlzIGxpY2Vuc2UgZG9jdW1lbnQuCgogICBkKSBEbyBvbmUgb2Yg\ndGhlIGZvbGxvd2luZzoKCiAgICAgICAwKSBDb252ZXkgdGhlIE1pbmltYWwg\nQ29ycmVzcG9uZGluZyBTb3VyY2UgdW5kZXIgdGhlIHRlcm1zIG9mIHRoaXMK\nICAgICAgIExpY2Vuc2UsIGFuZCB0aGUgQ29ycmVzcG9uZGluZyBBcHBsaWNh\ndGlvbiBDb2RlIGluIGEgZm9ybQogICAgICAgc3VpdGFibGUgZm9yLCBhbmQg\ndW5kZXIgdGVybXMgdGhhdCBwZXJtaXQsIHRoZSB1c2VyIHRvCiAgICAgICBy\nZWNvbWJpbmUgb3IgcmVsaW5rIHRoZSBBcHBsaWNhdGlvbiB3aXRoIGEgbW9k\naWZpZWQgdmVyc2lvbiBvZgogICAgICAgdGhlIExpbmtlZCBWZXJzaW9uIHRv\nIHByb2R1Y2UgYSBtb2RpZmllZCBDb21iaW5lZCBXb3JrLCBpbiB0aGUKICAg\nICAgIG1hbm5lciBzcGVjaWZpZWQgYnkgc2VjdGlvbiA2IG9mIHRoZSBHTlUg\nR1BMIGZvciBjb252ZXlpbmcKICAgICAgIENvcnJlc3BvbmRpbmcgU291cmNl\nLgoKICAgICAgIDEpIFVzZSBhIHN1aXRhYmxlIHNoYXJlZCBsaWJyYXJ5IG1l\nY2hhbmlzbSBmb3IgbGlua2luZyB3aXRoIHRoZQogICAgICAgTGlicmFyeS4g\nIEEgc3VpdGFibGUgbWVjaGFuaXNtIGlzIG9uZSB0aGF0IChhKSB1c2VzIGF0\nIHJ1biB0aW1lCiAgICAgICBhIGNvcHkgb2YgdGhlIExpYnJhcnkgYWxyZWFk\neSBwcmVzZW50IG9uIHRoZSB1c2VyJ3MgY29tcHV0ZXIKICAgICAgIHN5c3Rl\nbSwgYW5kIChiKSB3aWxsIG9wZXJhdGUgcHJvcGVybHkgd2l0aCBhIG1vZGlm\naWVkIHZlcnNpb24KICAgICAgIG9mIHRoZSBMaWJyYXJ5IHRoYXQgaXMgaW50\nZXJmYWNlLWNvbXBhdGlibGUgd2l0aCB0aGUgTGlua2VkCiAgICAgICBWZXJz\naW9uLiAKCiAgIGUpIFByb3ZpZGUgSW5zdGFsbGF0aW9uIEluZm9ybWF0aW9u\nLCBidXQgb25seSBpZiB5b3Ugd291bGQgb3RoZXJ3aXNlCiAgIGJlIHJlcXVp\ncmVkIHRvIHByb3ZpZGUgc3VjaCBpbmZvcm1hdGlvbiB1bmRlciBzZWN0aW9u\nIDYgb2YgdGhlCiAgIEdOVSBHUEwsIGFuZCBvbmx5IHRvIHRoZSBleHRlbnQg\ndGhhdCBzdWNoIGluZm9ybWF0aW9uIGlzCiAgIG5lY2Vzc2FyeSB0byBpbnN0\nYWxsIGFuZCBleGVjdXRlIGEgbW9kaWZpZWQgdmVyc2lvbiBvZiB0aGUKICAg\nQ29tYmluZWQgV29yayBwcm9kdWNlZCBieSByZWNvbWJpbmluZyBvciByZWxp\nbmtpbmcgdGhlCiAgIEFwcGxpY2F0aW9uIHdpdGggYSBtb2RpZmllZCB2ZXJz\naW9uIG9mIHRoZSBMaW5rZWQgVmVyc2lvbi4gKElmCiAgIHlvdSB1c2Ugb3B0\naW9uIDRkMCwgdGhlIEluc3RhbGxhdGlvbiBJbmZvcm1hdGlvbiBtdXN0IGFj\nY29tcGFueQogICB0aGUgTWluaW1hbCBDb3JyZXNwb25kaW5nIFNvdXJjZSBh\nbmQgQ29ycmVzcG9uZGluZyBBcHBsaWNhdGlvbgogICBDb2RlLiBJZiB5b3Ug\ndXNlIG9wdGlvbiA0ZDEsIHlvdSBtdXN0IHByb3ZpZGUgdGhlIEluc3RhbGxh\ndGlvbgogICBJbmZvcm1hdGlvbiBpbiB0aGUgbWFubmVyIHNwZWNpZmllZCBi\neSBzZWN0aW9uIDYgb2YgdGhlIEdOVSBHUEwKICAgZm9yIGNvbnZleWluZyBD\nb3JyZXNwb25kaW5nIFNvdXJjZS4pCgogIDUuIENvbWJpbmVkIExpYnJhcmll\ncy4KCiAgWW91IG1heSBwbGFjZSBsaWJyYXJ5IGZhY2lsaXRpZXMgdGhhdCBh\ncmUgYSB3b3JrIGJhc2VkIG9uIHRoZQpMaWJyYXJ5IHNpZGUgYnkgc2lkZSBp\nbiBhIHNpbmdsZSBsaWJyYXJ5IHRvZ2V0aGVyIHdpdGggb3RoZXIgbGlicmFy\neQpmYWNpbGl0aWVzIHRoYXQgYXJlIG5vdCBBcHBsaWNhdGlvbnMgYW5kIGFy\nZSBub3QgY292ZXJlZCBieSB0aGlzCkxpY2Vuc2UsIGFuZCBjb252ZXkgc3Vj\naCBhIGNvbWJpbmVkIGxpYnJhcnkgdW5kZXIgdGVybXMgb2YgeW91cgpjaG9p\nY2UsIGlmIHlvdSBkbyBib3RoIG9mIHRoZSBmb2xsb3dpbmc6CgogICBhKSBB\nY2NvbXBhbnkgdGhlIGNvbWJpbmVkIGxpYnJhcnkgd2l0aCBhIGNvcHkgb2Yg\ndGhlIHNhbWUgd29yayBiYXNlZAogICBvbiB0aGUgTGlicmFyeSwgdW5jb21i\naW5lZCB3aXRoIGFueSBvdGhlciBsaWJyYXJ5IGZhY2lsaXRpZXMsCiAgIGNv\nbnZleWVkIHVuZGVyIHRoZSB0ZXJtcyBvZiB0aGlzIExpY2Vuc2UuCgogICBi\nKSBHaXZlIHByb21pbmVudCBub3RpY2Ugd2l0aCB0aGUgY29tYmluZWQgbGli\ncmFyeSB0aGF0IHBhcnQgb2YgaXQKICAgaXMgYSB3b3JrIGJhc2VkIG9uIHRo\nZSBMaWJyYXJ5LCBhbmQgZXhwbGFpbmluZyB3aGVyZSB0byBmaW5kIHRoZQog\nICBhY2NvbXBhbnlpbmcgdW5jb21iaW5lZCBmb3JtIG9mIHRoZSBzYW1lIHdv\ncmsuCgogIDYuIFJldmlzZWQgVmVyc2lvbnMgb2YgdGhlIEdOVSBMZXNzZXIg\nR2VuZXJhbCBQdWJsaWMgTGljZW5zZS4KCiAgVGhlIEZyZWUgU29mdHdhcmUg\nRm91bmRhdGlvbiBtYXkgcHVibGlzaCByZXZpc2VkIGFuZC9vciBuZXcgdmVy\nc2lvbnMKb2YgdGhlIEdOVSBMZXNzZXIgR2VuZXJhbCBQdWJsaWMgTGljZW5z\nZSBmcm9tIHRpbWUgdG8gdGltZS4gU3VjaCBuZXcKdmVyc2lvbnMgd2lsbCBi\nZSBzaW1pbGFyIGluIHNwaXJpdCB0byB0aGUgcHJlc2VudCB2ZXJzaW9uLCBi\ndXQgbWF5CmRpZmZlciBpbiBkZXRhaWwgdG8gYWRkcmVzcyBuZXcgcHJvYmxl\nbXMgb3IgY29uY2VybnMuCgogIEVhY2ggdmVyc2lvbiBpcyBnaXZlbiBhIGRp\nc3Rpbmd1aXNoaW5nIHZlcnNpb24gbnVtYmVyLiBJZiB0aGUKTGlicmFyeSBh\ncyB5b3UgcmVjZWl2ZWQgaXQgc3BlY2lmaWVzIHRoYXQgYSBjZXJ0YWluIG51\nbWJlcmVkIHZlcnNpb24Kb2YgdGhlIEdOVSBMZXNzZXIgR2VuZXJhbCBQdWJs\naWMgTGljZW5zZSAib3IgYW55IGxhdGVyIHZlcnNpb24iCmFwcGxpZXMgdG8g\naXQsIHlvdSBoYXZlIHRoZSBvcHRpb24gb2YgZm9sbG93aW5nIHRoZSB0ZXJt\ncyBhbmQKY29uZGl0aW9ucyBlaXRoZXIgb2YgdGhhdCBwdWJsaXNoZWQgdmVy\nc2lvbiBvciBvZiBhbnkgbGF0ZXIgdmVyc2lvbgpwdWJsaXNoZWQgYnkgdGhl\nIEZyZWUgU29mdHdhcmUgRm91bmRhdGlvbi4gSWYgdGhlIExpYnJhcnkgYXMg\neW91CnJlY2VpdmVkIGl0IGRvZXMgbm90IHNwZWNpZnkgYSB2ZXJzaW9uIG51\nbWJlciBvZiB0aGUgR05VIExlc3NlcgpHZW5lcmFsIFB1YmxpYyBMaWNlbnNl\nLCB5b3UgbWF5IGNob29zZSBhbnkgdmVyc2lvbiBvZiB0aGUgR05VIExlc3Nl\ncgpHZW5lcmFsIFB1YmxpYyBMaWNlbnNlIGV2ZXIgcHVibGlzaGVkIGJ5IHRo\nZSBGcmVlIFNvZnR3YXJlIEZvdW5kYXRpb24uCgogIElmIHRoZSBMaWJyYXJ5\nIGFzIHlvdSByZWNlaXZlZCBpdCBzcGVjaWZpZXMgdGhhdCBhIHByb3h5IGNh\nbiBkZWNpZGUKd2hldGhlciBmdXR1cmUgdmVyc2lvbnMgb2YgdGhlIEdOVSBM\nZXNzZXIgR2VuZXJhbCBQdWJsaWMgTGljZW5zZSBzaGFsbAphcHBseSwgdGhh\ndCBwcm94eSdzIHB1YmxpYyBzdGF0ZW1lbnQgb2YgYWNjZXB0YW5jZSBvZiBh\nbnkgdmVyc2lvbiBpcwpwZXJtYW5lbnQgYXV0aG9yaXphdGlvbiBmb3IgeW91\nIHRvIGNob29zZSB0aGF0IHZlcnNpb24gZm9yIHRoZQpMaWJyYXJ5LgoKLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t\nLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCiAgICAgICAgICAg\nU1BFQ0lBTCBFWENFUFRJT04gR1JBTlRFRCBCWSBDT1BZUklHSFQgSE9MREVS\nUwoKQXMgYSBzcGVjaWFsIGV4Y2VwdGlvbiwgY29weXJpZ2h0IGhvbGRlcnMg\nZ2l2ZSB5b3UgcGVybWlzc2lvbiB0byBsaW5rIHRoaXMKbGlicmFyeSB3aXRo\nIGluZGVwZW5kZW50IG1vZHVsZXMgdG8gcHJvZHVjZSBhbiBleGVjdXRhYmxl\nLCByZWdhcmRsZXNzIG9mCnRoZSBsaWNlbnNlIHRlcm1zIG9mIHRoZXNlIGlu\nZGVwZW5kZW50IG1vZHVsZXMsIGFuZCB0byBjb3B5IGFuZCBkaXN0cmlidXRl\nCnRoZSByZXN1bHRpbmcgZXhlY3V0YWJsZSB1bmRlciB0ZXJtcyBvZiB5b3Vy\nIGNob2ljZSwgcHJvdmlkZWQgdGhhdCB5b3UgYWxzbwptZWV0LCBmb3IgZWFj\naCBsaW5rZWQgaW5kZXBlbmRlbnQgbW9kdWxlLCB0aGUgdGVybXMgYW5kIGNv\nbmRpdGlvbnMgb2YKdGhlIGxpY2Vuc2Ugb2YgdGhhdCBtb2R1bGUuIEFuIGlu\nZGVwZW5kZW50IG1vZHVsZSBpcyBhIG1vZHVsZSB3aGljaCBpcyBub3QKZGVy\naXZlZCBmcm9tIG9yIGJhc2VkIG9uIHRoaXMgbGlicmFyeS4gSWYgeW91IG1v\nZGlmeSB0aGlzIGxpYnJhcnksIHlvdSBtdXN0CmV4dGVuZCB0aGlzIGV4Y2Vw\ndGlvbiB0byB5b3VyIHZlcnNpb24gb2YgdGhlIGxpYnJhcnkuCgo=\n",
"encoding": "base64",
"_links": {
"self": "https://api.github.com/repos/zeromq/netmq/contents/COPYING.LESSER?ref=master",
"git": "https://api.github.com/repos/zeromq/netmq/git/blobs/afab572debb5c88ab76ecca750c9b549e2fc78f5",
"html": "https://github.com/zeromq/netmq/blob/master/COPYING.LESSER"
},
"license": {
"key": "other",
"name": "Other",
"spdx_id": null,
"url": null,
"node_id": "MDc6TGljZW5zZTA="
}
}

**Comment by retslig** [comment]
This can be completed by updating you License.txt file to match Githubs known list licenses.
See here for exact details of how the license API works. https://developer.github.com/v3/licenses/
Brief snippet:

The Licenses API uses the open source Ruby Gem Licensee to attempt to identify the project's license. Licensee matches the contents of a project's LICENSE file (if it exists) against a short list of known licenses. As a result, the API does not take into account the licenses of project dependencies or other means of documenting a project's license such as references to the license name in the documentation.
If a license is matched, the license key and name returned conforms to the SPDX specification.

Another article that explains this well. https://blog.github.com/2016-09-21-license-now-displayed-on-repository-overview/

I tested this on one of my own repos and this did indeed work.
Only concern I have is that your license is in the known list.

**Comment by rebider** [comment]
mark
