### ISSUE TITLE
Make a stable NuGet

### ISSUE THREAD

**Issue by Stephilou** [zeromq/netmq#757]
### Environment

    NetMQ Version:    4.0.0.156-pre
    Operating System: Windows 10
    .NET Version:     4.7

### Expected behaviour
The latest stable release is 4.0.0.1 from the 22/01/2017
I would love to have a stable version of NetMQ with #656, #663 and #664
Those issues were solved with prerelease of NetMQ.

As nuget.exe prevent to use a prerelease dependency with stable release, my own nuget is stuck in prerelease.

What are the issues wich prevent to publish a stable version of NetMQ ?

Thanks

**Comment by Stephilou** [comment]
Any news for that?
Do you have plans on releasing a stable version?

If there is a list of issues that prevent the publication maybe I could help on these?

I don't want to put pressure on anyone, I just want to know if I'd better find another solution...

Anyway thank you for all the work!

**Comment by Stephilou** [comment]
Sorry wrong click...

**Comment by niwrA** [comment]
I second this ... why no stable version release?

**Comment by Stephilou** [comment]
Thanks for the release !
