### ISSUE TITLE
Secured communication with JeroMQ

### ISSUE THREAD

**Issue by willm01** [zeromq/netmq#762]
### Environment

NetMQ Version:    4.0.0.1
Operating System: windows10
.NET Version:     4.X

It doesn't appear that there is much on communicating between JeroMQ and NetMQ in terms of security. NetMQ.Security seems to be unique to NetMQ, where as Jero has Curve and Plain. Would the quickest route to secure messaging be to implement a similar X509 setup for Jero? Or maybe trying to implement some sort of working system from the NETMQ side that resembles Curve or Plain? Will this be looked at in the future?

**Comment by JingchengLao** [comment]
I got the same question mate, please check this out:

https://github.com/zeromq/jeromq/issues/628

**Comment by ptwohig** [comment]
Have you actually got any communication going between JeroMQ and NetMQ?  I have been largely unsuccessful.

**Comment by somdoron** [comment]
JeroMQ and NetMQ can communicate, JeroMQ had an issue with ZMTPv2 at some version but it was fixed. Regarding security, NetMQ is not implementing the zeromq curve encryption yet.
You can use clrzmq which is a wrapper around native zeromq.
