### ISSUE TITLE
Any plans to move license to MPLv2?

### ISSUE THREAD

**Issue by napalu** [zeromq/netmq#765]
ZeroMQ http://zeromq.org/area:licensing mentions the intention to move to the Mozilla Public license V2 and recommends:
"MPLv2 is the recommended license for new ZeroMQ projects, and where possible, ZeroMQ projects should collect approval from contributors to move towards MPLv2."
Moving to MPLv2 would make it easier for those of us who have to deal with corporate lawyers who get very nervous at anything with a 'GPL' in it,

**Comment by somdoron** [comment]
I know :(

However, we first need zeromq to move, and then ask all of the contributors to approve.
It will take time :(
