### ISSUE TITLE
Meaning of @ and > characters in connection string

### ISSUE THREAD

**Issue by samuell** [zeromq/netmq#771]
On many pages in the documentation, such as [this one](https://netmq.readthedocs.io/en/latest/message/), the connection string is started with an `@` character, such as in: `"@tcp://127.0.0.1:5556"`.

I haven't managed to find any documentation about what this means, neither on the NetMQ nor ZeroMQ documentation.

What is the meaning of the `@`-character? Any pointers welcome.

There is also a string `"&gt;tcp://127.0.0.1:5556"`, which looks like a formatting error on the documentation page? (Should it be `">tcp://127.0.0.1:5556"`?, and what is then the meaning of that?).

**Comment by somdoron** [comment]
When you provide list of addresses to ctors of the different socket types you can specify if you want the socket to bind or connect. This is what @ and > (bind and connect). Each socket type also have default behavior. For router for example the default behavior is bind.

**Comment by samuell** [comment]
> When you provide list of addresses to ctors of the different socket types you can specify if you want the socket to bind or connect. This is what @ and > (bind and connect). Each socket type also have default behavior. For router for example the default behavior is bind.

@somdoron  Ah, many thanks! Should have realized :)

**Comment by ogroehn** [comment]
I also do not think this is obvious. Wouldn't it be much clearer to have the behavior as a ctor argument instead of some magic strings? One could also use default values for the arguments so that it is clear for everyone.

**Comment by iiwaasnet** [comment]
@ogroehn There are bind() and connect() methods if you want it explicitly. I think @ and > are good for config approach.

**Comment by eatfrog** [comment]
i just spent hours stuck on this, because i didn't think the @ in the beginning of the example had any particular meaning. the discoverability is very poor with magic strings, and the documentation does not make it clear that in the examples it is vital that you actually use either @ or > to get the intended functionality.

**Comment by somdoron** [comment]
@eatfrog do you want to make a pull request removing the use of @ and > from the docs? I think it confused enough people. Next we can remove them from all the tests (and eventually mark them as obsolete)

**Comment by eatfrog** [comment]
sure, i can do it
