### ISSUE TITLE
How about changing attributes, [CanBeNull] in src/NetMQ/Msg.cs

### ISSUE THREAD

**Issue by moreal** [zeromq/netmq#774]
In function [Buffer.CopyBlock](https://docs.microsoft.com/en-us/dotnet/api/system.buffer.blockcopy?view=netframework-4.7.2), if src or dst is null, then it raises ArgumentNullException. So I think this shouldn't be null. But in Msg.cs source, function Put() allow null by using [CanBeNull] Attribute. So I suggest how about using attribute [NotNull] not [CanBeNull]

**Comment by somdoron** [comment]
Make the pull request

**Comment by moreal** [comment]
Ok, I will make the pr as soon
