### ISSUE TITLE
Calling RunAsync Causes Frequent Garbage Collection Calls

### ISSUE THREAD

**Issue by mrnr1** [zeromq/netmq#782]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: Windows 10 x64 (Version 10.0.17763 Build 17763)
    .NET Version:     4.6
    Visual Studio Community 2017 Version 15.9.4

### Expected behaviour
Calling RunAsync() should run without causing the .NET Garbage Collector to collect every couple of seconds.

### Actual behaviour
Calling RunAsync() causes the .NET Framework Garbage Collector to collect every couple of seconds.

### Steps to reproduce the behaviour
Call the RunAsync method on the NetMQPoller object and make a connection to another machine, e.x: 
`if (!_poller.IsRunning) _poller.RunAsync();`
If I remove this call, the GC stops collecting so often.

**Comment by mrnr1** [comment]
**With Call:** 
![withcall](https://user-images.githubusercontent.com/28109318/53049223-3b6ac780-345c-11e9-9f4e-5d437f015298.png)
**Without Call:** 
![withoutcall](https://user-images.githubusercontent.com/28109318/53049221-3b6ac780-345c-11e9-9f78-60718905e310.png)

**Average GC Collection interval:** 3.04 seconds

**Comment by somdoron** [comment]
Can you create a piece of code that reproduces the issue?
Alternatively, if you can run a memory profiler that will tell us what we create so many of.

**Comment by mrnr1** [comment]
Sure. Attached is the client project with quite a few redactions as to simplify analysis, but it does however demonstrate the issue. The server-side code is fairly standard. Please compile with /unsafe or strip out the Kernel32.SetConsoleCtrlHandler call from Server.cs. Please let me know if you need any additional information.

**Client Project Files:**
[ApexServerTesting.zip](https://github.com/zeromq/netmq/files/2890240/ApexServerTesting.zip)

**Client Memory Analysis (JetBrains dotMemory, 4 mins) Files:**
[ApexServerTesting DMW.zip](https://github.com/zeromq/netmq/files/2890243/ApexServerTesting.DMW.zip)

**Comment by mrnr1** [comment]
Can anybody confirm that they can replicate this issue as well? If so, I'll begin looking into NetMQPoller.

**Comment by somdoron** [comment]
Sorry, didn't have the time to look into that, will try this week
