### ISSUE TITLE
all source code wrong &gt;  <- this is error

### ISSUE THREAD

**Issue by avap90** [zeromq/netmq#783]
### Environment

    NetMQ Version:    v4.0.0.1
    Operating System: Windows 10
    .NET Version:     4.7.2

   site : https://netmq.readthedocs.io/en/latest/request-response/
  
### Expected behaviour
all source code wrong &gt ; <- this is error html source is <  but 
web page source code &gt ;

if user source code copy and past then runtime error &gt ; tcp://..... so error

**Comment by avap90** [comment]
https://ibb.co/3CbdTcj

**Comment by avap90** [comment]
[https://ibb.co/3CbdTcj](url)

**Comment by moreal** [comment]
actually &gt; is same with '>'

In my thought, it is occured by `readthedocs`, they will filter '<' and '>' for restrict xss

**Comment by somdoron** [comment]
can you make a pull request?

**Comment by moreal** [comment]
it seems i found the way to solve

can I be assigned on this issue?

**Comment by moreal** [comment]
https://netmq-forked.readthedocs.io/en/latest/request-response/

like this

**Comment by avap90** [comment]
> can you make a pull request?

...... can i have permission?

**Comment by avap90** [comment]
> https://netmq-forked.readthedocs.io/en/latest/request-response/
> 
> like this

nice!~~

**Comment by moreal** [comment]
@avap90 @somdoron 

I made pull request, can you check the new docs?

**Comment by avap90** [comment]
> @avap90 @somdoron
> 
> I made pull request, can you check the new docs?

Yes. I am checked.
But, not changed.... "&gt" same...

**Comment by moreal** [comment]
@avap90 

The original page will be changed when the pr was accepted

**Comment by moreal** [comment]
In my thought, it seems resolved by #785. Is there remained parts, yet?
