### ISSUE TITLE
Suggest to append codecov

### ISSUE THREAD

**Issue by moreal** [zeromq/netmq#784]
Suggest to append codecov for measure code coverage

**Comment by somdoron** [comment]
@moreal can you make the pull request?

**Comment by moreal** [comment]
@somdoron I will try to find the way (xunit, codecov)

**Comment by moreal** [comment]
I saw like this, https://github.com/tonerdo/coverlet

I will make pr as soon :)

**Comment by somdoron** [comment]
Thanks

**Comment by moreal** [comment]
Hello, @somdoron. Though it took a long time I just made new PR to resolve this. could you review it, please?
