### ISSUE TITLE
NetMq worker can't establish connection with Zmq Broker

### ISSUE THREAD

**Issue by zedo02** [zeromq/netmq#787]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System:  Windows 10
    .NET Core Version:   2.1

### Expected behaviour

NetMq worker should connect successfully with broker.

### Actual behaviour

NetMq worker not connecting successfully with broker.

### Steps to reproduce the behaviour

I'm using the following majordomo implementation: https://github.com/NetMQ/Samples/tree/master/src/Majordomo

I'm receiving System.FormatException: 'Input string was not in a correct format.'  at the broker's end. 

More details below:

[2019-03-26T14:59:45:9886552 +05:00] - I: MDP broker/0.2.0 is active at tcp://*:5555
[2019-03-26T15:00:10:8788153 +05:00] - I: received message:
[2019-03-26T15:00:10:8808128 +05:00] - 	D: [005]:0080000029
[2019-03-26T15:00:10:8808128 +05:00] - 	D: [000]:
[2019-03-26T15:00:10:8808128 +05:00] - 	D: [006]:MDPW01
[2019-03-26T15:00:10:8808128 +05:00] - 	D: [001]:01
[2019-03-26T15:00:10:8808128 +05:00] - 	D: [004]:test
[2019-03-26T15:00:12:9580603 +05:00] - I: registering new worker: '0080000029'
Exception thrown: 'System.FormatException' in mscorlib.dll
Input string was not in a correct format.

**Comment by KamranShahid** [comment]
> ### Environment
> ```
> NetMQ Version:    4.0.0.1
> Operating System:  Windows 10
> .NET Core Version:   2.1
> ```
> 
> ### Expected behaviour
> NetMq worker should connect successfully with broker.
> 
> ### Actual behaviour
> NetMq worker not connecting successfully with broker.
> 
> ### Steps to reproduce the behaviour
> I'm using the following majordomo implementation: https://github.com/NetMQ/Samples/tree/master/src/Majordomo
> 
> I'm receiving System.FormatException: 'Input string was not in a correct format.' at the broker's end.
> 
> More details below:
> 
> [2019-03-26T14:59:45:9886552 +05:00] - I: MDP broker/0.2.0 is active at tcp://*:5555
> [2019-03-26T15:00:10:8788153 +05:00] - I: received message:
> [2019-03-26T15:00:10:8808128 +05:00] - D: [005]:0080000029
> [2019-03-26T15:00:10:8808128 +05:00] - D: [000]:
> [2019-03-26T15:00:10:8808128 +05:00] - D: [006]:MDPW01
> [2019-03-26T15:00:10:8808128 +05:00] - D: [001]:01
> [2019-03-26T15:00:10:8808128 +05:00] - D: [004]:test
> [2019-03-26T15:00:12:9580603 +05:00] - I: registering new worker: '0080000029'
> Exception thrown: 'System.FormatException' in mscorlib.dll
> Input string was not in a correct format.

I am able to work with majordomo. there were some problem in the implementation. which i have corrected. some minor improvement is there
[MajorDomoPratternRelated.zip](https://github.com/zeromq/netmq/files/3635521/MajorDomoPratternRelated.zip)

**Comment by somdoron** [comment]
Want to make a pull request?

**Comment by KamranShahid** [comment]
Hi Doron Somech,
 As I have informed you i haven't use the pull request feature on github for active repository. Due to some workload i have directly shared my implementation in zip so that it might help other's.
Thanks
