### ISSUE TITLE
When will be the new Public release expected

### ISSUE THREAD

**Issue by KamranShahid** [zeromq/netmq#789]
I have seen so many issues get solved but there is no new release. are we expecting any release in recent time? Ideally it should also target .net standard 2 as well

**Comment by KamranShahid** [comment]
i have seen that release v4.0.1.2 is merged to master but not available on nuget package

**Comment by somdoron** [comment]
It is, as a pre-release

**Comment by KamranShahid** [comment]
> It is, as a pre-release

Ok. I amusing that pre release.

**Comment by dxdjgl** [comment]
@KamranShahid  4.0.1.4 has just been released, could you close the issue?
