### ISSUE TITLE
Issue Stats links in README.md are broken

### ISSUE THREAD

**Issue by garkpit** [zeromq/netmq#794]
### Environment

    NetMQ Version:    
    Operating System: 
    .NET Version:     

I used Firefox browser

### Expected behaviour

I don't know! Some sort of helpful web page [in English] perhaps?

Also, why 2 identical links there?

### Actual behaviour

A web site apparently in Indonesian

### Steps to reproduce the behaviour

Click the links.

**Comment by moreal** [comment]
Hello @garkpit, Could you specify what the links  able to reproduce it, please?

**Comment by garkpit** [comment]
The links are no longer present. You can close this issue.

Rather surprised to get a response _10 months_ after reporting it!
