### ISSUE TITLE
NetMQ not working in NUnit environment

### ISSUE THREAD

**Issue by gthvidsten** [zeromq/netmq#796]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: Windows 10 (1809)
    .NET Version:  .Net Core 2.2

### Expected behaviour

NetMQ should work in an NUnit environment

### Actual behaviour

No errors, but `ReceiveFrameBytes()` never receives any data

### Steps to reproduce the behaviour

I've created a Gist with my NetMQ implementation: https://gist.github.com/gthvidsten/e626d7e6c51012b1ba152d22e034d93d

If I run the following in a .Net Core console app, everything works fine:

```csharp
static void Main(string[] args)
{
    _transportWithHost = new NetMqTransport("tcp://localhost:9990", "tcp://localhost:9991", true);
    _transportWithHost.Start();

    Console.WriteLine("Press [Enter] to publish");
    Console.ReadLine();

    _transportWithHost.MessageReceived += (sender, e) =>
    {
        ;
    };
    _transportWithHost.Publish(new byte[] { 1, 2, 3, 4 });

    Console.WriteLine("Press [Enter] to exit");
    Console.ReadLine();
}
```

However, if I try to do the same in an NUnit test environment, the `MessageReceived` event is never fired!

```csharp
class NetMqTransportTests
{
    private NetMqTransport _transportWithHost;

    [OneTimeSetUp]
    public void Setup()
    {
        _transportWithHost = new NetMqTransport("tcp://localhost:9990", "tcp://localhost:9991", true);
        _transportWithHost.Start();
    }

    [Test]
    public void PublishTest()
    {
        ManualResetEvent mre = new ManualResetEvent(false);

        _transportWithHost.MessageReceived += (sender, e) =>
        {
            mre.Set();
        };

        _transportWithHost.Publish(new byte[] { 1, 2, 3, 4 });

        bool eventFired = mre.WaitOne(new TimeSpan(0, 0, 5));
        Assert.True(eventFired);
    }
}
```

Why does the virtually identical code work in a console app, but not in an NUnit environment?

**Comment by gthvidsten** [comment]
Bump?

**Comment by MeaningOfLights** [comment]
Hi Guys I've been trying to work out with gthvidsten how to unit test the NetMqTransport class and couldn't see any unit tests. Is there any chance you can shed light on this:
https://stackoverflow.com/questions/56975021/why-doesnt-netmq-work-in-an-nunit-environment

**Comment by dxdjgl** [comment]
See https://github.com/zeromq/netmq/issues/482 also mentioned in https://stackoverflow.com/questions/56975021/why-doesnt-netmq-work-in-an-nunit-environment
