### ISSUE TITLE
Proxy with no traffic still consumes over 20% cpu

### ISSUE THREAD

**Issue by robvon** [zeromq/netmq#798]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: WIndows Server 2012
    .NET Version:     4.7.2
    Running as a 'service' under IIS with an 'always running' app pool

### Expected behaviour

More or less no CPU overhead except when processing messages. BTW, the proxy works just fine when it does receive a message.

### Actual behaviour

Between 10 and 40% of the server is being consumed

### Steps to reproduce the behaviour

Create a proxy instance and start it.

**Comment by drewnoakes** [comment]
Can you use a profiler to see what it is doing?

Please provide some sample code that reproduces this.

**Comment by somdoron** [comment]
Which socket types, using with a poller?
