### ISSUE TITLE
Production nuget release -estimated date

### ISSUE THREAD

**Issue by WattsC-90** [zeromq/netmq#799]
Hi folks/contributors, 
Looks like youre doing a great job with issue tracking etc, i just wondered what the likelihood of a .netstandard 2.0 production release is? I see there are some pre-release versions, but with the release of .netcore 3.0, i wondered if you would allocate effort to that rather than .net std 2.0?

Well done though, i will be pulling the latest prerelease, just would prefer production!

**Comment by somdoron** [comment]
I made the 207 version a production version:
https://www.nuget.org/packages/NetMQ/4.0.0.207

I would guess supporting .net core 3 would be just to add another target to the csproj, @WattsC-90 do you want to try?

**Comment by drewnoakes** [comment]
There's no benefit to increasing the `netstandard` version on the package if we're not going to use newer APIs in the code itself. As it stands, it will run just fine on .NET Core 3.0.

Is there a particular reason you wanted to have it updated, or did you just want an official `netstandard`release?

**Comment by WattsC-90** [comment]
Its just about having an official release, my understanding is that unless its marked as dotnet 3 compatible it wont install the nuget? Maybe I am wrong? I am just trying to get all my ducks in a row before piling jn on a project!

**Comment by drewnoakes** [comment]
> my understanding is that unless its marked as dotnet 3 compatible it wont install the nuget

The maximum `netstandard` version that `netcoreapp3.0` supports isn't yet published on the [docs](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), but so long as a library supports `netstandard2.1` or lower, it will definitely work for you. The versions are backwards compatible.

If NetMQ increases the version of `netstandard` that is supports, fewer runtimes and platforms will be able to use it. Library maintainers are motivated to keep the version low to maximise support, but have to balance that against increasing the version to get access to newer library features.
