### ISSUE TITLE
Is there any analog of socket's listener or thing that seems like that?

### ISSUE THREAD

**Issue by Linkovskiy** [zeromq/netmq#800]
### Point
When I was doing my multi-clients server I've got a problem with getting clients. When a client just connected I want server to add client to my List with it's IP. Does anybody know how I can do this? Is there something that I can use like listener? Thanks in advance

**Comment by somdoron** [comment]
Not really.
You can design your own protocol on top of NetMQ, where the client sends a login message, and you can then register the client.

**Comment by Linkovskiy** [comment]
> Not really.
> You can design your own protocol on top of NetMQ, where the client sends a login message, and you can then register the client.

I also wanted to ask you if it's allowed to use your library as additional library in my own library?

**Comment by drewnoakes** [comment]
@Linkovskiy the [license is LGPL](https://github.com/zeromq/netmq/blob/master/COPYING.LESSER) which allows linking to a compiled NetMQ license from any other project, irrespective of what license your own project users. See the license for additional terms, such as if you make changes to NetMQ.
