### ISSUE TITLE
NetMQConfig.Cleanup(false) hangs

### ISSUE THREAD

**Issue by longfin** [zeromq/netmq#806]
### Environment

    NetMQ Version: 4.0.0.239-pre
    Operating System: macOS
    .NET Version:  .NETCore 2.2.203

### Expected behaviour

`NetMQConfig.Cleanup(false)` get stuck when it called.

### Actual behaviour

`NetMQConfig.Cleanup(false)` doesn't block current thread.

### Steps to reproduce the behaviour

```
public class SwarmTest : IDisposable
{
    // some test cases with NetMQSocket

     public void Dispose()
     {
        NetMQConfig.Cleanup(false);
     }
}
```

**Comment by longfin** [comment]
It seems that hanging [here](https://github.com/zeromq/netmq/blob/04e56a4a7187b783802d77101af87a34bfce28bc/src/NetMQ/Core/Ctx.cs#L214).

**Comment by follesoe** [comment]
Experiencing this issue still on macOS using version 4.0.1.6 when running unit tests. From what I can see the PR is merged and included in this release. Could it be a regression or a change in .NET Core on macOS?

**Comment by jen-co** [comment]
Hitting this issue as well on macOS using version 4.0.1.10.
