### ISSUE TITLE
Cannot achieve high MulticastRate with NetMQ SubscriberSocket

### ISSUE THREAD

**Issue by ragohin** [zeromq/netmq#809]
### Environment

    NetMQ Version: 4.0.0.207
    Operating System: Windows 10 x64 (Version 10.0.18362)
    .NET Version: .NET Framework 4.7.2
Visual Studio Professional 2017 Version 15.9.23

### Expected behaviour

On a Linux VM, I am running a zeromq (C++) PublisherSocket. There doesn't seem to be any apparent issues with this.

In Windows, a NetMQ (C#) SubscriberSocket inside of a NetMQPoller as shown in the code below. In the publisher code, I limit the rate that the PublisherSocket sends at by setting an upper limit on the MulticastRate as well as encoding sleeps. My expected behavior is to send data from the PublisherSocket at rates up to 1Gbps and receive on the SubscriberSocket side at rates up to 1Gbps as well.

### Actual behaviour

I can verify that the Publisher Socket can send data up to rates of 1Gbps, but the SubscriberSocket cannot seem to keep up. Without setting an upper limit on the SubscriberSocket's MulticastRate (i.e. setting it to 1Gbps), the SubscriberSocket can only reliable receive data if the PublisherSocket sends at no more than 400Gbps. At any higher speed, the SubscriberSocket starts dropping messaging and potentially does not receive anything at all.

Analyzing throughput in Task Manager in Windows, even without limiting the MulticastRate, the throughput on receiving data cannot reach higher than ~400-500 Mbps.

Is there an inefficiency in my code somewhere that might be limiting the SubscriberSocket's reliable receiving rate? Potentially the fact that I am using a NetMQPoller? 

Thanks.

### Steps to reproduce the behaviour

Client Code
```
public Subscriber(string name, string[] topics, string multicastAddress, string publisherTestLoggerAddress) : this()
{
    Console.WriteLine("Starting new subscriber session");

    _name = name;
    _test = new TestResults(name, topics, publisherTestLoggerAddress);
    _multicastAddress = multicastAddress;

    //Initialize Timer Events
    _timerTimeout = TimeSpan.FromSeconds(10);
    _timer = new NetMQTimer(_timerTimeout);
    _timer.Elapsed += ProcessMessageTransmissionEnd;
    _timer.Enable = false;
}

// Methods
public void RunSubscriber()
{
    using (NetMQPoller Poller = new NetMQPoller())
    using (SubscriberSocket Sub = new SubscriberSocket())
    {
        // Initialize socket options
        Sub.Options.ReceiveHighWatermark = 0;
        Sub.Options.MulticastRate = 1000*1000; //1000*Kb
        Sub.Options.Linger = TimeSpan.FromSeconds(1);
        Sub.Options.ReceiveBuffer = 0;
        Sub.Connect(_multicastAddress);
        Thread.Sleep(10);
        Console.WriteLine("Connecting to Multicast Publisher at {0}", _multicastAddress);
        
        if (_test._topics.Length > 0)
        {
            foreach (var topic in _test._topics)
                Sub.Subscribe(topic);
        }
        else
            Sub.SubscribeToAnyTopic();
            
        Sub.ReceiveReady += ProcessMessageReceived;

        // Initialize/run poller
        Poller.Add(Sub);
        Poller.Add(_timer);
        Thread.Sleep(10);
        Poller.Run();
    }
}
public void ProcessMessageReceived(Object source, NetMQSocketEventArgs e)
{
    string topic;
    while (e.Socket.TryReceiveFrameString(out topic))
    {
        string msgData = e.Socket.ReceiveFrameString();

        Console.Write(++_test._numMessagesReceived % 10 == 0 ? "|" : ".");
        Message newMsg = new Message(msgData);

        //Check if msg passed checksum
        if (newMsg._passed)
            ++_test._numMessagesPassedChecksum;
        
        //Check for dropped messages
        uint drops;
        if ((drops = newMsg._seqNum - (_test._lastSeqNum + 1)) > 0)
        {
            _test._numDroppedMessages += (int)drops;
            Console.Write("Dropped {0} message(s)", (int)drops);
        }
        _test._lastSeqNum = newMsg._seqNum;

        // Record time of first packet received/last received
        if (_test._numBytesReceived == 0)
        {
            _test._timeFirstMessageSentByPublisher = newMsg._timestamp;
            _test._timeFirstMessageReceived = (DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalMilliseconds;
        }
        _test._timeLastMessageReceived = (DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalMilliseconds;
        
        // Update total number of bytes received
        int numBytes = (msgData.Substring(96)).Length;
        _test._numBytesReceived += numBytes;

        // Reset timer
        _timer.EnableAndReset();
    }
}
```

**Comment by drewnoakes** [comment]
Console output can be slow. Have you tried this without logging every frame?

**Comment by somdoron** [comment]
Also try increasing watermark & ReceiveBuffer on the subscriber.

**Comment by ragohin** [comment]
I attempted without logging every frame, but it seems like increasing the watermark (to 10,000) did the trick. In any case, I thought a value of 0 was supposed to place "no limit" on the watermark?

**Comment by ragohin** [comment]
I'm still having some suspicious behavior on my client side. I'm a bit confused by the role of the "MulticastRate" socket option. If I have this set to 300 Mbps (300,000 Kbps) for both the Publisher and Subscriber, there are no issues. All messages are transmitted perfectly. However, if I set Subscriber's MulticastRate any higher (say up to 1000 Mbps), the Subscriber starts dropping message. 

Does MulticastRate have to be the same on both Publisher and Subscriber? And if so, why?

Thanks again,
Hinton
