### ISSUE TITLE
TrySend/TryReceive with timeout specified: socket becomes unusable after timeout

### ISSUE THREAD

**Issue by Cassandra-d** [zeromq/netmq#817]
If I want to send and receive messages in a loop, I would go with something like
```
while(true)
{
	success = requestSocket.TrySendFrame(requestTimeout, request);
	if (!success)
        {
            NotifyFailedSend();
            continue;
        }

	success = requestSocket.TryReceiveFrameString(requestTimeout, out response);
	if (!success)
		NotifyFailedRecv();
}
```
The problem arises when `TrySendFrame` ends successfully and `TryReceiveFrameString` returns by timeout. In that case, on the next loop iteration I will get an exception that `TrySendFrame` can't be called as receive isn't finished/called yet.

Normally, I would expect that TryXXX methods would not put object in broken state, but in case of sockets, I'll have to recreate one to be able to have loop calls. And that's a bit performance inefficient.

Is there any workarounds so I wouldn't need to recreate sockets and I will be able to notify that send/recv hasn't finished in appropriate time?

I've found `RequestResponseStringWithRetry` which does almost what I need, except that it creates a new socket internally on each iteration.

**Comment by somdoron** [comment]
There is a work around.
The problem is, that if you don't create a new socket you might get an old reply.

The workaround, with the issue above, is to use Dealer instead of Request. To accomplish this you must first send an empty frame and then your message, you can do the following:

```
requestSocket.SendMoreFrameEmpty().TrySendFrame(requestTimeout, request);
```

That will solve your problem, but as I said, you might get an old replies.

libzmq actually solved this, with sending a request id,  as part of every request and matching it to the response, if it is an old one it will be dropped. This is completely backward-compatible, actually, you can have the Req be libzmq and Rep be netmq and it will still work.

If you want, I can mentor you in porting this feature. Let me know I will look for the commits in libzmq

**Comment by Cassandra-d** [comment]
@somdoron , thanks for the help.
I'm interested in porting that feature that drops old replies.
Do you have a link for the original code where I can look at what needs to be done?
Will appreciate your help in porting this feature.

**Comment by somdoron** [comment]
So what you want is a combination of two features with in libzmq, ZMQ_REQ_CORRELATE and ZMQ_REQ_RELAXED.

Both are options for the request socket.
You can port it from here:
https://github.com/zeromq/libzmq/blob/master/src/req.cpp

To here:
https://github.com/zeromq/netmq/blob/master/src/NetMQ/Core/Patterns/Req.cs

Relevant commits:
https://github.com/zeromq/libzmq/commit/b9646f2aacf414eb30044a9be3a03d2bd9230c7f#diff-80edcca992f1dac36f48cb59ffba75cc
https://github.com/zeromq/libzmq/commit/a0cc87a9d922dd3187f07962536ee676033e0ef8#diff-80edcca992f1dac36f48cb59ffba75cc
https://github.com/zeromq/libzmq/commit/f5c59556bd232064230b39c05d858ce69d59ae09#diff-80edcca992f1dac36f48cb59ffba75cc
https://github.com/zeromq/libzmq/commit/423ca36b17264ca7b71b23e4a110aa847fd7ac27#diff-80edcca992f1dac36f48cb59ffba75cc
https://github.com/zeromq/libzmq/commit/89417ddb9f9609a9d719d288391e03c531d365b7#diff-80edcca992f1dac36f48cb59ffba75cc
https://github.com/zeromq/libzmq/commit/89417ddb9f9609a9d719d288391e03c531d365b7#diff-80edcca992f1dac36f48cb59ffba75cc
https://github.com/zeromq/libzmq/commit/e45dfe3bc7e19233c7d0e1244c62c48cba227b4e#diff-80edcca992f1dac36f48cb59ffba75cc
https://github.com/zeromq/libzmq/commit/625b6187767451444fb68035883f442393b87f9f#diff-80edcca992f1dac36f48cb59ffba75cc
https://github.com/zeromq/libzmq/commit/c8592dfbc337dd43cdc12962508918e5a51b6ad3#diff-80edcca992f1dac36f48cb59ffba75cc
https://github.com/zeromq/libzmq/commit/423ca36b17264ca7b71b23e4a110aa847fd7ac27#diff-80edcca992f1dac36f48cb59ffba75cc

**Comment by Cassandra-d** [comment]
@somdoron 
Thanks for the links, will look.
I will be absent this week and will start porting starting from the next one.
