### ISSUE TITLE
Majordomo with cluster where i have number of separate broker/worker sets

### ISSUE THREAD

**Issue by KamranShahid** [zeromq/netmq#820]
### Environment

    NetMQ Version:    4.0.0.207
    Operating System: Windows/Linux
    .NET Version: .net core 2.1.6    

### Expected behavior

Make cluster of brokers which will load balance as per worker availability.

### Actual behavior

At the moment i have Majordomo pattern implemented as per https://github.com/NetMQ/Samples . For load balancing i am using nginix. What i want is to avoid nginix and do load balancing with zmq/netmq

Please guide me how to achieve.

**Comment by KamranShahid** [comment]
Any help guys?

**Comment by somdoron** [comment]
Deploy multiple majordomo brokers, each talking to all workers. Then the client can be a dealer that connects to all brokers. Dealer socket automatically do round robin.

**Comment by KamranShahid** [comment]
Client shouldn't know how many brokers are there. On client end there will be single ip on which they will be requesting. At the moment i have already tested with two broker sets which have workers attached to them. I have done it via ngnix proxy at front of two brokers. Client connect with that ngnix. Now i am thinking if i can try out some thing without ngnix.

**Comment by KamranShahid** [comment]
basic idea is i can put broker worker set on the fly on basis of load. Also instead of round robin request should be sent to those broker/workers which have less load.

**Comment by KamranShahid** [comment]
Client ideally needed to know single external address to communicate. also trying interbrokerouter sample but it's seems not to work. have posted an issue there
