### ISSUE TITLE
Topic comparison based on substring?

### ISSUE THREAD

**Issue by Kelvhan** [zeromq/netmq#822]
### Environment

    NetMQ Version:   4.0.0.1  
    Runtime Version: 4.0.30319
    Operating System:  Win10 / Win Server 2012 R2
    .NET Version:     4.5

### Expected behaviour

"a:HAI"

### Actual behaviour

"a:HAI"
"ab:HAI2"
"abc:HAI3"

### Steps to reproduce the behaviour

Subscriber Side:

String topic = "a";
subSocket.Subscribe(topic);

                while (isAlive)
                {
                    string messageTopicReceived = subSocket.ReceiveFrameString();
                    string messageReceived = subSocket.ReceiveFrameString();
                    Console.WriteLine(messageTopicReceived + ":" + messageReceived);

                  ...

Publisher Side:

pubSocket.SendMoreFrame("a").SendFrame("HAI");
pubSocket.SendMoreFrame("ab").SendFrame("HAI2");
pubSocket.SendMoreFrame("abc").SendFrame("HAI3");

*code condensed.

**Comment by drewnoakes** [comment]
Only prefix matching is supported.
