### ISSUE TITLE
Concurrency issues in Clock.cs

### ISSUE THREAD

**Issue by acizmarik** [zeromq/netmq#823]
Current implementation of `NowMs` is source of multiple concurrency issues which causes the method to return incorrect time. The issue is caused by usage of two static fields `s_lastTsc` and `s_lastTime`

https://github.com/zeromq/netmq/blob/057532db183ea001548a54a22ffebd630801c000/src/NetMQ/Core/Utils/Clock.cs#L88-L105

The condition `if (tsc - s_lastTsc <= Config.ClockPrecision / 2 && tsc >= s_lastTsc)` is in race with the subsequent assignments (both can be issued from different threads):
`s_lastTsc = tsc;`
`s_lastTime = NowUs() / 1000;`

Additionally when reading/writing 64bit fields, one must use `Interlocked.Read` or `Interlocked.Write` to ensure that these operations are atomic also for 32bit programs.

**Comment by somdoron** [comment]
Want to make a pull request?

**Comment by Andy1221** [comment]
Yes I will make one tomorrow or later today.

**Comment by somdoron** [comment]
Thanks
