### ISSUE TITLE
Is it possible to bind one socket with inproc and tcp both type of address?

### ISSUE THREAD

**Issue by KamranShahid** [zeromq/netmq#825]
I have implemented a majordomo implementation as per netmq samples. I have some external client sending the request on tcp://ip:port which is recived by broker and process by workers as per requested service.
What appears that communication between broker and worker seems slow.
What i am thinking is if there is any possibility that client connect with same broker in tcp address while broker and worker communication can be done in inproc
I am using .net core 3.0 with netmq library version as 4.0.0.207

**Comment by somdoron** [comment]
Yes. You can bind a socket to multiple addresses. Both tcp and inproc
