### ISSUE TITLE
Does NetMQ supports ZMQ Curve Encryption Algorithm?

### ISSUE THREAD

**Issue by rpbarros** [zeromq/netmq#827]
Does NetMQ supports ZMQ Curve Encryption Algorithm?

**Comment by KamranShahid** [comment]
can you give bit detail about what you want to try?
Curve encryption is simply a way of encryption whom you can find number of example in C#
where as netmq is native implemenation of ZeroMQ messaging

**Comment by somdoron** [comment]
NetMQ doesn't support zeromq curve mechanism yet.

**Comment by rpbarros** [comment]
Thank you, Doron!

Is there an effort to have it supporting Curve?

Rgds,

Rodrigo.


==========================
Rodrigo de Passos Barros
Cel:  +55 19 991390804
email: rpbarros@gmail.com
Skype: rodrigopassosbarros


Em dom, 27 de out de 2019 às 11:43, Doron Somech <notifications@github.com>
escreveu:

**Comment by somdoron** [comment]
I can see myself allocating time for this in the coming months.

**Comment by somdoron** [comment]
It is not ongoing effort. ZMTP3 with null mechanism is already in master

**Comment by dxdjgl** [comment]
@rpbarros 4.0.1.4 has just been released with curve support, could you close this ticket?
