### ISSUE TITLE
NetMQ.Monitoring.NetMQMonitor.AttachToPoller signature changed

### ISSUE THREAD

**Issue by amichel** [zeromq/netmq#829]
### Environment

    NetMQ Version:    4.0.0.207,4.0.0.1
    Operating System: 
    .NET Version: 4.8    

### Expected behaviour
After upgrading project from 4.0.0.1 to 4.0.0.207 
Existing code throws 
**System.MissingMethodException: Method not found: 'Void NetMQ.Monitoring.NetMQMonitor.AttachToPoller(NetMQ.ISocketPollableCollection)'.**

previous signature was:
```csharp
 public void AttachToPoller(ISocketPollableCollection poller) {}
```
new signature:
```csharp
 public void AttachToPoller([NotNull] NetMQPoller poller) {}
```

This looks like a non-backward compatible change introduced in minor release

**Comment by somdoron** [comment]
Do you want to make a pull request? I will release a new beta after it.

**Comment by amichel** [comment]
I consider an overload and then on next major you can decide whether to obsolete one of them.

**Comment by somdoron** [comment]
That will work too.
