### ISSUE TITLE
Can UDP???支持UDP吗？？？

### ISSUE THREAD

**Issue by BUGyyc** [zeromq/netmq#833]
支持UDP吗？
`            using (var client = new NetMQ.Sockets.RequestSocket())
            {
                client.Connect("udp://localhost:5555");
                for (int i = 0; i < 10; i++)
                {
                    Console.WriteLine("Client Sending Hello");
                    client.SendFrame("Hello");
                    var message = client.ReceiveFrameString();
                    Console.WriteLine("Server Rep Msg: {0}", message);
                }
            }`

ERROR:

**NetMQ.ProtocolNotSupportedException:“Invalid protocol: udp”**

**Comment by KamranShahid** [comment]
Please check
https://netmq.readthedocs.io/en/latest/transports/
I can't see udp supported

**Comment by somdoron** [comment]
Udp is not  supported.
