### ISSUE TITLE
How to know which client is disconnected，怎么确定是哪一个客户端断开连接

### ISSUE THREAD

**Issue by zcteo** [zeromq/netmq#840]
### Environment
    NetMQ Version:    Latest of master
    Operating System: window 10 1909
    .NET Version:     framework4.0 && standard2.0 

 A RouterSocket as server, and the clients are DealerSockets. Use a Monitor to listen the RouterSocket 's Disconnected event. When listened to the client disconnected, how to confirm which client is disconnected.

**Comment by dxdjgl** [comment]
It seems to work, with the following code I get the ipaddress and port of the client.
        static void Main(string[] args)
        {
            using (var rep = new RouterSocket())
            using (var req = new DealerSocket())
            using (var monitor = new NetMQMonitor(rep, "inproc://rep.inproc", SocketEvents.Accepted | SocketEvents.Disconnected))
            {
                monitor.Accepted += (s, a) =>
                {
                    Console.WriteLine("local accept " + a.Address);
                    Console.WriteLine("accept " + a.Socket.RemoteEndPoint);

                };
                monitor.Disconnected+= (s, a) =>
                {
                    Console.WriteLine("local disconnected " + a.Address);
                    Console.WriteLine("disconnected " + a.Socket.RemoteEndPoint);
                };

                monitor.Timeout = TimeSpan.FromMilliseconds(100);

                var monitorTask = Task.Factory.StartNew(monitor.Start);

                Thread.Sleep(10);

                var port = rep.BindRandomPort("tcp://0.0.0.0");

                req.Connect("tcp://127.0.0.1:" + port);

                Thread.Sleep(50);
                req.Dispose();

                monitor.Stop();
            }
        }

**Comment by dxdjgl** [comment]
I Will close this issue, if problem still exist please reopen.

**Comment by zcteo** [comment]
**sometimes, e.Socket could throw an exception**

![screen](https://user-images.githubusercontent.com/39565725/97946506-a5a8d480-1dc5-11eb-8e28-8b287c9c458f.jpg)
