### ISSUE TITLE
Documentation Code example not work

### ISSUE THREAD

**Issue by tinohager** [zeromq/netmq#841]
All code is in one line without syntax highlighting

https://netmq.readthedocs.io/en/latest/queue/

![image](https://user-images.githubusercontent.com/8215186/71882002-d7b0c200-3133-11ea-88d0-069868ab67e0.png)

**Comment by drewnoakes** [comment]
This looks like a bug in readthedocs.

The problem also exists in https://netmq.readthedocs.io/en/latest/timer/, though not in https://netmq.readthedocs.io/en/latest/async-await/ and others. Perhaps it doesn't like documents that end in a fenced code block?
