### ISSUE TITLE
Support cancellation tokens everywhere where you can set a timeout

### ISSUE THREAD

**Issue by erndob** [zeromq/netmq#855]
Currently CancellationToken is not supported, which is an issue if you are trying to handle a shut down of a service. At the moment you are forced to make the timeouts short enough to catch the canceled token in between requests, but it would work a lot better if instead of just timeout, CancelationToken itself would be accepted too.

I could try implementing this if you agree.

**Comment by somdoron** [comment]
I'm not sure it is possible to implement the cancellation tokens.
NetMQ is using sockets (file descriptors) and `select` for signaling.  To use cancellation token you would have to get a handle that can be used in a select operation.

**Comment by erndob** [comment]
@somdoron You are right. I've quickly had a look at NetMQSelector, saw some timeout logic in an infinite loop and assumed it can be handled there.

**Comment by somdoron** [comment]
Ok, you would still have to use some timeout, like half second to query the token.
