### ISSUE TITLE
Run tests on debug builds

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#888]
@somdoron currently tests run with release builds. We have quite a few debug assertions in code that only run during debug builds. What would you say about running tests on debug builds so that these assertions are included?

The only downside I can see is that builds would be slower.

I am adding a trace listener that converts the assertion dialogs into exceptions, so there won't be any popups during CI.

**Comment by somdoron** [comment]
Sounds good to me. I'm thinking maybe to do both, as eventually, users are using the release version.

**Comment by drewnoakes** [comment]
#895 contributes to this.

I'll look into setting up GitHub workflows (#891) that run tests in both debug and release.
