### ISSUE TITLE
Socket Identity not honored when using InProc

### ISSUE THREAD

**Issue by reiroldan** [zeromq/netmq#89]
I've not tested this thoroughly just yet, but it seams that when using the InProc transport, the connecting socket's identity is ignored for Router sockets. 

Both setting the identity before or after connecting exhibits the same behavior.

**Comment by somdoron** [comment]
solved by #343

**Comment by iiwaasnet** [comment]
Confirm the same behavior.
Is it fixed in NetMQ version="3.3.0.13-alpha594?

**Comment by somdoron** [comment]
Fixed in master
