### ISSUE TITLE
Empty NetMQPoller throws "contains a disposed NetMQSocket" exception on dispose

### ISSUE THREAD

**Issue by snechaev** [zeromq/netmq#905]
When I create poller without any items at all, it throws on Dispose call.

### Environment

    NetMQ Version: 4.0.0.207 from nuget 
    Operating System: Win10 pro 1909
    .NET Version:     Net FW4.8

### Expected behaviour
Application finishes without any exceptions

### Actual behaviour
Exception
NetMQ.NetMQException: 'Invalid state detected: NetMQPoller contains a disposed NetMQSocket. Sockets must be either removed before being disposed, or disposed after the poller is disposed.'

### Steps to reproduce the behaviour
* create net FW 4.8 console application
* insert following code
```
        static void Main(string[] args)
        {
            using (var poller = new NetMQ.NetMQPoller())
            {
            }
        }

```
* run

**Comment by snechaev** [comment]
The code above works fine after downgrade from 4.0.0.207 to 4.0.0.1

**Comment by somdoron** [comment]
I think I fixed it with later versions, can you check with latest pre release?

**Comment by snechaev** [comment]
Yes, you are right - works fine on version 4.0.1.2-pre.
