### ISSUE TITLE
Migrating to zeromq from clrzmq4

### ISSUE THREAD

**Issue by grahamglover** [zeromq/netmq#916]
Is there any documentation / wiki on translating to netmq from the clrzmq binding?

I particularly want to take advantage of the netmq websocket extension so can use a zmq server / browser pub-sub. 

Was hoping that the clrzmq translated e.g. ZContext, ZSocket etc persisted but alas it seems to require a refactor to new classes - any conversion headstart would be greatly appreciated please :)

**Comment by h2zzhou** [comment]
libzeromq   
New DRAFT (see NEWS for 4.2.0) transport options WS and WSS added for support
of WebSockets (and secure WebSockets via TLS) via the ZWS 2.0 protocol.
