### ISSUE TITLE
Background Thread Default False Needs Comments Change

### ISSUE THREAD

**Issue by tylerje** [zeromq/netmq#926]
https://github.com/zeromq/netmq/blob/45365a6fc999111fe51e34f4f15257fc145fc2a8/src/NetMQ/NetMQPoller.cs#L429

The recent change to this line in the code makes the XML comments false in the two methods that call that method. It's not a huge deal. Just a nitpick.

**Comment by dxdjgl** [comment]
You are right the comment has never been valid, since it has previously been executed as a foreground thread. I have fixed the comments for the 2 method in a pull request.
