### ISSUE TITLE
.NET 3.5 compatibility

### ISSUE THREAD

**Issue by cncfanatics** [zeromq/netmq#98]
I write games using Unity 3D.

Unity 3D uses mono to run managed code, while the engine itself is written in another language.
This means all extra programming happens using mono. Unfortunatly, it's a rather outdated version of mono that doesn't have any of the features of .NET 4.0.

NetMQ refuses to run on it, is it possible to fix this ?

(I could possibly do this myself with some guidance on how to do this)

**Comment by neozeed** [comment]
I started to play around with Kerbal Space program, a which is powered by Unity3d, and I wanted to take a plugin, namely <a href="//https://raw.githubusercontent.com/zitron-git/KSPSerialIO/master/KSPSerialIO/KSPIO.cs">KSPIo</a>, and convert it to using some kind of messaging.  Naturally mono doesn't support Win32 named pipes, so I thought I'd try netmq.  I downloaded the zip file from <a href="https://github.com/somdoron/netmq/tree/Unity">here</a>, and loaded it into Visual Studio 2013, and built the .net 3.5 version.  It 'builds' in under a second so I wonder if it's really compiling anything....  Anyways as a simple test, I setup two small projects in VS 2013, a client/server to verify that they work with .net 3.5 ...

Server:
<quote>
using System;
using System.Threading;
using NetMQ;

namespace HelloWorldDemo
{
    class Program
    {
        private static void Main(string[] args)
        {
            NetMQ.NetMQContext xx = NetMQContext.Create();
            NetMQ.Sockets.ResponseSocket xy = xx.CreateResponseSocket();
            xy.Bind("tcp://127.0.0.1:5557");
            while (true)
            {
                Console.WriteLine(xy.ReceiveString());
                xy.Send("Packet ");
            }
        }
    }
}
</quote>

Client:
<quote>
using System;
using NetMQ;

namespace HelloWorldDemo
{
    class Program
    {
        private static void Main(string[] args)
        {
            NetMQ.NetMQContext xx = NetMQContext.Create();
            NetMQ.Sockets.RequestSocket xz = xx.CreateRequestSocket();
            xz.Connect("tcp://127.0.0.1:5557");
            xz.Send("Data");
            Console.WriteLine(xz.ReceiveString());
            xz.Disconnect("tcp://127.0.0.1:5557");
        }
    }
}
</quote>

And these work as I'd expect.

So now the fun part, I paste the client portion into the existing plugin, on it's awake method, and I get this nice crash...

<quote>
[EXC 12:41:29.332] FormatException: Invalid format for Guid.Guid(string).
	System.Guid+GuidParser.ParseChar (Char c)
	System.Guid+GuidParser.ParseGuid2 ()
	System.Guid+GuidParser.Parse ()
	System.Guid..ctor (System.String g)
	AsyncIO.Windows.UnsafeMethods..cctor ()
	Rethrow as TypeInitializationException: An exception was thrown by the type initializer for AsyncIO.Windows.UnsafeMethods
	AsyncIO.CompletionPort.Create ()
	NetMQ.zmq.Utils.Proactor..ctor (System.String name)
	NetMQ.zmq.IOThread..ctor (NetMQ.zmq.Ctx ctx, Int32 threadId)
	NetMQ.zmq.Ctx.CreateSocket (ZmqSocketType type)
	NetMQ.NetMQContext.CreateHandle (ZmqSocketType socketType)
	NetMQ.NetMQContext.CreateRequestSocket ()
	KSPSerialIO.SettingsNStuff.Awake ()
</quote>

Obviously I'm doing something wrong.

**Comment by somdoron** [comment]
You are actually doing ok, NetMQ is using AsyncIO, which uses guid in a way
that mono doesn't support, I fixed that but need to release a version and
netmq to use that. Anyway you can download the source code from following
link, it should work:

https://github.com/zeromq/netmq/pull/175

and compile netmq.unity

**Comment by neozeed** [comment]
Wow that did it!  

I'm now exporting my telemetry data from my rocket!  This is totally awesome!

I don't know why, but i had to manually add the project NetMQ.Unity to the master project, but again it compiles in 1 second, and works!

Thank you so much for your help!!!!

**Comment by krisrok** [comment]
for later visitors looking for a unity compatible version: by now it works with the .net3.5 project in the master branch, no need to resort to somdoron's previous pull request. (working for win, osx and ios export).

**Comment by FaisalZ** [comment]
@krisrok are you shure that the 3.3.0.11 release of netMQ is compatible with Unity? I tried to use it, and it compiles and imports without issues. But there are no messages comming through (using a simple PUSH/PULL pattern).
When I swap the AsyncIO.dll and NetMQ.dll to the ones compiled from the Unity fork by @somdoron it workes flawless.

**Comment by somdoron** [comment]
Try version 3.3.0.12-rc1, or to build from source.

**Comment by Flime** [comment]
I cant get NetMQ to work when building for Android in Unity. It doesnt have any errors, but the server does not receive anything. In the unity editor it does work. But I need to restart the Unity every time when I hit play for the second time. (Unity freezes) I used the 3.3.0.12-rc1 build.

**Comment by somdoron** [comment]
Try to compile from master, also try to run following line at the beginning
of the Main functions:

ForceDotNet.Force();

**Comment by somdoron** [comment]
Also if it still doesn't work, try to compile NetMQ with AsyncIO.Unity from
here:

https://github.com/somdoron/AsyncIO/tree/master/Source/AsyncIO

**Comment by Flime** [comment]
It does work. Only after a few minutes it stops working. I need to reopen my unity android app to let it start working again.

**Comment by pixerati** [comment]
Hey guys,

I've been happily working with this build of NetMQ for Unity both in OS X and Windows. 

But I've been doing all my testing using the loop back 127.0.0.1. As soon as I moved the server (a Pyzmq server) to another machine I get no connection, at least nothing that sends and receives data.

I'm using tcp://*:5555 as the bind address on the server and tcp://theServerMachineIP:5555 on the client. 

When I look at windows netstat on the server box it actually shows an active connection with the client binding to 5555 but connecting to some random port on the client (which I'm assuming is normal) but my code is unresponsive in terms of sending and receiving data. 

No the machines firewalls are off and I've even explicitly set rules to allow port 5555 through, but no joy. Even tried connecting to a different router in case that was the issue. 

Any ideas? So weird that it works fine on the same machine using the loopback. Incredibly frustrating after having spent weeks building up the code on a local box and everything testify fine:(

**Comment by drewnoakes** [comment]
Can you telnet to port 5555 between the boxes? That's a good test to rule
out network issues.

**Comment by pixerati** [comment]
I did a raw telnet through to port 5555 without any issue.

**Comment by dragosbulugean** [comment]
Hey guys, if anyone is still troubled by this, you have to dispose of any sockets and contexts at unity's app quit like:
```
 void OnApplicationQuit()
        {
            socket.Dispose();
            context.Dispose();
        }
```

**Comment by Mystfit** [comment]
@pixerati I'm running into the same problem. Running PyZmq server on localhost, 2 clients can connect to the host and directly to each other just fine via bindRandom ports. Moving the server or either client to another machine still lets the connection form but no messages make their way through.

I'm running the latest AsyncIO3.5 code, the latest NetMQ code, Unity 5.2.1 and Windows 10. Network issues have been ruled out by using lightweight PyZmq and NetMq servers/clients to simulate a similar environment.

Also, if one of the sockets times out whilst sending (rather than blocking forever) then disposing the sockets and context at the end will still hard freeze Unity. I suspect that the busted socket is still being held by a thread somewhere.

**Comment by LewisBridgeman** [comment]
Thanks. I'm currently using 5.2.1. I'll upgrade to 5.2.2 quickly, just in case that changes anything.

**Comment by somdoron** [comment]
Can you also upload somewhere a project that get freeze?  I have little
experience with unity...

**Comment by Mystfit** [comment]
Lewis, the most success I've had is with the latest branch of NetMQ using
the NetMQ.3.5 project, compiled with the latest version of ASyncIO using
the ASyncIO.Unity project, and everything compiled with .Net 3.5 (Any CPU)
and used with Unity 5.2.1f1.

This got me to the point where a very simple Unity project could
send/receive messages, but anything more complex fell apart quite quickly.

**Comment by LewisBridgeman** [comment]
Thanks both. Mystfit, I'll try doing that. Somdoron, I'll upload my Unity project after I've tried Mystfits advice.

**Comment by LewisBridgeman** [comment]
I tried your method, but it doesn't seem to work for me. It might be that I'm misunderstanding how to use NetMQ in Unity, so I've attached the script that freezes.
Am I right to be using a coroutine? Maybe a backgroundworker would be better?

void Start ()
 {
        AsyncIO.ForceDotNet.Force();
        StartCoroutine(ReqCoroutine());
}

    IEnumerator ReqCoroutine()
{
        using (NetMQContext ctx = NetMQContext.Create())
        {
            using (var client = ctx.CreateRequestSocket())
            {
                client.Connect("tcp://127.0.0.1:5555");

                while (true)
                {
                    var reqMsg = DateTime.Now.ToString();                    
                    Debug.Log(reqMsg);

                    client.TrySendFrame(reqMsg);
                    yield return new WaitForSeconds(1);

                    var replyMsg = client.ReceiveFrameString();
                    Debug.Log(replyMsg + Environment.NewLine);
                }
            }
        }
}

**Comment by drewnoakes** [comment]
@LewisBridgeman I don't know much about Unity, but the coroutine (C# generator function) has one problem in that the `while (true)` loop can never, meaning that the socket and context are never disposed.

**Comment by LewisBridgeman** [comment]
@drewnoakes Thanks, you were right!

**Comment by monsdar** [comment]
I've got the problem that @dragosbulugean and @Flime wrote about. The following code freezes Unity when I start the game in the editor for the second time:

```cs
using UnityEngine;
using NetMQ.Sockets;

public class PosResetter : MonoBehaviour
{
    SubscriberSocket subSocket = null;
    
    void Start ()
    {
        Debug.Log("Starting up NetMQ interface");        
        subSocket = new SubscriberSocket();
    }

    void OnApplicationQuit()
    {
        subSocket.Dispose();
    }
}
```

I'm using the following:
* Unity 5.3.3f1 64bit Free
* Windows 10 64bit
* Latest master [AsyncIO.Unity (Any CPU)](https://github.com/somdoron/AsyncIO/archive/master.zip)
* [NetMQ-x-3.3.3.0-rc9](https://github.com/NetMQ/NetMQ3-x/archive/3.3.3.0-rc9.zip) in its NetMQ-3.5 version
* Visual Studio 15 Community Edition

Do I have to build something in a specific way?

It seems as if the SubscriberSocket is not being released after OnApplicationQuit. On the second startup this let's Unity freeze. But that's just a blind guess...

**Comment by monsdar** [comment]
I've probably been able to fix the above mentioned issue myself with the following code:

```cs
using UnityEngine;
using NetMQ;
using NetMQ.Sockets;

public class PosResetter : MonoBehaviour
{
    NetMQContext context = null;
    SubscriberSocket subSocket = null;
    
    void Start ()
    {
        Debug.Log("Starting up NetMQ interface");
        context = NetMQContext.Create();
        subSocket = context.CreateSubscriberSocket();
    }

    void OnApplicationQuit()
    {
        Debug.Log("Shutting down...");
        subSocket.Close();
        context.Terminate();
        Debug.Log("Done...");
    }
}
```

Looks like it is somehow related to issue #424. Due to the missing context it is not possible to clean up completely. By explicitly terminating it works as expected and Unity does not freeze on second start.
