### ISSUE TITLE
Missing interfaces

### ISSUE THREAD

**Issue by matthiasgeller** [zeromq/netmq#99]
U are using ReSharper... So maybe u could refactor some classes and extract some interfaces to be able to simplify writing unit tests using a mocking framework instead of always writing integration tests.

Really cool would be all classes which are using private constructors only (like the NetMQContext class).

Temporarily i am using adapters realizing fake interfaces to solve that problem... But please...

Thx & Greetz
Matthias Geller

**Comment by drewnoakes** [comment]
I figure this is a duplicate of #63 so will close it.
